microsoft/msquic

- .azure/azure-pipelines.ci.yml
- src/test/lib/HandshakeTest.cpp
When the server uses CIBIR but the client doesn't, the connection should be rejected.
In regular sockets, the client's invalid handshake makes it up to QUIC and a transport
error is sent. But for LoLa, there is a filter based on the CIBIR ID for packet delivery to
the server, so the client's connect attempt times out instead. We already have a check
at the end for the connection not being successfully set up, so this can be addressed
by simply not asserting that we don't time out waiting for the handshake to complete.
> Fix QuicTestCibirExtension for LoLa and enable *CibirExtension* tests

- src/core/send.c
- src/platform/datapath_raw_socket.c
- src/platform/unittest/DataPathTest.cpp
The status code handling logic CxPlatResolveRoute is problematic because the status code conversion at the end of the function assumes `NETIO_STATUS Status` is `NT_STATUS`. However, in usermode, `NETIO_STATUS` = WIN32 errors.
Also, set route state to resolving before we queue a non-successful route resolution completion to prevent multiple route resolution jobs get queued up before the completion gets drained.
Covered by existing tests.
> Fix route resolution error handling

- scripts/generate-dotnet.ps1
- src/cs/lib/msquic_generated.cs
Fixes #2625 by post processing to replace `const int` with `const uint`.
Existing tests cover.
None
> Change C# Constants to uint

- src/inc/msquic_winuser.h
- src/inc/quic_platform_winuser.h
- src/platform/cert_capi.c
- src/platform/certificates_capi.c
- src/platform/selfsign_capi.c
- src/platform/unittest/TlsTest.cpp
Fix a build break from spurious warnings in public headers on certain versions of the VS2022 build tools.
Existing CI will cover this.
No Documentation changes needed.
> Fix errant warning on some versions of VS2022 build tools.

- .github/workflows/test-down-level.yml
- .github/workflows/wan-perf.yml
Cancels the down-level test and wan perf test workflows if a new commit is pushed to a PR.
N/A
N/A
> Cancel Long Running Workflows on New PR Commits

- src/platform/datapath_raw_xdp.c
When we count unique RSS procs from the interface's indirection table, we forget to take CPU group into account and thus undercount the number of unique RSS procs. When plumbing XDP rules, only a portion of the queues get rules applied.
Also, fail interface initialization if queue count == 0.
> Fix unique RSS procs counting

- docs/api/MsQuicClose.md
- docs/api/MsQuicOpenVersion.md
Fixes #2641 by adding more documentation on the calling restrictions around `MsQuicOpenVersion` and `MsQuicClose`.
cc @wizmann
> Document API Thread-Safety Issues

- src/core/settings.c
- src/test/lib/MtuTest.cpp
Closes #2647. Setting a minimum mtu only during ConfigurationOpen results in a failure, because the default values are 0. Set the default values to things more sane.
Also fixes a bug where minimum can be higher then maximum, if only 1 value is set on the configuration, and the global value is not within the bounds.
New test added to cover case
N/A
> Fix only setting minimum mtu during config open failing

- src/platform/datapath_raw_socket.c
Support cases in the raw datapath where the ethernet frame is larger than the IP frame.
Existing test coverage.
N/A
> Allow Too Big IP in Raw Parsing

- src/core/binding.c
Fix port number for NetBIOS datagrams in list of blocked ports
Same tests as for the blocked list of ports
You write it.
> NetBIOS Datagrams is port 138, not 128

- scripts/performance.ps1
- src/core/connection.c
- src/core/cubic.c
- src/inc/quic_datapath.h
- src/perf/lib/SecNetPerfMain.cpp
Change secnetperf to take `-cpu:-1` as all procs used by raw datapath. Also, change perf test script to pass in `-cpu:-1` for XDP.
Covered by existing tests.
> Use all processors for XDP perf test

- src/platform/datapath_epoll.c
- src/platform/datapath_kqueue.c
kqueue and epoll datapaths have a race condition upon pended sends whereas they might not get trigger notifications. By switching to level triggers, we solve this issue.
Closes #2654
Existing tests cover the change.
N/A
> Switch epoll and kqueue to level triggers

- src/perf/lib/PerfCommon.h
XDP is getting dangerously close to the hardcoded RPS limit for latency data, and some times has gone over, causing a crash
> Increase RPS latency storage

- src/core/packet_builder.c
It was being incremented by a variable that had just been set to 0, which means it always stayed 0 itself
> Fix Builder->TotalDatagramsLength being incorrectly calculated

- src/platform/datapath_winkernel.c
Packets without segmentation enabled were always resulting in SendData->TotalSize being 0. This didn't affect the sends, but make log debugging harder
> Fix PMTU packets logging as a 0 length send in kernel mode

- src/cs/lib/msquic_extensions.cs
Because of how function pointers in .NET work, calling SetCallbackHandler is a bit more difficult then it should be, and requires a weird and uncommon pattern. A solution to this problem is to write a few extension methods that abstract out the function pointers. These are just called like normal on the api table, but can take a .NET function directly rather then requiring a local of the function pointer to be created first.
This is in a separate file so it doesn't always have to be imported if callers don't want extension methods.
> Add Callback Helpers to .NET Interop Layer

- .azure/OneBranch.Official.yml
- .azure/OneBranch.Package.yml
- .azure/OneBranch.PullRequest.yml
- .azure/OneBranch.Tests.Official.yml
- .azure/OneBranch.Tests.PullRequest.yml
The docker image we build is not used internally, and is built for public consumption in an external setup. Disable the detector that warns for this case in internal builds.
> Add variable to skip docker detector in onebranch

- src/perf/lib/RpsClient.cpp
- src/perf/lib/RpsClient.h
~~Add scenarios to RPS client that align with how System.Net.Quic uses MsQuic, to be able to compare performance fairly:~~
~~- Turn on/off send buffering~~
~~- Sending data after receiving stream started event~~
Add param to RPS client to turn on/off send buffering
> Add sendbuf param to RPS client

- src/platform/datapath_raw_xdp.c
Since XDP queues are assigned to XDP workers in a round-robin pattern, some workers might not get assigned any queues. Simply skip registering those workers to datapath for now.
CI
> Ignore XDP workers that do not have an XDP queue assigned

- scripts/prepare-machine.ps1
- scripts/xdp-devkit.json
- scripts/xdp-install.ps1
Now, xdp-install.ps1 downloads the xdp devkit that is used by the head commit of msquic. When we ingest a new devkit, we just need to change the path in xdp-devkit.json.
@nibanks will need your help to make https://aka.ms/xdp-install redirect to https://raw.githubusercontent.com/microsoft/msquic/main/scripts/xdp-install.ps1.
> Improve https://aka.ms/xdp-install

- src/platform/tls_openssl.c
This is fix for regression caused by #2419, reported by @manickap.
The problem is that without calling X509_verify_cert() there are no chain certificates in x509_ctx.
The logic kicks in in but `sk_X509_num` on `X509_STORE_CTX_get0_chain(x509_ctx)`  return -1 so we pass empty buffer instead of peer's certificates.  
There may be other ways how to fix it but for now I put the call back for cases when certificate and chain is going to be presented to caller. For non-portable, it is ok since the raw x509_ctx is passed in so callers can fix it anyway they need to. 
contributes to #2732
cc: @rzikm
> make sure PEER_CERTIFICATE_RECEIVED has certificate chain even if Quic does not do validation

- scripts/performance.ps1
prepare-machine.ps1 is copied to the perf test machines but xdp-devkit.json is not.
CI
> Copy xdp-devkit.json to perf test setup

- .azure/azure-pipelines.ci.yml
- src/core/unittest/SettingsTest.cpp
Newer GCC has a new warning that triggers on the SettingsTest. Explcitly zero buffers to avoid the warning.
Also adds a 22.04 build configuration on azure pipelines
> Fix build on Ubuntu 22.04

- src/platform/datapath_raw_xdp.c
```
XDP_MATCH_TYPE MatchType =
QUIC_ADDRESS_FAMILY_INET ? XDP_MATCH_IPV4_UDP_PORT_SET : XDP_MATCH_IPV6_UDP_PORT_SET;
```
This code doesn't really check the address family. This got caught up in datapath unittests but I didn't notice when checking in the original PR #2748.
CI
> Fix port set rules not working for IPv6

- docs/Settings.md
Set goes to QUIC_STATUS_INVALID_PARAMETER
https://github.com/microsoft/msquic/blob/0fffdc076abd52a61a2d4d8d699cf6a5f80e56e5/src/core/stream.c#L563-L580
> QUIC_PARAM_STREAM_ID is get only

- docs/Settings.md
- scripts/generate-dotnet.ps1
- src/core/library.c
- src/cs/lib/msquic_generated.cs
- src/inc/msquic.h
- src/inc/quic_tls.h
- src/lib.rs
- src/platform/tls_openssl.c
- src/platform/tls_schannel.c
- src/test/lib/ApiTest.cpp
Fixes #2761. Adds a new parameter that can be called via GetParam to query the compiled in TLS provider. This allows application code to handle any TLS provider specific differences.
cc @rzikm
Added get/set test.
Updated for new parameter.
> Expose Parameter for TLS Provider

- scripts/RemoteTests.json
- scripts/performance-helper.psm1
- scripts/performance.ps1
- src/perf/lib/ThroughputClient.cpp
Make TCP connection failures not kill the perf pipeline. The test isn't that important, so skip any failures here
Closes #2527
Do not merge until I remove the tcp change that forces it to always fail.
> Allow TCP perf to fail to complete without failing pipeline

- src/inc/quic_platform.h
- src/platform/platform_worker.c
Add synchronization for EC contexts to solve #2763. Since EC contexts are uncontended except for registration init/uninit, simply taking a CS lock to synchronize the access should be performant enough.
CI
> Add synchronization for EC contexts

- src/platform/datapath_raw_xdp.c
It's possible that due to memory allocation failures, the port set rule isn't programmed on the interface during socket creation and during socket deletion, we incorrectly assume we can always find the corresponding rule for the socket.
Fixes #2793.
CI
> Handle port set rule not found during socket deletion gracefully

- src/platform/datapath_raw.c
Hit an assert in CI:
```
CXPLAT_FRE_ASSERTMSG(Worker->DatapathEC == NULL, "Only one datapath allowed!");
0d 00000062`504ff6c0 00007ff8`bd8e7aa3     msquic!CxPlatWorkerRegisterDataPath+0x76 [D:\a\1\msquic\src\platform\platform_worker.c @ 97] 
0e 00000062`504ff700 00007ff8`bd8dbe8b     msquic!CxPlatDpRawInitialize+0x683 [D:\a\1\msquic\src\platform\datapath_raw_xdp.c @ 1111] 
0f 00000062`504ff7f0 00007ff8`bd873ad4     msquic!CxPlatDataPathInitialize+0x24b [D:\a\1\msquic\src\platform\datapath_raw.c @ 155] 
10 00000062`504ff860 00007ff6`7b4139fd     msquic!MsQuicRegistrationOpen+0x214 [D:\a\1\msquic\src\core\registration.c @ 70] 
11 00000062`504ff960 00007ff8`f6f64ed0     spinquic!RunThread+0x2cd [D:\a\1\msquic\src\tools\spin\spinquic.cpp @ 965] 
```
DatapathEC isn't null when registering the …
> Clean up datapath on route resolution init failure

- src/platform/tls_schannel.c
Schannel did not check whether the caller is server.
will be added
Settings.md
> Add server validation for CxPlatTlsSecConfigSetTicketKeys

- .github/workflows/test-down-level.yml
- src/test/lib/HandshakeTest.cpp
- src/test/lib/TestConnection.cpp
- src/test/lib/TestConnection.h
- src/test/lib/TestHelpers.h
Fixes #2758, but will need to be backported to the 2.0 release in order for the tests to pass.
CI.
N/A
> Support multiple expected certificate validation results in tests

- src/inc/msquic.h
I noticed the SAL annotation on the RECEIVE event for a stream wasn't correctly indicating that the `BufferCount` could be zero (in the FIN only case).
N/A
N/A
> Fix RECEIVE BufferCount SAL Annotation

- .github/ISSUE_TEMPLATE/bug_report.yaml
Renamed CO_RELEASE to "Windows 11, version 21H2" and added NI_RELEASE to the list of affected operating systems in the issue template.
N/A
N/A
> Add NI_RELEASE to issue template

- src/core/api.c
- src/core/stream.h
- src/core/stream_recv.c
- src/generated/linux/stream_recv.c.clog.h
- src/generated/linux/stream_recv.c.clog.h.lttng.h
1. Updates the receive flush code to run inline if it's the end of the buffer.
2. Optimizes for apps that call receive complete in the receive callback, instead of just returning success.
Existing tests?
N/A?
> Improvements to Latency of Receive Code Paths

- src/inc/msquichelper.h
I use Wireshark sniff and analyze packet. sslkeylogfile is opened by Wireshark. It is failed to open sslkeylogfile when I redebug my program. So I need to close Wireshark. It is not convenient. 
N/A
N/A
> open sslkeylogfile with shared read-write flag on Windows

- src/test/lib/DatagramTest.cpp
Fixes a recent regression in the DatagramSend test because of a timing change.
Existing test coverage (w/ fix)
N/A
> Fix for Recent DatagramSend Test Regression

- docs/api/QUIC_CONNECTION_EVENT.md
- src/core/connection.c
- src/cs/lib/msquic_generated.cs
- src/inc/msquic.h
- src/lib.rs
Fixes #2851. It exposes the wire format error code to the app.
No new tests were added.
Update API docs
> Expose Wire Format Error Code on Close

- src/perf/lib/RpsClient.cpp
- src/perf/lib/RpsClient.h
Allows for the command line to specify a set of local addresses that are used for RPS perf testing.
Locally tested
N/A
> RPS Perf Client Custom Local Addresses

- .gitmodules
Full change log for OpenSSL can be found [here](https://www.openssl.org/news/cl111.txt). The CVE doesn't apply to MsQuic out of the box, but best to stay up to date.
N/A
> Update to OpenSSL 1.1.1q

- src/core/stream.c
- src/cs/lib/msquic_generated.cs
- src/generated/linux/stream.c.clog.h
- src/generated/linux/stream.c.clog.h.lttng.h
- src/inc/msquic.h
- src/manifest/clog.sidecar
This PR is **just a proposal of a change** that would eventually help us get rid of an explicit link from stream to connection. We'd like to adopt `SafeHandle` reference counting to keep connection alive for all the streams instead of a manual reference counting.
The event contains information whether it's happening due to connection closure, but it doesn't contain any details. As a result, the user has to manually keep reference between stream and connection if they want to use those details. This is the last thing that forces us to keep reference from stream to connection.
Local test with System.Net.Quic and closing the connection via application and via idle timeout while stream is opened.
- ~~Yes. I can fill it in if this proposal …
> Include connection close details in stream's SHUTDOWN_COMPLETE

- src/core/operation.c
- src/core/stream.c
- src/core/stream.h
- src/core/stream_send.c
- src/inc/msquic.hpp
- src/plugins/dbg/quictypes.h
- src/test/MsQuicTests.h
- src/test/bin/quic_gtest.cpp
- src/test/bin/winkernel/control.cpp
- src/test/lib/ApiTest.cpp
For #2869. Updates the send abort logic to indicate a start abort if the send has a start flag.
Added new test.
N/A
> Indicate Stream Start Abort Event from Send Start

- src/core/stream.c
- src/cs/lib/msquic_generated.cs
- src/generated/linux/stream.c.clog.h
- src/generated/linux/stream.c.clog.h.lttng.h
- src/inc/msquic.h
- src/manifest/clog.sidecar
- src/test/lib/DataTest.cpp
- src/test/lib/TestStream.cpp
- src/test/lib/TestStream.h
Small follow up on #2872. Renamed "ByPeer" to "ByApp" since it applies to local connection close as well. And included info whether it's local or remote close.
System.Net.Quic tests.
No, docs do not include event details.
> Fixed details of stream SHUTDOWN_COMPLETE for ConnectionShutdown

- src/core/worker.c
- src/inc/quic_platform.h
- src/inc/quic_platform_posix.h
- src/inc/quic_platform_winkernel.h
- src/inc/quic_platform_winuser.h
- src/manifest/MsQuicEtw.man
- src/perf/lib/RpsClient.cpp
- src/perf/lib/RpsClient.h
- src/platform/platform_worker.c
- In order to help diagnosing some RPS scenarios that seem to have packet loss, add packet drop events to the RPS keyword.
- Add support for printing stats in RPS client.
- Fix race condition in setting/clearing `Ready` event from multiple threads.
Fixes #2888.
Fixes #2900.
Existing CI tests
N/A
> Fixes for Tail Latency Issues with XDP

- scripts/log.ps1
- scripts/run-executable.ps1
- scripts/spin.ps1
- src/manifest/MsQuic.wprp
#2685 Added a new logging profile for SpinQuic, which didn't follow the correct conventions and broke the ability for WPR to start logging.  This change fixes that by following the guidelines
Ran log.ps1 locally to verify it parses the WPRP file without error.
> Fix logging profile names

- src/platform/datapath_epoll.c
With socket option IP_MTU_DISCOVER=IP_PMTUDISC_DO a linux IPv4 socket rejects packets larger than route MTU (as shown by ip route get DST-IP) with EMSGSIZE. With IP_MTU_DISCOVER=IP_PMTUDISC_PROBE the linux socket ignores the route MTU.
To apply this also for an IPv6, I set IPV6_MTU_DISCOVER=IP_PMTUDISC_PROBE, too.
Probably not and maybe.
Probably not.
> Linux IP_PMTUDISC_PROBE

- docs/Settings.md
- src/core/quicdef.h
- src/core/settings.c
- src/generated/linux/settings.c.clog.h
- src/generated/linux/settings.c.clog.h.lttng.h
- src/inc/msquic.hpp
- src/manifest/clog.sidecar
- src/test/MsQuicTests.h
- src/test/bin/quic_gtest.cpp
- src/test/bin/winkernel/control.cpp
- src/test/lib/ApiTest.cpp
Enable configuration of Version Settings via the Windows Registry.
Manual testing with `quicinteropserver` and `quicinterop`.
> Add registry configuration for Version Settings.

- src/core/bbr.c
- src/core/congestion_control.h
- src/core/cubic.c
- src/core/loss_detection.c
These fields in QUIC_ACK_EVENT/QUIC_LOSS_EVENT are simply "what is the current value of
some field in the QUIC_LOSS_DETECTION". So I've renamed them to match exactly.
> Rename QUIC_ACK_EVENT/QUIC_LOSS_EVENT fields to match their QUIC_LOSS_DETECTION counterparts

- src/inc/msquic_posix.h
- src/inc/msquic_winkernel.h
- src/inc/msquic_winuser.h
- src/test/lib/HandshakeTest.cpp
- src/test/lib/TestConnection.cpp
- src/test/lib/TestConnection.h
- src/test/lib/TestHelpers.h
Backport #2758 to Release/2.0 with required variables and values.
> Backport #2758 to Release/2.0

- src/platform/tls_schannel.c
This PR adds check for failure statuses on `CxPlatTlsSetClientCertPolicy` when creating security config. Previously, attemt to require client certificates on Windows Server 2022 successfully created security config (although in debug builds it would hit an assert).
Tested manually on Windows Server 2022.
No changes needed.
> Correctly handle unsupported client cert on Windows Server 2022

- src/core/stream.c
- src/cs/lib/msquic_generated.cs
- src/generated/linux/stream.c.clog.h
- src/generated/linux/stream.c.clog.h.lttng.h
- src/inc/msquic.h
- src/manifest/clog.sidecar
- src/test/lib/DataTest.cpp
- src/test/lib/TestStream.cpp
- src/test/lib/TestStream.h
This is another small follow-up on https://github.com/microsoft/msquic/pull/2872. It allows application to differentiate different transport-initiated shutdowns based on the Connection->CloseStatus (like CONNECTION_IDLE vs CONNECTION_TIMEOUT). without maintaining an explicit link to the main QUIC Connection object.
Tests were updated to check the close status, also tested against local .NET runtime build.
No change (there are no docs for event data AFAICS).
> Add ConnectionCloseStatus to Stream SHUTDOWN_DONE event

- src/test/lib/ApiTest.cpp
An attempt to fix #2905 by ignoring errors from Send.
Automation.
None
> Fix CloseConnBeforeStreamFlush Test Failure

- .azure/azure-pipelines.perf.yml
Fix #2794 by disabling the slow tests.
Automation
None
> Disable Failing Loopback Tests on Shared EC Linux

- .azure/azure-pipelines.ci.yml
- .gitmodules
Remove OpenSSL submodule from Release/1.0 due to build failures.
CI
OpenSSL wasn't officially supported on Release/1.0, and Linux support was in preview, so it's fine to remove.
> Remove OpenSSL from 1.0 builds.

- scripts/make-packages.sh
This adds platform recognition for arm/arm64 on Linux
script can now make arm packages
```
root@1284925c1f1c:~/msquic# ls -al artifacts/packages/linux/arm64_Release_openssl/
total 8816
drwxr-xr-x 2 root root    4096 Aug  4 21:26 .
drwxr-xr-x 6 root root    4096 Aug  4 16:24 ..
-rw-r--r-- 1 root root 4503356 Aug  4 21:26 libmsquic-2.1.0-1.aarch64.rpm
-rw-r--r-- 1 root root 4513350 Aug  4 21:26 libmsquic_2.1.0_arm64.deb
```
no.
> add support for arm packages

- src/test/lib/ApiTest.cpp
We can't test the minor version because it will 100% fail when run as a down-level test. To support running this with future versions of MsQuic, just validate the major version.
Tests updated
N/A
> Don't Check Minor Version in Test

- .github/workflows/cargo.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/docker-publish.yml
- .github/workflows/test-down-level.yml
The Harden runner step produces policy to enforce based on auditing. This change implements the generated policy and enforces it.
**NOTE:** this may cause a build break if anything was missed. But it's trivial to fix as we go forward.
Automated CI
N/A
> Harden Github Actions.

- .azure/OneBranch.Official.yml
Shared ACR for onebranch build pipeline is retiring soon. Use isolated ACR instead as suggested.
OB CI
> Use isolated ACR for linux

- .azure/OneBranch.Publish.yml
It seems that by default, azure pipelines are triggered by main branch. Remove it for this pipeline.
OBP CI
> Remove main trigger for publish OBP

- src/inc/msquic.h
Updates `QUIC_STATISTICS_V2_SIZE_2` to reflect the correct final size for v2.1. Also adds comments explaining what these are for.
> *Note* - This must be backported to release/2.1
Existing
N/A
> Fix QUIC Statistics Size Helpers

- src/platform/platform_posix.c
when we try to set affinity on core that is offline pthread_create fails (on glibc) 
We should perhaps figure out better way how to do the core management but this is simple fix that unblocks .NET ARM testing. Performance may be sub-optimal but at least msquic is functional. 
running .NET test suite on ARM64 box with some offline cores. 
no
> retry pthread create if it failes with ENOKEY

- src/platform/platform_posix.c
This is follow-up on #2989. I was trying to debug some more failed test runs. It seems like the behavior was same e.g. we fail to created thread when trying to set on offline CPI but the `errno` was set to `ENOENT`. I did not figure out why it would sometimes fail with different error. 
For now I added `pthread_create` retry also for other errno code. 
running .NET test suite.
> retry pthread_create also on ENOENT

- scripts/make-packages.sh
Fixes #2975 
This PR explicitly states that the deb package depends on libssl1.1 being installed. This makes the installation fail on e.g. Ubuntu 22.04 which is on OpenSSL 3.0 and the lib would fail to load unless user manually installs missing libssl1.1.
I wanted to change the rpm package as well, but I did not manage to make it work across RHEL/CentOS 8/9 since RHEL 8 uses `openssl-libs` and RHEL 9 uses `compat-openssl11` to install `libcrypto.so.1.1` (and specifying `libcrypto.so.1.1` directly as a dependency did not work). Suggestions welcome.
Tested locally built deb package on:
- Ubuntu 20 - no functional change
- Ubuntu 22 - dpkg -i mentions that there are unmet dependencies, I assume that apt-get install would fail with meaningful error message. After manually installing libssl1.1 …
> Specify libssl1.1 dependency on deb package

- src/core/crypto_tls.c
Fixing for Linux Non-Tested CI, ignore lint checks for readability size.
N/A
N/A
> Fix CI: Ignore Lint Check

- scripts/RemoteTests.json
Convert throughput tests to timer-based instead of data-transferred based. This will help the tests have more predictable results in a variety of scenarios.
CI
N/A
> Convert throughput tests from data transferred to timed.

- .azure/azure-pipelines.periodic.yml
- .azure/templates/make-pgo-pr.yml
- scripts/make-pgo-pr.ps1
- scripts/performance-helper.psm1
- scripts/performance.ps1
Support OpenSSL in automated PGO runs.
Ci
N/A
> Add PGO support for OpenSSL

- src/inc/quic_platform_posix.h
These macros are unused and confusing due to similarity to the new CxPlatSchedulerYield.
> Remove unused YieldProcessor macros

- src/inc/quic_platform_posix.h
POSIX is just so much bigger than that
> Fix abstract comment in quic_platform_posix.h that just claims it's for linux

- src/inc/quic_platform.h
- src/platform/platform_worker.c
This is the next step in merging support for either combined or separate threads for QUIC and UDP layers. The CxPlat layer now supports both. This PR is done separate to ensure no significant perf regressions.
Perf pipeline
N/A
> Remove QUIC_USE_EXECUTION_CONTEXTS from CxPlat

- src/cs/lib/MsQuicException.cs
- src/cs/lib/msquic.cs
- src/cs/lib/msquic_generated_linux.cs
- src/cs/lib/msquic_generated_macos.cs
Fixes dotnet/runtime#74053 by introducing a new status code so dotnet runtime could display a friendly message when IPv6 is not supported.
> add 0x63 status code

- scripts/generatevpackpat/Program.cs
- scripts/generatevpackpat/generatevpackpat.csproj
Replaces Newtonsoft.Json with System.Text.Json. The latter supports .NET Framework 4.6.2 onwards.
> Replace Newtonsoft.Json with System.Text.Json

- src/cs/lib/msquic_generated_macos.cs
Follow up PR for dotnet/runtime#74053. As mentioned by @rzikm, the code error for EADDRNOTAVAIL code is 49 on macos.
https://github.com/dotnet/runtime/pull/74780#discussion_r958375123
> EADDRNOTAVAIL code is 49 on macos

- src/generated/linux/platform_posix.c.clog.h
- src/generated/linux/platform_posix.c.clog.h.lttng.h
- src/manifest/clog.sidecar
- src/platform/platform_posix.c
On combination Docker+Debian11+ARM64, the call to pthread_create sometimes returns EINVAL when attempting thread affinitization. This PR always retries thread creation without thread affinitization when the first call to pthread_create fails.
Related to https://github.com/dotnet/runtime/issues/74952
Tested manually on the affected platform.
NO
> Always creating worker threads without affinitization on error.

- docs/Release.md
- scripts/make-packages.sh
Only armhf is accepted by packages.microsoft.com.
packages.microsoft.com validates it.
> Fix arm32 package naming

- src/platform/datapath_epoll.c
On Arm32 devices, we encountered an issue where all attemts at connection timeout, closer investigation showed that all `sendmmsg` calls were failing with errno 22. I dug around a bit and it seems that the platform in question (Debian 10 on arm) was checking the expected length against `IP_PKTINFO` control header and failed the send. Using correct length for IPv4 and IPv6 solved the issue.
More info at https://github.com/dotnet/runtime/issues/75493#issuecomment-1246556769
Tested on affected platform.
N/A
> Use correct length increment for IP_PKTINFO CMsg header

- docs/BUILD.md
`MsQuic` available as a port in [vcpkg](https://github.com/microsoft/vcpkg), a C++ library manager that simplifies installation for `MsQuic` and other project dependencies. Documenting the install process here will help users get started by providing a single set of commands to build `MsQuic`, ready to be included in their projects.
We also test whether our library ports build in various configurations (dynamic, static) on various platforms (OSX, Linux, Windows: x86, x64) to keep a wide coverage for users.
I'm a maintainer for vcpkg, and [here is what the port script looks like](https://github.com/microsoft/vcpkg/blob/master/ports/ms-quic/portfile.cmake). We try to keep the library maintained as close as possible to the original library.
> Add vcpkg installation instructions

- src/inc/msquicp.h
Change the test transport parameter to use 4 bytes for `Type` instead of 2 bytes, allowing for the version negotiation extension transport parameter to be supplied.  This is needed for #3076.
CI tests
N/A
> Change Test TP to use 4 bytes for Type instead of 2.

- src/fuzzing/fuzz.cc
malloc and memcpy are not needed.
Test works without issue.
This is test.
N/A
> Use LibFuzzer data as it is

- src/test/lib/HandshakeTest.cpp
Fix the client to use the correct address to contact the server at to exercise XDP. "loopback" won't use XDP, and thus the connection will fail.
Bug introduced in #3076.
CI
N/A
> Fix VNE TP test.

- src/platform/datapath_raw.c
Fixes #3103. Reorders the cleanup code for initialization failure.
Existing CI (spinquic).
N/A
> Fix XDP Cleanup on Init Failure Crash

- .azure/azure-pipelines.ci.yml
- CMakeLists.txt
- scripts/build.ps1
- src/core/unittest/SettingsTest.cpp
- src/inc/msquicp.h
- src/test/MsQuicTests.h
- src/test/bin/quic_gtest.cpp
- src/test/bin/winkernel/control.cpp
- src/test/lib/ApiTest.cpp
- src/test/lib/HandshakeTest.cpp
- src/test/lib/TestConnection.cpp
- src/test/lib/TestHelpers.h
Official builds need to disable the tests for preview features since those features may change in the future. We can't publish down-level tests for things that are expected to change in the future. Those tests will break.
Ran locally. Added a CI for build. Should I onboard a test too?
N/A
> Disable Preview Feature Tests on Official Builds

- src/perf/lib/HpsClient.cpp
- src/perf/lib/HpsClient.h
Fixes a race condition in the cleanup / error path of HPS client, where the connection would be freed early.
Tested locally. Validated with perf automation.
> Fix Race Condition in HPS Client

- src/fuzzing/fuzz.cc
Fix error reported from OSS-Fuzz
1. pointer-pointer was passed
2. SEGV by accessing random address when QUIC_PARAM_GLOBAL_VERSION_SETTINGS
this is test
N/A
> Fix passing pointer-pointer, skip inevitable SEGV case

- CMakeLists.txt
- scripts/build.ps1
1. Add `-StaticCRT` to allow full static CRT linking.
2. Never apply partial static CRT linking to debug bits.
CI
> Add -StaticCRT switch to build script and never use partial static crt linking for debug builds

- src/perf/lib/Tcp.cpp
- src/perf/lib/Tcp.h
There is a window in which the receive callback can happen after we start deleting the connection object, but haven't yet deleted the socket (in the destructor). This updates the receive path to bail if it fails to queue in this case.
Perf tests
No
> Fix TCP Perf Test Race Condition on Shutdown

- src/tools/spin/CMakeLists.txt
- src/tools/spin/spinquic.cpp
`CXPLAT_TEL_ASSERT(MsQuicLib.Loaded)` in MsQuicAddRef abort when libmsquic is statically linked with spinquic
locally tested
N/A
> Add lock to avoid MsQuicOpen abort issue for statically linked spinquic

- src/core/connection.c
- src/generated/linux/connection.c.clog.h
- src/generated/linux/connection.c.clog.h.lttng.h
- src/manifest/clog.sidecar
- src/test/MsQuicTests.h
- src/test/bin/quic_gtest.cpp
- src/test/bin/winkernel/control.cpp
- src/test/lib/HandshakeTest.cpp
Add tests to ensure that client and server fail parsing the Version Info transport parameter when it contains a zero version.
New testing.
N/A
> Add Tests for Zero version in VN TP.

- src/test/lib/DataTest.cpp
To make "test down level" pass in #3118 
I have tested manually on ubuntu 20.04 with the msquic binary built from #3118 
N/A
> fix(test): allow QUIC_CONNECTION_EVENT_PEER_NEEDS_STREAMS

- .azure/azure-pipelines.perf.yml
- scripts/performance-helper.psm1
- scripts/performance.ps1
Depends on #3151.
- Saves all runs' histogram files from perf tests
- Moves histogram files into a separate folder
- Enables dry run perf publishing for PRs
Perf pipeline
None
> Save All Histograms from Perf

- docs/TSG.md
Just some minor issue I discovered while reading the documentation.
- `QUIC_CONNECTION_EVENT_SHUTDOWN_INITIATED_BY_APP` is actually called `QUIC_CONNECTION_EVENT_SHUTDOWN_INITIATED_BY_PEER`.
- Some Markdown links were broken.
n/a
n/a
> TSG: Fix some minor issues

- scripts/RemoteTests.json
- scripts/performance.ps1
- src/core/stream_send.c
- src/perf/lib/ThroughputClient.cpp
Collect stream-level stats for throughput perf runs. Also has a few fixes to when we add/remove blocked flags for streams.
Perf pipeline
N/A
> Enable Stream Stats on Perf

- CMakeLists.txt
- src/core/api.c
- src/core/bbr.c
- src/platform/datapath_kqueue.c
- src/platform/hashtable.c
Fix/suppress some new clang/cppcheck warnings
Should be covered by existing tests.
Nope.
> Fix/suppress some new clang/cppcheck warnings

- src/platform/datapath_winkernel.c
Discovered by the ECN tests from #3168. We forgot to set the ECN socket option.
CI in #3168
> Configure ECN socket option for winkernel

- src/core/library.c
- src/core/library.h
- src/generated/linux/library.c.clog.h
- src/generated/linux/library.c.clog.h.lttng.h
Two main updates to perf counter snapshots:
- Change interval from 30 seconds to 1 second
- Fire off the ETW event every time we snapshot
The goal here is that if we collect low volume logs, we implicitly will collect our perf counters.
TODO: Update WPA plugin to decode these counters for nice viewing.
Perf pipeline to make sure there is no significant regression.
N/A
> Perf Counter Snapshot Improvements

- docs/api/StreamReceiveComplete.md
Clarify the handling of dup StreamReceiveComplete calls per `QUIC_STREAM_EVENT_RECEIVE` event in MsQuic
no code change.
This is pure doc update.
> doc: no dup StreamReceiveComplete call

- src/plugins/trace/dll/Properties/launchSettings.json
- src/test/lib/EventTest.cpp
The Event tests fail occassionally, and at least in one case it's because the app thread didn't wait long enough. It only waited 20 ms and expected the QUIC thread to run, but it took over 100 ms for it to eventually run. This PR significantly increases wait time for these particular tests. We might want to do the same for other tests...
Fixes #3193
Likely need to backport for test reliability.
N/A
> Tests Wait Longer

- src/core/connection.c
- src/core/connection.h
- src/core/inline.c
- src/core/loss_detection.c
- src/core/worker.c
- src/generated/linux/TestHelpers.h.clog.h
- src/generated/linux/TestHelpers.h.clog.h.lttng.h
- src/generated/linux/datapath_raw_socket.c.clog.h
- src/generated/linux/datapath_raw_socket.c.clog.h.lttng.h
- src/generated/linux/worker.c.clog.h
- src/generated/linux/worker.c.clog.h.lttng.h
- src/inc/msquic.hpp
- src/manifest/MsQuicEtw.man
- src/manifest/clog.sidecar
- src/platform/datapath_raw_socket.c
- src/test/MsQuicTests.h
- src/test/bin/quic_gtest.cpp
- src/test/bin/winkernel/control.cpp
- src/test/lib/HandshakeTest.cpp
- src/test/lib/TestHelpers.h
New tests to improve upon our random loss tests. This explicitly tests different loss patterns. This led to the following additional changes:
1. Found/fixed bug in the timer wheel, when pushing back the first timer on a connection didn't result in updating the timer wheel (fixes #3206).
2. Improved/optimized the loss detection timer to not query time again every time.
3. Added extra logs to route resolution path (fixes #2635).
4. Fix route resolution issue with IP comparison.
Automated testing
N/A
> Test Specific Handshake Loss Patterns

- src/tools/spin/spinquic.cpp
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52744&q=msquic&can=2&sort=-reported
GetRandom(int) cause unexpected value with fuzzer
e.g. 0xffffffff % 16 = 0xffffffff (-1 % 16 = -1)
This might fix another OSS-Fuzzer reported issues
run locally
N/A
> Fix modulo issue of MSB 1 with signed type

- docs/Deployment.md
- src/core/connection.c
- src/core/library.c
- src/core/quicdef.h
- src/core/settings.c
- src/core/settings.h
- src/core/unittest/SettingsTest.cpp
- src/cs/lib/msquic_generated.cs
- src/generated/linux/settings.c.clog.h
- src/generated/linux/settings.c.clog.h.lttng.h
- src/inc/msquic.h
- src/manifest/clog.sidecar
> CP: v2.1 Load Balancing Fixed Server ID

- .gitmodules
Consume the new quictls release: https://github.com/quictls/openssl/releases/tag/OpenSSL_1_1_1s%2Bquic1
Automation
None
> Update to QuicTls (OpenSSL) 1.1.1s

- docs/Platforms.md
Add explicit statement about possible usage of MsQuic with older Windows version, when using OpenSSL.
Changes are only made to documentation. 
MsQuic tested on Windows Server 2012.
Changes to documentation were made.
> Add info about usage with older Windows releases with OpenSSL

- .azure/azure-pipelines.ci.yml
Fixes https://github.com/actions/runner-images/issues/6697 by making sure to use 20.04 to build, not latest.
Existing CI.
N/A
> Use Ubuntu 20.04 to Build OpenSSL-Systemcrypto Variant

- .github/workflows/codeql-analysis.yml
Update Security Hardener to allow URL used by CodeQL.
> Fix CodeQL break

- src/platform/datapath_winuser.c
As a follow up for #3282, split the IO completion routines into atomic units.
CI/CD
No.
> Split out CQE completion routines for winuser

- .azure/OneBranch.Official.yml
- .azure/OneBranch.PullRequest.yml
We have been using deprecated docker images for onebranch pipelines, and we've got lots of warnings.
OB CI
> Address onebranch pipeline warnings

- src/platform/datapath_winuser.c
Experiment: during RIO development, removing CancelIo in CxPlatSocketContextUninitialize caused an HPS perf regression from ~9500 HPS (main baseline) to ~4500 HPS (PR), so I ultimately did not remove the CancelIo call. Now, a set of perf runs comparing main to main without CancelIo shows a perf improvement from 4500 HPS (main) to 9500 HPS (PR) which is exact opposite of the previous findings.
Experiment with CancelIo and HPS tests to attempt to find the root cause of these inconsistencies.
> Don't invoke CancelIo in CxPlatSocketContextUninitialize

- src/platform/datapath_winuser.c
While RIO doesn't support UDP unreachable indications (yet) we should add support for those on the RIO path, which use Winsock rather than Win32 error codes.
Tested locally on a prototype RIO implementation.
> check for Winsock unreachable error codes in addition to Win32

- src/platform/platform_winuser.c
`timeGetDevCaps` is not available in `WINAPI_FAMILY_GAMES` and importing it in `gamecore_console` builds will crash the process at runtime due to `DLL_NOT_FOUND`. 
See [Windows 10 Software Development Kit (Win10SDK)](https://learn.microsoft.com/en-us/gaming/gdk/_content/gc/getstarted/overviews/sdk-and-tools#windows-10-software-development-kit-win10sdk) for the API family available to Microsoft GDK gaming platform.  
Existing tests do not cover the issue fixed by this PR.  
The issue should be captured by the linker (and cause build failures) instead of automated tests. We should not link against `OneCore.lib` on `gamecore_console` as it [provides the exports for the subset of Win32 APIs that are common to all Windows 10 devices.](https://learn.microsoft.com/en-us/windows/win32/apiindex/win …
> gamecore_console: avoid importing timeGetDevCaps

- scripts/run-executable.ps1
- scripts/run-gtest.ps1
A couple scripts have a `-Debugger` option that defaults to WinDbgX on Windows, which is only one of many possible debuggers. To support users who are still using the venerable WinDbg, support graceful fallback if WinDbgX is not installed.
Tested locally without WinDbgX. Also swapped parameters to simulate WinDbgX without WinDbg.
Nope, both are debuggers.
> Fall back to WinDbg if WinDbgX is not installed

- CMakeLists.txt
- src/platform/tls_schannel.c
Fix `gamecore_console` build failure on SDK `10.0.20348.0`. `WINAPI_PARTITION_GAMES` never exposed `UNICODE_STRING`.  
Bumping the minimum required SDK version to >= `10.0.20348.0` as we are using a new API (`SetThreadIdealProcessor`) exposed to `WINAPI_PARTITION_GAMES` since `10.0.20348.0`.  
See #3343.  
Built `10.0.20348.0`, `10.0.22000.0`, `10.0.22621.0` for `gamecore_console` and verified the build passed. Binaries produced no longer import `winmm.dll`.  
N/A
> gamecore_console: fix build with 10.0.20348.0

- .azure/OneBranch.Docker.Official.yml
- .azure/OneBranch.Official.yml
- .azure/dockers/ob/windows/Dockerfile
- .azure/dockers/ob/windows/install-workloads.ps1
- .azure/dockers/ob/windows/vsconfig.2019
- CMakeLists.txt
Follow-up PR to address the onebranch pipeline failures introduced by #3343.  
`gamecore_console` builds need to be on SDK `10.0.20348.0` or later and the latest SDK in our existing image is `10.0.19041.0`.  
The old base image (`cdpxwin1809.azurecr.io/global/vse2019:latest`) had some issues with installing the new SDK, so we've changed to a more recent onebranch base image for our builds.  
Also adding a new pipeline parameter to specify the base image tag to use, so we could test the official build against wip images. Defaulting to `latest` instead of `20220812.8`.  
Thanks to @csujedihy for helping out!  
Through pipeline runs.  
`msquic-Official-Docker #20230113.3` publishing to `testing`, and subsequent `msquic-Official #20230113.2` based on the `testing` image.  
Waiting for the …
> build: fix onebranch pipelines

- src/platform/datapath_epoll.c
it would fail as 
```
[ 86%] Building C object src/platform/CMakeFiles/platform.dir/certificates_posix.c.o
cd /home/furt/github/wfurt-msquic/build/linux/x64_openssl/src/platform && /usr/bin/cc -DCXPLAT_NUMA_AWARE -DCX_PLATFORM_LINUX -DHAS_SENDMMSG -DHAS_SYSCONF -DHAS__SC_PHYS_PAGES -DQUIC_CLOG -DQUIC_ENABLE_CA_CERTIFICATE_FILE_TESTS -DQUIC_SHARED_EPHEMERAL_WORKAROUND -DQUIC_TEST_OPENSSL_FLAGS=1 -DVER_BUILD_ID=0 -DVER_GIT_HASH=216fc71d3ef68c7b63cd5666306aba8bc564e5ef -DVER_SUFFIX=-private -D_GNU_SOURCE -I/home/furt/github/wfurt-msquic/src/inc -I/home/furt/github/wfurt-msquic/src/generated/common -I/home/furt/github/wfurt-msquic/src/generated/linux -I/home/furt/github/wfurt-msquic/build/linux/x64_openssl/_deps/opensslquic-build/openssl/include  -Og -ggdb3   -fms-extensions -fPIC -Werror …
```
> fix build on Ubuntu 18

- scripts/make-packages.sh
debian dependencies were fix in  #2995. As noted, the RPM package names differ among various distributions. 
Because of that, we need to claim dependency on the actual library. Without specifying the 64bits, package manager seems to pull in both x86_64 and i686 binaries.  I left ie empty for 32bit as it seems to be ok. (no testing on arm)
cc: @manickap @rzikm @omajid 
Fedora37
Comes with OpenSSL 3, pulls in openssl1.1 as dependency.
```
[root@3add993fe42c wfurt-msquic]# openssl version
OpenSSL 3.0.5 5 Jul 2022 (Library: OpenSSL 3.0.5 5 Jul 2022)
[root@3add993fe42c wfurt-msquic]# dnf  install artifacts/packages/linux/x64_Release_openssl/libmsquic-2.2.0-1.x86_64.rpm
Last metadata expiration check: 1:04:21 ago on Thu Feb  2 02:42:00 2023.
Dependencies resolved. …
```
> fix dependency for rpm packages

- docs/api/ConnectionCertificateValidationComplete.md
- src/core/api.c
- src/core/connection.c
- src/core/crypto.c
- src/test/MsQuicTests.h
- src/test/bin/quic_gtest.cpp
- src/test/bin/winkernel/control.cpp
- src/test/lib/HandshakeTest.cpp
- src/test/lib/TestHelpers.h
Add test to repro scenario where server asynchronously validates a client certificate.
Update `ConnectionCertificateValidationComplete` to allow calling on server connections as well.
Existing and new tests in CI.
Update the documentation for `ConnectionCertificateValidationComplete` to allow use for server scenarios.
> Add test for async client certificate validation.

- submodules/CMakeLists.txt
follow-up on https://github.com/dotnet/runtime/pull/81481#discussion_r1095979398
attempt to use system crypto fails on Alpine Linux
```
ldd /usr/lib/libmsquic.so.2
/lib/ld-musl-x86_64.so.1 (0x7fbc0efdf000)
libcrypto.so.1.1 => /lib/libcrypto.so.1.1 (0x7fbc0ec00000)
libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x7fbc0efdf000)
Error relocating /usr/lib/libmsquic.so.2: EVP_seed_cbc: symbol not found
```
It is because it is build with `no-seed`
https://git.alpinelinux.org/aports/tree/main/openssl/APKBUILD?h=3.15-stable#n110
I could make this Alpine specific but I feel like we should not pull in parts that we don't need. 
So I left it as general change to decrease expectation from OS.
> build libssl with  no-seed

- scripts/get-buildconfig.ps1
- submodules/CMakeLists.txt
This is follow-up on https://github.com/microsoft/msquic/pull/3387#issuecomment-1412201754
I changed the check so 3.0.2 would be acceptable when we expect 3.0. 
The problem its that if we expect `1.1.1`, `3.0` would also work with `VERSION_GREATER`.
To fix that, I now construct subversion as `1.1` or '3.0' and I use that for comparison as well. 
The expected `1.1.1` would never match but the `3.0` would work as expected. 
Running "wrong" configure on Ubuntu 22 now produce
```
$ pwsh scripts/build.ps1 -Tls openssl -UseSystemOpenSSLCrypto
fatal: no tag exactly matches '28bc496577c067fc7657588f933d8178b79849b2'
[02/01/2023 12:36:07] Generating files...
Executing: -G "Unix Makefiles" "Unix Makefiles" -DQUIC_TLS=openssl -DQUIC_OUTPUT_DIR="/home/furt/github/msquic/artifacts/bin/linux/x64_Debug_o …
```
> improve OpenSSL detection during build

- src/perf/lib/ThroughputClient.cpp
The description of parameter `encrypt` in `secnetperf` is confusing. 
Changed from 
`-encrypt:<0/1>               Disables/enables encryption. (def:1)`
to 
`-encrypt:<0/1>               Enables/disables encryption. (def:1)` 
to ensure 0 stands for "enables" and 1 for "disables".
No tests are covering this change and no new tests are needed.
This impacts the `secnetperf` documentation of parameter `encrypt`.
> CHANGED: Description of encrypt parameter in secnetperf

- src/inc/quic_trace.h
Disable the code paths that were unnecessary triggered for logging (even when disabled).
Automation
N/A
> Disable Expensive Logging Stuff for LTTng

- .azure/obtemplates/build-winuser.yml
Our internal OneBranch builds were failing because of the known arm64 build failure. Disable those internal builds, just like we've done for the external.
Automation
N/A
> Disable OneBranch Windows OpenSSL arm64 Builds

- submodules/CMakeLists.txt
fixes Alpine binaries when build with -UseSystemCrypto
cc: @ManickaP
> [release/2.1] build libssl with  no-seed (#3394)

- scripts/performance.ps1
- scripts/prepare-machine.ps1
On Ubuntu20.04
prepare-machine.ps1 only initialize one of submodules/openssl, but build.ps1 use openssl3
https://github.com/microsoft/msquic/issues/3426
build succeeded by newly cloned repo
N/A
> Use same Tls as Prep

- .azure/azure-pipelines.ci.yml
- src/platform/tls_openssl.c
Contributes to https://github.com/microsoft/msquic/issues/2039
it seems like the context was not created properly so handling of tickets was failing.
Interestingly, OpenSSL would just surface internal error so it was not obvious what was happening. 
With this, all the tests can now pass for me on Ubuntu 22.04.
> fix MAC_CTX creation with OpenSSL 3

- src/inc/quic_platform_winuser.h
- src/platform/platform_worker.c
There is a very small race condition in event queue processing on Windows where we could dequeue an event on one thread and then another thread tries to enqueue it again, but zeros out the important user data before the dequeue thread has a chance to read it.
This PR fixes that by not ever zero'ing out the user data.
N/A
> Fix Race Condition Between Enqueue and Dequeue of Event Queue

- src/core/stream_set.c
While looking at the code, I noticed it was using the wrong variable to check if unidirectional or bidirectional streams were blocked. Updates the code to use the correct one.
Existing automation. Ideally, it might be good to add a test case for this.
N/A
> Fix Stream Blocked

- .azure/azure-pipelines.perf.yml
The pipeline was incorrecly triggering the linux openssl3 builds when only openssl was selected.
Automation
N/A
> Fix Manual Flag for OpenSSL3 Perf Pipeline

- src/inc/quic_platform_posix.h
- src/inc/quic_platform_winuser.h
- src/platform/unittest/PlatformTest.cpp
- src/platform/unittest/TlsTest.cpp
My recent PR for adding asserts to the event queue apparently broke the unittests. This fixes them.
This also fixes a recent Windows build regression on key exchange strength. Apparently the values are no longer zero. Commenting out these tests for now.
Existing automation.
N/A
> Fix Recent Breaks in Unittests

- src/core/listener.c
Seen in https://github.com/microsoft/msquic/actions/runs/4196169506/jobs/7276764256, the listener was checking a flag after it was freed on a different thread.
This updates the code to cache the variable that decided if we free the listener before setting the stop event, which wakes the other thread to free the listener first (in some cases).
N/A
> Fix Listener Use after Free in Cleanup Path

- src/core/library.c
@ami-GS found an issue where our logic for preventing ephemeral matches on Linux wasn't working correctly between client and server sockets. The issue was that we weren't finding the matching server socket when the networking stack returned us a client socket that matched it.
The fix updates the `QuicLibraryLookupBinding` function to make sure the server socket is returned if it is using the same local port as the requested client socket. This will then trigger the fallback logic to start looking for a new socket instead.
**Note** - This *might* be a good candidate for backport to 2.1...
Existing automation.
N/A
> Update the Binding Lookup Logic to Match Server and Client Sockets

- scripts/make-packages.sh
This adds option to package msquic with 'openssl3' tls
```
$./scripts/make-packages.sh -c Release -t openssl3
$rpm -qpR artifacts/packages/linux/x64_Release_openssl3/libmsquic-2.2.0-1.x86_64.rpm
libcrypto.so.3()(64bit)
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
$ dpkg -I   artifacts/packages/linux/x64_Release_openssl3/libmsquic_2.2.0_amd64.deb
new Debian package, version 2.0.
size 5482352 bytes: control archive=540 bytes.
373 bytes,    14 lines      control
233 bytes,     3 lines      md5sums
Package: libmsquic
Version: 2.2.0
License: MIT
Vendor: Microsoft
Architecture: amd64
Maintainer: Microsoft QUIC Team [quicdev@microsoft.com](mailto:quicdev@microsoft.com)
Installed-Size: 16628
Depends: libssl3
Conflicts: libmsquic-debug
Provides: libmsquic
Section: …
```
> fix packaging for OpenSSL 3

- src/test/lib/PathTest.cpp
https://github.com/microsoft/msquic/issues/1805
The test is incrementing client port by hooking server side interface.
The test timed out by (maybe) client port is changed to that of server.
This fix is just skip when server side hook try to change client port to same as server
test fix
N/A
> Fix loopback test to use same port as that of server

- src/core/library.c
It's possible for the counters to hit some of these values with spinquic in debug mode. That's not a bad thing, and we don't want the fuzzer going crazy over it. Just disable them.
Automation.
N/A
> Disable Perf Counter Telemetry Asserts in Debug Mode

- src/platform/crypt_openssl.c
The problem is fact that `EVP_chacha20_poly1305` is also referenced from `ossl_init_ssl_base`. That is linked  statically but the dependency may be missing. 
The fix is to override that function and return CXPLAT_CHACHA20_POLY1305_ALG_HANDLE e.g. point at the original implementation. The `ossl_init_ssl_base`  may run before the `CxPlatCryptInitialize` loads. I check and the `EVP_add_cipher` would silently ignore if `NULL` is passed in. 
contributes to #3422
> another attempt to fix quic loading when chacha is missing

- src/core/connection.c
- src/platform/hashtable.c
Thanks to https://twitter.com/nachoskrnl for finding these. One is a small race condition on cleanup where we should clear the registration pointer, and the other is a copy/paste issue (in a comment) from a few years back.
Automation
N/A
> Few Fixes Identified On Twitter

- src/test/lib/DatagramTest.cpp
Fixes https://github.com/microsoft/msquic/issues/1994
Datagram get lost at unexpected point. Which causes failure by validating the number of packets get lost.
Running some hours.....
> Fix DatagramSend test by expecting multiple loss

- src/core/send.c
- src/core/send.h
Fixes #3478, which is a benign assert during connection uninitialization where some send flags were left over and not matching the expected state.
Existing CI
N/A
> Improve Send Cleanup Path to Fix Benign Assert

- src/platform/tls_openssl.c
OpenSSL only, contributes to #2344
> get client random if setting TlsSecrets on server

- src/test/lib/ApiTest.cpp
We are fixing the product code up-level to 0.0.0.0 being set to remote addr, and it caused these tests to fail.
Existing CI
N/A
> Fix Remote Addr Tests Down Level (v2.1)

- docs/Diagnostics.md
Described to build `clog2text_lttng` on Linux and enable `lttng` logging in an application.
There are no build tests, this is strictly a doc change.
Update is to documentation.
> Document how to build and use clog2text and lttng

- src/core/unittest/TransportParamTest.cpp
- src/platform/platform_posix.c
- src/platform/platform_winuser.c
- src/platform/tls_openssl.c
- src/platform/unittest/TlsTest.cpp
- src/test/lib/TestHelpers.h
A test case was failing with verifier enabled when we tried to allocate a zero by buffer for `QUIC_PARAM_GLOBAL_VERSION_NEGOTIATION_ENABLED` `GlobalSettingScope` test.
Existing CI
N/A
> Fix Zero-byte Test Allocation

- CMakeLists.txt
- src/generated/linux/tls_openssl.c.clog.h
- src/generated/linux/tls_openssl.c.clog.h.lttng.h
- src/inc/quic_crypt.h
- src/platform/crypt_bcrypt.c
- src/platform/crypt_openssl.c
- src/platform/platform_posix.c
- src/platform/tls_openssl.c
- src/platform/unittest/TlsTest.cpp
backport of two changes to load msquic on Centos 7 and Mariner Linux 2.0 
fixes #3422
> [release/2.1] make chacha optional on Linux 

- src/core/send.c
It's possible that when sending a path challenge, the route is not yet resolved. We need to pause and resume path challenge when that happens.
CI
> Handle sending path challenge on paths that have not resolved route yet

- src/core/crypto.c
- src/core/crypto.h
- src/core/crypto_tls.c
- src/platform/tls_openssl.c
- src/platform/tls_schannel.c
- src/test/lib/DataTest.cpp
- src/test/lib/HandshakeTest.cpp
- src/test/lib/TestConnection.cpp
- src/test/lib/TestConnection.h
- src/test/lib/TestHelpers.h
Fixes #2344
Specifically,
* Copies the ClientRandom on server side.
* Copies the ClientEarlyTrafficSecret on server side.
* Copies the ClientRandom on client side when 0-RTT is used.
* Manual testing with quicinteropserver to ensure the ClientRandom is logged.
* New automated tests.
N/A
> Fix QUIC_TLS_SECRETS on Server and Client.

- docs/TEST.md
Add instructions for testing on a different machine from the one that builds msquic. It's useful for testing XDP datapath and KM msquic.
> Add instructions for testing on a different machine

- src/test/lib/ApiTest.cpp
Fixes a test bug found on the Windows side where perf counters were non-zero.
Existing automation. Will have to ingest into Windows to verify fix.
N/A
> Perf Counters can be non-zero on Release Tests

- src/test/lib/ApiTest.cpp
Fix a test bug where the perf counters can be non-zero on release builds.
CI. Need to be ingested to verify.
N/A
> Perf counters can be non-zero on release part 2

- src/platform/datapath_raw_socket.c
- src/test/lib/DatagramTest.cpp
We can't guarantee getting the datagram lost event because it required an ACK, which has to come from a new packet being sent. So just remove the check.
Automation
N/A
> More Datagram Test Fixes

- src/manifest/MsQuic.wprp
- src/test/bin/quic_gtest.cpp
- src/test/bin/quic_gtest.h
- src/test/lib/ApiTest.cpp
- src/test/lib/DataTest.cpp
- src/test/lib/MtuTest.cpp
Test code references the flag `UseQTIP` defined in quic_gtest.cpp unconditionally for RAW datapath. However, the definition of UseQTIP is gated behind QUIC_API_ENABLE_PREVIEW_FEATURES.
This PR gates all references behind the same macro, QUIC_API_ENABLE_PREVIEW_FEATURES and QUIC_USE_RAW_DATAPATH.
CI
> Fix QTIP tests in release branch

- .azure/OneBranch.Publish.yml
- .azure/dockers/ob/pkg-publish/publish-packages.sh
- .azure/obtemplates/upload-linux-package.yml
- scripts/upload-linux-packages.sh
Automatically upload signed linux packages to PMC repos. Triggered by tags.
Currently, intentionally not use the correct secret to avoid accidentally uploading unexpected packages to PMC repos. After we create the new release and tag, we will need to change `-s $(Client)` to `-s $(Secret)` in .azure/dockers/ob/pkg-publish/publish-packages.sh.
Tested in OB pipeline when the trigger is always on.
> Automatic linux package publish pipeline Part 2

- .azure/OneBranch.Official.yml
- .azure/dockers/ob/windows/Dockerfile
Use vse2022:latest to avoid onebranch warnings
OB CI
> Use vse2022:latest to avoid onebranch warnings

- .azure/OneBranch.Docker.Official.yml
1. Clean up the official docker image build pipeline and make it run on every Saturday.
2. Make the pipeline triggered by any changes to the docker file.
3. The task for linux build docker has been removed because we don't use onebranch hosted docker images for linux builds.
OB CI
> Scheduled windows docker update pipeline

- .azure/OneBranch.Official.yml
- .azure/dockers/ob/windows/Dockerfile
> Backport "Use vse2022:latest to avoid onebranch warnings" to 2.2

- src/core/path.c
- src/core/path.h
Add check for invalid path removal case. It shouldn't ever happen, but from some crashes I've seen, I suspect it might be happening.
N/A
> Prevent Path Removal Underflow

- src/platform/datapath_raw.c
- src/platform/datapath_raw_dpdk.c
- src/platform/datapath_raw_xdp.c
Wire up the initial plumbing to QEO in XDP.
Must wait for real HW or official tests.
N/A
> Plumb QEO to XDP

- src/core/api.c
- src/core/binding.c
- src/core/connection.c
- src/core/operation.h
- src/core/registration.c
- src/core/stream_send.c
Fixes #3638 and #3639. In the rare case (OOM) that stream start fails when you use the `QUIC_SEND_FLAG_START` flag, it should be delivering a shutdown complete event to indicate this failure to start. Also fixes more event issues in the case of OOM in the send flush operation alloc path.
Existing automation and manual testing from original bug opener.
N/A
> Shutdown Stream on Send/Start Failure

- src/generated/linux/platform_winuser.c.clog.h
- src/generated/linux/platform_winuser.c.clog.h.lttng.h
- src/platform/platform_winuser.c
We're incorrectly building our processor mapping tables for only the active processor count, but then using max to look up in the table.
Existing + manual (WIP)
N/A
> Build Processor Info for Max Processors

- src/core/crypto.c
- src/test/lib/HandshakeTest.cpp
Currently, while we're narrowing down the ALPN list with ReNegotiation, if we can't negotiate with client on ALPN, we're closing the connection with `QUIC_ERROR_INTERNAL_ERROR`, but looks like it should be `QUIC_ERROR_CRYPTO_NO_APPLICATION_PROTOCOL`.
I've updated the necessary unit test, but this is a breaking change since we're changing close status behavior.
No
> Fix transport error code for new alpn negotiation

- src/generated/linux/datapath_raw_xdp.c.clog.h
- src/generated/linux/datapath_raw_xdp.c.clog.h.lttng.h
- src/manifest/clog.sidecar
- src/platform/datapath_raw.h
- src/platform/datapath_raw_socket.c
- src/platform/datapath_raw_xdp.c
If XDP runs on VM with SR-IOV, trying to attach XDP to VF
Send/Recv is failing
N/A
> Attaching XDP to VF

- src/platform/datapath_raw_xdp.c
The interface list is initialized after calling XdpOpenAPI. When XdpOpenAPI fails, the code checks an uninitialized list, which triggers an AV.
Found by @pongba.
Not covered.
> Correctly handle XdpOpenAPi failure

- src/core/binding.c
- src/core/connection.c
- src/core/inline.c
- src/core/library.c
- src/core/library.h
- src/core/packet_builder.c
- src/core/packet_space.c
Updates the code to use current partition everywhere instead of current processor directly, because current processor may be beyond the allowable partitions.
Automation
N/A
> Current Partition instead of Current Processor

- scripts/make-packages.sh
Fixes #3421.
Existing automation covers some of this.
N/A
> Update Linux Packages to Depend on libnuma

- docs/api/QUIC_CONNECTION_EVENT.md
- docs/api/StreamOpen.md
- src/core/api.c
- src/core/connection.c
- src/core/stream.c
- src/core/stream.h
- src/core/stream_set.c
- src/cs/lib/msquic_generated.cs
- src/generated/linux/stream.c.clog.h
- src/generated/linux/stream.c.clog.h.lttng.h
- src/generated/linux/stream_set.c.clog.h
- src/generated/linux/stream_set.c.clog.h.lttng.h
- src/inc/msquic.h
- src/manifest/clog.sidecar
- src/plugins/dbg/quictypes.h
- src/tools/spin/spinquic.cpp
Sometimes apps might want to delay the stream ID FC updates to StreamClose if they intend on doing significant work between SHUTDOWN_COMPLETE and the close call.
Updated spinquic.
Updated.
> Support Delaying Stream ID FC Updates to StreamClose

- docs/api/QUIC_CONNECTION_EVENT.md
- docs/api/StreamOpen.md
- src/core/api.c
- src/core/stream.c
- src/core/stream.h
- src/core/stream_set.c
- src/cs/lib/msquic_generated.cs
- src/generated/linux/stream.c.clog.h
- src/generated/linux/stream.c.clog.h.lttng.h
- src/generated/linux/stream_set.c.clog.h
- src/generated/linux/stream_set.c.clog.h.lttng.h
- src/inc/msquic.h
- src/manifest/clog.sidecar
- src/plugins/dbg/quictypes.h
- src/tools/spin/spinquic.cpp
Cherry-pick #3665 to release/2.2.
> Support Delaying Stream ID FC Updates to StreamClose (#3665)

- .azure/OneBranch.Publish.yml
Publish pipeline sometimes fails due to infra issues from PMC, ESRP and etc. Allow the pipeline to publish new releases through manually triggered runs.
OB CI
> Publish pipeline manual mode

- src/platform/datapath_raw_socket.c
UDPv6 requires checksum to be non-zero.
CI
> Fix UDPv6 checksum

- src/core/worker.c
The QUIC_WORKER Worker->Ready event handle is created unconditionally in QuicWorkerInitialize, but only closed `if (!Worker->IsExternal)` in QuicWorkerUninitialize. The handle is leaked in other cases.
This leak was detected by AppVerifier in the HTTP.SYS tests.
> Fix worker event handle leak in MsQuic!RegistrationClose

- src/platform/datapath_raw_xdp.c
We were passing array size instead of the total byte count.
Existing
N/A
> Connections Size, Not Count

- src/generated/linux/platform_winuser.c.clog.h
- src/generated/linux/platform_winuser.c.clog.h.lttng.h
- src/inc/quic_platform_posix.h
- src/inc/quic_platform_winkernel.h
- src/inc/quic_platform_winuser.h
- src/manifest/clog.sidecar
- src/perf/lib/RpsClient.cpp
- src/perf/lib/RpsClient.h
- src/platform/platform_winuser.c
Recent changes to how the processor index is calculated broke RPS tests on Windows. This fixes them by taking into account that a given processor index may refer to an inactive processor (since we track maximum, not active, processors). The RPS test code wants to only use active processors, so it iterates over all processors, skipping inactive ones.
Automation
N/A
> Fix RPS Processor Usage

- .azure/obtemplates/run-bvt.yml
Recent signing changes regressed OneBranch tests. This updates the OneBranch test pipeline to sign the drivers before installing them.
Will need to mirror into OneBranch to test.
N/A
> Sign Drivers for OneBranch Testing

- .github/workflows/test.yml
- scripts/prepare-machine.ps1
Linux BVT tests are skipped due to linux permission issue because the artifacts are built somewhere else.
CI
> Fix skipped linux tests

- src/generated/stdout/quic_trace.c
Fix compile error for library build with stdout logging type when using older compilers without C23 standard syntax support.
> Fix syntax for pre-C23 standard compilers

- src/core/unittest/CMakeLists.txt
- src/platform/unittest/CMakeLists.txt
- src/test/bin/CMakeLists.txt
- src/tools/CMakeLists.txt
RUNPATH is by default set to the folder where the binary is located at build time. This makes locally reproducing issues cumbersome for Linux. Also, if the build and test runner machine have different folder structure, our tests won't run due to this issue.
CI
> Set $ORIGIN in RUNPATH in linux binaries

- .github/workflows/package-linux.yml
The test is supposed to test if the installed package can be loaded into BVT test. However, the libs are also present in the same folder where the test is. Delete them to make sure libs in the package gets loaded.
CI
> Delete msquic libs in packgaging test in case they get loaded instead of the ones in the installed package

- .docker/ubuntu-20.04/Dockerfile
- .docker/ubuntu-22.04/Dockerfile
Pin the hash so the security warnings go away.
CI
> Pin ubuntu docker base image hash

- .github/workflows/build-reuse-darwin-framework.yml
- .github/workflows/build-reuse-unix.yml
- .github/workflows/build-reuse-win.yml
- .github/workflows/build-reuse-winkernel.yml
- .github/workflows/build.yml
- .github/workflows/dotnet-test.yml
- .github/workflows/test-down-level.yml
- .github/workflows/test.yml
- scripts/prepare-machine.ps1
1. Skip installing signing certs if `ForTest` is not used with `ForKernel` in prepare-machine.ps1.
2. Only fetch the number of commits in checkout action required by the workflow.
CI
> Minor fixes for Github workflows

- src/core/listener.c
Noticed that a few lines were uncovered in code coverage, so I did some minimal refactoring to clean that up.
Existing CI
N/A
> Minor Changes to Improve Listener Code Coverage

- docs/Settings.md
- src/core/connection.c
- src/cs/lib/msquic_generated.cs
- src/inc/msquic.h
- src/test/lib/ApiTest.cpp
This PR fixes #3613 that requests a new feature which allows clients and servers to get the original destination CID of the client that initialized the connection. 
A new test was added that checks the various fail conditions and edge cases.
Yes, a new GetParameter was added.
> Support retrieving the initial destination CID from GetParam

- src/platform/selfsign_openssl.c
Renamed the variable 'X509' to 'x509' to fix a compilation warning issued by GCC. The warning was due to the variable name being the same as the class name. This change prevents any confusion or issues related to naming conflicts.
>Do any existing tests cover this change?
Yes.
>Are new tests needed?
No.
> Is there any documentation impact for this change?
No.
> Refactor: Resolved GCC compilation warning by renaming variable.

- .github/workflows/test.yml
While investigating why certain stress tests were crashing in [Add QUIC_SETTINGS Support to SpinQuic by nibanks](https://github.com/microsoft/msquic/pull/3758), it became apparent that finding the crash dump artifact is somewhat cumbersome in the current CI pipeline as pointed out by Yi. 
This PR addresses this issue by explicitly tagging the artifacts that get uploaded as a result of a failure of a stress tests to make the process of finding it's crash dump easier.
N/A
No
> Tag artifacts uploaded due to a failure with their corresponding test type

- src/platform/CMakeLists.txt
- src/platform/datapath_raw_xdp_win.c
Use `XdpLoadApi` which uses run-time linking instead of `XdpOpenApi` which uses load-time linking.
CI/CD
No.
> Dynamically load/unload xdp dll

- src/inc/msquic.hpp
- src/perf/lib/PerfServer.cpp
- src/perf/lib/PerfServer.h
- src/test/lib/ApiTest.cpp
- src/test/lib/DataTest.cpp
- src/test/lib/EventTest.cpp
This PR completes the MsQuicListener implementation in that it adds a proper C++-style MsQuicListenerCallback type. This type is in line with other callback implementations in the C++ wrapper. Furthermore, the PR improves the consistency of some function signatures and adds a few retrieval functions for certain object parameters.
These changes are affect certain tests, which have been updated accordingly. New API additions where not added to the tests.
Smaller API changes and additions have been made and might require doc updates.
> Improve C++ wrapper.

- src/platform/datapath_raw_socket.c
Uses the UDP length field instead of the IP length for receiving the UDP payload. Fixes #3776.
CI
N/A
> Use UDP Length for XDP RX

- scripts/prepare-machine.ps1
- scripts/xdp-devkit.json
- scripts/xdp-install.ps1
- src/platform/datapath_raw_xdp_win.c
Upgrade to XDP v0.17.0 This contains a number of editorial API changes and an MSI installer. The QEO function is also now an optional function in XDP.
Builds locally. CI/CD.
I don't think so.
> Consume XDP v0.17.0

- src/core/configuration.h
- src/core/connection.h
- src/core/listener.h
- src/core/registration.h
- src/core/stream.h
Add a name to unnamed struct QUIC_HANDLE to improve compatibility with C++. #3785 
> Add a name to unnamed struct QUIC_HANDLE

- src/core/connection.c
Logic wasn't correct for determining when a short header packet wasn't actually encrypted.
Will do manual testing.
N/A
> Fix QEO RX Packet Encrypted Logic

- .azure/OneBranch.Publish.yml
Adds Debian 12 (bookworm) to the list of distros to publish to. Debian 12 was released on [June 10](https://www.debian.org/releases/bookworm/). The distro already exists on [packages.microsoft.com](https://packages.microsoft.com/debian/12/prod/). LMK if I've missed something @nibanks @csujedihy
The second change is an attempt to fix Fedora 37 usecase, which has strange problems with OpenSSL 3 package (https://github.com/microsoft/msquic/issues/3640#issuecomment-1579439966). However, the distro has a compat OpenSSL 1.1 package, so I propose to fallback to that, given that the distro will be supported only until [2023-11-14](https://fedorapeople.org/groups/schedule/f-39/f-39-key-tasks.html).
I've verified that Ubuntu 22.04 package (OpenSSL 3) works on Debian 12, and that CentOS 8 package …
> Add Debian 12 package & fix Fedora 37 package

- .gitmodules
Consumes the latest OpenSSL v3 release. Notes: https://www.openssl.org/news/openssl-3.1-notes.html
Automation
N/A
> Update OpenSSL to v3.1.2

- .azure/obtemplates/run-bvt.yml
Fixes the kernel OneBranch tests by making sure to prepare machine for kernel mode, which includes downloading signing certs.
Automation
N/A
> Fix OneBranch Kernel Tests

- .github/workflows/build-reuse-darwin-framework.yml
- .github/workflows/build-reuse-unix.yml
- .github/workflows/build-reuse-win.yml
- .github/workflows/build-reuse-winkernel.yml
- .github/workflows/stress.yml
- .github/workflows/test.yml
Artifacts uploaded in a GitHub workflow cannot be accessed before the entire workflow has completed. Split stress and BVT so we can get to the dumps generated from stress sooner.
Remove `workflow_dispatch` from reusable worfklows because they are not supposed to be run directly.
CI
> Split stress test and BVT test

- codecov.yml
Add a config file for codecov so that the workflow won't just fail for every PR when code coverage moves a little bit due to stress test.
Feel free to push a change to modify the threshold and target.
Currently, for the whole project, it compares with the parent commit and fails if the coverage is down more than 2% (threshold).
For the diff in a PR/commit, I currently set the target to 80% with a 2% threshold.
CI
> Configure Codecov to reduce noise

- src/test/lib/ApiTest.cpp
- src/test/lib/DataTest.cpp
- src/test/lib/MtuTest.cpp
- src/test/lib/precomp.h
Kernel build has build warning by trying to define `UseQTIP` multiple times.
build matter
N/A
> fix kernel build warning

- .azure/obtemplates/build-linux.yml
- .azure/obtemplates/build-winuser-xdp.yml
- .azure/obtemplates/build-winuser.yml
- scripts/build.ps1
With a recent change to fetch depth, our logic to determine if we're doing an official break, based on reading tags, broke (they aren't present any more). Rework things so we don't care for the public CI.
BTW, the break above was causing all prerelease tests to get disabled on Windows. Fixing that is the primary motivation here.
Automation
N/A
> Only do Official Releases in OneBranch

- src/inc/msquicp.h
- src/inc/quic_platform_winuser.h
- src/test/bin/quic_gtest.cpp
For some reason the previous logic for setting the `DEBUG` flag didn't work for Windows user mode always (i.e. not in CI, but it did locally). Updates the logic to hopefully work consistently now.
Automation
N/A
> Fix Debug Builds on Windows User Mode

- .github/workflows/code-coverage.yml
There are a lot of lines not executed in packet.c and frame.c that are related to logging. Enable those logs during code coverage.
Automation
N/A
> Enable logs to get the code coverage

- src/platform/datapath_winuser.c
XDP and normal socket has different data structure, which makes address calculation difficult.
Add new struct to wrap CXPLAT_RECV_DATA by SOCK specific struct
automation
N/A
> wrap metadata with CXPLAT_RECV_DATA to be same as XDP_RX_PACKET

- src/core/binding.c
- src/core/binding.h
- src/core/connection.c
- src/core/datagram.c
- src/core/datagram.h
- src/core/inline.c
- src/core/library.c
- src/core/packet.c
- src/core/packet.h
- src/core/stream.h
- src/core/stream_recv.c
- src/core/worker.c
- src/generated/linux/datapath_winkernel.c.clog.h
- src/generated/linux/datapath_winkernel.c.clog.h.lttng.h
- src/generated/linux/packet.c.clog.h
- src/generated/linux/packet.c.clog.h.lttng.h
- src/inc/quic_datapath.h
- src/manifest/clog.sidecar
- src/platform/datapath_epoll.c
- src/platform/datapath_kqueue.c
- src/platform/datapath_raw_dpdk.c
- src/platform/datapath_raw_xdp_linux.c
- src/platform/datapath_raw_xdp_win.c
- src/platform/datapath_winkernel.c
- src/platform/datapath_winuser.c
Cleans up a few things:
1. Creates a clear abstraction between QUIC and platform layer.
2. Renames QUIC layer objects to remove CXPLAT name.
3. Refactors internals of datapaths to have similar structs/names to make it easier to understand (and maybe converge eventually).
N/A
> Refactor the RX Datapath Object Abstraction Model

- src/core/listener.c
- src/core/listener.h
- src/core/registration.c
- src/core/registration.h
> feat: close listeners in registration rundown

- src/plugins/trace/dll/DataModel/QuicStream.cs
Fixes bugs found while manually inspecting some traces with the WPA plugin.
Manually with some traces
N/A
> WPA Plugin Fixes for Stream Timing Breakdowns

- src/tools/attack/packet_writer.cpp
Sometime in the past, the tool was broken in its TLS abstraction layer. This fixes that.
Manually
N/A
> Fix Attack Tool

- .github/workflows/build-reuse-darwin-framework.yml
- .github/workflows/build-reuse-unix.yml
- .github/workflows/build-reuse-win.yml
- .github/workflows/build-reuse-winkernel.yml
Updates the reusable build yamls to explicitly specify this repository, so when another repository reuses it (for perf automation), it doesn't use that one instead.
Tested via microsoft/netperf experimental workflow.
N/A
> Explicitly Set Checkout Repository

- scripts/build.ps1
.NET builds msquic using the same script (script/build.ps1) that we use to build the project, which does not work well with their cross-compile method where a toolchain file is not used as reported in https://github.com/dotnet/msquic/pull/149.
This PR allows empty toolchain file for cross-compile. So, we only use a default toolchain file for our own OneBranch/container builds.
Needs help from @wfurt to test it.
> Set default toolchain file only for OneBranch/container builds

- .github/workflows/publish-docfx.yml
Trigger for pushes did not take into account changes to the workflow YAML itself.
I had implicitly assumed that updating the workflow YAML file itself would trigger a workflow run automatically.
Therefore publish-docfx workflow did not run.
Updating paths to account for this.
N/A
N/A
> Add run on_push.

- .github/workflows/publish-docfx.yml
We can see bash was used instead of powershell in this run: https://github.com/microsoft/msquic/actions/runs/6243171195/job/16948179512. That means the pipe operator did not work correctly.
Indentations are used by YAML pipes to discern distinct commands, spaces were used (previously I was unaware my tabs got converted to 4 spaces in vscode). 
To avoid this whole mess, avoid using pipes + indentations and separate out the `run` commands. 
Apologies for any inconveniences :)
Added a clause to the workflow to allow commits on manual dispatch, for additional verification.
Here is a successful run (with commit): https://github.com/microsoft/msquic/actions/runs/6243193515/job/16948251428 
We can remove the workflow_run on-commit clause if it's decided that isn't smart for main branch. But we …
> Do not use pipe operator.

- src/generated/linux/datapath_epoll.c.clog.h
- src/generated/linux/datapath_epoll.c.clog.h.lttng.h
- src/platform/datapath_epoll.c
Update Linux epoll datapath to fallback to non-GSO sends if the `EIO` error is returned, which most likely indicates the NIC doesn't support it. This seems to be the case on at least some Android devices.
Fixed #3865.
CI/CD for regression testing. Not sure how to actually test this fallback atm.
N/A
> Disable Segmentation Support on EIO

- src/generated/stdout/quic_trace.c
Backports #3736 to release/2.2
> Backport v2.2: Fix syntax for pre-C23 standard compilers (#3736)

- scripts/build.ps1
GitHub Runners started pushing a new version of the Android NDK that seems to be breaking openssl builds. This change continues to use the older version.
CI/CD
None
> Work Around Android Build Failures

- src/inc/quic_datapath.h
QuicCopyRouteInfo copies up to before State
N/A
N/A
> move DatapathType location to be copied by QuicCopyRouteInfo

- src/platform/platform_posix.c
fix a NumaNodeMasks leakage.
N/A
> fix: leakage of NumaNodeMasks

- src/platform/datapath_raw_socket.c
- src/platform/datapath_win.c
- src/test/MsQuicTests.h
- src/test/bin/quic_gtest.cpp
- src/test/bin/winkernel/control.cpp
- src/test/lib/HandshakeTest.cpp
main branch has issue of CxPlatSendDataAlloc where the Config->Route->DatapathType unexpectedly become _TYPE_USER even though Config->Route->Queue is set to XDP_QUEUE*.
See CI result
N/A
> Fix route updating logic

- src/inc/msquic.h
- src/inc/msquic.hpp
- src/inc/msquic_posix.h
For non-MSVC compilers, <code>#pragma once</code> shall be replaced with more generic and reliable include guard method. In addition, <code>#pragma warning(disable:\*)</code> are not supported by non-MSVC compilers, it shall not be enabled in public header files (<code>\*.h</code> and <code>\*.hpp</code> files) for all non-MSVC compilers.
Compile test.
No impact.
> Avoid using unknown #pragma for non-MSVC compiler in public header files.

- src/core/api.c
Updates the StreamSend code to make sure we hold the ref before trying to queue the operation, just in case the send is drained, canceled and the stream closed before the current thread complete.
CI/CD
N/A
> Move Stream Send Reference

- src/core/stream.h
- src/core/stream_send.c
- src/generated/linux/stream_send.c.clog.h
- src/generated/linux/stream_send.c.clog.h.lttng.h
- src/test/lib/DataTest.cpp
This PR proposes a solution to handle bad behavior by the app: the application exhibits undesirable behavior by attempting to send data after or during a send shutdown operation in the reliable reset path.
This PR also refactors the sendFlush method, and attempts to address the ETW trace misconfiguration in issue #3891 
Added an extra send in Datateset after calling shutdown.
n/a
> Handle bad behavior by app in reliable shutdown path.

- src/platform/datapath_epoll.c
It should account for MIN MTU, not MAX.
Updates #3917
This PR increases the value for the constant controlling the max number of datagrams per coalesced group on Linux. Previously this value was lower than what the max batch size needed to reach in cases where MTU < 1500.
I'm not familiar with related unit tests, but I have verified this fixes #3917 in functional testing.
Not to my knowledge.
> datapath_epoll: adjust CXPLAT_MAX_IO_BATCH_SIZE arithmetic

- scripts/log.ps1
try-catch does not work to catch perf command existence.
Sadly, the command result changes once the system install the linux-tools even after uninstall the tools. 
N/A
> Fix perf command existence check

- src/test/lib/ApiTest.cpp
From recent CI testing, it looks like MsQuicLib.Datapath isn't being uninitialized, which is the case for Kernel mode tests.
In that case, tests that expect MsQuicLib.Datapath to be NULL is erroneously finding out it's still initialized.
In those cases, since we don't support them in Kernel mode, we will just skip them.
N/A
N/A
> Skip Datapath Global Param tests while in Kernel mode.

- scripts/build.ps1
Android is tweaking.
Old workaround didn't work due to slightly different newer version of Android being released... 
Just use regex to replace it.
CI
N/A
> Do not hardcode Android version

- src/test/lib/precomp.h
Turn off optimizations for functional tests for arm64 to work around arm64 stack overflow due to compiler over-aggressive optimizations.
Will need to inspect the disassembly from CI.
> Turn off optimizations for functional tests for arm64

- src/core/ack_tracker.c
- src/core/connection.c
- src/core/connection.h
- src/core/inline.c
- src/core/send.c
- Support disabling delayed ACK.
- Don't include timer resolution when polling timeout is greater than delayed ACK timeout.
CI/CD
N/A
> Better Delayed ACK Support

- src/core/connection.c
- src/core/connection.h
- src/core/stream.c
Make sure to keep the connection alive as long as the stream.
CI/CD
N/A
> Streams Hold References on Connections

- src/platform/datapath_epoll.c
- src/platform/platform_internal.h
There are a few bugs in the epoll TCP implementation.
1. TX: busy spinning on non-blocking socket regardless of whether eagain/ewouldblock is encountered.
2. RX: not draining all of the ready data upon EPOLLIN signal.
3. Wrong buffer length passed to read, which causes debug build to crash consistently.
4. Unnecessary RSS config for TCP server sockets.
Local perf test in WSL showed 2x perf improvement with loopback but the numbers from the perf machines didn't seem to move at all.
CI
> Fix epoll TCP implementation

- src/platform/platform_worker.c
We've found concrete examples where CPU affinitization hurts latency significantly, and initial tests seem to indicate minimal negative impact of just setting ideal processor.
CI/CD
N/A
> Don't Affinitize Platform Worker

- .github/workflows/stress.yml
- src/tools/recvfuzz/recvfuzz.cpp
This PR focuses on the the work involving fuzzing of the packets by modifying different bytes of the packet array instead of header values.
> New Way of Fuzzing Packet

- .azure/OneBranch.Tests.Official.yml
- .azure/OneBranch.Tests.PullRequest.yml
- .github/workflows/code-coverage.yml
- .github/workflows/stress.yml
- .github/workflows/test.yml
WSPrerelease is misconfigured to replicate unnecessarily to our own compute gallery and storage account, which costs money. This can't be undone due to limitations of 1ES system.
CI
> Use a new 1ES image that's configured correctly

- .azure/azure-pipelines.periodic.yml
- .azure/obtemplates/build-winuser.yml
Removes leftover usages of old prepare-machine arguments.
CI/CD
N/A
> Fix Internal Build Break from XDP Kit Removal

- docs/Streams.md
- docs/api/QUIC_CONNECTION_EVENT.md
- docs/api/StreamShutdown.md
- src/core/ack_tracker.c
- src/core/bbr.h
- src/core/connection.c
- src/core/connection.h
- src/core/loss_detection.c
- src/core/quicdef.h
- src/core/send.c
- src/core/transport_params.h
- src/plugins/dbg/quictypes.h
Remove the 'e' used in British English version of the word.
N/A
Updated
> Use American English Spelling of 'acknowledgment'

- src/perf/lib/RpsClient.h
without this fix, user of Linux aarch64 get `SIGBUS`
my OS ubuntu 20.04:
```
uname -a
Linux convincing-jellyfish 5.4.0-166-generic #183-Ubuntu SMP Mon Oct 2 11:31:37 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
```
gcc:
```
gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/aarch64-linux-gnu/9/lto-wrapper
Target: aarch64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.4.0-1ubuntu1~20.04.2' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=aarch64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib …
```
> fix(perf): RpsClient SIGBUS on aarch64

- src/test/bin/quic_gtest.cpp
- src/test/bin/winkernel/control.cpp
- src/test/lib/ApiTest.cpp
- src/test/lib/DataTest.cpp
- src/test/lib/EventTest.cpp
Internal build doesn't use preview features for tests. The code needs to account for this at build time.
CI/CD
N/A
> Fix Internal Build Referencing Preview Features

- src/inc/quic_datapath.h
Fix some code comment spelling in quic_datapath.h
N/A
N/A
> Fix some code comment spelling

- src/core/connection.c
- src/test/lib/HandshakeTest.cpp
- src/test/lib/TestConnection.cpp
- src/test/lib/TestConnection.h
The original destination CID field was getting freed when it was no longer used, but that's not very helpful to external consumers of it, so we need to remove the early free logic.
Updated the handshake tests to verify.
N/A
> Fix Original Destination CID Query

- .azure/OneBranch.Official.yml
The current image isn't cached anymore. Use a newer image that's cached.
OB CI
> Use a newer docker image for Onebranch build pipeline

- .docker/ubuntu-20.04/Dockerfile
- .docker/ubuntu-20.04/arm-cross-compile-sources.list
- .docker/ubuntu-22.04/Dockerfile
- .docker/ubuntu-22.04/arm-cross-compile-sources.list
One of the steps is modifying sources.list to add amd64 label for each repo. This step prints out the file and eventually redirects the output to the file itself. This doesn't work like a programming language where the statements are normally evaluated from left to right. The output of the redirection might get created before anything else, in which case, the resulting file will be empty. It seems like on a newer kernel, this particular step `RUN cat /etc/apt/sources.list | grep "^deb" | sed 's/deb /deb [arch=amd64] /g' > /etc/apt/sources.list` always generates an empty file whereas on an older kernel, it always generates the result that the step is intended to do.
Just never overwrite the file itself in a unix pipeline!
CI
> Fix cross-compile docker image building

- src/core/library.c
- src/core/unittest/SettingsTest.cpp
- src/generated/linux/platform_winuser.c.clog.h
- src/generated/linux/platform_winuser.c.clog.h.lttng.h
- src/inc/quic_platform_posix.h
- src/inc/quic_platform_winkernel.h
- src/inc/quic_platform_winuser.h
- src/perf/lib/PerfClient.cpp
- src/perf/lib/SecNetPerfMain.cpp
- src/perf/lib/Tcp.cpp
- src/platform/datapath_epoll.c
- src/platform/datapath_kqueue.c
- src/platform/datapath_raw_dpdk.c
- src/platform/datapath_raw_xdp_linux.c
- src/platform/datapath_raw_xdp_win.c
- src/platform/datapath_winkernel.c
- src/platform/datapath_winuser.c
- src/platform/platform_posix.c
- src/platform/platform_winkernel.c
- src/platform/platform_winuser.c
- src/platform/platform_worker.c
- src/platform/unittest/TlsTest.cpp
- src/test/lib/ApiTest.cpp
- src/tools/attack/attack.cpp
- src/tools/spin/spinquic.cpp
Removes the notion of "max" and "active" processor counts from the codebase, as this continued to be a source of platform specific bugs, and there is almost no real scenario where we expect the number of active processors to ever change. In these rare cases, we will just ignore these new processors.
CI/CD
N/A
> Refactor Processor Count Usage

- src/inc/msquic.hpp
- src/perf/lib/PerfClient.h
- src/perf/lib/PerfServer.cpp
- src/perf/lib/PerfServer.h
- src/perf/lib/Tcp.cpp
TCP code didn't parallelize its worker before. When I enabled that, I had to fix some other issues.
CI/CD
N/A
> Update TCP testing to Run in Parallel

- src/tools/attack/attack.cpp
Enable the attacking tool to control the attacking rate, to allow for granular comparison between different DoS attack types.
Manually tested my changes with an attacker VM that has XDP option enabled and a target VM that has Windows HTTP server running.
n/a
> Add 'attacking rate' option to the attacking tool.

- scripts/clog.inputs
- src/core/recv_buffer.h
- src/core/unittest/CMakeLists.txt
- src/core/unittest/RecvBufferTest.cpp
- src/generated/linux/RecvBufferTest.cpp.clog.h
- src/generated/linux/quic.clog_RecvBufferTest.cpp.clog.h.c
We will be refactoring `QUIC_RECV_BUFFER` to support multiple parallel outstanding reads, so let's add some tests first to make sure we don't regress things with the upcoming refactor.
Added
N/A - internal interface
> Add New Receive Buffer Unit Tests

- src/core/connection.c
- src/core/connection.h
- src/core/inline.c
- src/core/timer_wheel.c
- src/generated/linux/connection.c.clog.h
- src/generated/linux/connection.c.clog.h.lttng.h
The existing timer operations rely on a sorted timer entry array, where each entry has a type and expiration time, to maintain the earliest expiration time. However, it's not necessary to maintain a sorted array for this purpose. The earliest expiration time can be calculated on the fly when setting/canceling/expiring timers with the same complexity (it doesn't really matter as we only have a few timer types) and more readable code.
CI
> Simplify timer operations

- src/bin/CMakeLists.txt
Compile as static library in Ubuntu 22.04 LTS, may failed by try linking with dl.a, skip the dependency just like Threads::Threads can fix this issue
Resolved issue #3989
> Compile static library may failed by linking dl.a

- src/core/library.c
- src/core/unittest/SettingsTest.cpp
Fixing an issue where the CID prefix
lengths (`MsQuicLib.CidServerIdLength` and `MsQuicLib.CidTotalLength`) weren't being updated properly when transitioning the lb mode from its default state (disabled) to `QUIC_LOAD_BALANCING_SERVER_ID_IP`. This resulted in the server source CIDs not being prefixed with the source IP
New unittest:
```TEST(SettingsTest, GlobalLoadBalancingServerIDSet)```
NO
> fix: apply lb settings after lb mode change

- .github/workflows/build.yml
- .github/workflows/test.yml
No longer build on Windows Server 2019 as it is causing breaks in PGO. Still test on 2019, but use 2022 built binaries.
CI/CD
N/A
> Remove Windows 2019 Builds

- src/perf/lib/PerfClient.cpp
- src/perf/lib/PerfClient.h
- src/perf/lib/PerfServer.cpp
- src/perf/lib/PerfServer.h
- src/perf/lib/SecNetPerf.h
- src/perf/lib/SecNetPerfMain.cpp
- src/perf/lib/Tcp.h
Refactoring (mostly the server) code in secnetperf to make it simpler.
Built/tested locally. CI/CD
N/A
> More SecNetPerf Cleanup/Refactoring

- scripts/secnetperf-helpers.psm1
- scripts/secnetperf.ps1
With respect to improving database storage, we proposed a new SQL schema.
This PR adjusts the workflow script to generate SQL strings that conform to the new schema. 
CI
N/A
> Update SQL strings to conform to new format.

- .github/workflows/build-reuse-unix.yml
- .github/workflows/build-reuse-win.yml
- .github/workflows/build-reuse-winkernel.yml
- .github/workflows/code-coverage.yml
- .github/workflows/package-reuse-linux.yml
- .github/workflows/stress.yml
- .github/workflows/test.yml
Updates to allow NetPerf to build just the perf tools to improve build time, as well as copy/download artifact time.
Each reusable workflow renames the `test` parameter to a more general `build` parameter that does much the same thing, but also allows for `-Perf` to be passed in, and it will disable test and tools from being built.
CI/CD
N/A
> Update the Reusable Build Workflows to Support Perf Builds

- src/inc/msquic.h
Passing zero as timeout will cause KeWaitForSingleObject to not wait at all. We will lose the ability to wait forever but that's not useful and can still be somewhat achieved by passing a ULONG_MAX.
CI
> Allow NMR helpers to not wait at all

- src/bin/winkernel/msquicpriv.kernel.vcxproj
- src/bin/winkernel/nmrprovider.c
- src/inc/msquicp.h
- src/test/bin/winkernel/control.cpp
- src/test/bin/winkernel/msquictestpriv.kernel.vcxproj
The inbox msquic and the driver built by the CI/CD pipeline share the same NMR NPI. The tests might be testing the inbox version. This PR makes msquicpriv and tests use a private NPI that's different from the public msquic NMR NPI.
CI
> Fix tests not targeting private msquic.sys

- .github/workflows/build-reuse-winkernel.yml
- scripts/prepare-machine.ps1
- scripts/secnetperf-helpers.psm1
- scripts/secnetperf.ps1
- src/inc/msquic.hpp
- src/perf/lib/PerfClient.cpp
- src/perf/lib/PerfServer.cpp
- src/perf/lib/SecNetPerfMain.cpp
- src/perf/lib/Tcp.cpp
- src/perf/lib/Tcp.h
Improvements to the NetPerf automation to restart the server for each test, but also includes several other fixes found along the way:
- Refactoring the helper to have a "run" of a test to run the server only for the time it takes to do the couple of tries for that test.
- Fix log collections (client and server).
- Collect crash dumps (Windows only for now) on client and server.
- Fix a bug in the perf server code that wasn't passing the context pointer in for a callback.
- Improvements (but not a complete fix yet) of the TCP cleanup path to handle some race conditions.
NetPerf Automation
N/A
> Restart Server on Each NetPerf Test Run

- src/bin/winkernel/nmrprovider.c
- src/inc/msquic.h
- src/test/bin/winkernel/control.cpp
MsQuicOpenVersion and MsQuicClose are defined as macros for 32 bit environment.
MsQuicOpenVersion and MsQuicClose are members of MSQUIC_NMR_DISPATCH.
The expanded code of the instances of MSQUIC_NMR_DISPATCH will become non-sense like `QUIC_GET_DISPATCH(QuicNmrHandle)->(QUIC_STATUS_NOT_SUPPORTED)`.
CI
> Fix a naming conflict in msquic.h

- .github/workflows/netperf.yml
- scripts/secnetperf-helpers.psm1
- scripts/secnetperf.ps1
We've been seeing hangs on shutdown, so we are going to try running the test in a separate process so we can wait with a timeout. Also updated the yaml to trigger when necessary. Finally, should enable core dump collection for Linux.
netperf automation
N/A
> Run secnetperf in Separate Process to Wait on (with Timeout)

- .azure/OneBranch.Publish.yml
I have no idea if this is all that needs to happen to add Ubuntu 23.10 support; I'm just going off what was done in #3652. :slightly_smiling_face:
> Add Ubuntu 23.10 to `OneBranch.Publish.yml`.

- src/generated/linux/tls_schannel.c.clog.h
- src/generated/linux/tls_schannel.c.clog.h.lttng.h
- src/manifest/clog.sidecar
- src/platform/tls_schannel.c
- src/test/lib/HandshakeTest.cpp
- src/test/lib/TestHelpers.h
A user reported an issue with the schannel variant of MsQuic sometimes not working, and it was an issue with too large of output buffers. This change updates the code to dynamically increase the buffer size as necessary.
**Note** - We might want to backport this.
Updated a test to exercise the new code paths.
N/A
> Update Schannel Logic to Handler Larger Output Buffers

- .azure/OneBranch.Publish.yml
Add Fedora 39 to the list of rpm packages that get published
I do not believe I have the ability to force a publish, so I doubt I can test this.
Most documentation already says dotnet core and msquic support fedora 37+, so I do not think anything needs updated.
> Add Fedora 39 to OneBranch.Publish.yml

- scripts/package-nuget.ps1
Fixes #4102 
Fix regression in `scripts/package-nuget.ps1` script: `$Headers` array was getting overwritten vs. appended.
None
None
> Fix missing headers in NuGet packaging script

- src/core/stream.c
- src/generated/linux/stream.c.clog.h
- src/generated/linux/stream.c.clog.h.lttng.h
- src/inc/quic_trace.h
- src/manifest/clog.sidecar
Previous change seems to be causing kernel crashes. Undo that and fix individual event.
> Another Try at Fixing the Long Event

- src/core/api.c
- src/inc/quic_platform_posix.h
- src/inc/quic_platform_winkernel.h
- src/inc/quic_platform_winuser.h
- src/test/lib/TestStream.cpp
We've seen indication of a possible issue when sending at DISPATCH_LEVEL, so we're fixing the behavior to always queue in these cases (no inline execution).
Updated some tests to send at DISPATCH_LEVEL in kernel.
N/A
> Fix Possible DISPATCH_SEND Inline Issue

- scripts/secnetperf-helpers.psm1
- scripts/secnetperf.ps1
- src/platform/datapath_raw_xdp_win.c
A few minor changes to make sure we can run qtip in netperf.
Automation
N/A
> Fixes to Support qtip in netperf

- scripts/secnetperf.ps1
WS2025 exhibits weird behavior when starting remote PWSH sessions. This is a workaround.
CI
N/A
> use cred to make remote pwsh session

- src/test/lib/DataTest.cpp
Fixes a race condition in the test code where it set a completion event before the return code, so the main thread that waits on the event and validates the code some times fails.
Also fixed a number of style nits.
Locally. CI/CD
N/A
> Fix Cancel On Loss Test's Race Condition

- src/inc/quic_platform_posix.h
- src/inc/quic_platform_winkernel.h
- src/inc/quic_platform_winuser.h
When UINT32_MAX is passed as a timeout value to CxPlatEventWaitWithTimeout on the winkernel platform, an arithmetic overflow happens resulting in a positive timeout value and the wait timing out immediately. The winuser and posix platform implementations of CxPlatEventWaitWithTimeout appear to handle this case gracefully, even though callers should really be using CxPlatEventWaitForever for the infinite wait case. Fixing winkernel to handle this gracefully to eliminate this developer trap.
Also adding asserts to catch cases where the developer is calling the CxPlatEventWaitWithTimeout API incorrectly.
Local testing w/ debugger confirmation of overflow and the fix.
N/A
> Fix overflow in winkernel CxPlatEventWaitWithTimeout

- src/manifest/MsQuic.wprp
Only collect build/image name for metadata events. The default set is too noisy and largely useless.
Locally tested
> Limit the scope of metadata events in MsQuic.wprp

- src/core/send.c
Found during testing, it's possible for a non-active (i.e. primary) path to be resolving and used for probing.
CI/CD
N/A
> Remove Invalid Assert

- src/core/packet_builder.c
- src/test/lib/HandshakeTest.cpp
Fixes #4132.
Fixed tests so that they would detect the bug before the fix.
No.
> Don't send client CONNECTION_CLOSE on 1-RTT before handshake completion.

- scripts/secnetperf.ps1
`Get-NetView` was only supposed to run if logs are collected. This fix negates a negative to achieve this now.
CI/CD
N/A
> Fix Get-NetView Execution

- scripts/secnetperf-helpers.psm1
- scripts/secnetperf.ps1
Updates the secnetperf scripts to process the latency output files and grab the data we need, then encode it in the json output.
Manual netperf job; CI/CD
N/A
> Process Full Latency Output and Encode in Json

- scripts/secnetperf.ps1
As of today, the current logic for assigning environment IDs to test runs is using $isWindows.
A lot of work has been done on netperf's side to enable querying / dynamic environments, so we should adjust the driver script to work with that interface.
CI
N/A
> Enable dynamic environment

- scripts/secnetperf.ps1
Based on past discussions, we decided it was better to collect metadata about when a test was run, instead of purely relying on history of commits. 
This would give additional insights while debugging as well. 
CI
N/A
> Add a run date column for the test runs

- scripts/secnetperf.ps1
As detailed in this issue: https://github.com/microsoft/netperf/issues/92 
It's apparent that if we do all post-processing of SQL-related stuff at the end, that makes simple a lot of logic. 
To start this refactor, we need to pass all relevant metadata in the intermediary JSON files we produce.
Once the full refactor is done, we can safely delete the code that produces the SQL files. 
CI
N/A
> Cache all metadata we need to unblock JSON refactor

- src/core/packet_builder.c
- src/test/lib/HandshakeTest.cpp
> [release/2.3] Don't send client CONNECTION_CLOSE on 1-RTT before handshake completion. (#4145)

- src/core/api.c
- src/core/connection.c
- src/core/connection.h
- src/core/library.h
- src/core/operation.c
- src/core/operation.h
- src/core/stream.c
- src/core/stream.h
- src/core/stream_recv.c
- src/generated/linux/api.c.clog.h
- src/generated/linux/api.c.clog.h.lttng.h
- src/inc/quic_platform_posix.h
- src/platform/inline.c
- src/plugins/dbg/quictypes.h
- src/tools/spin/spinquic.cpp
Some internal refactoring in preparation to support multiple parallel receives to the app. No actual external behavior change yet. Just making sure no existing scenarios are broken.
CI/CD
N/A
> Support Multiple Pending Receives

- src/core/api.c
Stress tests recently started failing because of `QUIC_CONN_VERIFY` check that tries to make sure the app doesn't try to complete more than it was actually given in past receives. The problem is that there is a race condition where this value can be cleared on stream shutdown. So this change just ignores cases where the pending length has already been cleared.
Automation
N/A
> Fix Verify Check to Account for Race Conditions

- .azure/obtemplates/build-winkernel.yml
- .azure/obtemplates/build-winuser.yml
Sets a flag to enable automatic SPGO build information to be included when building Windows code.
Automation
N/A
> Enable SPGO for OneBranch Builds

- .github/workflows/code-coverage.yml
Looks like recent breaking changes to code coverage caused our uploads to start failing. This PR tries to fix that.
Automation
N/A
> Fix CodeCoverage Upload

- .github/workflows/code-coverage.yml
- src/inc/msquic.hpp
For some reason the platform unittests were failing, causing the BVTs never to be run in code coverage.
CI/CD
N/A
> Skip Unit Tests in Code Coverage

- .github/workflows/code-coverage.yml
Increase code coverage by leveraging OpenSSL, which supports full set of features/tests.
Automation
N/A
> Move Code Coverage to OpenSSL

- scripts/secnetperf-helpers.psm1
- scripts/secnetperf.ps1
To increase observability and developer productivity, we want to make each netperf run output a comprehensive summary. 
With this commit on netperf: https://github.com/microsoft/netperf/commit/2f147803a8784802404433a21c27aea2937f550f, we added functionality to see how each run compares against the best run. 
This PR makes the necessary test code changes to work with the recent patch. 
CI
N/A
> Persist BestResult / BestResultCommit / Baseline for all results, regardless of regression. 

- .docker/ubuntu-22.04/Dockerfile
Linux xdp dependencies
N/A
not officially supported yet
> setup container env for linux xdp

- .github/workflows/docker-publish-xcomp.yml
The automation is expecting `ubuntu:22.04` as the tag, but it is publishing only `22.04`. This PR fixes the publish.
CI/CD
N/A
> Fix Publish of Cross-Compile Docker Image Tag

- .docker/ubuntu-20.04/Dockerfile
See if that resolves the failure blocking the docker image build
> Work around fpm dependencies for ubuntu 20.04

- scripts/secnetperf-helpers.psm1
Thus far for secnetperf runs, we have relied on the Github runner agent to cleanup any managed directories pertaining to github actions. 
However, MsQuic modifies directories outside of the ones managed by Github Actions. 
Specifically, for logs, we know the /artifacts/logs gets cleaned up after every run, but /AppData/Local/Temp remains. 
So we must clean them up too. 
CI 
N/A
> Add logic to remove any logging residue. 

- scripts/log.ps1
- scripts/secnetperf-helpers.psm1
Earlier, we merged PRs to always cancel logging prior to each run because we noticed MsQuic was building up residual ETL traces, causing the storage to balloon. This is necessary until we get to dynamic, temporary lab VMs.
However, after merging those PRs, that surfaced an issue with the usage of "sudo" in the Log.ps1 script when we run it in our lab Linux VMs. 
This PR makes it so we do the cancellation of logs on Windows systems, to properly garbage collect the residual ETLs, which looks to be a Windows-only issue anyway. 
CI
N/A
> Implement workaround for log.ps1 not working on Lab Linux

- scripts/build.ps1
`apt-get install pkg-config` affects linking of libcrypto.so. arm build tries to link x86-64's libcrypto.so
This environment variable assists pkg-config to search right directory.
tested with commit da24f2d027fed3c55b315a1717be189ca4b9b657 with this change.
Works fine.
> Fix pkgconfig setting to link with pkg-config

- src/tools/spin/spinquic.cpp
SpinQuic was incorrectly doing multiple receive completes for a single receive indiciation, because it was marking `PendingRecvLength` as non-zero when it did a partial receive. That was incorrect. Fixed that, and improved synchronization around a few other things.
Local and CI runs
N/A
> Fix Bug in SpinQuic Around Receive Complete

- scripts/log.ps1
Recently we noticed buildup of ETL logs in AppData by MsQuic in our windows perf machines.
A temporary workaround was to remove them each time we cancelled logs.
However, this has some unforeseen consequences. 
Since we're implementing temporary VMs anyway, we should revert those workarounds. 
Merge when ready.
CI
N/A
> Revert AppData removal in log.ps1

- src/core/recv_buffer.c
- src/core/unittest/RecvBufferTest.cpp
This PR fixes bug where in certain situations, MsQuic would drop/corrupt data when received out of order + specific read timing from application side.
Failing test added to detect future regressions.
N/A.
> Don't do full drain on chunks containing future buffered data

- .docker/ubuntu-20.04/Dockerfile
- .docker/ubuntu-22.04/Dockerfile
Remove dependency to xdp-tools. install libxdp/libbpf headers instead.
N/A
N/A
> update dependency for libxdp/libbpf

- src/core/api.c
- src/core/datagram.c
- src/tools/spin/spinquic.cpp
SpinQuic now always sends data so the value is equal to (offset % 256) and verifies this on the receive path.
Automation
N/A
> Update SpinQuic to Validate Bytes in Stream Receive aren't Corrupted

- .docker/ubuntu-20.04/Dockerfile
- .docker/ubuntu-22.04/Dockerfile
- .github/workflows/build-reuse-unix.yml
- .github/workflows/docker-publish-xcomp.yml
Installing libxdp/libbpf conflicts libc6 version for arm cross compile toolset.
Multistage build to avoid installing toolset on one image.
Locally passed `docker build --target ${arch|-build` and `pwsh ./scripts/build.ps1 -Arch ${arch}` for each arch
Ubuntu 20.04 cannot build xdp related source code as bpf.h (linux-libc-dev) header doesn't have required struct declaration.
This can be avoided by apt-get upgrade linux-libc-dev, but not good from CI/CD point of view.
 
N/A
> docker multistage build for xdp support

- src/platform/datapath_epoll.c
Fixes #3958 
Support arm32 memory alignment
Tested and passed on raspberry pi.
It had been failed at processing 3rd or 4th packets consistently (during handshake). now it has gone with the fix.
> add memory alignment for ARM32

- .docker/ubuntu-22.04/Dockerfile
libc6-dev-i386 installs & upgrade additional packages which breaks building "Release" build.
locally tested. especially for Release build.
N/A
> Fix libc6-dev-i386 to install cause of corruption

- src/core/packet_builder.c
- src/core/packet_builder.h
- src/core/send.c
Fixes #4242.
Stress test in CI.
N/A
> Fix for a deadlock discovered in 4169

- .CodeQL.yml
Tells internal CodeQL scans to ignore some directories that we don't care about alerts for.
Required to be merged and go through full OneBranch pipeline run before we can verify.
N/A
> CodeQL Classification

- src/plugins/dbg/library.cpp
- src/plugins/dbg/quictypes.h
- src/plugins/dbg/worker.cpp
Fixes some broken stuff and adds improved library output on the workers' state for each registration. This helps you easily see which are currently active.
Used locally on a dump
N/A
> Debugger Extension Fixes & Improvements

- scripts/secnetperf-helpers.psm1
The test continues to fail, so let's disabled it to get a clean pass for now.
Automation
N/A
> Disable Linux XDP HPS

- src/generated/linux/datapath_raw_xdp_linux.c.clog.h
- src/generated/linux/datapath_raw_xdp_linux.c.clog.h.lttng.h
- src/manifest/clog.sidecar
- src/platform/datapath_raw_xdp_linux.c
sendto() sometimes fail by EAGAIN and stop sending anymore.
tested with secnetperf throughput test. Using 2 local Ubuntu22.04 VMs
N/A
> Fix Tx to retry sending

- src/generated/stdout/quic_trace.c
Fix buffer overflow while stdout trace is enabled.
N/A
N/A
> fix: buffer overflow in quic_trace

- src/core/connection.c
- src/core/datagram.c
- src/core/datagram.h
- src/core/loss_detection.c
- src/core/packet_builder.c
- src/core/sent_packet_metadata.c
- src/core/sent_packet_metadata.h
App allocated buffer for Datagram Frame has been leaking due to
- missing callback handler when waiting Ack for the Datagram frame.
- allocation failure for packet metadata
Ran local test. No leak detected. No leak found from my own memory tracker either.
`./artifacts/bin/linux/x64_Debug_openssl3/spinquic both -timeout:600000 -repeat_count:20 -alloc_fail:100`
`./artifacts/bin/linux/x64_Debug_openssl/spinquic both -timeout:600000 -repeat_count:20 -alloc_fail:100`
Let's see automation results
N/A
> Uninitialize LossDetection earlier to cleanup Datagram frame

- .github/workflows/build-reuse-unix.yml
- .github/workflows/dotnet-test.yml
- .github/workflows/package-linux.yml
- .github/workflows/package-reuse-linux.yml
- .github/workflows/stress.yml
- .github/workflows/test.yml
- docs/BUILD.md
- scripts/prepare-machine.ps1
Fix of https://github.com/microsoft/msquic/issues/4299
Currently Linux XDP setup is for Ubuntu 22.04, but installing dependencies from Ubuntu 24.04 which should break the environment.
This change shows warning to user before actually execute prepare-machine.ps1
Locally works this "YES" prompt
wrote.
> show warning prompt for installing Linux XDP deps

- scripts/prepare-machine.ps1
Currently ubuntu22.04 always install xdp dependencies which are from ubuntu24.04 repository.
N/A
N/A
> block installing Linux XDP dependencies unless setting -UseXdp

- scripts/run-gtest.ps1
Several tests sometimes fail due to randomness and slower test environment on Github Action.
This change executes retry once if first trial fails. Then failure twice in a row is considered as actual failure.
(e.g. take over 10sec to start processing received packets which causes IDLE.TIMEOUT then shutdown its connection.)
See automation....
N/A
> Retry flaky test

- .azure/OneBranch.Official.yml
- .azure/OneBranch.PullRequest.yml
- .azure/obtemplates/build-linux.yml
- .github/workflows/build-reuse-unix.yml
ubuntu22.04 epoll test get affected by mismatched libc due to XDP dependencies which come from ubuntu 24.04 repository.
The new docker image doesn't reuse xdp environment for normal socket datapath.
See automation
N/A
> Update Docker image to fix ubuntu22 test runtime issue

- scripts/prepare-machine.ps1
Updates the prepare-machine script to install Perl on windows for OpenSSL builds.
Ran the script locally and it worked fine.
N/A
> Install Perl on Windows via WinGet

- scripts/run-gtest.ps1
An issue encountered when adding a new test resulted in the powershell process crashing. The problem was the auto-generated test name contained characters that were invalid in a directory path, which wasn't sanitized by the existing log path creation code. This resulted in powershell crashing when trying to create the log directory.
This change updates the log path creation code to sanitize the test name for all invalid path characters. 
Locally run works fine and CI to validate other platforms.
N/A
> Fix test log path sanitation

- scripts/secnetperf-helpers.psm1
- scripts/secnetperf.ps1
This PR adds the scripts and workflow templates to enable 2 machine testing on 1ES pools. 
Note: a lot of stuff can be re-factored and cleaned up for a better user experience. This should be done in a follow up PR, as this PR is already pretty massive. 
The work done here follows: 
See: https://github.com/microsoft/netperf/actions/runs/9586048711
N/A
> Add infrastructure to enable 2-machine network testing on 1ES Azure pools.

- src/platform/datapath_epoll.c
Backport of #4208 
The fix was for an alignment problem -> arm is sensitive in places where  x64 is not.
Manually tested
No
/cc @ManickaP
> [release/2.3] Add memory alignment for ARM32

- .azure/OneBranch.Publish.yml
Update package publish pipeline to distinguish ubuntu version. Previously openssl versions are used, but now both ubuntu22 and 24 use openssl3.
> Publish Ubuntu 24.04

- src/core/quicdef.h
- src/platform/datapath_winuser.c
- src/platform/datapath_xplat.c
QTIP case has been failing recently.
segfault by SocketProc->RefCount become negative value, but SocketProc under normal socket is not touched at all for QTIP case.
See automation.
N/A
> QTIP case only delete raw socket

- src/test/lib/DataTest.cpp
Some Connections are queued at test initialization phase which affects test result.
This change add sleep to make sure the unnecessary operations are really flushed.
CI (`Basic.ConnectionPriority`)
N/A
> add sleep to flush unnecesaly operations (test fix)

- .azure/obtemplates/build-linux-packages.yml
- scripts/make-packages.sh
- scripts/package-distribution.ps1
Checking artifact directory name doesn't work for identifying Ubuntu version for XDP build.
locally done and used internal repo
N/A
> Fix package distribution. Specify OS explicitly

- scripts/secnetperf-helpers.psm1
Right now, we are skipping all HPS tests on kernel mode msquic. 
Let's enable it, and use netperf to figure out whether or not we have a bug somewhere. 
CI
N/A
> Fix HPS test on WSK

- src/core/connection.c
- src/core/connection.h
- src/core/inline.c
- src/core/operation.h
- src/core/worker.c
* lock to check queue
* Some refactoring and other fixes
---------
> Lock OperQ before checking content (#4446)

- .github/workflows/test.yml
While triaging a kernel test failure in MsCodeHub mirror from the latest ingestion, 839a2fbde9a2cecdcf0c41649037fa091cbb0e06,
it became apparent that reproducing the failure (kernel mode test) would be challenging using the current CI setup. 
This PR makes it so a developer can target a specific version of MsQuic while running the BVT test suite. 
CI
N/A
> Add ref option to workflow dispatch

- .github/workflows/package-linux.yml
- .github/workflows/package-reuse-linux.yml
- scripts/package-distribution.ps1
Linux packages should work without needing to prepare the machine or checkout msquic. This PR removes the unnecessary steps.
CI tests should pass
No
> Delete Prepare Machine and Checkout from Linux Package Testing

- .azure/OneBranch.Official.yml
- .azure/OneBranch.Publish.yml
- .azure/OneBranch.PullRequest.yml
- .azure/obtemplates/build-distribution.yml
- .azure/obtemplates/build-linux-packages.yml
- .azure/obtemplates/build-linux.yml
- .azure/obtemplates/download-artifacts.yml
- scripts/make-packages.sh
- scripts/package-distribution.ps1
- Add more distros. fedora39, 49, azure linux 3.0
- Correct openssl dependencies (e.g. fedora 37, debian 12)
- Refactoring
- Stop using ubuntu_2X04 keyword for differentiate builds. Use kernel version instead.
Use internal pipeline
N/A
> Publish package to more distros and refactoring

- .azure/OneBranch.Publish.yml
- scripts/make-packages.sh
rpm package generation is skipped when `(!xdp && x86_64)`. remove the check.
https://github.com/microsoft/msquic/issues/4450
running internal CI
N/A
> Make rpm package for x86_64

- src/bin/CMakeLists.txt
fix cmake install error:
```
cmake -S msquic -B msquic-build -DCMAKE_INSTALL_PREFIX=msquic-install
cmake --build msquic-build
cmake --install msquic-build
```
target_link_libraries(app msquic)
```
cmake -S app -B app-build -DCMAKE_PREFIX_PATH=msquic-install
cmake --build app-build
```
#include <msquic.h>: No such file or directory
> set include_dest value

- .github/workflows/plugins.yml
- src/plugins/trace/dll/Tables/QuicStreamLifetime.cs
- src/plugins/trace/dll/pluginManifest.json
Update WPA Plugin to Include Process, Thread and CPU in Stream Lifetime Table
Will install plugin from CI/CD.
N/A
> Update WPA Plugin Stream Lifetime Table

- scripts/run-gtest.ps1
Non-Windows platforms allow characters in filenames that are not allowed on Windows, or in Github's artifact storage.
This change removes the characters that Github claims are disallowed.
Tested by CI and by manually testing against the string containing invalid characters that started this.
N/A.
> Remove invalid characters from logfile names on non-Windows

- src/platform/datapath_winuser.c
The send path error processing logic assumed errors could/should be processed synchronously, and since we never see them for UDP, it wasn't a big deal. For TCP, though, we see them more often, and it results in a use-after-free because we incorrectly release the last ref inline, and later the completion fires after the object had been freed.
P.S. I wish there was a `FILE_SKIP_COMPLETION_PORT_ON_ERROR` so that only PENDING results completed async. Errors should be processed inline too.
Locally via secnetperf
N/A
> Socket Errors are Asynchronous

- src/inc/quic_platform.h
- src/perf/lib/Tcp.cpp
- src/perf/lib/Tcp.h
- src/platform/datapath_winuser.c
As of today, MsQuic has several execution modes, namely Max Throughput, and Low Latency.
We use the Secnetperf tool to measure this performance impact between the different modes.
However, with our Secnetperf TCP implementation, there is no such distinction between modes.
Meaning, we are artificially giving QUIC an advantage in performance when we run it in Lowlat mode to optimize thread / context switching, but we are not doing the same for TCP.
This PR implements the actual TCP lowlat execution context part.
> Implement LowLat mode in TCP

- src/inc/quic_datapath.h
- src/platform/datapath_kqueue.c
- src/platform/datapath_winkernel.c
- src/platform/datapath_xplat.c
- src/platform/unittest/DataPathTest.cpp
Error from RawDataPathInitialize has been ignored because it is optional.
Handle the error as the raw datapath is now user opt-in.
See automation
N/A
> Handle error from RawDataPathInitialize

- src/platform/datapath_winuser.c
Finally fixes the real reason we were seeing secnetperf crash.
Local. CI/CD
N/A
> Use Rundown Protection for TCP Send Completions

- src/platform/CMakeLists.txt
Compile for Android failed by __atomic_add_fetch(), only emulator and some old ChromeBooks are X86, so the performance penalty may be acceptable, do not patch all the atomic usage
> error: misaligned atomic operation may incur significant performance penalty; the expected alignment (8 bytes) exceeds the actual alignment (4 bytes)
CI/CD
N/A
> Avoid treat atomic alignment warning as error for Android X86

- src/core/binding.c
- src/core/binding.h
- src/generated/linux/Tcp.cpp.clog.h
- src/generated/linux/Tcp.cpp.clog.h.lttng.h
- src/generated/linux/binding.c.clog.h
- src/generated/linux/binding.c.clog.h.lttng.h
- src/inc/quic_datapath.h
- src/manifest/clog.sidecar
- src/perf/lib/Tcp.cpp
- src/perf/lib/Tcp.h
- src/platform/datapath_epoll.c
- src/platform/datapath_kqueue.c
- src/platform/datapath_winkernel.c
- src/platform/datapath_winuser.c
- src/platform/datapath_xplat.c
- src/platform/pcp.c
- src/platform/platform_internal.h
- src/platform/unittest/DataPathTest.cpp
- src/test/lib/QuicDrill.cpp
- src/tools/recvfuzz/recvfuzz.cpp
The CxPlatSocketSend function generally is fire and forget for UDP, and for TCP it always sends a completion (even on sync completions). The status was only used for error logging (and it's already logged at the lower layer). It's simply unnecessary and a waste of CPU instructions (and a bit of complexity). So, let's remove it all.
CI/CD
N/A
> Return void for CxPlatSocketSend

- src/core/library.c
- src/test/lib/ApiTest.cpp
One the server-side, QUIC cleans up the TLS state once the connection handshake is complete. This means that the last time `QUIC_PARAM_TLS_HANDSHAKE_INFO` can be queried on a server is in the `QUIC_CONNECTION_EVENT_CONNECTED` event.
Once cleaned up, attempting to query this state returned `QUIC_STATUS_INVALID_PARAMETER`, as pointed out in #4457, this is confusing. This change updates it so that `QUIC_STATUS_INVALID_STATE` is returned once the TLS state has been cleaned up to more clearly indicate that internal state has changed.
Tested by CI
This behavior isn't documented, so no new documentation is needed. However, maybe the limitation of this GetParam needs to be documented better for the difference between client and server behavior.
> Make GetParam return INVALID_STATE error when TLS has been cleaned up

- src/platform/platform_posix.c
CxPlatTimespecToUs:Microsecond time conversion overflow on 32-bit unix platforms
The timespec structure is defined as follows
struct timespec
{
time_t tv_sec;  // Seconds - >= 0
long   tv_nsec; // Nanoseconds - [0, 999999999]
};
On a 32-bit platform, time_t t is usually defined as a 32-bit signed integer (int or long) .
Therefore, byte overflow occurs in the following calculation:
#define CXPLAT_MICROSEC_PER_SEC     (1000000)
Time->tv_sec * CXPLAT_MICROSEC_PER_SEC
This will cause the calculated microsecond time to be discontinuous, and the time obtained after overflow is smaller than the last time obtained
> CxPlatTimespecToUs:Microsecond time conversion overflow on 32-bit unix platforms

- src/inc/quic_platform_posix.h
- src/platform/platform_posix.c
`kevent.ident` is a `uintptr_t`, not an `int`. C didn't really care, but if C++ included quic_platform.h, an error would occur as narrowing from signed to unsigned in a designated initializer is an error in C++. Could be solved either by adding an explicit cast, or changing the type to be correct. Changing the type seemed like the better option.
Existing tests will cover it.
N/A
> Fix kqueue CSPLAT_SQE Type

- src/platform/datapath_epoll.c
- src/platform/datapath_winuser.c
- src/platform/unittest/DataPathTest.cpp
On linux, server sockets always enable SO_REUSEPORT. This has a side affect of not blocking other processes from accessing the port. If running in a single core execution context, we don't need to set SO_REUSEPORT, which allows that port blocking to work.
On windows, server sockets always are enabled with processor affinity. On single proc, this is likely not wanted, and similar behavior to client sockets are likely wanted.
Mac is already treated as single core, so no changes required.
Note that single core systems themselves are extremely rare nowadays, so this behavior is generally explicitly requested.
New test added to verify this behavior.
> Disable port sharing mechanisms when running in single processor mode

- src/plugins/trace/README.md
> Update WPA Plugin Installation Steps

- scripts/secnetperf.ps1
- src/perf/bin/appmain.cpp
- src/perf/lib/PerfClient.cpp
- src/perf/lib/PerfClient.h
- src/perf/lib/PerfServer.cpp
- src/perf/lib/PerfServer.h
- src/perf/lib/SecNetPerf.h
- src/perf/lib/SecNetPerfMain.cpp
In the Secnet tool, 
when something is wrong or supposed to crash, exiting gracefully leads to quiet errors and a massive pain while debugging.
This PR makes it so it will actually crash and a core dump gets generated.
Netperf CI
N/A
> Do not exit gracefully in error cases

- .github/workflows/test.yml
- src/test/MsQuicTests.h
- src/test/bin/quic_gtest.cpp
- src/test/bin/winkernel/control.cpp
- src/test/lib/ApiTest.cpp
#4518 Was completed with some tests still failing, so this PR attempts to fix the test failures introduced in that PR.
Fix the ApiTests for TLS parameters to run on XDP and not run test cases unsupported by kernel mode.
N/A
> Fix test failures from #4518

- src/manifest/MsQuicEtw.man
Noticed this while looking at a log. Example:
```
[8]0004.0E28::2024/09/03-16:13:49.692808900 [Microsoft-Quic][conn][0xFFFFEF82DA6DE100] STATS: SRtt=26359 CongestionCount=19 PersistentCongestionCount=0 SendTotalBytes=48827769 RecvTotalBytes=2731188 CongestionWindow=385840 Cc=Cubic EcnCongestionCount=Cubic
```
N/A
N/A
> Fix ETW Manifest Typo

- src/inc/quic_datapath.h
- src/perf/lib/Tcp.cpp
- src/perf/lib/Tcp.h
- src/platform/datapath_epoll.c
- src/platform/datapath_winuser.c
- src/platform/unittest/DataPathTest.cpp
Currently, it is impossible to reject a TCP connection. Calling CxPlatSocketDelete() from the Accept callback results in a use after free, and there isn't any way to detect that, other then to return a value from Accept()
New test added to cover this case.
No, there is no documentation for TCP.
> Add a method to reject a TCP connection

- src/core/library.c
- src/inc/msquicp.h
- src/test/lib/ApiTest.cpp
Before #4492, it was possible for apps statically linking to MsQuic and CxPLat to get the default worker pool used by Quic. After that PR, the default worker pool is no longer accessible. Add a new global param getter to make that accessable.
Added test to cover the new parameter.
Internal, so not documented.
> Add global internal param to get default datapath worker pool

- src/platform/datapath_epoll.c
- src/platform/datapath_winuser.c
- src/platform/unittest/DataPathTest.cpp
TCP accepted connections did not have a filled out remote or local address. Fill them out.
Update the connect test to assert things are valid.
N/A
> Fill out remote and local addresses on TCP server connection

- src/platform/datapath_epoll.c
Linux TCP was recently broken when secnetperf was updated to handle send completion errors. This exposed a bug in the platform layer that was always passing up `errno` incorrectly.
This PR updates the platform abstraction to return the proper status.
Verified locally on Linux GitHub Codespaces. CI/CD
N/A
> Fix Linux Send Complete Status

- src/core/bbr.c
> Remove Unnecessary Unit Conversion

- src/platform/datapath_epoll.c
Unix is a bit more strict about TIME_WAIT state, and actually puts any sockets that have had a valid accept() called on them into the TIME_WAIT state.
This makes writing a listener app difficult, as if that ever crashes the bind() will fail for the next few minutes.
Pretty much all other TCP libraries set SO_REUSEADDR (Including libuv, which is what our app has used before). Libuv sets it on all TCP sockets, but its generally less required on client sockets, as they rarely actually specify a local port.
Not really possible to test with our current setup, as a crash is the only way to get a listener socket into TIME_WAIT. A properly shutdown socket doesn't stay in TIME_WAIT.
N/A
> Set SO_REUSEADDR on epoll tcp listener sockets

- .azure/nuget.config
- .azure/obtemplates/build-winkernel.yml
- scripts/onebranch-build-kernel.cmd
Updates internal builds to use nuget.config to use internal mirror instead of nuget.org directly.
Created internal draft PR to trigger pipeline: https://mscodehub.visualstudio.com/msquic/_build/results?buildId=531354&view=logs&j=4e010f65-6a42-5318-8120-b81b51c2abd2&t=abd3eb9e-9a6d-521e-c133-9e198ddfd123
N/A
> Use Private Nuget Feed for OneBranch

- src/core/binding.c
Fixes #4558, which was zero'ing out too much memory.
CI/CD
N/A
> Zero out memory from PacketNumber in QuicBindingPreprocessPacket

- src/core/binding.c
Cherry-pick #4560 to release/2.4.
> Zero out memory from PacketNumber in QuicBindingPreprocessPacket (#4560)

- src/perf/lib/Tcp.cpp
We were getting arm64 build errors when we accessed volatile variables directly in C++ code. Remove those.
CI/CD
N/A
> Don't Access Volatile Variables Directly

- .azure/OneBranch.Official.yml
- .azure/obtemplates/build-nuget.yml
- docs/Release.md
Automatically publishes the NuGet packages to nuget.org for both tags (official packages) and `main` builds (prerelease packages). Publishing prerelease pacakges allows partners to try out these before we release.
Will have to merge into main to let an official pipeline run go through.
Updated release process.
> Publish NuGet Packages Automatically

- docs/Release.md
Add prereqs to publishing alpine package docs
No test is needed
Release doc
> Add prereqs to publishing alpine package docs

- src/perf/lib/PerfClient.cpp
Added the ability for secnetperf to use the unit of `cpu` to indicate it's a multiple of the number of CPUs on the machine. This is usefull for generically defining a perf test case that scales with the type of machine its run on.
Examples:
```
> secnetperf.exe -target:localhost -conns:1cpu -rstream:1 -plat:1 -up:100 -down:100 -run:1s
Started!
Result: 124985 RPS, Latency,us 0th: 37, 50th: 164, 90th: 414, 99th: 500, 99.9th: 557, 99.99th: 6013, 99.999th: 13355, 99.9999th: 13396, Max: 13396
App Main returning status 0
> secnetperf.exe -target:localhost -conns:2cpu -rstream:1 -plat:1 -up:100 -down:100 -run:1s
Started!
Result: 277589 RPS, Latency,us 0th: 47, 50th: 108, 90th: 352, 99th: 803, 99.9th: 1187, 99.99th: 10995, 99.999th: 20259, 99.9999th: 21174, Max: 21174
App Main returning status 0 …
```
> Support for SecNetPerf Variables to be in Units of CPU Count

- .github/workflows/netperf.yml
Changing the XDP MSI could change performance, so netperf should be triggered.
CI.
No.
> trigger netperf when xdp json changes

- scripts/quic_callback.ps1
From recent discussions, the command-callback model intermixed component specific logic between Msquic and netperf.
We should make it so all component-specific logic lives in MsQuic. 
A corresponding PR will be made on Netperf that reflects this change. Will schedule a run against that with this PR.
https://github.com/microsoft/netperf/actions/runs/11185806638
N/A
> Move `quic_callback` to msquic

- src/platform/datapath_raw_xdp_win.c
I noticed MsQuic is missing the mandatory (on x64) barrier between submitting TX producer entries and checking the TX ring for the NeedPoke flag. If these operations get reordered, pokes could be missed.
CI.
No.
> add barrier missing between producer submit and needpoke check

- src/core/mtu_discovery.c
- src/core/packet_builder.h
- src/core/quicdef.h
- src/core/range.h
This resolves build failures on macOS 15 "Sequoia" / XCode Command Line Tools 16 detected while attempting to update vcpkg's build and test lab: https://github.com/microsoft/vcpkg/pull/41307
Example:
```
/Users/vcpkg/Data/b/msquic/src/v2.4.5-9d07a67b94.clean/src/core/quicdef.h:243:66: error: encoding prefix 'L' on an unevaluated string literal has no effect [-Werror,-Winvalid-unevaluated-string]
243 | CXPLAT_STATIC_ASSERT(IS_POWER_OF_TWO(QUIC_MAX_RANGE_ALLOC_SIZE), L"Must be power of two");
|                                                                  ^
```
None, there are no runtime changes.
No.
> Remove the L from unevaluated string literals.

- src/platform/datapath_epoll.c
My phone: Samsung A217M (Android 12)
After I upgraded MsQuic to v2.3.6, crash occurs when sending big payload size. I have tried the releases both v.2.3.4 and v.2.3.5, also failed on my phone.
With MsQuic v2.2.4, it's ok. 
Please see the discussion here:
https://github.com/microsoft/msquic/issues/4144
No need to add new test case. The gtest "WithSendArgs2.SendLarge" in guic_gtest.cpp already covers this issue.
> Fix crash issue on Samsung phone A217M when send big payload size

- CMakeLists.txt
The `find_program()` command is now executed during the configuration phase to locate `mc.exe` in predefined locations. This approach allows the CMake toolchain to influence the search without modifying the `%PATH%`.
If `mc.exe` is not found, a clear error message is reported at configuration time, improving the ease of diagnosing build issues compared to discovering the failure in build logs.
> Locate `mc.exe` at configuration time

- src/core/binding.c
- src/core/lookup.c
- src/inc/msquic.hpp
- src/inc/quic_platform_posix.h
- src/inc/quic_platform_winkernel.h
- src/inc/quic_platform_winuser.h
Fixes an issue with kernel mode RW locks where they were sharing the previous IRQL state across calls, which could result in incorrect state on release.
CI/CD
N/A
> Don't Share Previous IRQL for Dispatch RW Locks

- docs/API.md
- docs/Execution.md
This revamps our documentation on MsQuic's execution mode, including how we manage callbacks and threads.
N/A
Updated
> Update Execution Docs

- docs/Deployment.md
- docs/Settings.md
- docs/Versions.md
Improve the version deployment documentation.
> Improve version deployment documentation

- src/platform/datapath_epoll.c
- src/platform/datapath_kqueue.c
- src/platform/datapath_winkernel.c
- src/platform/datapath_winuser.c
- src/platform/platform_internal.h
Refactoring CXPLAT_DATAPATH, CXPLAT_SOCKET and CXPLAT_SEND_DATA
CI
N/A
> Extract common member variables

- scripts/secnetperf-helpers.psm1
- scripts/secnetperf.ps1
- src/inc/msquichelper.h
- src/perf/lib/PerfClient.cpp
- src/perf/lib/SecNetPerfMain.cpp
Adds a new secnetperf cmd line arg `-scenario:` which standardizes a few common test cases. This then simplifies the secnetperf scripts for netperf to just use these scenarios.
CI/CD
Updated help text
> Standard SecNetPerf Scenarios

- src/test/bin/quic_gtest.cpp
Fixes the following OneBranch build error of Windows user mode:
```
C:\__w\1\s\src\test\bin\quic_gtest.cpp(92,41): error C2065: 'QUIC_EXECUTION_CONFIG_FLAG_XDP': undeclared identifier [C:\__w\1\s\build\windows\x64_schannel\src\test\bin\msquictest.vcxproj]
```
This happens because internally we don't build test code with preview features enabled.
Need to run through the CI.
N/A
> Fix OneBranch Build of msquictest

- .github/workflows/test-down-level.yml
Updates to test the latest v2.3 and v2.4 releases.
CI/CD
N/A
> Update test-down-level.yml for new Releases

- .github/workflows/build-reuse-win.yml
- src/bin/CMakeLists.txt
- src/platform/unittest/external/CMakeLists.txt
- Add namespace
- Enable sanitize builds
- Refactor platform unittest external cmake
> Refactor: Add namespace, enable sanitize builds

- docs/Release.md
Doc change only
No needed
Make a clarification on alpine release docs
> Update Alpine Release doc

- src/platform/datapath_raw_xdp_win.c
error from SetFileCompletionNotificationModes is not set to Status. then clean up phase should not work as expected.
CI
N/A
> potential memory leak without setting Status

- src/core/settings.c
- src/test/lib/ApiTest.cpp
Fixes #4705 by disallowing the app to set a value of zero.
Added
N/A
> Restrict MaxOperationsPerDrain to Greater Than Zero

- .github/workflows/cargo.yml
- scripts/build.rs
- src/lib.rs
Rust code should be formatted and linted to ensure consistency and quality.
Added fmt and clippy lint to cargo pipeline.
NA
NA
> Run fmt and clippy for rust code

- Cargo.toml
- src/lib.rs
This pull request includes significant changes to the `src/lib.rs` file and updates to the `Cargo.toml` file to improve the handling of socket addresses and address families. The most important changes include the addition of new dependencies, the removal of redundant structures, and the introduction of new methods for address conversion and retrieval.
* Added `socket2` crate to `Cargo.toml` for enhanced socket address handling.
* Replaced our own `sockaddr_in` and `sockaddr_in6` structures with `c_types::sockaddr_in` and `c_types::sockaddr_in6` .
* Added methods to the `Addr` union for converting to and from `std::net::SocketAddr`, and for retrieving port numbers.
* Implemented `get_local_addr` and `get_remote_addr` methods in the `Connection` struct to retrieve local and remote …
> Add conversion method for Addr

- src/test/lib/DataTest.cpp
There were several timeouts observed in bvt tests and testmd runs due to connections pointer not returning the registration reference in connectionpriority test. unique_ptr is used for this and the issue is fixed.
> added unique pointer for connection

- .github/workflows/wan-perf.yml
> Changes to trigger wan perf test run manually

- .github/workflows/build-darwin-framework.yml
- .github/workflows/build-reuse-darwin-framework.yml
- .github/workflows/build-reuse-unix.yml
- .github/workflows/build-reuse-win.yml
- .github/workflows/build-reuse-winkernel.yml
- .github/workflows/build.yml
Change ci that it can run from other repos.
> Change ci that it can run from other repos

- CMakeLists.txt
- src/bin/CMakeLists.txt
- src/bin/msquic-config-unix.cmake.in
- src/bin/msquic-config.cmake.in
Removes an ununsed config template.
Adopts the common configuration template pattern of only substituting `@VAR@` references, allowing to use a literal `${CMAKE_CURRENT_LIST_DIR}` expression for evaluation when the condig is used.
Covered by `find_package(msquic REQUIRED)` in `src/platform/unittest/external/CMakeLists.txt`.
No change.
> Simplify cmake config chainloading

- src/bin/CMakeLists.txt
This PR ensures that the exported CMake target carries the include directories property which is necessary for accessing the installed headers.
The location corresponds to the destination in 
https://github.com/microsoft/msquic/blob/10f248775a5e32f1c0935ab794c0fb4c3e2f9c18/src/bin/CMakeLists.txt#L270
This is backported from the vcpkg port of msquic. In vcpkg, the exported config is consumed by port msh3.
No impact AFAICT. CMake usage is not covered at all.
FTR vcpkg's (tested) usage notice is:
~~~
msquic provides CMake targets:
find_package(msquic CONFIG REQUIRED)
target_link_libraries(main PRIVATE msquic::msquic)
~~~
which is pretty much what is expected for Modern CMake. (But the vcpkg port comes with more patches.)
> Export msquic include install dir

- .CodeQL.yml
Fixes up the CodeQL path classifiers to restrict which paths should be analyzed.
This will have to be merged and go through the OneBranch build to be validated.
N/A
> Fix Path Classifiers in CodeQL YML

- Cargo.toml
- src/lib.rs
This pull request introduces a new feature flag, `preview-api`, and updates the `Settings` struct and related methods in `src/lib.rs`. The most important changes include adding the new feature flag in `Cargo.toml`, updating the `Settings` struct to include a new field, adding a new method under the `preview-api` feature, and modifying a test function to conditionally use the new method based on the feature flag.
cargo test --features preview-api
TBD
> Add preview API feature

- src/lib.rs
This pull request includes several changes to the `src/lib.rs` file, focusing on enhancing the `Listener` and `Stream` structs, as well as ensuring thread safety for multiple structs. The most important changes include implementing `Sync` and `Send` traits for various structs, adding new methods to the `Listener` and `Stream` structs, and modifying existing methods for better functionality.
Thread safety improvements:
* Implemented `Sync` and `Send` traits for `Registration`, `Configuration`, `Connection`, `Listener`, and `Stream` structs to ensure they can be safely shared across threads.
Enhancements to `Listener` struct:
* Added a `Default` implementation for the `Listener` struct to provide a default instance.
* Separated the `new` method of the `Listener` struct into `new` and `open` …
> Refactor lib.rs

- src/generated/linux/datapath_raw_xdp_linux.c.clog.h
- src/generated/linux/datapath_raw_xdp_linux.c.clog.h.lttng.h
- src/generated/linux/datapath_raw_xdp_win.c.clog.h
- src/generated/linux/datapath_raw_xdp_win.c.clog.h.lttng.h
- src/generated/linux/datapath_winuser.c.clog.h
- src/generated/linux/datapath_winuser.c.clog.h.lttng.h
- src/inc/quic_platform.h
- src/inc/quic_platform_posix.h
- src/inc/quic_platform_winkernel.h
- src/inc/quic_platform_winuser.h
- src/platform/datapath_epoll.c
- src/platform/datapath_kqueue.c
- src/platform/datapath_linux.c
- src/platform/datapath_raw_dummy.c
- src/platform/datapath_raw_xdp.h
- src/platform/datapath_raw_xdp_linux.c
- src/platform/datapath_raw_xdp_win.c
- src/platform/datapath_win.c
- src/platform/datapath_winuser.c
- src/platform/inline.c
- src/platform/platform_internal.h
- src/platform/platform_winuser.c
- src/platform/platform_worker.c
- src/platform/unittest/PlatformTest.cpp
Refactors the CxPlat event queue interface to have completions execute callback functions instead of call hardcoded functions with type value.
Existing CI/CD
N/A - Internal (for now)
> Event Queue Completion Refactor

- src/bin/CMakeLists.txt
- src/bin/msquic-config.cmake.in
- src/inc/CMakeLists.txt
- src/platform/CMakeLists.txt
- src/platform/unittest/external/CMakeLists.txt
Projects (e.g. msh3) that use CMake targets from dependencies (here: msquic) should use namespaced target names from those dependencies. This enables CMake to recognize the intention to use a target, not a library name. CMake can report a missing target definition early (at generation time), instead of creating linker instruction which may fail at build time.
msquic already added namespace `msquic::` to the exported CMake config. However, this should be complemented with `msquic::` `ALIAS` targets inside the build, for reverse dependencies which integrate msquic via `add_subdirectory`. This PR adds the missing targets.
In addition the PR shortens the exported name of `msquic_platform` to `msquic::platform`.
The `msquic::base_link` alias is added for use in msh3. (This nicely illustrate …
> Provide namespaced CMake targets

- src/platform/datapath_epoll.c
- src/platform/datapath_kqueue.c
- src/platform/datapath_raw.c
- src/platform/datapath_winkernel.c
- src/platform/datapath_winuser.c
- src/platform/platform_internal.h
- src/platform/platform_winkernel.c
- src/platform/platform_winuser.c
There was some additional feedback from https://github.com/microsoft/msquic/pull/4602
The biggest one being that we have the version fetching logic in a bunch of different places, let's instead standardize it in the CX_PLATFORM global object so subroutines can just reference it.
CI
No.
> [Expose TTL Follow up PR] move version logic to platform_xyz instead of datapath

- src/error.rs
- src/lib.rs
Rust Api typically returns Result<T,Error> where Error contains the error details of the api failure.
This PR implements ErrorCode enum type which can be easily converted from FFI error numbers, and Error type which produces decent error message when printed or formated. For example:
```rs
let err = Error::new(ErrorCode::QUIC_ERROR_ABORTED);
assert_eq!(format!("{err}"), "QUIC_ERROR_ABORTED (0x80004004)");
```
Changes all Apis to return Result<T,Error> instead of Result<T,u32> and removed all redundant code.
Added unit tests for error code conversion and formating.
NA
> Implement Error and ErrorCode for Rust

- src/error.rs
- src/ffi/mod.rs
- src/lib.rs
This is the beginning of a series of PRs to migrate from manually written code to use auto generated Rust ffi bindings, and make Rust APIs safe in default, and handles ffi internally in the crate.
This PR changes the following:
* Migrate to use ffi QUIC_API_TABLE from manually written ApiTable.
* Change Error::from_u32 and Error::ok to Error::ok_from_raw for dedicated error conversion from ffi function returns.
* Reorganize apis like get_param, set_param and simplify other apis built on top of them.
* Refactor the static api table initialization.
* Add unified raw handle functions for all wrapper handle types. All wrappers support from_raw(HQUIC), into_raw()->HQUIC, as_raw()->HQUIC, close() and Drop. This allows user to use unsafe ffi apis directly.
* Refactored the test code into test …
> Rust: Migrate to use ffi QUIC_API_TABLE

- .github/workflows/package-alpine-linux.yml
- .github/workflows/package-linux.yml
- src/cs/QuicSimpleTest/QuicHello.net8.0.csproj
.NET 9.0 is out, and we don't need 8.0 testing anymore. Most likely, we need to back port this change to older branches
CI
No
> Delete .NET 8.0 from pipeline

- docs/Sample.md
Delete the "{}" which makes the ip unable to identified
`-target:{127.0.0.1}` will result in error.
None
Modified the sample.md
> Fix wrong instruction in sample.md

- src/error.rs
- src/lib.rs
Originally Error was crated to wrap the quic status code in rust Result<(),Error>, but it creates confusions with the msquic naming. In callback events, "status" fields are used and Error in status fields looks odd.
Using StatusCode in callback events has other problems since StatusCode enum does not capture all possible returns from msquic. See #4786.
This PR renames Error to Status, and it will be used in callback events. This is also consistent with the StatusCode rename completed previously in #4765 
Existing tests.
NA
> Rust: Rename Error to Status

- src/platform/datapath_winuser.c
The `WSAIoctl` call for `RioDispatch` might fail, but it should not block initialization if we have already decided not to use Rio.
Existing tests do not cover the issue fixed by this PR.
N/A
> datapath_winuser: query RioDispatch only if we are using Rio

- src/platform/unittest/TlsTest.cpp
The latest (internal) Windows version made a slight change to the TLS behavior, so we need to relax the unit test checks.
CI/CD
N/A
> Relax TLS Unit Test Checks

- src/inc/msquic_winkernel.h
- src/inc/msquic_winuser.h
- src/test/MsQuicTests.h
- src/test/bin/quic_gtest.cpp
- src/test/bin/winkernel/control.cpp
- src/test/lib/BasicTest.cpp
Fixes #3969.
- Initialize address field when setting given QUIC_ADDR to loopback address
- Basic tests for several QuicAddr* API
Some existing tests hit this code path and new tests have been added for specific checks.
No
> Correctly initialize the ip address when setting QUIC_ADDR to the loopback address

- src/core/unittest/CMakeLists.txt
- src/platform/unittest/CMakeLists.txt
- src/test/bin/CMakeLists.txt
> added oldnames.lib in test files

- .github/workflows/build-reuse-unix.yml
- .github/workflows/build.yml
- .github/workflows/docker-publish-xcomp.yml
- .github/workflows/dotnet-test.yml
- .github/workflows/package-linux.yml
- .github/workflows/package-reuse-linux.yml
- .github/workflows/stress.yml
- .github/workflows/test-down-level.yml
- .github/workflows/test.yml
- scripts/secnetperf.ps1
GitHub is removing support for ubuntu-20.04 builds soon. Fixes #4809.
CI/CD
N/A
> Remove ubuntu-20.04 from GitHub Actions

- src/lib.rs
- src/types.rs
Provide a safe ConnectionEvent enum implementation. Added code to convert from ffi ConectionEvent union.
Removed manual ffi code for ConnectionEvent.
Added StreamRef as an none-owning handle wrapper used in ConnectionEvent.
Changed the existing test to use the new ConnectionEvent enum.
NA
> Rust: ConnectionEvent enum

- scripts/build.ps1
- scripts/generate-dotnet.ps1
- scripts/prepare-machine.ps1
- scripts/test.ps1
- scripts/update-sidecar.ps1
It is easy to miss / forget about the powershell 7 requirement for running scripts, especially when Windows still ship with version 5.
This makes the script failure clearly indicate that the powershell version is the reason for the failures (versus the current undefined variables errors).
Resolves #4810 
CI
N/A
> Require powershell 7.2 for scripts susceptible to be run manually

- src/inc/msquichelper.h
Debian Bookworm uses gcc version 12.2.0 (Debian 12.2.0-14) by default. It generates errors if `#pragma GCC diagnostic ignored "-Wstringop-overflow"` is not set. Lowering the minimum GCC version from 13 to 12 therefore fixes this problem.
To my knowledge, no existing tests cover this change. The only way to properly test this would be to add a Debian build to the CI/CD workflow.
There is no documentation impact for this change.
> Fix Release-Build Failure on Debian Bookworm

- src/lib.rs
- src/types.rs
Provide safe Listener callback event enum implementation. Added code to convert from ffi ListenerEvent union.
Removed manual ffi code for ListenerEvent.
Listener path for rust is not yet tested. Test will be added once we get more complete safe api wrappers.
NA
> Rust: ListenerEvent enum

- .github/workflows/test.yml
The BVT pipeline today takes roughly 90 minutes to complete all the tests.
While for official PRs this is acceptable, draft PRs that implement specific changes require a shorter turnaround time.
Introducing the filter on workflow dispatch expedites this process.
EDIT: not sure what happened with my git settings, it seems this change was pushed to main directly... This should not be allowed to happen (accidental or not). Let that be a follow up.
CI
N/A
> Add option to specify test filters on workflow dispatch

- src/core/connection.c
`QuicConnStart` sets the keep alive timer, when a client creates a new connection. However, this timer set is unnecessary because `QuicConnDrainOperations` will update the keep alive timer every time, for example, when the initial packet is set. 
Keep alives are already tested, so no new tests are needed.
Nope.
> Remove Extra Keep Alive set in ConnectionStart

- Cargo.toml
- src/lib.rs
Removed QUIC_STATS manual ffi wrappers and let api return generated ffi types.
Changed get_perf() api to return a struct and removed manual ffi types.
Added unsafe get_param_auto<T>() generic api to do auto mem allocation for type T, which simplifies the existing usage of get_param() api.
Added tests for get_perf and get_stats Api call in the existing test.
NA
> Rust: Refactor GetParam

- src/plugins/dbg/quictypes.h
- src/plugins/dbg/stream.cpp
- src/plugins/trace/dll/DataModel/QuicEvents.cs
Closes #4747 
Update the windbg and etw/wpa plugings with the updated enum definition + add the receive buffer mode to the stream description.
Local validation of the output when running tests
N/A
> Update windbg and etw plugins

- src/lib.rs
- src/settings.rs
Add safe wrapper for QUIC_SETTINGS ffi type.
Add setters for each setting entry using macro.
Changed Configuration new() to use new Settings type and removed the manual ffi type.
MISC:
Preview settings is removed/regressed because the auto generated bindings do not have preview apis yet.
Rust code files are accumulated in src dir. We should add a dedicated dir inside src to keep all rust code together. Will do it in a separate PR.
Added simple test to set settings using setters, and get the settings using ffi type to verify they match.
NA
> Rust: Settings type

- src/platform/platform_winuser.c
The `PADDING` field wasn't being set and apparently some code depended on that being explicitly zero.
Ci/CD & Locally
N/A
> Initialize processor info memory to prevent garbage values

- CMakeLists.txt
When compiled for sanitizer builds, ASAN loads from a local directory. So, we must relax the production requirement to load from only system32.
Locally and CI/CD
N/A
> Allow non-System32 DLL Loads for Sanitizer Builds

- scripts/run-executable.ps1
Often we're not actually seeing a dump file when a stress test crashes. Try adding a wait in there for up to 30 seconds.
CI/CD
N/A
> Wait for Dumps

- src/core/stream.c
- src/core/stream.h
- src/core/stream_set.c
- src/core/stream_set.h
- src/inc/quic_platform.h
- src/platform/inline.c
- src/plugins/dbg/quictypes.h
Store new streams that are blocked by Stream Id flow control in a sorted list (instead of the hash table containing all streams) to improve the performances of `QuicStreamSetUpdateMaxStreams`.
It will now be enough to iterate over a subset of this list instead of iterating over the entirety of opened streams when receiving a "MAX_STREAMS" frame increasing the limit.
Closes #3538
Already covered by existing tests.
In code documentation added.
> Optimize QuicStreamSetUpdateMaxStreams

- .github/workflows/cargo.yml
- Cargo.toml
- scripts/build.rs
- src/rs/config.rs
- src/rs/lib.rs
Provide safe Rust wrapper for RegistrationConfig and CredentialConfig types.
Removed the manual ffi code respectively.
Replaced the crate feature switch schannel with openssl. This makes the rust code by default compiles with schannel on winodws unless openssl feature is enabled. For linux, openssl is the default.
Added tests for loading credentials for each credential types.
NA
> Rust: RegistrationConfig and CredentialConfig types

- src/tools/recvfuzz/recvfuzz.cpp
Updates the receive fuzzer's packet queue to have a lock. Also removes usage of the std::list since it's not really needed.
Also cleaned up some of the code while I was at it.
Ran locally. CI/CD
N/A
> Fix Some Synchronization Issues in Receive Fuzzer

- scripts/quic_callback.ps1
- scripts/secnetperf-helpers.psm1
Expand the "Collect CPU traces" feature that was previously merged where `wpr.exe` was directly invoked to utilize the more established logging power-shell scripts in MsQuic.
Closes https://github.com/microsoft/netperf/issues/532
From this CI run on Netperf:
https://github.com/microsoft/netperf/actions/runs/13820352608/job/38666893105
WPR etl Logs were accumulated with "Basic.Lignt" configuration.
N/A
> Add support for MsQuic Logging on Azure Netperf

- Cargo.toml
- src/rs/lib.rs
* Update cargo edition from 2018 to 2021. We will update to the latest 2024 in the future.
* Update all dependencies to latest versions. And dependencies are specified up to the minor version, ignoring the patch version, which is typically what lib crate should do to allow apps to pick the exact patch version to use and avoid conflicts with other crates.
* Removed serde dependency since the manual ffi struct does not utilize it. In future serde might be added back if we support a safe wrapper over ffi types and the safe type might need serde.
NA
NA
> Rust: Update cargo edition and dependencies

- .github/workflows/build.yml
- scripts/build.ps1
- src/tools/forwarder/forwarder.cpp
- src/tools/interopserver/InteropServer.cpp
- src/tools/ip/server/quicipserver.cpp
- src/tools/lb/loadbalancer.cpp
- src/tools/sample/sample.c
There was an issue in updating ndk in openssl3/Configurations/15-android.conf. It gets updated based on value of 
env: ANDROID_NDK_ROOT, but this was not getting set properly. Updated the same in scripts/build.ps1 file.
Then there were errors related to unhandled return value for getchar() call, changed them to ignore the return value.
Resolves #4856.
Existing tests should be run successfully.
No
> Enable Android on 24.04 with openssl3

- src/rs/config.rs
- src/rs/lib.rs
- src/rs/server_client_test.rs
- src/rs/types.rs
Replaced various u32 flag types with bitflag enums.
Only the frequently used flags are implemented, other flags will be added when needed in the future.
NA
NA
> Rust: Implement various bitflags enums

- .github/workflows/publish-docfx.yml
- docs/Settings.md
Not much docs on the usage and behavior of stream priority set parameters for streams.
This PR should fill in the gaps.
Closes #4826 
N/A
N/A
> Document usage of stream priority set param

- src/rs/lib.rs
- src/rs/server_client_test.rs
Enable server client test on linux an macos.
Using test certs in the openssl submodule.
Removed code that sets the handle context to null after the handle close. It causes access violation in some cases, and handle after close should not be accessed anymore.
NA
NA
> Rust: Enable server client test on nix

- src/test/lib/DataTest.cpp
`QuicTestStreamMultiReceive` was using a global buffer as a send buffer, shared between test cases.
Test cases would modify the buffer, but also assume it was zeroed.
CI
N/A
> Avoid reuse of a global buffer between test cases

- .github/workflows/cargo.yml
- Cargo.toml
- scripts/build.rs
Added new feature to support linking pre-installed msquic lib in system location, and in vcpkg location. 
Manual local testing with pre-installed deb pkg, and vcpkg respectively. 
NA
> Rust: Support linking pre-installed msquic lib

- src/core/recv_buffer.c
- src/core/unittest/RecvBufferTest.cpp
Fixes an edge case received data could be overwritten before being drained in the receive buffer.
The issue occurs when:
- A read is pending
- A write triggers a buffer re-allocation
- The math aligns such that the write almost fills the newly allocated buffer
The logic to determine the size needed for the new buffer would consider that the "read pendind" data doesn't need room in the newly allocated buffer. This is wrong, as the data needs to be kept in case it isn't drained.
This would lead to two issues:
- in Single mode, a write could wrap around
- in Single and Circular mode, the newly written data could overwrite the data pending a read
- this doesn't cause an immediate issue since the pending read points to the now retired buffer
- but if the data isn't drained, it will have been …
> Fix data corruption in receive buffer

- docs/API.md
- docs/Execution.md
- docs/Streams.md
- docs/api/QUIC_CONNECTION_CALLBACK.md
- docs/api/QUIC_CONNECTION_EVENT.md
- docs/api/QUIC_LISTENER_EVENT.md
- docs/api/QUIC_STREAM_CALLBACK.md
- docs/api/QUIC_STREAM_EVENT.md
Add/update documentation around events in MsQuic
- Add documentation for QUIC Stream events
- Update/clarify existing documentation on use of events in MSQuic and events for other class types
No new tests necessary
This is a documentation change
> Add QUIC stream event documentation and other event related doc updates

- src/test/bin/quic_gtest.h
- src/test/lib/HandshakeTest.cpp
Add CIBIR tests back to the connection pool API tests.
Adding new tests
N/A.
> Add Cibir tests to Connection Pool tests

- .github/workflows/test.yml
- scripts/prepare-machine.ps1
Add a log level parameter to the BVT workflow to allow invoking it directly to collect more logs.
The valid client certificate test frequently fails on Windows 2025 (and 2022) as reported in #4927. This PR adds logging to the certutil command that installs the root certificate that signs the client certificate.  This may help shed light on why the client certificate is untrusted.
CI
> Add log level parameter to BVT workflow and Log Certutil errors

- src/platform/datapath_epoll.c
1.Temporarily stashing the newly accepted socket in the listener's socket context is unnecessary. It's copied from winuser where the listener always keeps a pre-posted acceptex IO.
2. Use accept4() to accept and set nonblocking in one shot.
3. Load balancing on accept to match UDP behavior. HPS increased ~30% on my 20-core linux home machine over loopback (`secnetperf -target:127.0.0.1 -tcp:1 --scenario:hps -rconn:1 -runtime:5s -conns:64`).
CI
> Epoll TCP accept load balancing and code clean up

- src/core/connection.c
Fixes the issue #4326.
Update the HpMask when processing batch of packets in function QuicConnRecvDatagramBatch.
If KeyType of packet changes then use new KeyType of current packet (ReadKeys[Packet->KeyType]->HeaderKey) to compute HpMask which is used to decrypt the packets.
Ran existing test cases to make sure it is not breaking anything.
This may not fully solve Misc/WithCidUpdateArgs.CidUpdate/5 faliure, but it solves decryption failure issues caused by change in packet header key.
No.
> Avoid Batching of Packets with Different Keys

- .github/workflows/cargo.yml
- rust-toolchain.toml
- src/rs/error.rs
Rust ci is broken due to compiler version upgrade.
Fixed the clippy error and pinned the rust version in ci using standard setup rust github action.
CI should not be broken in the future like this time without code changes.
NA
NA
> Rust: Fix rust ci build

- docs/Streams.md
- docs/api/ConfigurationClose.md
- docs/api/ConnectionClose.md
- docs/api/ListenerClose.md
- docs/api/StreamClose.md
- docs/api/StreamReceiveComplete.md
- docs/api/StreamReceiveSetEnabled.md
- src/core/stream.c
Update documentation to clarify some ordering constraints between API.
Focuses on "*Close" calls and the send and receive operations.
Closes #3635.
N/A
Doc only
> Update documentation to clarify API ordering constraints

- src/rs/lib.rs
- src/rs/server_client_test.rs
Add api to get stream id.
Added api call in existing test.
NA
> Rust: Add get stream id API

- src/core/connection.c
- src/generated/linux/connection.c.clog.h
- src/generated/linux/connection.c.clog.h.lttng.h
- src/manifest/clog.sidecar
Log the version in hex instead of decimal.
Automation
N/A
> Change Formatting of QUIC Version Trace

- scripts/build.rs
Should hopefully fix the following random build failure:
```
D:/a/msquic/msquic/target/debug/build/msquic-7d379929a28ccd7c/out/build/inc\MsQuicEtwTEMP.BIN : error : Failed to open file for write: 'D:/a/msquic/msquic/target/debug/build/msquic-7d379929a28ccd7c/out/build/inc\MsQuicEtwTEMP.BIN' [D:\a\msquic\msquic\target\debug\build\msquic-7d379929a28ccd7c\out\build\MsQuicEtw_HeaderBuild.vcxproj]
```
CI/CD
N/A
> Disable Parallel Builds for Rust on Windows

- docs/api/ConnectionOpen.md
- docs/api/ConnectionOpenEx1.md
- docs/api/ConnectionOpenInPartition.md
- src/core/api.c
- src/core/api.h
- src/core/library.c
- src/cs/lib/msquic_generated.cs
- src/inc/msquic.h
- src/inc/msquic.hpp
- src/rs/ffi/linux_bindings.rs
- src/rs/ffi/win_bindings.rs
- src/test/lib/ApiTest.cpp
Adds the new API `ConnectionOpenInPartition` that adds a new parameter that allows the application to specify the partition index explicitly so we don't need to infer/guess based on the current processor it's running on.
Updated, but the old function goes through the new one, so really it is completely covered already.
Updated/added.
> Add ConnectionOpenInPartition

- src/core/recv_buffer.c
- src/core/recv_buffer.h
This is the first of a series of PR to simplify the receive buffer code by unifying the handling of the different buffer modes where possible.
This change:
-  introduces a "RetiredChunk". It is meant to store a chunk when Single/Circular mode duplicates its content but can't free it yet because it is externally referenced.
- we could add the retired chunk to the chunk list later on if we want to save a pointer, but setting it aside will make it easier to reason about changes to the read, write and drain logics for now
- make sure the "Capacity" is properly updated for single / circular mode when allocating a new buffer
- fixes some comments, add assertions and fix variable name style
N/A
No, the documentation doesn't go in that level of details
> RecvBuffer simplifications [1/N]

- docs/Streams.md
- docs/api/QUIC_STREAM_EVENT.md
Document the lifetime of the QUIC_BUFFER array in receive events.
It is otherwise easy to assume the pointer to the provided to the callback is alive until the receive is completed.
N/A
N/A
> Document the lifetime of the QUIC_BUFFER array in receive events

- src/platform/platform_posix.c
- src/platform/platform_winuser.c
In secnetperf, we call CxPlatSystemLoad and CxPlatInitialize before calling into msquic open. When statically linking to msquic, CxPlatSystemLoad and CxPlatInitialize access the set of global variables in memory. This leads to double free.
Add a safety guard to prevent it from happening.
CI
> Fix secnetperf calling some cxplat functions twice

- scripts/run-gtest.ps1
Print out when a test case is skipped so it's possible to tell the difference from tests that ran and passed.
N/A
N/A
> Print out when test cases are skipped

- src/perf/lib/Tcp.cpp
- src/perf/lib/Tcp.h
It's a race between `PerfClientWorker::WorkerThread` and `TcpWorker::WorkerThread`. In the middle of creating a socket from the perf client worker thread, as long as epoll has been told to monitor the socket, a notification could come up at the same time from tcp worker thread and frees the connection.
```
#1  0x00005b7e577eec9f in CxPlatSocketContextSetEvents
#2  0x00005b7e577ef725 in CxPlatSocketCreateTcpInternal
#3  0x00005b7e577efb8a in SocketCreateTcp
#4  0x00005b7e577ebdb9 in CxPlatSocketCreateTcp
#5  0x00005b7e577db274 in TcpConnection::Start
#6  0x00005b7e577def35 in PerfClientConnection::Initialize
#7  0x00005b7e577df124 in PerfClientWorker::StartNewConnection
#8  0x00005b7e577df140 in PerfClientWorker::WorkerThread
```
The fix is moving the actual connection start to the tcp …
> Fix a race condition in TCP epoll code

- src/test/bin/quic_gtest.cpp
The test is flaky and is causing too much noise. Just disable it until we figure it out. Related to #4927.
CI/CD
N/A
> Temporarily Disable the Flaky ConnectValidClientCertificate Test on windows-2025 GitHub Runner

- .github/workflows/build-reuse-unix.yml
https://github.com/actions/runner-images/issues/11101 broke ubuntu 20.04 builds.
Let's add this patch to fix netperf, while transitioning towards ubuntu 22.04.
CI 
N/A
> Hotfix: add support for building on ubuntu 20.04

- src/perf/lib/PerfClient.cpp
For TCP, in `PerfClientConnection::OnHandshakeComplete`, we free up the `PerfClientConnection` object inline in the shutdown call. Immediately after that, we still try to access fields on this `PerfClientConnection` object to queue a new connection. This is writing to already freed memory. It also leads to queuing 2 connections on each handshake completion (once in `PerfClientConnection::OnShutdownComplete` and once in `PerfClientConnection::OnHandshakeComplete`).
Locally ran secnetperf with ASAN.
> Fix a memory corruption in secnetperf

- src/fuzzing/fuzz.cc
CXPLAT_DBG_ASSERT is failing compilation in the fuzzer here: https://github.com/google/oss-fuzz/actions/runs/14454075706/job/40663846040?pr=13222
Because both msquic.hpp and quic_platform.h define the macro, and only the former has ifndef guards around the definition.  This is not problematic in other inclusion sites because quic_platform.h is always included first.  This is not true in the case of fuzz.cc, which reverses the inclusion order.
Correct fuzz.cc to include files in the same order as other inclusion sites to avoid the duplicate definition issues
CXPLAT_DBG_ASSERT is failing compilation in the fuzzer here: https://github.com/google/oss-fuzz/actions/runs/14454075706/job/40663846040?pr=13222
Building the fuzzer in oss-fuzz covers the needed testing for this issue
None
> Prevent duplicate definitions of CXPLAT_DBG_ASSERT

- src/perf/bin/appmain.cpp
#5004 has a bug where QUIC_SUCCEEDED is missing in `CXPLAT_FRE_ASSERT(MsQuic.GetInitStatus())`. I probably forgot to run it locally on the last iteration.
Ran locally.
> Missing QUIC_SUCCEEDED in secnetperf main

- src/platform/datapath_epoll.c
Writing on a peer closed TCP socket triggers a SIGPIPE signal, which can cause the application to exit silently if not captured. Disable it by setting the MSG_NOSIGNAL flag in the `CxPlatSendDataSendTcp` function.
CI. Locally ran secnetperf and I have not seen server exit silently with this change.
> Disable SIGPIPE signal on epoll TCP send 

- src/perf/lib/PerfClient.cpp
- src/perf/lib/PerfClient.h
- src/perf/lib/PerfServer.h
- src/perf/lib/Tcp.cpp
- src/perf/lib/Tcp.h
- src/platform/datapath_epoll.c
By reusing the security config for TCP, this should significiantly improve performance on the client side.
CI/CD
N/A
> Refactor TCP Security Config for Reuse on Client Connections

- src/perf/lib/Tcp.h
They are never used and defaults were unsafe. Delete them.
CI/CD
N/A
> Delete TCP C++ Copy/Move Functions

- scripts/secnetperf-helpers.psm1
- src/perf/lib/PerfClient.cpp
- src/perf/lib/PerfClient.h
Updates the output for throughput prints to sum the rates across all the streams/connections that were run. Makes it much easier to understand total throughput with multi-connection tests.
Locally. CI/CD
N/A
> Sum Throughput Rates Across Streams/Connections

- src/platform/datapath_epoll.c
In HPS scenario, we can run out of ephemeral ports quickly. Set linger option to force reset on socket close to prevent the connection from entering TIME_WAIT state.
Locally ran secnetperf and now it can be run repeatedly without hitting 111 error.
> Set linger socket option to prevent TIME_WAIT for HPS scenario to work repeatedly

- scripts/build.rs
windows "static" build for rust is flakey maybe due to the cmake --parallel option.
It is injected by cmake-rs:
https://github.com/rust-lang/cmake-rs/blob/fd56c5a6b4ecda8815c863eb5b12d7b3f0391197/src/lib.rs#L877
Removing the cargo env var NUM_JOBS prevents the injection.
CI
NA
> Rust: disable cmake-rs --parallel option on windows

- src/test/lib/ApiTest.cpp
This will need to be backported to 2.3 and 2.4, to fix down level tests.
CI/CD
N/A
> Fix the QUIC_HANDSHAKE_INFO Test to Allow for Future Versions to Grow Size

- src/perf/lib/PerfClient.cpp
In #5023, PrintThroughput was changed and PrintConnThroughput was added. This add the number of connections and streams to the -ptput argument, which prints the sum of the throughputs.
The documentation has to be updated. The -pctput argument is not documented.
> Print connections and stream number for more useful throughput data

- scripts/build.ps1
The `VERBOSE=1` arg is nonstandard and not supported by Ninja build, so pass that param only to default or "cmake" generators.
Seems to work on my machine.
Nope.
> Avoid passing incompatible argument to ninja in build.ps1

- src/test/lib/HandshakeTest.cpp
Updates `QuicTestHandshakeSpecificLossPatterns` to have the registration shutdown/abort any leftover connections on test exit.
Related to #5024, but may not fix it.
CI/CD
N/A
> Shutdown Connections on QuicTestHandshakeSpecificLossPatterns Exit

- src/core/recv_buffer.c
- src/core/recv_buffer.h
Part of a series of PR to simplify the receive buffer code by unifying the handling of the different buffer modes where possible.
This change:
- introduces an iterator over the receive buffer chunk list. It provides a view to the contiguous spans of data in chunk list, skipping an initial offset
- refactors the read and write operations using the iterator
- introduce a validation function to enforce the receive buffer invariants consistently
CI
N/A
> RecvBuffer simplifications [2/N]

- src/bin/winkernel/driver.c
- src/core/configuration.c
- src/core/listener.c
- src/inc/quic_platform_winkernel.h
- src/platform/platform_winkernel.c
We don't support per-silo ETW tracing. So, always use the host silo for everything in DriverEntry and DriverUnload,
Locally tested in a VM. CI.
> Always use host silo for ETW registration

- .azure/OneBranch.Package.yml
- .github/workflows/build-reuse-unix.yml
- .github/workflows/test-down-level.yml
- CMakeLists.txt
- Cargo.toml
- scripts/package-distribution.ps1
- scripts/package-nuget.ps1
- scripts/prepare-machine.ps1
- scripts/write-versions.ps1
- src/bin/winkernel/driver.c
- src/core/configuration.c
- src/core/listener.c
- src/distribution/Info.plist
- src/inc/msquic.ver
- src/inc/quic_platform_winkernel.h
- version.json
1. Backport ETW silo fix (#5049) to 2.3.
2. Fix pipeline regressions introduced in #4862.
CI
> Backport ETW silo fix to v2.3

- .azure/OneBranch.Package.yml
- CMakeLists.txt
- Cargo.toml
- scripts/package-distribution.ps1
- scripts/package-nuget.ps1
- scripts/write-versions.ps1
- src/bin/winkernel/msquic.kernel.vcxproj
- src/bin/winkernel/msquicpriv.kernel.vcxproj
- src/distribution/Info.plist
- src/inc/msquic.ver
- src/perf/bin/secnetperfdriver.kernel.vcxproj
- src/perf/bin/secnetperfdriverpriv.kernel.vcxproj
- version.json
Cherry-pick of #5063 to release/2.4.
> CP: Randomize Base Address in Kernel Projects (#5063)

- src/test/lib/TestConnection.cpp
Increases the total wait time from 2 seconds to 5 seconds for the Key and CID update tests. We still occassionally see failures in these tests on oversubscribed VMs used for testing.
Closes #4325.
CI/CD
N/A
> Increase Retry Limit for Key/CID Update Tests

- src/test/lib/TestConnection.cpp
Revert recent retry increase because it's causing other test issues.
Automation
N/A
> Revert Recent Large Retry

- .docker/ubuntu-22.04/Dockerfile
- .docker/ubuntu-24.04/Dockerfile
For the io_uring PR #5061, the build containers need liburing-dev.
CI?
No.
> Add liburing to ubuntu 22.04 and 24.04 Docker images

- src/core/recv_buffer.c
- src/core/unittest/RecvBufferTest.cpp
Refactor the "drain" operation in the receive buffer.
The "drain" operation has a lot of mode-specific behavior and ended-up being implemented in a way that required a lot of special casing.
In particular, the "full" and "partial" drain logic was convoluted.
This PR simplify the "drain" operation by using a more generic approach and limit the number of special cases. It still uses a "full" and "partial" drain helpers, but in a more systematic way:
- the "full" drain deals with all chunks that are fully consumed (all bytes have been written, read and drained)
- the "partial" (or "firstchunk") drain updates the chunk now at the front of the list
C/I
No changes, the existing documentation cover this.
> RecvBuffer simplifications [3/N]

- CMakeLists.txt
Fixes DLL load failure on gamecore, where msvcrt is shipped with application. 
ref: #4883 
Manually verified locally. 
N/A
> gamecore: allow non-system32 DLLs to be loaded

- scripts/update-sidecar.ps1
CLOG currently requires a .NET framework be installed matching its target framework version, which is 6.0. Since 6.0 is out of support, we should not require build or test machines to have this obsolete library installed, or even to keep in lockstep.
Instead, use a .NET [environment variable](https://learn.microsoft.com/en-us/dotnet/core/versions/selection) to allow any newer framework to run the older code in compatibility mode.
Works locally with only .NET 8.x installed.
Nope.
> Allow update-sidecar to run on newer framework versions

- .github/workflows/cargo.yml
- src/inc/msquic.h
Upload rust binding diff as an artifact + print it in the logs: the comment on the PR doesn't work for forks based PRs.
See on this PR CI run.
N/A
> Upload rust binding diff as an artifact

- scripts/generate-dotnet.ps1
- src/core/connection.c
- src/cs/lib/msquic_generated.cs
- src/inc/msquic.h
- src/rs/ffi/linux_bindings.rs
- src/rs/ffi/win_bindings.rs
Added RttVariance to connection statistics. Fixes #4360
Adds the RttVariance statistic to QUIC_STATISTICS_V2, allowing applications to monitor changes to the Rtt of a connection over time.
> Added RttVariance to connection statistics.

- README.md
Some tweaks to the readme to hopefully make it more streamlined and helpful.
N/A
N/A
> Readme Tweaks

- scripts/prepare-machine.ps1
- scripts/quic_callback.ps1
- scripts/secnetperf-helpers.psm1
- scripts/xdp.json
The steps to install and uninstall XDP are implemented in several different places, each one subtly different. This is contrary to the software engineering best practice of reducing duplication and having a single point of maintenance for a given piece of functionality. 
For unknown reasons, each of these duplicated implementations was actually not duplicated, but subtly different.
Use one function to do one thing.
CI.
No.
> Update XDP to latest prerelease, dedupdupduplicate xdp install/uninstall

- scripts/secnetperf.ps1
The secnetperf script collects Get-NetView only if a session exists, which isn't very useful if a session doesn't exist.
Update the script to always collect local data.
CI.
No.
> always collect Get-NetView in secnetperf

- src/core/connection.c
- src/platform/datapath_raw_socket_win.c
- src/platform/datapath_raw_xdp_linux.c
- src/platform/datapath_raw_xdp_win.c
Recent onboarding of the interop over XDP exposed an issue with the RAW datapath and the rebind scenario. The route was kept as resolved, but it was clearing the queue, which would later crash on send. This fix clears the resolved state to force a new route resolution.
Validated locally over XDP. CI/CD
N/A
> Fix Rebind for Raw Datapath

- src/generated/linux/datapath_winkernel.c.clog.h
- src/generated/linux/datapath_winkernel.c.clog.h.lttng.h
- src/platform/datapath_winkernel.c
For several years now, the Windows kernel datapath has been always copying the recevied data in to local buffers because we found that any significant queuing can cause problems lower in the stack (i.e., the NIC); even if we queued only 1 indication. So, let's just remove all the code that supported the queuing mode to eliminate unnecessary branches in the kernel datapath code.
CI/CD
N/A
> Remove DataIndication Queuing from  Kernel Datapath

- scripts/xdp.json
Partially revert #5085 and use the most recent official XDP release, version 1.1.
CI.
No.
> Revert to XDP version 1.1 (official)

- scripts/secnetperf-helpers.psm1
- scripts/secnetperf.ps1
To independently test the client IO mode vs a constant server IO mode across IO models, add a new serverio knob.
Used by https://github.com/microsoft/netperf/pull/629.
Manually triggered run in netperf - https://github.com/microsoft/netperf/actions/runs/15030683055.
No.
> Make server IO independently configurable in secnetperf

- src/platform/datapath_raw_xdp_win.c
#5080 added TX checksum offload and set the precedent for how RX checksum offload could work, so remove the experimental knob to simply fake the offload.
Builds locally, CI.
No.
> remove unused XDP skip checksum logic

- src/platform/datapath_raw_socket.c
- src/platform/platform_internal.h
Our SW checksum code does not reset the checksum field on IP/TCP/UDP header to zero before calculating the checksum. This will lead to packet drops if it happens not to be zero.
CI
> Set checksum field to zero before performing SW checksum

- src/test/lib/DataTest.cpp
The `AckSendDelay` test was flaky and of doubtful utility:
- it asserts there was only a single ACK received after a client send a buffer, which isn't fully true: other frames can be sent for reasons outside of the test control (for instance, NEW_CONNECTION_ID).
- the ack delay feature tested is more about whether an ACK is eventually sent if no other ack-eliciting frame is received, and less about whether an ack piggy-pack on the next frame sent by the server (which is an MsQuic implementation detail)
The test is re-written to validate an ACK is received within a reasonable amount of time after a send.
N/A
N/A
> Fix the AckSendDelay test

- src/core/loss_detection.c
- src/core/packet_builder.c
- src/core/send.c
- src/core/send.h
- src/generated/linux/loss_detection.c.clog.h
- src/generated/linux/loss_detection.c.clog.h.lttng.h
- src/generated/linux/packet_builder.c.clog.h
- src/generated/linux/packet_builder.c.clog.h.lttng.h
- src/manifest/clog.sidecar
Randomizes the initial packet number used and periodically (randomly) skips packet numbers.
CI/CD
N/A
> Implement packet number skipping for attack detection and improve security

- src/inc/quic_platform_winkernel.h
This adds a static assert to the kernel header to ensure we're targetting the right downlevel release (Fe). Otherwise, it can break back-compat.
CI/CD
N/A
> Add Kernel Static Assert Correct Version is Targetted

- src/inc/quic_platform_winkernel.h
Hard code the NTDDI_VERSION in code since OneBranch sometimes overwrites the compiler/linker cmd line.
CI/CD
N/A
> Define NTDDI_VERSION in Code

- src/core/configuration.c
- src/core/library.c
- src/core/unittest/SettingsTest.cpp
- src/generated/linux/storage_winuser.c.clog.h
- src/generated/linux/storage_winuser.c.clog.h.lttng.h
- src/inc/quic_storage.h
- src/platform/storage_posix.c
- src/platform/storage_winkernel.c
- src/platform/storage_winuser.c
- src/test/bin/quic_gtest.cpp
- src/test/lib/ApiTest.cpp
- src/test/lib/precomp.h
* Add Writability to Storage Abstraction
* Add tests from #5132
> CP: Add Writability to Storage Abstraction (#5133)

- src/platform/tls_quictls.c
The latest version of MSVC supplies a warning on these static asserts which guarantee interoperability of certain enumerated types. This former cast-to-int approach was no longer working. This now uses a cast to the MsQuic enumerated type.
CI
No documentation change needed.
> Fix quictls static assert

- Cargo.toml
Crates.io only accept crates of less than 10MB and MsQuic.crate grew above it.
This reduces the weigth by trimming OpenSSL and QuicTLS fuzzing cases.
More would be nice to trim (test, documentation), but it causes build failures.
Related to #5175.
`cargo publish --dry-run --allow-dirty` succeeds and create 9.9MB crate.
N/A
> Reduce rust crate size by excluding fuzz test corpora

- src/core/connection.c
Attach to the right silo when uninitializing a connection. Otherwise, the security context could be freed in a silo that's not where the context was allocated.
CI and local testing
N/A
> More silo enlightenment

- src/perf/bin/appmain.cpp
> Fix SecNetPerf Parameter Handlings

- scripts/log.ps1
Fixes #4375 
In the `log.ps1` script, we test if 'perf' is installed by running the CLI tool directly.
Obviously, if perf was not installed, we will throw a "Command Not Found" error.
This problem has been silently lurking for so long due to most linux machines already having perf installed.
CI + manual testing with WSL
N/A
> Fix Linux Log "perf not found" errors

- src/core/connection.c
- src/platform/datapath_win.c
- src/platform/tls_openssl.c
#5220 Attach to the right silo when uninitializing a connection. Otherwise, the security context could be freed in a silo that's not where the context was allocated.
CI and local repro
N/A
> CP: More silo enlightenment (#5220) - v2.4

- CMakeLists.txt
Optimization level -Og doesn't allow proper debugging, as most functions and variables still end up being optimized.
This PR uses -O0 instead for Linux debug builds.
Related to #5024
CI.
N/A
> Use O0 instead of Og in Linux debug builds

- submodules/CMakeLists.txt
In non-onebranch scenarios, the target architecture needs to be set in OpenSSL/quicTLS configure step for clang builds cross-compiling for arm64.
CI
N/A
> Set the Target Architecture on OpenSSL/quicTLS arm64 builds

- src/platform/tls_openssl.c
Size checks on QUIC_HANDSHAKE_INFO need to take into account backward compatibility, as some prior versions were a shorter length.  Quictls and schannel account for this but openssl does not.
Fix that up
Fixes #5217
> Fix size check for QUIC_HANDSHAKE_INFO

- CMakeLists.txt
The undock pipeline uses the same cmake flags for all the archs of a target container which means it will throw an error when QUIC_LINUX_XDP_ENABLED is on for arm architectures as its not supported. This PR adds a check to disable the flag for arm archs.
> modified cmake to disable xdp for arm architecture

- docs/PreviewFeatures.md
- docs/Streams.md
- docs/api/QUIC_STREAM_EVENT.md
- docs/api/StreamProvideReceiveBuffers.md
- src/core/crypto.c
- src/core/recv_buffer.c
- src/core/recv_buffer.h
- src/core/stream.c
- src/core/stream.h
- src/core/stream_recv.c
- src/core/unittest/RecvBufferTest.cpp
- src/cs/lib/msquic_generated.cs
- src/generated/linux/stream.c.clog.h
- src/generated/linux/stream.c.clog.h.lttng.h
- src/inc/msquic.h
- src/manifest/clog.sidecar
- src/rs/ffi/linux_bindings.rs
- src/rs/ffi/win_bindings.rs
- src/test/MsQuicTests.h
- src/test/bin/quic_gtest.cpp
- src/test/bin/winkernel/control.cpp
- src/test/lib/DataTest.cpp
Cherry-pick of #5313
When using app-provided buffers, the flow control window was constrained to the amount of buffer provided by the application.
Assuming the application mis-calculates the amount of buffer needed, this could cause a stream to be soft-locked: the receive window would be zero and the sender wait forever.
This changes this behavior:
- the flow control window is no longer bound by the amount of buffer provided
- if more data is received than there is buffer space, a `QUIC_STREAM_EVENT_INSUFFICIENT_RECEIVE_BUFFER` is sent to the app which can:
- provide more buffer space inline
- close abortively the receive side of the stream inline
Otherwise, the connection is aborted.
Test have been improved and adapted for the new behavior.
Instead of validating that when the sender …
> CP: Allow the app to react when app-provided buffer is insufficient

- scripts/quic_callback.ps1
- scripts/secnetperf-helpers.psm1
- scripts/secnetperf.ps1
Attempt to address issues #5348 #5334 
The idea here is that for projects like MsQuic to leverage both lab-based and Azure-vm based perf testing, we have a standardized interface such that no internal implementation details leak.
Here is the proposed design:
For projects that only need to use the lab, they can still leverage remote powershell.
Every project that wants to leverage both Azure + Lab in their workflows needs to run:
- InitNetperfLib "project_callback.ps1"
- CopyRepoToPeer
Each time the client needs to orchestrate some remote commands to run on the peer, you always use:
- NetperfSendCommand -Command X
- NetperfWaitServerFinishExecution
And you add details to "project_callback.ps1" where:
if (command == X) {
...do XYZ...
}
Needs dependent Netperf PR: …
> Simplify Netperf API

- scripts/log.ps1
CLOG by default requires exactly version 6.0 of the .NET framework, which is obsolete and not secure. Allow CLOG to run with newer version of the framework in the logging script, which is used by test infra.
Tested locally.
No.
> Allow CLOG to run on newer frameworks in test

- src/platform/tls_openssl.c
Casting an unaligned byte pointer to uint32_t can result in a crash on ARM architectures, and result in low-performance on x64 architectures. Discovered via UBSAN.
Existing tests should exercise this scenario thoroughly
N/A
> Fix unaligned memory access

- CMakePresets.json
- scripts/build.ps1
- QUIC_LINUX_LOG_ENCODER is an incorrect CMake options, should be modified to `QUIC_LOGGING_TYPE`.
No new tests should be required.
No docs need be updated.
> Fix incorrect cmake option name in build.ps1 and cmakepreset

- src/platform/datapath_raw_xdp_win.c
As part of the change to have listeners support both QTIP and QUIC/UDP, we configure the XDP rules to listen to both 
UDP and TCP packets bound to the listener port. 
But the problem is, we always set these rules, even in cases where XDP is enabled but not QTIP. What that means is we don't create an auxiliary TCP socket, so other applications bound to the same TCP port as the msquic listener will have their traffic stolen. 
CI
N/A
> QTIP: Configure XDP rules properly

- .docker/ubuntu-22.04/Dockerfile
- .docker/ubuntu-24.04/Dockerfile
- .github/dependabot.yml
- scripts/build.ps1
> Update dependency version constraints for ubuntu build dockers

- src/inc/quic_platform_posix.h
- src/inc/quic_platform_winkernel.h
- src/inc/quic_platform_winuser.h
- 1. in any cases, `T2 + (0xFFFFFFFF - T1) + 1` is equal to `T2 - T1`;
- 2. subtraction (`T2 - T1`) can handle wraparound automatically in the ring 2^32;
- 3. removed if-else in TimeDiff function improves the performance;
No new testing required.
No docs need to be updated.
> Removed unnecessary if-else in TimeDiff functions

- .github/workflows/test.yml
Improvement to the auto-issue filer. 
Right now, it would create issues even on pull requests, which would be a WIP. 
In theory, if a PR had 100+ failures, then it would log 100+ issues. This would be bad.
CI
No
> Only create issues on Merge Events

- codecov.yml
The code coverage CI validation is very often failing without a clear reason.
For instance, this should be included in the 2% threshold allowance, but is however marked as failing.
This introduces noise in the CI and show failing overall CI result that we simply ignore.
This PR makes the code coverage informational only, since this is already how we treat it in practice.
- Make codecov informational
- Fix config to follow the codecov documentation
n/a
n/a
> Make codecov informational

- src/core/connection.c
Cherry-pick #5477 
Some spurious test failures show a pattern when the two peers entered a loop of sending CONNECTION_CLOSE frames to each other. This regression was introduced by #5107.
According to RFC 9000:
- When a peer sends a CONNECTION_CLOSE frame, it enters the "closing" state and should answer any incoming packet on the connection with a new CONNECTION_CLOSE frame (subject to rate limiting), to ensure the peer get the CONNECTION_CLOSE.
- When a peer receives a CONNECTION_CLOSE frame, it enters the "draining" state and should not send any more packets.
(The RFC is not explicit about what happens when a peer in the "closing" state receives a CONNECTION_CLOSE, but since it means both peers are closing the connection, it can stop sending additional CONNECTION_CLOSE).
However, #5107 …
> CP: Do not send CONNECTION_CLOSE frames in draining state.

- .github/workflows/netperf-kernel-bvt.yml
Netperf, in addition to measuring performance data on MsQuic, should also be able to run MsQuic functional CI (a subset) in Kernel mode and collect crash dumps for analysis.
Fixes #5273 
We can leverage this pattern for the XDP-for-windows project too.
Validation: 
https://github.com/microsoft/netperf/actions/runs/18208239591,
which ran on MsQuic Ref: https://github.com/microsoft/msquic/compare/main...jackhe/bugcheck-on-purpose
Here is another run which doesn't run on an MsQuic version that does not bugcheck:
https://github.com/microsoft/netperf/actions/runs/18206803000
> Leverage Netperf Lab to Collect CI MEMORY dumps

- src/platform/datapath_iouring.c
Add diagnostics to try to detect #5490 closer to the root cause. Debugging details are in the bug, but it looks like the crash occurs when a send IO completes after the socket is torn down. I'm not certain this newly-asserted code path _is_ happening, but with the assert added we can rule it out or confirm it.
Builds and spins locally.
No.
> Add io_uring assert to detect send-after-shutdown

- .github/dependabot.yml
Update test and CI dependencies on a monthly basis to reduce overhead.
Code (submodule) / build (cargo, etc...) dependencies keep being updated on a weekly basis.
CI
N/A
> Reduce test-only dependency upgrade to a monthly cadence
