docs/Support.md

Also being used as a sample workflow after making the repo public.

Remove MsQuic 1.0 Link in Support Docs

---

README.md

Fixing wording, per suggestion on quicdev Slack.

Minor Rewording of Readme on OpenSSL Usage

---

scripts/build.ps1
scripts/interop.ps1
scripts/spin.ps1
scripts/test.ps1

`$null` was giving me weird results. `""` seems to work better.

Fix PowerShell Script Defaults

---

src/core/registration.c
src/core/registration.h
src/core/session.c
src/inc/quic_platform_linux.h
src/tools/interopserver/InteropServer.cpp
src/tools/ping/PingConnection.cpp
src/tools/ping/QuicPing.cpp
src/tools/ping/QuicPing.h

Fixes up several callers of strcpy, strcat and strcpy_s to improve them some.

Refactor String API Dependencies

---

src/inc/msquic_winuser.h

Fixes #376. See Issue for details. FYI @ThadHouse

Change QUIC_API to __cdecl on Windows User Mode

---

.azure/scripts/run-gtest.ps1
.azure/templates/run-bvt-int.yml
.azure/templates/run-bvt.yml
scripts/test.ps1

Finishes up the NoProcDump support to provide a similar level of support (as far as collecting dump files) but in a much more efficient way. Pushing this to test how it works in Azure Pipelines.

Finish NoProcDump Support for Azure Pipelines

---

src/core/settings.c
src/tools/interop/interop.cpp

Fix #363.
This PR first adds more configurable functionality to the quicinterop tool to allow for easier/custom debugging and log collection. Second it fixes a bug in the settings where the ValueLen field was being used on output when the storage query was failing. Apparently, the Windows APIs were changing the value of that, causing the "default" logic to end up setting a value of zero to the setting.

Fix No Idle Timeout TP Bug

---

.gitignore

This folder contains user specific settings which should be ignored. Specific files we don't want ignored can be added later.

Ignore VS Code Settings Folder

---

CMakeLists.txt
src/platform/CMakeLists.txt
src/platform/unittest/CMakeLists.txt

In case this changes across different platforms.

Use CMAKE_STATIC_LIBRARY_SUFFIX for openssl

---

src/bin/winkernel/msquic.kernel.vcxproj
src/core/core.kernel.vcxproj
src/platform/platform.kernel.vcxproj
src/test/bin/winkernel/msquictest.kernel.vcxproj
src/test/lib/testlib.kernel.vcxproj

An attempt to fix another Xbox issue.

Add More Kernel Mode Compiler Options

---

README.md

Now that I've created a publicly viewable CI pipeline, update the readme badge to point to it.

Update Badge to Public Location

---

src/bin/winkernel/msquic.kernel.vcxproj
src/core/core.kernel.vcxproj
src/platform/platform.kernel.vcxproj
src/test/bin/winkernel/msquictest.kernel.vcxproj
src/test/lib/testlib.kernel.vcxproj

Another build flag required for Xbox it seems.

Add -d2epilogunwindrequirev2 Compiler Flag

---

src/platform/datapath_linux.c

Fix incorrect SAL annocation on linux QuicDataPathUninitialize

---

src/bin/winuser/dllmain.c
src/bin/winuser_fuzz/dllmain.c

Don't call DisableThreadLibraryCalls with static CRT

---

.azure/azure-pipelines-int.ci.yml
.azure/azure-pipelines.ci.yml
.azure/templates/build-config-dbgext.yml
.azure/templates/build-config-user.yml
.azure/templates/build-config-winkernel.yml
.azure/templates/run-bvt-int.yml
.azure/templates/run-bvt.yml
.azure/templates/run-quicinterop.yml
.azure/templates/run-spinquic.yml

Just a cosmetic change so that the jobs look nicer in the GitHub UI when viewing the jobs that are run.

Improve Azure Pipeline Job Names

---

src/tools/interop/interop.cpp

Updates the `quinn` and `applequic` interop servers

Update Interop Servers

---

src/core/connection.c
src/core/connection.h
src/core/crypto.c
src/core/crypto.h
src/core/quicdef.h
src/inc/quic_tls.h
src/inc/quic_trace_lttng.h
src/manifest/MsQuicEtw.man
src/platform/tls_mitls.c
src/platform/tls_openssl.c
src/platform/tls_schannel.c
src/platform/tls_stub.c
src/platform/unittest/TlsTest.cpp
src/tools/attack/packet_writer.cpp

No-op stubbed TLS implementations for now.

Resumption ticket generation/parsing logic

---

scripts/performance.ps1

Last comma was missing, making parsing harder

Fix data published to file

---

.dockerignore

Fixes regression in building the docker image.

Don't Exclude run_endpoint.sh in Docker

---

.azure/scripts/publish-performance-results.ps1
.azure/templates/publish-performance.yml
.azure/templates/run-performance.yml
scripts/performance.ps1

Easier to build a webpage for, and much easier to maintain in the long run.

Switch to using SQL database for performance results rather then files

---

.azure/templates/run-bvt-int.yml
.azure/templates/run-bvt.yml
.azure/templates/run-spinquic.yml
scripts/interop.ps1
scripts/spin.ps1
scripts/test.ps1
src/inc/msquic_linux.h
src/inc/msquic_winkernel.h
src/inc/msquic_winuser.h
src/platform/inline.c
src/test/MsQuicTests.h
src/test/bin/quic_gtest.cpp
src/test/bin/winkernel/control.cpp
src/test/lib/ApiTest.cpp
src/test/lib/BasicTest.cpp
src/test/lib/DataTest.cpp
src/test/lib/DatagramTest.cpp
src/test/lib/EventTest.cpp
src/test/lib/HandshakeTest.cpp
src/test/lib/TestConnection.cpp
src/test/lib/TestConnection.h
src/test/lib/TestHelpers.h

Refactoring the test code to improve the flow and reduce duplication where possible. More PRs likely to follow after this.

Test Refactoring and Improvements

---

.azure/scripts/publish-performance-results.ps1
.azure/templates/publish-performance.yml

New data isn't getting published, so need to print to figure out why.

Add debugging for perf publishing

---

src/perf/dbserver/Controllers/PerformanceController.cs

Was using a select rather then a where.

Fix CreatePlatform not working correctly in database

---

scripts/performance.ps1

Ports below 1000 are blocked for non root users on linux.
Closes #534

Use port 4433 for performance testing

---

scripts/performance.ps1

We seem to be getting some failures with the new perf machines. Need more info to debug.

Dump Results on Error

---

scripts/publish-performance-results.ps1

Fixes a break in the perf publish script when moving directories.

Fix Break in Perf Publish Script

---

scripts/performance.ps1

- Increases the length of the run so we're sure it's hitting peak perf.
- Specify a starting core for the client to be more consistent.

Performance Stability Improvements

---

src/tools/spin/spinquic.cpp

Updates SpinQuic to not randomize the ALPN if there is only a single session; and defaults the session count to 1 if there is an explicit ALPN passed in.

SpinQuic Explicit ALPN Improvements

---

scripts/performance.ps1

First step for #561.
This disabled APIPA interfaces for loopback perf tests because those periodically cause the system to take the "slow path". This fix makes things quite a bit more consistent.

Disable APIPA Interface for Loopback Test Perf

---

.azure/templates/publish-performance.yml

VS Code search missed this one.

Fix missed temp directory change

---

.azure/azure-pipelines.ci.yml
scripts/build.ps1

Switches the raspbian build to ninja, which will likely test this much better.

Update clog submodule to fix output overwriting

---

.azure/templates/run-performance.yml

Add DeploymentKeys group to run-performance.yml

---

src/inc/quic_platform_winuser.h
src/platform/datapath_winuser.c

Fixes a recent regression in setting the group affinity of a thread.

Fix Setting Group Affinity

---

.azure/azure-pipelines.ci.yml
.azure/templates/run-bvt.yml
scripts/install-build-artifacts.ps1
scripts/run-gtest.ps1
scripts/test.ps1
src/test/bin/quic_gtest.h

Onboard Windows kernel mode testing to Azure Pipelines CI.

Windows Kernel Mode Test Automation

---

src/core/binding.c
src/core/binding.h
src/core/library.c
src/core/library.h
src/inc/quic_crypt.h
src/platform/tls_schannel.c

Use QUIC_DISPATCH_LOCK for Stateless Retry Keys

---

.azure/templates/create-package.yml

I missed updating the packaging yaml when I refactored the build artifacts.

Fix Internal Packaging YML

---

src/core/connection.c

Separates out some the logic for generating the local TP structure into it's own function.

Minor Refactoring of Creating Local TP

---

.azure/templates/build-config-winkernel.yml
scripts/generate_kernel_clog.bat
src/manifest/create_kernel_clog_dependencies.bat

Bad files were being picked up, in addition clog wasn't being installed, and the kernel build is just ignoring this. I need to figure that out, but wanted the build fixed first

Fix clog in kernel mode

---

scripts/merge-coverage.ps1

Allows for easy viewing of code coverage reports locally.

Support Local Code Coverage Usage

---

.azure/azure-pipelines.ci.yml
.azure/azure-pipelines.coverage.yml

Refactors the CI pipeline to make a few things run only on master/feature branches. Also adds a new pipeline purely for code coverage if anyone needs to run that on a custom branch.

Refactor Azure Pipeline CI

---

scripts/install-powershell-docker.sh

Fixes (hopefully) the Docker pipeline.

Update Docker Script to Clog v0.1.2

---

.azure/azure-pipelines.ci.yml
.azure/templates/build-distribution.yml
scripts/package-distribution.ps1

Takes all artifacts and zips them into a zip with the correct headers and binaries.
Partial work on #611, still much more to go.

Add zip archive distribution for libraries

---

.azure/azure-pipelines.spin.yml
.azure/templates/run-spinquic.yml

A new pipeline just for running spinquic a configurable amount of time. Using it to test recent _wcpros ALE leak fix.

SpinQuic Pipeline

---

scripts/package-distribution.ps1

Name of clog library was incorrect

Fix distribution builds

---

.azure/templates/run-spinquic.yml
src/core/connection.c
src/core/inline.c
src/core/library.h
src/core/registration.c
src/core/registration.h
src/core/unittest/CMakeLists.txt
src/core/unittest/PartitionTest.cpp
src/inc/quic_platform_winuser.h
src/platform/platform_winuser.c
src/tools/spin/spinquic.cpp

- To hopefully exercise more code paths (valid and invalid).
- Found and fixed bug in processor group offset logic.

Some More SpinQuic

---

scripts/run-executable.ps1
src/core/connection.c
src/core/stream_set.c

More code coverage for async settings changed code paths.

Exercise Settings Code Paths

---

src/core/connection.c
src/manifest/clog.sidecar

`QuicTraceLogConnInfo_Skip` -> `QuicTraceLogConnInfo` to see how clog handles it.

Remove Skip Event

---

src/core/binding.c
src/core/connection.c
src/core/listener.c
src/core/packet.c
src/manifest/clog.sidecar
src/manifest/msquic.clog.cs
src/manifest/msquic.clog_config
src/platform/datapath_linux.c
src/platform/datapath_winkernel.c
src/platform/datapath_winuser.c

Cleans up the MsQuic specific CLOG types.

Refactor MsQuic CLOG Types

---

scripts/performance-helper.psm1
scripts/performance.ps1

Units were forced to kbps, default arguments were incorrect

Fix some minor perf script bugs

---

CMakeLists.txt
src/core/unittest/FrameTest.cpp
src/inc/quic_platform.h
src/inc/quic_platform_linux.h
src/perf/lib/CMakeLists.txt
src/platform/datapath_linux.c
src/tools/interopserver/InteropServer.cpp
src/tools/interopserver/InteropServer.h
src/tools/ping/PingConnection.cpp

Also fix a bug (== instead of =) found by not suppressing those warnings anymore.

With some fixes, we can remove "-Wno-unused-value"

---

src/core/connection.c
src/core/listener.c
src/core/lookup.c
src/core/sent_packet_metadata.c
src/platform/datapath_winkernel.c
src/platform/hashtable.c

Closes #704
Found 1 actual use after free bug, 2 potential things we probably should be debug asserting, and then a few uninitialized variables that very much seem like false positives.

Fix compilation with VS 16.7

---

src/perf/bin/CMakeLists.txt
src/perf/bin/appmain.cpp

Add inc and warnings to perf binary

---

.azure/azure-pipelines.ci.yml
.azure/templates/build-config-user.yml
scripts/build.ps1

Onboard clang into build scripts and CI

---

.azure/azure-pipelines.qns.yml
.azure/templates/run-qns.yml

PoC pipeline to run the interop runner ion Azure Pipelines. FYI @marten-seemann

QNS Runner Pipeline

---

.azure/azure-pipelines.ci.yml

Also remove master requirement for interop

Add Docker to Main Pipeline

---

scripts/install-powershell-docker.sh
scripts/prepare-machine.ps1
src/manifest/clog.sidecar

Fixes decoder build. Also removes untrimmed variable files.
There are still some issues even in the trimmed files.

Update to clog 0.1.7

---

scripts/performance.ps1

Upload separate PGO for localhost vs remote

---

.azure/templates/run-qns.yml

Also uses new `-l` option for log directory. cc @marten-seemann

Increase QNS Timeout to 25 min

---

.github/workflows/codeql-analysis.yml
src/core/frame.c
src/core/library.c

Fixes a few issues CodeQL found. (Thanks @larseggert for setting it up!)

Fix For Loop Type Comparison Issues

---

src/core/binding.c

Fix invalid ptr in QuicBindingInitialize OOM Scenario

---

src/core/connection.c

Fix QuicConnAlloc OOM freeing invalid pointer

---

src/core/binding.c

Fix Cleanup Bug in Binding

---

scripts/log.ps1
scripts/run-gtest.ps1

An attempt to help with the out of disk errors caused by logging left running

Clean up Logs on Failure

---

src/core/packet_builder.c
src/platform/datapath_linux.c

These aren't really helpful and they're quite verbose. Let's just remove them.

Remove a few unnecessary logs

---

src/core/datagram.c

Fix unaligned write in QuicDatagramSendComplete

---

scripts/install-powershell-docker.sh
scripts/prepare-machine.ps1
src/manifest/clog.sidecar

Fixes output of characters, and also properly updates sidecar

Update to CLOG 0.1.8

---

src/platform/tls_mitls.c

Use [Thread-Local Storage](https://docs.microsoft.com/en-us/windows/win32/procthread/thread-local-storage) to store the current connection pointer to be used by the global logging function so that we can get per-connection logging events:
```
[4]51E0.53D8::2020/09/07-16:07:01.041696600 [Microsoft-Quic][conn][0x1D3A989F380] Encoded 46 bytes for QUIC TP
[4]51E0.53D8::2020/09/07-16:07:01.041725200 [Microsoft-Quic][ tls][0x1D3A989F380] FFI| setting early data limit to ffffffff
[4]51E0.53D8::2020/09/07-16:07:01.041751300 [Microsoft-Quic][ tls][0x1D3A989F380] FFI| offering custom extension 0010
[4]51E0.53D8::2020/09/07-16:07:01.041753900 [Microsoft-Quic][ tls][0x1D3A989F380] FFI| extension contents: 000b0a4d735175696354657374
[4]51E0.53D8::2020/09/07-16:07:01.041756900 [Microsoft-Quic][ …
```

miTLS Thread-Local Storage Logging

---

src/core/binding.c

There are too many error cases to manually free, and we can't call uninitialize on a failed to initialize hashtable, so a bool check variable was needed.

Properly error if QuicHashtableInitialize fails in binding

---

src/core/cid.h
src/core/connection.c
src/core/connection.h
src/core/inline.c
src/core/library.c
src/core/library.h
src/core/lookup.c
src/core/lookup.h
src/core/quicdef.h
src/core/registration.c
src/core/unittest/PartitionTest.cpp
src/core/worker.c
src/core/worker.h
src/inc/msquic.h
src/inc/quic_datapath.h
src/inc/quic_platform_linux.h
src/inc/quic_platform_winkernel.h
src/inc/quic_platform_winuser.h
src/manifest/MsQuicEtw.man
src/manifest/clog.sidecar
src/tools/etwlib/MsQuicEventCollection.h
src/tools/spin/spinquic.cpp

This will allow us to support up to 65k processors, which should be good for the forseeable future.
Needs to be tested a lot, especially if we can access that 256 core system again.
Closes #809

Update Partition size to 16 bits.

---

.azure/azure-pipelines.qns.yml
.azure/templates/run-qns.yml

Using --replace is better than manually hacking the JSON file to update the image tag.

use --replace in QNS 

---

scripts/RemoteTests.json
scripts/performance-helper.psm1
src/core/api.c
src/core/connection.c
src/inc/msquic.h
src/inc/quic_platform_winuser.h
src/perf/dbserver/Controllers/HpsController.cs
src/perf/dbserver/Data/PerformanceContext.cs
src/perf/dbserver/Migrations/20200914154603_HPSData.Designer.cs
src/perf/dbserver/Migrations/20200914154603_HPSData.cs
src/perf/dbserver/Models/Db/DbHpsTestRecord.cs
src/perf/dbserver/Models/Db/DbMachine.cs
src/perf/dbserver/Models/Db/DbPlatform.cs
src/perf/dbserver/Models/Db/HpsTestResult.cs
src/perf/dbserver/Models/HpsRequest.cs
src/perf/dbserver/Models/HpsTestPublishResult.cs
src/perf/dbserver/Models/HpsTestPublishResultWithTime.cs
src/perf/dbserver/Models/RpsRequest.cs
src/perf/lib/CMakeLists.txt
src/perf/lib/HpsClient.cpp
src/perf/lib/HpsClient.h
src/perf/lib/PerfCommon.h
src/perf/lib/perflib.kernel.vcxproj
src/perf/lib/quicmain.cpp

Adds a new handshakes per second test with the goal of measuring the maximum handshakes that can be completed per second.

Handshakes Per Second Perf Test

---

src/core/path.c

These can sometimes happen in the same batch of receive packets, which caused an assert to be hit. Update to allow this case.
Closes #690

Handle path being removed by loss prevention as new path is being added.

---

src/core/api.c

Revert Recent Inline SetParam Change

---

src/tools/attack/attack.cpp

Create a UDP binding per attack thread.

Multi-Binding Attack

---

.github/workflows/codeql-analysis.yml

An attempt to fix the CodeQL breaks.

Fix CodeQL Break

---

src/core/frame.h
src/tools/etw/quicetw.h

https://github.com/quicwg/base-drafts/pull/4088
Closes #824

Fix AEAD Limit reached value conflict with TLS key update error value

---

.azure/templates/build-distribution.yml
.azure/templates/run-bvt.yml
.azure/templates/run-performance.yml
.azure/templates/run-quicinterop.yml
.azure/templates/run-spinquic.yml

Cleans the workspaces for all jobs run on our custom AZP pools.

Clean Workplace on Custom Pools

---

README.md

FYI @NorbertNemec. Closes #877.

Additional Readme Text in Protocol Features

---

README.md
docs/Deployment.md
docs/Diagnostics.md

This fixes most of @pravb's comments on the other PR. Diagnostics will be added in a separate PR.

More Deployment Documentation

---

src/tools/attack/attack.cpp
src/tools/attack/packet_writer.cpp
src/tools/attack/packet_writer.h

- Fix the cred config args.
- Pre-generate the CRYPTO frame once.

Some Attack Tool Fixes and Improvements

---

docs/Deployment.md

Some text on QUIC deployment considerations in general.

General QUIC Deployment Considerations

---

src/tools/sample/sample.cpp

Add Comments to Sample Code

---

docs/Diagnostics.md

Still very minimal. Lots still left to add.

Some Initial Diagnostics Documentation

---

scripts/run_endpoint.sh
src/tools/interopserver/InteropServer.cpp

Splits out part of the changes to try to get the interop runner's logging working better.

Add noexit Option for Interop Server

---

scripts/RemoteTests.json
scripts/performance-helper.psm1
src/perf/lib/ThroughputClient.cpp
src/perf/lib/ThroughputClient.h

Adds Download support to throughput perf client.

Download Perf Support

---

src/core/ack_tracker.c
src/core/connection.c
src/core/connection.h
src/core/send.c
src/inc/msquic.h
src/inc/msquic.hpp
src/test/MsQuicTests.h
src/test/bin/quic_gtest.cpp
src/test/bin/winkernel/control.cpp
src/test/lib/DataTest.cpp

Ensure sending stream data also includes outstanding ACKs.

---

scripts/RemoteTests.json

Decrease the number of iterations to increase the speed of the tests.

5 Iterations for All Perf Tests

---

src/inc/msquic_linux.h

Fixes #901. Thanks @cuijeff for finding!

Fix QuicAddrToString for Linux

---

src/core/binding.c
src/manifest/clog.sidecar
src/platform/tls_openssl.c

Improves OpenSSL encryption performance by preallocating the crypto objects. Fixes #530.

OpenSSL Crypto Thin Abstraction Layer

---

src/core/loss_detection.c
src/core/path.c
src/core/path.h

Fix Path Removal of Timed Out Paths

---

.azure/azure-pipelines.ci.yml
.azure/templates/run-qns.yml

Some fixes to get the interop pipeline (and on the main CI) working again.

Get Interop Running

---

src/core/packet_builder.c

For https://github.com/quicwg/base-drafts/pull/4188. Ensures server side fails if MTU is too small.

Pad Server Initial Packets

---

README.md

Fixes spelling of `Reliable` in README.md

Fixes spelling in README.md

---

src/tools/dbg/library.cpp
src/tools/dbg/quictypes.h

The debugger extension part of #935.

Add Retry Send State to Debugger Extension

---

src/manifest/MsQuic.wprp

Adds a profile to collect CPU and QUIC data path traces.

Improve Datapath ETW Profile

---

scripts/prepare-machine.ps1

Print out clog error messages at end of prepare-machine.ps1

---

src/tools/wpa/DataModel/ETW/QuicEtwEvent.cs
src/tools/wpa/DataModel/QuicConnection.cs
src/tools/wpa/Tables/QuicConnectionTable.cs
src/tools/wpa/Tables/QuicSchedulingTable.cs

- Couple minor fixes
- Various small improvements to existing tables
- Adds scheduling table

WPA Scheduling Table

---

src/tools/wpa/DataModel/ETW/QuicEtwEvent.cs
src/tools/wpa/DataModel/ETW/QuicEtwEventPayload.cs
src/tools/wpa/DataModel/QuicConnection.cs
src/tools/wpa/DataModel/QuicData.cs
src/tools/wpa/DataModel/QuicEvent.cs
src/tools/wpa/DataModel/QuicEventPayload.cs
src/tools/wpa/Tables/QuicExecutionTable.cs

Adds initial support for the execution table.

WPA Execution Table

---

src/tools/wpa/DataModel/ETW/QuicEtwEvent.cs
src/tools/wpa/DataModel/ETW/QuicEtwEventPayload.cs
src/tools/wpa/DataModel/QuicConnection.cs
src/tools/wpa/DataModel/QuicData.cs
src/tools/wpa/DataModel/QuicEventPayload.cs
src/tools/wpa/Tables/QuicRttTable.cs
src/tools/wpa/Tables/QuicThroughputTable.cs
src/tools/wpa/Tables/QuicTxWindowsTable.cs

Adds support for the TX/RX, TX Windows and RTT network tables.

WPA Network Tables

---

src/tools/wpa/DataModel/ETW/QuicEtwEvent.cs
src/tools/wpa/DataModel/ETW/QuicEtwEventPayload.cs
src/tools/wpa/DataModel/QuicConnection.cs
src/tools/wpa/DataModel/QuicData.cs
src/tools/wpa/DataModel/QuicEventPayload.cs
src/tools/wpa/DataModel/QuicState.cs
src/tools/wpa/Tables/QuicApiTable.cs
src/tools/wpa/Tables/QuicTxBlockedTable.cs

Finished up the WPA code.
- Adds API table
- Add TX flow blocked table

WPA Rest of the Tables

---

src/tools/wpa/DataModel/ETW/QuicEtwEvent.cs
src/tools/wpa/DataModel/ETW/QuicEtwEventPayload.cs
src/tools/wpa/DataModel/QuicConnection.cs
src/tools/wpa/DataModel/QuicData.cs
src/tools/wpa/DataModel/QuicDatapath.cs
src/tools/wpa/DataModel/QuicEvent.cs
src/tools/wpa/DataModel/QuicEventPayload.cs
src/tools/wpa/DataModel/QuicState.cs
src/tools/wpa/Tables/QuicDataBatchingTable.cs

- Adds parsing for datapath events.
- Adds table for throughput batching in "bytes per event".

WPA Datapath Throughput Batching Table

---

src/plugins/wpa/DataModel/QuicConnection.cs
src/plugins/wpa/DataModel/QuicState.cs
src/plugins/wpa/DataModel/QuicStream.cs
src/plugins/wpa/Tables/QuicStreamLifetime.cs

This table can be used to effectively calculate RPS.

WPA Stream Lifetime Table

---

README.md
docs/Support.md

The MsQuic `release/1.0` branch will be created by the end of the week!
At that point, new feature work will not be integrated into this release branch. We will continue to take any necessary bug fixes though. The 1.0 Release milestone (https://github.com/microsoft/msquic/milestone/2) tracks the work currently planned to be included.
All other work will continue to flow into the `main` branch.

Release 1.0 Forking Soon

---

.azure/azure-pipelines.ci.yml
.azure/azure-pipelines.plugins.yml

Split out the Plugins to Separate Pipeline

---

src/core/connection.c
src/core/connection.h
src/inc/quic_platform_dispatch.h
src/inc/quic_trace.h
src/platform/datapath_winuser.c
src/platform/platform_linux.c

Just removing a few unnecessary things (mostly comments).

Clean up a Couple TODOs

---

src/manifest/MsQuicEtw.man
src/manifest/clog.sidecar
src/platform/datapath_linux.c
src/platform/datapath_winkernel.c
src/platform/datapath_winuser.c
src/plugins/wpa/DataModel/QuicDatapath.cs
src/plugins/wpa/DataModel/QuicEvent.cs

Adds "created" and "destroyed" events for datapath binding objects.

Add Datapath Binding Lifetime Events

---

.azure/templates/run-spinquic.yml
src/core/connection.c

Fix SpicQuic verification failures during Code Coverage

---

.azure/templates/build-config-dbgext.yml
.azure/templates/build-config-wpa.yml
src/plugins/dbg/dbg.vcxproj
src/plugins/msquic.windbg.sln
src/plugins/msquic.wpa.sln
src/plugins/wpa/Properties/launchSettings.json
src/plugins/wpa/QuicEventDataSource.csproj

Just moves the VS solution files to the plugin folder.

Move Plugin Solutions

---

README.md
docs/FAQ.md
docs/Platforms.md
docs/Release.md

Cleans up the top level documentation to prepare it for release.

Reorganize Documentation

---

.azure/templates/run-performance.yml
scripts/RemoteTests.json
scripts/performance-helper.psm1

Also increase the thresholds for HPS and loopback

Mark perf failures as failing on Azure

---

src/plugins/msquic.wpa.sln
src/plugins/wpacmd/Program.cs
src/plugins/wpacmd/QuicEtw.csproj

This just adds a **very** trivial wrapper to the WPA plugin. Eventually, all quicetw native code will be migrated to this.

Initial Command Line Wrapper for WPA Plugin

---

.azure/azure-pipelines.ci.yml
.azure/templates/create-package.yml
src/inc/msquic.ver

Update mainline to version 1.1.0

Update to Version 1.1

---

scripts/interop.ps1
src/core/connection.c
src/core/datagram.c
src/core/datagram.h

Fix Datagram Receive setting not working in some instances.

---

.github/workflows/codeql-analysis.yml

Enable CodeQL on Release and Feature Branches (#1033)

---

docs/BUILD.md

State Build Requirements at the Top

---

src/core/library.h

Fix Windows Kernel Build

---

scripts/emulated-performance.ps1
src/perf/lib/ThroughputClient.cpp
src/perf/lib/ThroughputClient.h

- Adds pacing disable option
- Adds ability to upload/download based on time instead of length

QuicPerf Throughput Improvements

---

scripts/RemoteTests.json

OpenSSL has some nasty variations in it

Increase HPS threshold to 40%

---

.azure/azure-pipelines.wanperf.yml
.azure/templates/run-wanperf.yml
scripts/emulated-performance.ps1

Converts bottleneck buffer packets to a ratio of BDP instead.

WanPerf: BDP Ratio

---

src/core/ack_tracker.c
src/core/ack_tracker.h
src/core/connection.c

Don't Include Packet Processing Time in RTT (#1078)

---

.azure/azure-pipelines.ci.yml
.azure/azure-pipelines.wanperf.yml
.azure/templates/run-wanperf.yml

Onboard additional wanperf configurations.

Onboard More WanPerf

---

.github/CONTRIBUTING.md
README.md

v1.0 is forked. The year is almost done. Just about ready to remove restrictions on public contributions.

Remove Public Contribution Restrictions

---

src/platform/unittest/TlsTest.cpp

Adds a new test to run lots of TLS handshakes in parallel to make sure they aren't failing.

Stress Parallel TLS Handshakes

---

scripts/performance-helper.psm1
scripts/performance.ps1

This will be used from the perf scripts to get the date of when the commit happened

Insert current commit date into performance results.

---

scripts/performance-helper.psm1
scripts/performance.ps1

This will properly have data for branches

Get performance data from perf repo branch

---

.azure/azure-pipelines.ci.yml
.azure/azure-pipelines.qns.yml

Separates out the QNS pipeline stuff from the main CI. Also cleans up a few conditional statements in CI.

Refactor QNS Pipeline

---

.azure/azure-pipelines.ci.yml

Closed #1024. Schedules a weekly run (Mon morning, midnight UTC) for release branches to make sure they still build.

Weekly Release Build

---

.azure/azure-pipelines.periodic.yml
.azure/azure-pipelines.rps.yml
.azure/templates/run-performance.yml
scripts/FullRunRPS.json
scripts/performance-helper.psm1
scripts/performance.ps1

Pipeline is manual only currently, and test suite likely needs more, but adding more is easy once this is going.

Add full RPS matrix, and a pipeline to run it.

---

.azure/azure-pipelines.ci.yml
.azure/templates/build-config-user.yml
scripts/install-powershell.sh

Azure VM's updated, which broke powershell packages. Make install script take a parameter of which OS to use.

Fix Powershell not installing correctly

---

.azure/azure-pipelines.ci.yml
.azure/templates/build-config-user.yml
scripts/install-powershell.sh

Necessary to continue building. Cherry picked from main.

Fix Powershell not installing correctly (#1163)

---

THIRD-PARTY-NOTICES
scripts/package-distribution.ps1

Cherry-Picked from main. A license should be included in the binary distributions.

Add third party notices license, add that license to distribution (#1162)

---

assets/percommit/dataTemplate.js
assets/percommit/index.html
assets/percommit/style.css
assets/summary/dataTemplate.js
assets/summary/style.css
index.html

Adds the download throughput to the performance dashboard pages.

Download Throughput Perf Chart

---

.azure/azure-pipelines.ci.yml
CMakeLists.txt

latomic needs to be passed into openssl

Reenable Arm Linux OpenSSL build

---

.azure/azure-pipelines.periodic.yml
.azure/templates/post-process-periodic-performance.yml
.azure/templates/run-wanperf.yml
scripts/emulated-performance.ps1

This change adds "General Network" scenario WAN perf scenarios to the periodic performance pipeline.

Add WAN Perf to Periodic Perf Pipeline

---

src/platform/inline.c

Fix issues with inline c definitions.

---

src/core/crypto_tls.c

Fixes a recent regression in the logic for handling QUIC TP from older version.

Fix Regression in draft-29 TP Acceptance

---

docs/Diagnostics.md

Closes #1030 with some FAQ text.

FAQ for Linux Handle Limit Issue

---

.azure/azure-pipelines.periodic.yml
.azure/azure-pipelines.wanperf.yml
.azure/templates/run-wanperf.yml
scripts/emulated-performance.ps1
src/manifest/clog.sidecar
src/perf/lib/PerfServer.cpp
src/perf/lib/Tcp.cpp
src/perf/lib/Tcp.h
src/perf/lib/ThroughputClient.cpp
src/perf/lib/ThroughputClient.h

Added lots of logs to help debug TCP perf code. It seemed to be a synchronization bug on shutdown/clean up and seems to be fixed now.

Add Logs and Fix TCP Perf Code

---

scripts/emulated-performance.ps1

- Ignore invalid reorder scenarios (one zero and the other not).
- Fix duonic reorder property set bug

Fix Emulated Perf Reorder Bug

---

powershell/generate-graphs.ps1

Performance Branch Changes for RPS Latency

---

src/core/connection.c
src/manifest/MsQuicEtw.man
src/manifest/clog.sidecar

A few tweaks to get "ut:LowVolume @ level 4" to be nice and clean.

Tweak Low Volume Events

---

.azure/azure-pipelines-int.ci.yml
.azure/azure-pipelines.ci.yml
CMakeLists.txt
scripts/build.ps1
src/bin/winkernel/msquic.kernel.vcxproj
src/bin/winkernel/msquicpriv.kernel.vcxproj
src/core/core.kernel.vcxproj
src/inc/quic_platform_linux.h
src/inc/quic_platform_winkernel.h
src/inc/quic_platform_winuser.h
src/platform/platform_winkernel.c
src/platform/tls_stub.c

Adds, off by default, support for telemetry asserts to trigger a trace event.

Telemetry Assert Events

---

scripts/package-distribution.ps1
src/inc/msquic_posix.h

The header file name changed. Also updates the include guard.

Fix distribution of linux binaries

---

src/core/stream_recv.c
src/manifest/clog.sidecar

Found this log during an RPS test. It's not worth being an error message.

Stream Trace to Verbose

---

src/platform/platform_posix.c

Depending on the debugger, since no local variable was created, the result of the pthread call is clobbered by the time we get the bugcheck. Use a separate variable so the compiler actually assigns to a debuggable variable.
Will help with debugging #1268 as currently the actual failure reason is clobbered.

Move pthread asserts away from being inline

---

.azure/azure-pipelines.periodic.yml
scripts/FullRunRPS.json

- Adds a few more connection counts for RPS.
- Adds "no reordering" cases to wan perf.

More Periodic Perf Data

---

src/platform/datapath_epoll.c
src/platform/platform_posix.c

By using sendmmsg, we can send multiple buffers at once. GSO can be added later to improve this even more.

Implement UDP send buffering support in Linux

---

src/core/congestion_control.c
src/inc/quic_platform_posix.h
src/platform/inline.c

Fix a Few Casting Errors

---

docs/TLS.md

Adds a high level overview of the interface between TLS and QUIC.

Add TLS Overview

---

src/platform/datapath_epoll.c
src/platform/datapath_kqueue.c

Currently, the queue the send gets pended on is random. Ensure its added to the correct queue.
Closes #1290

Ensure pended sends get added to correct queue

---

src/inc/quic_driver_helpers.h
src/inc/quic_platform_winuser.h
src/inc/quic_storage.h
src/platform/CMakeLists.txt
src/platform/datapath_winuser.c
src/platform/platform_winuser.c
src/platform/selfsign_capi.c
src/platform/storage_winkernel.c
src/platform/storage_winuser.c
src/platform/tls_mitls.c
src/platform/tls_openssl.c
src/platform/tls_schannel.c
src/platform/tls_stub.c
src/tools/interopserver/InteropServer.cpp

Fixes some SAL mismatches, and a few code bugs.
Closes #1242

Enable SAL for platform component on Windows User Mode

---

.azure/templates/build-config-user.yml

Forgot to do this in the previous PR.

Rev Build Cache

---

src/core/stream.h
src/inc/quic_crypt.h
src/inc/quic_platform_winuser.h
src/perf/bin/drvmain.cpp
src/platform/datapath_epoll.c
src/platform/datapath_kqueue.c
src/platform/datapath_winkernel.c
src/platform/datapath_winuser.c
src/platform/tls_schannel.c
src/test/bin/winkernel/control.cpp
src/test/lib/KArray.h
src/tools/sample/sample.cpp

Fixes for clang-cl

---

scripts/performance-helper.psm1

Currently theyre sorted by strings.

Force medians to be sorted by number

---

.azure/azure-pipelines.qns.yml
.azure/templates/create-package.yml
src/core/quicdef.h
src/inc/msquic.ver
src/perf/lib/PerfServer.h
src/platform/datapath_winkernel.c
src/platform/datapath_winuser.c

* Disable send batching on perf server
* Reduce batch sizes
Cherry-Picked from f4cca46

Reduce batching counts for sends (#1321)

---

.azure/templates/build-config-user.yml
.azure/templates/run-bvt.yml
src/core/configuration.c
src/core/settings.c
src/inc/msquic.hpp
src/inc/quic_tls.h
src/perf/lib/PerfServer.h
src/perf/lib/Tcp.cpp
src/platform/tls_mitls.c
src/platform/tls_openssl.c
src/platform/tls_schannel.c
src/platform/tls_stub.c
src/platform/unittest/TlsTest.cpp
src/tools/attack/packet_writer.cpp

Correctly disable resumption when the app configured QUIC_SERVER_NO_RESUME

Disable Resumption When Not Used

---

.azure/azure-pipelines.ci.yml
.azure/templates/download-artifacts.yml
.azure/templates/run-bvt.yml
CMakeLists.txt
scripts/build.ps1
scripts/test.ps1

Try to see if we can statically link openssl, but dynamically link libcrypto.

Use system libcrypto

---

scripts/update-version.ps1

Fix version update script to update QNS file as well (#1332)

---

docs/BUILD.md

add notes for macOS build

---

scripts/prepare-machine.ps1

Credscan was complaining. This should fix it.

Change Test Cert Password to placeholder

---

scripts/emulated-performance.ps1

A try to fix the current WAN perf failures we're seeing.

Make WAN Perf Previous Results Failure Resilient

---

.azure/azure-pipelines.ci.yml
.azure/templates/run-bvt.yml
.azure/templates/run-quicinterop.yml
.azure/templates/run-spinquic.yml
.azure/templates/upload-artifacts.yml
.azure/templates/upload-test-artifacts.yml
scripts/performance-helper.psm1
scripts/performance.ps1
scripts/run-executable.ps1
scripts/run-gtest.ps1
scripts/spin.ps1
scripts/test.ps1

Updates the actual BVT task to fail (and not just the publish test results task) to make it clearer about what is going on.

Update BVT Task to Fail

---

src/platform/unittest/TlsTest.cpp

Reset TLS Unit Test Flags

---

scripts/performance-helper.psm1
src/perf/bin/appmain.cpp
src/perf/bin/drvmain.cpp
src/perf/bin/secnetperfdriver.kernel.vcxproj
src/perf/lib/SecNetPerfMain.cpp

This way loopback tests can be supported. Done by allowing user to supply driver name

Support multiple instances of secnetperf in kernel mode

---

scripts/Invoke-EtwTraceCollection.ps1

Currently doesn't actually invoke the trace, but has support for sanitizing IP Addresses

Add script to invoke ETW trace

---

scripts/Invoke-EtwTraceCollection.ps1

Adds etw flushing and conversion support.

Improve Invoke-EtwTraceCollection.ps1

---

docs/Release.md

Improve the documentation on how releases work. Also adds info for v1.2.

Improve Release Documentation

---

scripts/run_endpoint.sh

Updates the QNS interop runner script to enable 0-RTT and resumption test cases.

Update Interop for 0-RTT

---

.azure/azure-pipelines.ci.yml
scripts/build.ps1

CMake 3.20 seems to have gotten a lot more strict on the generator arguments. Properly use quotes, and also use -G not -g for generator

Fix Cmake generator arguments

---

src/core/unittest/VersionNegExtTest.cpp
src/core/version_neg.c
src/core/version_neg.h

Make Connection Required Arg for QuicVersionNegotiation Functions

---

scripts/Invoke-EtwTraceCollection.ps1

Example usage:
```PowerShell
.\scripts\Invoke-EtwTraceCollection.ps1 -Start -NetshScenario InternetServer_dbg -SessionName my_session
```
```PowerShell
.\scripts\Invoke-EtwTraceCollection.ps1 -Stop -SessionName my_session -Convert
```

Adds Start/Stop and Updates Flush for EtwTraceCollection

---

README.md
docs/Diagnostics.md
docs/TSG.md

Adds the initial trouble shooting guide documentation. It outlines a few known problems that people frequently encounter. Next steps will be to start filling this in.

Initial Trouble Shooting Guide

---

docs/TSG.md

Adds more information related to connection shutdown debugging.

Add Connection Shutdown to TSG

---

src/plugins/wpa/DataModel/QuicData.cs
src/plugins/wpa/DataModel/QuicWorker.cs
src/plugins/wpa/Tables/QuicDataBatchingTable.cs
src/plugins/wpa/Tables/QuicWorkerActivityTable.cs

Adds a CPU column to the worker and datapath batching tables.

Add CPU Columns to WPA Plugin

---

src/platform/datapath_winuser.c

In a high throughput scenario, if the send is alternating between the datapath and quic worker thread, the amount of packet reording can be massive. It can even be high enough to cause the connection to be killed. To make this work correctly, we need to have a flag for if any sends on the socket are queued, we need to queue until empty. However, this likely will be a larger change, and increase contention, so revert for now to remove the functional breakage.

If queued sends are enabled, ALWAYS send on datapath

---

src/plugins/wpa/Tables/QuicDataBatchingTable.cs

Now have two network tables at the datapath / binding layer (i.e. shared on server side across all connections):
- Data rates (bits per second)
- Batching sizes (bytes per second)

Clean up UDP Network Tables

---

docs/TSG.md
src/plugins/wpa/Tables/QuicDataBatchingTable.cs
src/plugins/wpa/Tables/QuicWorkerActivityTable.cs

Just a few minor things to finish up the "follow up" points.

More WPA Clean up

---

src/plugins/trace/exe/Program.cs

Refactors the quictrace tool to support different commands. The initial focus will be on the `--report` command next.

QuicTrace Refactor

---

.azure/azure-pipelines.perf.yml
.azure/templates/run-performance.yml
scripts/log.ps1
scripts/performance-helper.psm1
scripts/performance.ps1

Use the existing log scripts to perform logging, allow perf pipeline to log any supported log profile.

Enhance performance logging capabilities

---

.azure/azure-pipelines-int.ci.yml
.azure/azure-pipelines.ci.yml
src/inc/msquic.hpp
src/perf/lib/PerfServer.cpp
src/perf/lib/PerfServer.h
src/platform/unittest/CryptTest.cpp
src/test/lib/ApiTest.cpp
src/test/lib/DataTest.cpp
src/test/lib/EventTest.cpp

General clean up and improvements.

Various Test and MsQuic.hpp Improvements

---

src/core/stream_recv.c
src/inc/msquic.hpp
src/test/MsQuicTests.h
src/test/bin/quic_gtest.cpp
src/test/bin/winkernel/control.cpp
src/test/lib/DataTest.cpp

Fixes #1515. Validated with new tests and a test app (quicspeed).

Deliver Shutdown Complete on Recv of Reset

---

src/core/stream_recv.c

Backports https://github.com/microsoft/msquic/pull/1513 and https://github.com/microsoft/msquic/pull/1516 product code fixes (test code has too many dependencies) to `release/1.1`.

Backport Stream Receive Abort Fixes to 1.1

---

src/core/api.c
src/core/stream_recv.c

Execute StreamShutdown Inline on Callbacks

---

docs/Release.md

Compare link: https://github.com/microsoft/msquic/compare/prerelease/1.2...main

Release Notes for upcoming prerelease/1.3

---

scripts/performance-helper.psm1
scripts/performance.ps1

Definitely gets some interesting results if we get some massive jumps, but should make failures less of an issue if we're riding the edges of the performance ranges.

Average the last 5 results of runs for performance comparison

---

.azure/templates/run-bvt.yml
scripts/run-gtest.ps1
scripts/test.ps1

- Default to `Isolated` isolation mode
- Remove unused `ExecutionMode` knob

Simplify Test Scripts

---

src/core/crypto.c

Fixes https://github.com/microsoft/msquic/issues/1544.

Fix crypto buffer drain when switching to 1-RTT keys.

---

src/core/loss_detection.c
src/core/packet_builder.c

Fix Handshake Stall Bug (#1547)

---

src/core/connection.c

Only check stateless reset CID against non-retired CIDs

---

.azure/templates/run-spinquic.yml
scripts/run-executable.ps1
scripts/spin.ps1
src/core/cid.h
src/core/connection.c
src/core/crypto.c
src/core/library.c
src/core/loss_detection.c
src/core/loss_detection.h
src/core/packet_builder.c
src/core/send.c
src/core/stream.c
src/core/stream_set.c
src/core/stream_set.h
src/platform/datapath_winuser.c
src/platform/platform_winuser.c
src/platform/tls_openssl.c
src/plugins/dbg/quictypes.h
src/plugins/dbg/worker.cpp
src/tools/spin/spinquic.cpp

Found and fixes https://github.com/microsoft/msquic/issues/1544.

Fix more SpinQuic random allocation failure bugs

---

.azure/azure-pipelines.ci.yml

Reenable Tests with OpenSSL

---

src/core/loss_detection.c
src/core/sent_packet_metadata.h

Fix Bug in Allocation Failure Path of OnPacketSent

---

src/core/library.c
src/core/send.c
src/inc/msquic.hpp
src/platform/platform_posix.c
src/platform/platform_winkernel.c
src/platform/platform_winuser.c
src/test/MsQuicTests.h
src/test/bin/quic_gtest.cpp
src/test/bin/winkernel/control.cpp
src/test/lib/DataTest.cpp

This test will fail every Nth allocation for N from 100 down to 2.

Add test to fail every Nth allocation.

---

src/inc/msquichelper.h
src/tools/reach/reach.cpp

```
> quicreach.exe -server:google.com -version:4278190109
google.com:443:
hq-29  unreachable
h3  unreachable
smb  unreachable
hq-interop  unreachable
0xff00001d        h3-29    reachable
```

quicreach Version Support

---

.azure/azure-pipelines-int.ci.yml
.azure/azure-pipelines.ci.yml
.azure/azure-pipelines.qns.yml
.azure/templates/create-package.yml
scripts/test.ps1
src/inc/msquic.ver
src/test/bin/quic_gtest.cpp
src/test/lib/DatagramTest.cpp

Port Release Testing to 1.1

---

src/core/congestion_control.c

Currently in CA, 1 MTU is added to CongestionWindow, which assumes the
increase function is that of NewReno. Instead use 1.25*CongestionWindow,
which expands the region in which pacing will not dampen window growth.

Tweak EstimatedWnd calc in QuicCongestionControlGetSendAllowance

---

docs/Diagnostics.md
docs/TSG.md

Adds a trouble shooting guide section for diagnosing why a particular API is failing. This recently came up with a .NET issue so I figured it'd be a prime candidate for documentation.

TSG: Why is this API Failing?

---

docs/TEST.md

Adds more test documentation since it was woefully out of date.

More TEST.md

---

docs/Deployment.md
docs/Settings.md
docs/api/QUIC_SETTINGS.md

Refactor settings to be a separate document from deployment.

---

src/inc/quic_platform_winuser.h

One more build fix for the VS v16.10 breaks.

One More arm64 WinUser Build Fix

---

docs/api/StreamOpen.md

Change `desired the directionality` to `the desired directionality`.

Fix grammar

---

src/inc/msquic.hpp
src/inc/quic_platform.h
src/inc/quic_platform_winkernel.h
src/inc/quic_platform_winuser.h
src/perf/bin/drvmain.cpp
src/perf/lib/PerfServer.cpp
src/perf/lib/Tcp.cpp
src/perf/lib/ThroughputClient.cpp
src/test/bin/quic_gtest.cpp
src/test/bin/winkernel/control.cpp
src/test/bin/winkernel/driver.cpp

https://github.com/microsoft/msquic/commit/90064abe45ba71664460bb3960784c7959c31edc
https://github.com/microsoft/msquic/commit/0b6bef8b51580df7d277dc818dd6ba88cf2d47f4
https://github.com/microsoft/msquic/commit/105c3090ab11986d47d354ac1d61eaab15851659

Cherry pick VS 16.10 build updates to 1.1

---

src/inc/msquic.hpp
src/inc/quic_platform.h
src/inc/quic_platform_winkernel.h
src/inc/quic_platform_winuser.h
src/perf/bin/drvmain.cpp
src/test/bin/quic_gtest.cpp
src/test/bin/winkernel/control.cpp
src/test/bin/winkernel/driver.cpp

https://github.com/microsoft/msquic/commit/90064abe45ba71664460bb3960784c7959c31edc
https://github.com/microsoft/msquic/commit/0b6bef8b51580df7d277dc818dd6ba88cf2d47f4
https://github.com/microsoft/msquic/commit/105c3090ab11986d47d354ac1d61eaab15851659

Cherry pick VS 16.10 build updates to 1.0

---

src/core/library.c

Correctly Write Out Version

---

src/test/lib/HandshakeTest.cpp

Set has random loss flag for key update test

---

docs/TSG.md
src/core/api.c
src/core/api.h
src/core/registration.c
src/core/registration.h
src/inc/msquic.h

A write up to explain how to fix issues like https://github.com/microsoft/msquic/issues/1668. cc @wfurt

TSG: Debugging API Deadlocks

---

docs/Release.md

Not planning on CP'ing https://github.com/microsoft/msquic/pull/1653 back to previous releases.

Document Known Issue for Previous Releases

---

.azure/azure-pipelines.qns.yml
.azure/templates/create-package.yml
src/inc/msquic.ver

Now that prerelease/1.4 has been created, update the minor version.

Update main to v1.5

---

src/test/lib/TestConnection.cpp

Increase Try Count for Test Force Functions

---

src/platform/datapath_epoll.c
src/platform/datapath_kqueue.c
src/platform/datapath_winkernel.c
src/platform/datapath_winuser.c

Attempts to fix an assert we just saw in CI.

More DAL Assert Fixes

---

docs/api/ConnectionStart.md

Fix ConnectionOpen link

---

src/inc/msquic.hpp

Change quotes in msquic.hpp

---

scripts/performance.ps1

Finally was killing the wrong driver name, which is a problem

Fix kernel perf finally script

---

src/core/binding.c
src/core/binding.h
src/core/connection.c
src/core/library.c
src/core/library.h
src/core/send.c

Make stateless reset token generation per-processor.

---

src/inc/msquic.hpp
src/test/lib/HandshakeTest.cpp

Update LB Test to Handle Addr In Use Failures

---

.azure/azure-pipelines.ci.yml
src/platform/datapath_epoll.c
src/platform/datapath_kqueue.c
src/platform/datapath_winuser.c

Fix socket cleanup on allocation failure in kqueue and epoll datapaths

---

.azure/azure-pipelines-int.ci.yml
.azure/azure-pipelines.ci.yml
.azure/templates/run-bvt.yml
scripts/prepare-machine.ps1
scripts/run-gtest.ps1

Cherry picks 5f9b5482f0f 78a8ddbc8f3 and enables flags from cc104e8

Test sign kernel binaries

---

.azure/azure-pipelines-int.ci.yml
.azure/azure-pipelines.ci.yml
.azure/templates/run-bvt.yml
scripts/prepare-machine.ps1
scripts/run-gtest.ps1

Cherry picks 5f9b548 78a8ddb and enables flags from cc104e8

Test sign kernel binaries on Release/1.0

---

src/tools/spin/spinquic.cpp

Pulled out of #1748 to get it solid first.

More SpinQuic Parallelization

---

src/core/library.c
src/core/library.h
src/manifest/MsQuicEtw.man
src/manifest/clog.sidecar
src/plugins/trace/dll/DataModel/ETW/QuicEtwEvent.cs
src/plugins/trace/dll/DataModel/QuicEvent.cs
src/plugins/trace/dll/DataModel/QuicEvents.cs

Makes it easy to know the version when debugging both logs and dumps.

Add Version for Log and Dump Debugging

---

README.md

Update Sample Link

---

src/platform/cert_capi.c

Fix mismatched definitions of CxPlatCertSelect

---

src/tools/sample/sample.c

Remove Desired Version From Sample

---

src/platform/cert_capi.c

PCERT_CONTEXT to QUIC_CERTIFICATE

---

docs/api/StreamSend.md

Fix Broken Link in StreamSend.md

---

src/bin/winkernel/msquic.kernel.vcxproj
src/bin/winkernel/msquicpriv.kernel.vcxproj
src/core/core.kernel.vcxproj
src/inc/quic_platform.h
src/manifest/manifest.kernel.vcxproj
src/perf/bin/quicperfdriver.kernel.vcxproj
src/perf/bin/quicperfdriverpriv.kernel.vcxproj
src/perf/lib/perflib.kernel.vcxproj
src/platform/platform.kernel.vcxproj
src/test/bin/winkernel/msquictest.kernel.vcxproj
src/test/bin/winkernel/msquictestpriv.kernel.vcxproj
src/test/lib/testlib.kernel.vcxproj

* Correctly fix VS 16.10 UCRT issue
* Fix end of line
Cherry-Picked from #1813

Correctly fix VS 16.10 UCRT issue (#1813) (Cobalt)

---

src/bin/winkernel/msquic.kernel.vcxproj
src/bin/winkernel/msquicpriv.kernel.vcxproj
src/core/core.kernel.vcxproj
src/inc/quic_platform.h
src/manifest/manifest.kernel.vcxproj
src/perf/bin/performance.kernel.vcxproj
src/perf/lib/perflib.kernel.vcxproj
src/platform/platform.kernel.vcxproj
src/test/bin/winkernel/msquictest.kernel.vcxproj
src/test/bin/winkernel/msquictestpriv.kernel.vcxproj
src/test/lib/testlib.kernel.vcxproj

* Correctly fix VS 16.10 UCRT issue
* Fix end of line
Cherry-Picked from #1813

Correctly fix VS 16.10 UCRT issue (#1813) (Iron)

---

.azure/azure-pipelines.ci.yml
scripts/test.ps1
src/test/bin/quic_gtest.cpp
src/test/lib/DatagramTest.cpp

We want to be able to run release mode tests in downlevel builds. This should fix this to make that possible.

Get release tests running successfully in Iron

---

docs/Settings.md
docs/api/QUIC_SETTINGS.md

Add MTU documentation to settings documentation

---

docs/Release.md

Notes for the next prerelease.

v1.5 Release Notes

---

src/core/api.c
src/core/connection.c
src/core/connection.h
src/core/crypto.c
src/core/inline.c
src/core/loss_detection.c
src/core/packet_builder.c
src/core/send.c
src/core/stream.c

Adds a helper for checking if a connection is a client. I personally disliked reading !IsServer.

Add QuicConnIsClient Helper

---

CMakeLists.txt
src/core/settings.c
src/platform/datapath_kqueue.c
src/platform/pcp.c
src/platform/platform_posix.c
src/platform/tls_openssl.c

found by clang-tidy v12 and recent cppcheck.

Suppress or fix various issues 

---

.azure/azure-pipelines.qns.yml
.azure/templates/create-package.yml
src/inc/msquic.ver

Just forked prerelease/1.6, updating main to 1.7.

Update to v1.7

---

.azure/OneBranch.Official.yml

Triggers must be set for which branches we want to run

Configure OneBranch triggers

---

.github/workflows/codeql-analysis.yml
CMakeLists.txt
submodules/CMakeLists.txt

Currently has a regression where CMake will double build OpenSSL. Working on debugging this.

Consolidate OpenSSL build into a single CMakeLists file

---

.github/workflows/codeql-analysis.yml
CMakeLists.txt
submodules/CMakeLists.txt

https://github.com/microsoft/msquic/pull/1885
https://github.com/microsoft/msquic/pull/1891
The QNS pipeline does not like this configuration. I'll try to manually get a older cmake system and try again.

Revert OpenSSL changes 

---

docs/Diagnostics.md

Display how to use a newer manifest file then the one currently installed on the system, and how to set up the system for logging on linux by running prepare-machine

Improve logging docs

---

src/core/library.c

Broken in https://github.com/microsoft/msquic/pull/1782

Fix library version only being set on library unload

---

src/tools/ip/quicip.h
src/tools/ip/server/quicipserver.cpp

Fix quicip not waiting for connection shutdown before deleting context

---

.gitmodules

See https://github.com/quictls/openssl/pull/45.

Update OpenSSL to OpenSSL_1_1_1l+quic Branch

---

src/test/lib/DataTest.cpp

Increase Handshake Timeouts in Tests

---

src/test/lib/DatagramTest.cpp

Poll with Retry in Datagram Test

---

src/platform/cgroup.c

On some platforms, cgroups don't exist at all, which cause a debug assertion. Remove all debug asserts in the cgroup code, as theyre not actually helpful, and the code handles the asserts missing correctly

Fix cgroups debug asserting on certain platforms

---

src/core/connection.c
src/core/crypto.c
src/generated/linux/connection.c.clog.h
src/generated/linux/connection.c.clog.h.lttng.h
src/generated/linux/crypto.c.clog.h
src/generated/linux/crypto.c.clog.h.lttng.h
src/manifest/clog.sidecar
src/test/MsQuicTests.h
src/test/bin/quic_gtest.cpp
src/test/bin/quic_gtest.h
src/test/bin/winkernel/control.cpp
src/test/lib/HandshakeTest.cpp

Cherry-pick #1951 to release/1.0 (Fe).

CP #1951 to v1.0 (Fe)

---

src/core/connection.c
src/core/crypto.c
src/generated/linux/connection.c.clog.h
src/generated/linux/connection.c.clog.h.lttng.h
src/generated/linux/crypto.c.clog.h
src/generated/linux/crypto.c.clog.h.lttng.h
src/manifest/clog.sidecar
src/test/MsQuicTests.h
src/test/bin/quic_gtest.cpp
src/test/bin/quic_gtest.h
src/test/bin/winkernel/control.cpp
src/test/lib/HandshakeTest.cpp

Cherry-pick #1951 to release/1.1 (Co).

CP #1951 to v1.1 (Co)

---

src/core/connection.c
src/core/send.c
src/core/send.h

CP of #1850 (It can't be automatically CP'd because of large code changes).

Cancel all sends upon silent abort (Fe)

---

src/core/connection.c
src/core/send.c
src/core/send.h

Cancel all sends upon silent abort

---

.azure/templates/create-package.yml
scripts/package-distribution.ps1
src/inc/msquic.ver

Also fixes distribution pipeline stage while I'm at it.

Increment Patch Version (Fe)

---

.azure/azure-pipelines.qns.yml
.azure/templates/create-package.yml
scripts/package-distribution.ps1
src/inc/msquic.ver

Also fixes distribution pipeline stage while I'm at it.

Increment Patch Version (Co)

---

src/inc/msquic.ver

A few improvements after I happened to look at a recent Windows built driver.

Windows File Attribute Fixes

---

CMakeLists.txt
src/bin/CMakeLists.txt
src/core/unittest/CMakeLists.txt
src/inc/CMakeLists.txt
src/perf/bin/CMakeLists.txt
src/platform/unittest/CMakeLists.txt
src/test/bin/CMakeLists.txt
src/tools/CMakeLists.txt

Fix cmake static builds on ninja

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Per sync meeting held on 23rd September 2021, this pull request aims to expand and improve upon the overall quality of the existing issue templates.

Rework issue templates

---

.azure/OneBranch.Official.yml

A change was missed in the last PR that caused the official branch to not work.

Fix onebranch official pipeline

---

src/platform/datapath_raw.c

In the case of unconnected sockets, maybe we can also skip the lookup
for consecutive packets with just the same 2-tuple, but this is a start.

Skip socket lookup for consecutive packets with the same 4-tuple

---

src/platform/datapath_raw_xdp.c

Push/pop lists instead of single elements where possible in the XDP datapath.

maximize slist batching in XDP

---

src/perf/bin/appmain.cpp

Fix incorrect requests size in QuicHandleRpsClient

---

docs/API.md

Fix event name

---

src/platform/datapath_raw.c

Chain packets destined to the same socket instead of looking up
the socket for each packet.

Chain subsequent 4-tuple matches in CxPlatDpRawRxEthernet

---

src/platform/datapath_raw.c
src/platform/datapath_raw.h
src/platform/datapath_raw_socket.c

Updates the listener to properly handle wildcards. Consolidates the socket address comparison logic. Has been tested.

Improve Socket Lookup

---

src/core/library.c
src/core/timer_wheel.c
src/core/timer_wheel.h
src/core/worker.c
src/core/worker.h
src/generated/linux/worker.c.clog.h
src/generated/linux/worker.c.clog.h.lttng.h
src/inc/quic_platform.h
src/manifest/clog.sidecar

Taken from #2118, but updated to only do the refactoring (not the extra bits to actually share execution with the datapath).

Refactor Worker Exectution in to Generic Design

---

src/core/worker.c

Fixes #2133.
cc @maolson-msft this is the cause of the failures you saw recently.
cc @mtfriesen this is a regression from the EC work because of time caching

Account for Negative Queue Delay

---

src/bin/CMakeLists.txt
src/core/CMakeLists.txt
src/inc/CMakeLists.txt
src/platform/CMakeLists.txt

Fix static binary linking to runtime libs

---

src/generated/linux/datapath_raw.c.clog.h
src/generated/linux/datapath_raw.c.clog.h.lttng.h
src/generated/linux/datapath_raw_socket.c.clog.h
src/generated/linux/datapath_raw_socket.c.clog.h.lttng.h
src/platform/datapath_raw.c
src/platform/datapath_raw.h
src/platform/datapath_raw_dpdk.c
src/platform/datapath_raw_socket.c
src/platform/datapath_raw_xdp.c

For each CXPLAT_SOCKET, bind an auxiliary Winsock socket to acquire and reserve a port from tcpip.sys.

Bind aux socket to get a port

---

submodules/CMakeLists.txt

Needed by #2103 but better as a separate PR into main

Fix openssl 3 cmake build issues

---

src/core/connection.c
src/core/path.c

Update the core code to copy the full route object into the path, and not just the IP addresses.

Copy Full Route into Path

---

docs/api/StreamSend.md

Fix StreamSend Docs

---

scripts/install-test-certificates.ps1

Signed-off-by: Anthony Rossi <anrossi@microsoft.com>

Add SAN to leaf cert used in PFX tests.

---

src/inc/msquic_winkernel.h
src/inc/msquic_winuser.h

Fix QuicAddrFromString setting port incorrectly

---

scripts/build.ps1

If you don't pass an explicit generator to cmake, it will automatically find the newest version of cmake. This is cleaner then the old method, and much more futureproof.
Additionally, now use cmake's cache variables to find the correct runtime, rather than vswhere. This will ensure the runtime files always match the compiler used

Use CMake to find VS version

---

CMakeLists.txt
scripts/build.ps1

Were modifying the files in powershell, but I'd prefer not to do that.

Use CMAKE variable for setting extra PGO library directory

---

src/generated/linux/datapath_raw_socket.c.clog.h
src/generated/linux/datapath_raw_xdp.c.clog.h
src/generated/linux/datapath_raw_xdp.c.clog.h.lttng.h
src/inc/quic_datapath.h
src/platform/CMakeLists.txt
src/platform/datapath_raw.c
src/platform/datapath_raw.h
src/platform/datapath_raw_dpdk.c
src/platform/datapath_raw_socket.c
src/platform/datapath_raw_xdp.c

Updates the XDP code to query the RSS queue count and match it, so that we don't miss received packets when multiple RSS queues are configured.

Support Multiple RSS Queues

---

src/platform/datapath_raw_xdp.c

Updates XDP to default to affinitize to the last CPU available, if not explicitly specified, so that now you aren't required to have any  `xdp.ini` file and it will "just work". Also made the cleanup printfs debug mode only.

No INI File Required for XDP

---

scripts/package-distribution.ps1

3rd try is the charm? Yes it is, I locally tested this.

Finally use correct variable to skip extra folder

---

src/platform/datapath_raw.c
src/platform/datapath_raw.h
src/platform/datapath_raw_dpdk.c
src/platform/datapath_raw_xdp.c

Dynamically generate rules based on socket creation/deletion (XDP only).

Add Dynamic Rule Generation to XDP

---

.gitmodules

Update to OpenSSL_1_1_1m+quic

---

src/core/connection.c

Fix peer updating cid when using an empty cid killing a path

---

docs/Diagnostics.md
src/plugins/trace/dll/QuicTraceLib.csproj

Also removes unnecessary copying in quictrace project file.

Diagnostics Docs Improvements

---

src/core/api.c

Closes #2221 
Currently, if an app calls Connection/StreamClose, and this results in a ShutdownComplete, and in that ShutdownComplete the user calls close again, the object is double freed. This is 100% an app bug, and we have an `AppCloseInProgress` flag the app can check to ensure they don't do this. However, as the handle is still alive, its valid for us to detect this case, and actually respond to it. Many apps that are written (Including many of ours) have this bug when they are first written (usually in error cases) where its not caught until much later down the line. By handling this case, we remove an entire set of bugs from the API, without compromising anything internally.

Handle app calling Close from worker thread after calling from app thread

---

docs/TSG.md

Add details about collecting SMB over QUIC traces.

Updates TSG.cmd for SMB over QUIC

---

src/core/binding.c

Turns out there are other parts of the code that depend on an initial packet coming in first to initialize a connection. We're hitting testing asserts in 0-RTT tests after merging this change last week.
It might just be that we need to fix the assert, but in order to be sure I'd want to get a solid test case. But for now, I don't want broken code sitting in main.

Don't allow 0-RTT packets to initialize a connection

---

src/plugins/trace/dll/DataModel/QuicState.cs
src/plugins/trace/dll/Tables/QuicNetworkTable.cs

Updates to get the `TxUdp` actually working in the WPA plugin.

WPA Plugin Support for Connection UDP Send Batch

---

src/core/cubic.c
src/core/cubic.h

Changes AIMD-friendly region algorithm to an AIMD implementation (where bytes are added to a window
value for each ACK proportional to the number of ACKed bytes) from a time-based function, to make it
easier to implement the dynamic AIMD slope that's in the new bis RFC.

CUBICbis updates

---

src/manifest/MsQuic.wprp

Add per-frame XDP events to RPS profile.

Add XDP event provider to RPS profile

---

src/core/cubic.c

Port of a 2018 fix to the Windows TCP CUBIC implementation.

Prevent exponential CongestionWindow growth beyond SlowStartThreshold

---

.github/workflows/wan-perf.yml
scripts/emulated-performance.ps1

Makes it easier to open in Excel.

Write WAN Perf Results to CSV

---

.github/workflows/wan-perf.yml
scripts/emulated-performance.ps1

Experiment duonic with a larger TX and RX ring buffer size.

[Experiment] Use a larger ring buffer size for duonic

---

docs/api/QUIC_CONNECTION_EVENT.md
docs/api/QUIC_CREDENTIAL_CONFIG.md

See https://github.com/microsoft/msquic/issues/2332

Document effects of QUIC_CREDENTIAL_FLAG_USE_PORTABLE_CERTIFICATES

---

src/core/quicdef.h

Greatly increases the max receive queue to account for large BDP networks with bursty traffic.

Larger Max Connection Receive Queue

---

src/core/connection.c

Release/1.1 - Always Set CID if NULL

---

src/core/ack_tracker.c
src/core/ack_tracker.h
src/core/connection.c
src/core/crypto_tls.c
src/core/frame.c
src/core/frame.h
src/core/send.c
src/core/unittest/SpinFrame.cpp
src/core/unittest/main.h
src/generated/linux/frame.c.clog.h
src/generated/linux/frame.c.clog.h.lttng.h
src/manifest/clog.sidecar

Another change I wanted to get in before v2. Updates our ACK frequency usage to the latest draft version.

Updates for ACK Frequency Draft 2

---

docs/api/QUIC_CONNECTION_EVENT.md
src/inc/msquic.h
src/test/lib/TestConnection.cpp

Another ask from https://github.com/microsoft/msquic/issues/1709.

Add Unknown/Default Datagram Send State

---

.github/dependabot.yml
.github/workflows/check-clog.yml
.github/workflows/codeql-analysis.yml
.github/workflows/docker-publish.yml
.github/workflows/mirror-repo.yml
.github/workflows/scorecards-analysis.yml

- Make it run weekly (every Saturday) instead of daily.
- Remove nuget since it wasn't working.
- Remove version comments since those don't get updated by dependabot.

Dependabot Cleanup

---

scripts/package-distribution.ps1

First step of https://github.com/microsoft/msquic/issues/2060. Packages up the test code so that we can run it later, after we release. Only runs on `windows`, `linux` and `macos` platforms.

Package Up MsQuicTest

---

src/core/binding.c
src/core/configuration.c
src/core/connection.c
src/core/lookup.c
src/core/loss_detection.c

Minor comment tweaks that I made while refreshing myself on the quic core code.

Some code comment cleanup/additions

---

scripts/performance-helper.psm1
scripts/run-executable.ps1
scripts/run-gtest.ps1
scripts/test.ps1
src/test/lib/DataTest.cpp

Another "fix typos" PR, this time from a review of the tests.

Fix some typos in test code

---

src/core/api.c
src/test/lib/ApiTest.cpp

Hopefully fixes https://github.com/dotnet/runtime/issues/53090.
cc @CarnaViire

Report ABORTED for StreamSend if remotely closed

---

src/core/connection.c

Fix Stats v2 Query Size

---

docs/TSG.md

Add guides to troubleshoot local testing of WebTransport over HTTP/3.

Add troubles

---

scripts/generate-git-checkin.ps1

For some reason this is broken.

Remove optional reviewers from git checkin

---

scripts/generatevpackpat/Program.cs
scripts/generatevpackpat/generatevpackpat.csproj

The PAT has to be generated via the API. This tool creates the PAT with the right permissions.

Add tool to generate Vpack PAT

---

scripts/generate-dotnet.ps1
src/cs/lib/msquic_generated.cs

Updates the C# code generation step to add `[Flags]` attributes to the `_FLAGS` enums.

[C#] Adds Flags attribute to generated _FLAGS enums

---

CMakeLists.txt
scripts/generate-git-checkin.ps1
src/lib.rs

https://github.com/microsoft/msquic/pull/2439
https://github.com/microsoft/msquic/pull/2438

Backport PGO and rust fixes to Ni

---

.azure/azure-pipelines.qns.yml
.azure/obtemplates/push-vpack.yml
CMakeLists.txt
scripts/package-distribution.ps1
scripts/package-nuget.ps1
scripts/write-versions.ps1
src/distribution/Info.plist
src/inc/msquic.ver

Update main to v2.1

---

src/core/send.c
src/test/MsQuicTests.h
src/test/bin/quic_gtest.cpp
src/test/bin/winkernel/control.cpp
src/test/lib/DataTest.cpp

* Fix possible infinite loop in priority stream scheduling
* add test

Fix possible infinite loop in priority stream scheduling (#2451) (Backport to Ni)

---

.github/ISSUE_TEMPLATE/bug_report.yaml

Update the version list to just include main and official releases.

Update Issue Template for New Bugs

---

src/core/send.c
src/core/send.h
src/core/stream.c

Cherry-pick #2463 to release/2.0.

release/2.0 CP - Extra Protection Around Stream Send Queue #2463

---

.azure/templates/cargo.yml
Cargo.toml

Adds a dry run publish step to cargo.
Relies on CI.

Add cargo publish --dry-run to CI

---

.azure/templates/cargo.yml
Cargo.toml

release/2.0 CP - Add cargo publish --dry-run to CI (#2476)

---

src/lib.rs

Fixes a number of recent regressions in lib.rs.
Manually. CI will validate.

Fix Rust Issues

---

.azure/azure-pipelines.ci.yml

They cause issues with the machines.

release/1.0 - Disable Perf Tests

---

.github/workflows/test-down-level.yml
scripts/prepare-machine.ps1

Runs down-level tests. Currently on the down-level release binaries, but will be updated to build latest and run on those instead.
Tried out some of the commands locally. Need to test in CI.

Run Down-Level Tests

---

src/platform/datapath_kqueue.c

Fix kqueue timeout with shared ec mode (#2504)

---

src/test/lib/HandshakeTest.cpp
src/test/lib/QuicDrill.cpp

Trying to make some of these tests more stable. Candidate for backport.

Add Retry to Some Tests

---

.github/workflows/test-down-level.yml
scripts/run-gtest.ps1
src/inc/msquic.h

Fixes some issues found while testing a breaking change.

Fixes for Catching Breaking Changes

---

.azure/OneBranch.Tests.Official.yml
.azure/OneBranch.Tests.PullRequest.yml
.azure/azure-pipelines.ci.yml
.azure/azure-pipelines.perf.yml
.azure/azure-pipelines.periodic.yml
.azure/obtemplates/build-distribution.yml
.azure/obtemplates/build-linux-packages.yml
.azure/obtemplates/build-linux.yml
.azure/obtemplates/run-bvt.yml
.azure/templates/build-config-user.yml
.azure/templates/build-config-winkernel.yml
.azure/templates/build-distribution.yml
.azure/templates/build-nuget.yml
.azure/templates/merge-publish-coverage.yml
.azure/templates/run-bvt.yml
.azure/templates/run-dotnet.yml
.azure/templates/run-performance.yml
.azure/templates/run-quicinterop.yml
.azure/templates/run-spinquic.yml
.github/workflows/cargo.yml
.github/workflows/check-clog.yml
.github/workflows/check-dotnet.yml
.github/workflows/test-down-level.yml
.github/workflows/wan-perf.yml
docs/BUILD.md
docs/Diagnostics.md
docs/TEST.md
scripts/prepare-machine.ps1
scripts/test.ps1

Cleans up the prepare-machine.ps1 script and its usages.
Leveraging the CI.

Refactor prepare-machine.ps1

---

src/core/loss_detection.c
src/generated/linux/loss_detection.c.clog.h
src/generated/linux/loss_detection.c.clog.h.lttng.h
src/inc/quic_platform_posix.h
src/inc/quic_platform_winuser.h
src/manifest/MsQuicEtw.man
src/manifest/clog.sidecar
src/platform/platform_posix.c
src/platform/platform_winuser.c
src/test/lib/HandshakeTest.cpp
src/test/lib/QuicDrill.cpp
src/tools/etw/trace.c

Cherry pick a few recent fixes.

release/2.0 - CP #2508, #2511, #2512 & #2513

---

.github/codeql/codeql-config.yml

CodeQL - Add Quality

---

.azure/azure-pipelines.perf.yml
.gitmodules

Changes from https://github.com/quictls/openssl/pull/77.

Update OpenSSL to the 1.1.1.1n Branch

---

src/inc/msquic.h
src/lib.rs

For debugging packet captures
Manual test

Expose QUIC_TLS_SECRETS to Rust

---

.github/workflows/cargo.yml

An attempt to fix the cargo tests on ubuntu

Try to Fix Cargo Test on Ubuntu

---

.azure/OneBranch.Official.yml
.azure/obtemplates/build-nuget.yml

release/2.0 CP - Support Building Release NuGet Packages (#2551)

---

src/core/send.h
src/core/stream_recv.c

release/2.0 CP - Accumulator logic for MAX_DATA updates #2553

---

src/core/binding.c
src/core/binding.h
src/core/connection.c
src/core/inline.c
src/core/packet.c
src/core/packet.h

Refactors the token contents we use for retry tokens to be usable for NEW_TOKENs in a future PR.
Validated using existing tests.

Refactor for Future NEW_TOKEN Support

---

.azure/azure-pipelines.ci.yml
scripts/run-gtest.ps1
scripts/test.ps1
src/inc/quic_datapath.h
src/platform/datapath_raw.c
src/platform/datapath_raw.h
src/platform/datapath_raw_dpdk.c
src/platform/datapath_raw_socket.c
src/platform/datapath_raw_xdp.c
src/platform/unittest/DataPathTest.cpp
src/platform/unittest/main.cpp
src/test/bin/quic_gtest.cpp

Enables the unit tests on the XDP platform and fixes the code so that they run green.

Light up unit tests on XDP platform

---

.azure/azure-pipelines.qns.yml
.azure/obtemplates/push-vpack.yml
CMakeLists.txt
Cargo.toml
scripts/package-distribution.ps1
scripts/package-nuget.ps1
scripts/write-versions.ps1
src/distribution/Info.plist
src/inc/msquic.ver
src/lib.rs

CP https://github.com/microsoft/msquic/pull/2577 to release/2.0.

2.0 CP - [RUST] Implements stats v2 struct and missing stream events

---

docs/API.md

N/A
N/A
It is a documentation change

Fix listener stop documentation in api.md

---

.azure/azure-pipelines.ci.yml
.github/workflows/wan-perf.yml

Removes perf from release branches.

No Perf on Release Branches

---

.azure/azure-pipelines.perf.yml
.azure/templates/run-performance.yml
scripts/performance-helper.psm1
scripts/performance.ps1
scripts/prepare-machine.ps1

Things still blocking onboarding perf:
- DNS resolution of `quic-server` to appropriate IP address in XDP datapath.
- Seems to have reliability issues.
- Perf UDP signal to kill app doesn't work yet (requires an XDP polling thread).

Prepare for Onboarding XDP Perf

---

README.md

Updates the readme to reflect the latest RFC status.

Unreliable Datagram RFC 9221 is Official

---

.azure/azure-pipelines.ci.yml
.azure/obtemplates/test-distribution.yml
.azure/templates/test-distribution.yml
scripts/update-version.ps1

An attempt to fix #2632 with a new stage to run a test case using the installed package

Add Test for Linux Package

---

.azure/azure-pipelines.ci.yml
.azure/azure-pipelines.qns.yml
.azure/obtemplates/push-vpack.yml
.azure/templates/test-distribution.yml
.github/workflows/wan-perf.yml
CMakeLists.txt
Cargo.toml
scripts/make-packages.sh
scripts/package-distribution.ps1
scripts/package-nuget.ps1
scripts/update-version.ps1
scripts/write-versions.ps1
src/distribution/Info.plist
src/inc/msquic.ver

Cherry picks a few recent fixes for Linux packaging and canceling long running jobs for PRs.
#2621, #2634, #2636
Covered by existing.

CP release/2.0 - Linux Package and Infra Fixes

---

src/lib.rs

Close listener on drop
Manual test
No

Expose Listener close function

---

.azure/azure-pipelines.perf.yml
scripts/performance-helper.psm1
scripts/performance.ps1

This will make it so cancelled runs don't bring down the systems
N/A
N/A

Run perf from temp folder

---

.azure/obtemplates/build-linux-packages.yml

Fix RPM and Deb Signing
N/A
N/A

Switch to what should be the official signing profile

---

.azure/obtemplates/build-linux-packages.yml

Try another signing profile

---

.azure/obtemplates/build-linux-packages.yml

Backport of signing profile for actual windows package store on linux
N/A
N/A

Backport correct signing profile to Ni

---

src/platform/datapath_raw_xdp.c

Remove the workaround in QUIC for XDP TX hangs.
Covered by existing tests.

Consume XDP fix for TX hangs

---

src/platform/datapath_raw_xdp.c

Increase ring size and buffer count as we observed perf increase during local testing.
Covered by existing tests.

Increase ring size and buffer count

---

docs/api/ListenerStart.md

Closes #2417
Its a documentation change

Update listener docs for quirks regarding ListenerStart on the same port

---

.azure/azure-pipelines.perf.yml
.gitmodules

Update to openssl 1.1.1o

---

.azure/azure-pipelines.ci.yml
.azure/azure-pipelines.perf.yml
scripts/performance-helper.psm1
scripts/performance.ps1

Adds automation coverage for SharedEC
Onboarded to CI and Perf
N/A

Add SharedEC to Perf and SpinQuic

---

.azure/azure-pipelines.ci.yml

Fixes https://github.com/microsoft/msquic/issues/2692.
Validated via CI.
None

Disable XDP Builds on release/2.0

---

.azure/azure-pipelines.perf.yml
scripts/prepare-machine.ps1
src/platform/datapath_raw_xdp.c

Updates to latest XDP.
Existing
None

Update to Latest XDP SDK

---

.azure/templates/build-nuget.yml

Fix break in public CI build for Nuget package.
Via CI

Fix Nuget Packaging Failure in CI

---

detailed.html
index.html
rps.html
wanperf.html

Update Copyright info for performance dashboard

---

scripts/prepare-machine.ps1
src/platform/datapath_raw_xdp.c

To unblock RSS work and use new XDP port rules.
CI

Ingest the latest XDP devkit

---

src/platform/tls_schannel.c

Fixes incorrect usage of Schannel flags.
CI automation
N/A

Fix Schannel Context Request Flags

---

.azure/azure-pipelines.perf.yml
scripts/performance.ps1
src/platform/datapath_raw_xdp.c

Use the new port set XDP rules for client-side connections.
CI

Use port set XDP rules

---

src/cs/LicenseHeader.txt
src/cs/lib/msquic_generated.cs
src/cs/lib/msquic_generated_linux.cs
src/cs/lib/msquic_generated_macos.cs

Fix typo in generated .net code

---

src/inc/msquic.hpp

To be able to access Handle as other object (MsQuicConnection/Stream) does.
Will be used for test
N/A

class to struct to access Handle

---

src/cs/lib/msquic_extensions.cs

Switch order of unsafe and static in C# code

---

src/test/lib/ApiTest.cpp

SetParam tests for any object/parameter #1215
This is test
N/A

Add tests for SetParam for any object/parameter

---

src/test/lib/ApiTest.cpp

SetParam test for Registration #1215
This is test
N/A

Add SetParam test for Registration

---

docs/Settings.md
src/lib.rs
src/platform/tls_schannel.c

Fixes #2751 
CI testing.
Updated the documentation to reflect changes made for #2573

Update Rust definitions and documentation for new parameters.

---

.azure/azure-pipelines.perf.yml

Fix linux sharedec not using sharedec bits

---

detailed.html
index.html

The current titles are confusing.

Change 'Requests per Second Latency' titles in perf dashboard to 'Request Latency'

---

docs/Settings.md
scripts/generate-dotnet.ps1
src/core/connection.c
src/cs/lib/msquic_generated.cs
src/inc/msquic.h

Adds documentation and helper defines to make it easier for apps to query and consume `QUIC_STATISTICS_V2`.
N/A
Included

Documentation and Improvements to Help Consumers of QUIC_STATISTICS_V2

---

src/core/packet_builder.c
src/generated/linux/packet_builder.c.clog.h
src/generated/linux/packet_builder.c.clog.h.lttng.h
src/plugins/trace/exe/Program.cs

Lots of improvements for quictrace
N/A
N/A

Updates for QuicTrace

---

src/test/lib/ApiTest.cpp

More SetParam tests for Listener #1215
This is test
N/A

Add more SetParam tests for Listener

---

src/test/lib/ApiTest.cpp

SetParam test set for Stream object #1215
This is test
N/A

Add more SetParam tests for Stream

---

src/core/stream_recv.c
src/generated/linux/stream_recv.c.clog.h
src/generated/linux/stream_recv.c.clog.h.lttng.h
src/manifest/MsQuicEtw.man
src/manifest/clog.sidecar
src/plugins/trace/dll/DataModel/ETW/QuicEtwEvent.cs
src/plugins/trace/dll/DataModel/QuicEvent.cs
src/plugins/trace/dll/DataModel/QuicEvents.cs
src/plugins/trace/exe/Program.cs

More improvements for understanding RPS latency
Perf pipeline and local usage of tool.
N/A

RPS Latency Analysis Improvements

---

src/inc/quic_platform.h
src/platform/platform_worker.c

Acquire the EC lock only when there's new EC pending to be added to platform worker's EC list.
CI

Optimize EC list synchronization

---

src/core/quicdef.h
src/core/transport_params.h
src/test/lib/ApiTest.cpp
src/test/lib/TestHelpers.h
src/test/lib/precomp.h

More SetParam test set for global parameter #1215
This is test
N/A

Add more SetParam tests for Global

---

src/test/MsQuicTests.h
src/test/bin/quic_gtest.cpp
src/test/bin/winkernel/control.cpp
src/test/lib/ApiTest.cpp

GetParam tests for Listener #1215
This is test
N/A

Add GetParam tests for Listener

---

.azure/azure-pipelines.perf.yml
scripts/log.ps1
scripts/performance.ps1
src/manifest/MsQuicEtw.man
src/plugins/trace/dll/DataModel/ETW/QuicEtwEvent.cs
src/plugins/trace/dll/DataModel/QuicEvents.cs
src/plugins/trace/exe/Program.cs

More improvements while doing additional analysis of RPS scenarios and events.
N/A
N/A

More RPS Analysis and Updates

---

src/test/MsQuicTests.h
src/test/bin/quic_gtest.cpp
src/test/bin/winkernel/control.cpp
src/test/lib/ApiTest.cpp

GetParam tests for Registration and Common #1215
This is N/A
N/A

Add GetParam tests for Registration and Common

---

src/test/MsQuicTests.h
src/test/bin/quic_gtest.cpp
src/test/bin/winkernel/control.cpp
src/test/lib/ApiTest.cpp
src/test/lib/TestHelpers.h

Set/GetParam tests for Connection #1215
This is test
N/A

Add more Set/GetParam tests for Connection

---

src/core/settings.c
src/core/version_neg.c
src/cs/lib/msquic_generated.cs
src/inc/msquic.h
src/inc/msquic.hpp
src/test/lib/HandshakeTest.cpp
src/test/lib/TestHelpers.h

While adding version support to quicreach, I encountered a few things that made it a little difficult to use. This PR fixes those.
Fixes #2841.
Existing tests
N/A

Improve Version Settings API Usage

---

src/core/api.c
src/generated/linux/api.c.clog.h
src/generated/linux/api.c.clog.h.lttng.h
src/manifest/MsQuicEtw.man
src/manifest/clog.sidecar

New event to better understand timings.
N/A

Add new StreamAppReceiveCompleteCall Event

---

src/plugins/trace/dll/DataModel/ETW/QuicEtwEvent.cs
src/plugins/trace/dll/DataModel/QuicEvent.cs
src/plugins/trace/dll/DataModel/QuicEvents.cs
src/plugins/trace/dll/DataModel/QuicStream.cs
src/plugins/trace/dll/DataModel/QuicStreamTiming.cs

Added a new state called ProcessAppRecv. We transition from AppRecv to ProcessAppRecv when the app calls receive complete.
Tested locally with WPA.

Improve WPA stream state plugin to show when receive complete API is called

---

src/plugins/trace/dll/Tables/QuicStreamStateTable.cs

Just a minor UI update to sort stream state by time.
Before:
Now:

Sort stream state names by the time they occur

---

src/inc/msquic.hpp
src/test/MsQuicTests.h
src/test/bin/quic_gtest.cpp
src/test/bin/winkernel/control.cpp
src/test/lib/ApiTest.cpp

ConnectionClose in Callback #1715 
This is test
N/A

ConnectionClose test in Callback

---

src/inc/msquic.hpp
src/test/lib/ApiTest.cpp

StreamOpen/Start/Send from both Server/Client
Send Session resumption ticket from server
This is test
N/A

Stream send & Session resumption for Conn Close test

---

.azure/openssl.gdnsuppress

Suppress false positive by CredentialScanner for openssl
N/A
N/A

Add openssl supression

---

docs/Diagnostics.md

fix logging commands for Linux

---

scripts/run_endpoint.sh
src/tools/interop/interop.cpp
src/tools/interop/interop.h

Interop tool support for version 2, and interop runner script support.

Interop runner support for Version 2

---

docs/Diagnostics.md
scripts/log_wrapper.sh

wrap logging procedure for linux
N/A
done

logging wrapper for linux

---

src/inc/quic_platform_posix.h
src/inc/quic_platform_winkernel.h
src/inc/quic_platform_winuser.h
src/platform/datapath_epoll.c
src/platform/datapath_kqueue.c
src/platform/datapath_raw_xdp.c
src/platform/datapath_winuser.c
src/platform/platform_internal.h
src/platform/platform_worker.c

Give up the current thread quantum to the scheduler if we do 10 iterations of the loop with no work being done.
Existing perf tests
N/A

XDP Yield to Scheduler with No Work

---

.azure/azure-pipelines.perf.yml
scripts/xdp-devkit.json

Consume the latest XDP binaries.
Existing tests.
None

Update to v0.16.3 prerelease of XDP

---

src/core/api.c
src/core/binding.c
src/core/connection.c
src/core/connection.h
src/core/registration.c
src/core/registration.h

Fixes #2914 by ensuring the Worker is always set before registration.
Existing tests.
No

Fix QuicTraceRundown Race Condition

---

scripts/build.ps1

Fix android builds. FYI: https://github.com/actions/virtual-environments/issues/5879
CI
None

Try fix Android

---

src/inc/quic_platform_winuser.h
src/platform/crypt_bcrypt.c
src/platform/datapath_winuser.c

An attempt to improve perf by getting mulitple IOCPs per syscall.
Existing tests.
None

Move to GetQueuedCompletionStatusEx

---

scripts/build.ps1
src/platform/datapath_epoll.c

Cherry-pick #2912 to release/2.0 branch.
CI

CP 2.0: Try fix Android (#2912)

---

src/platform/datapath_winuser.c

Fixes a regression from https://github.com/microsoft/msquic/pull/2916 that was causing failures in perf pipeline and no perf uploads.
Existing CI.
None

Fix Shared EC Perf Regression

---

docs/Release.md

For the upcoming release.
N/A
Added

Release Notes for v2.1

---

.azure/obtemplates/push-vpack.yml
.azure/templates/test-distribution.yml
CMakeLists.txt
Cargo.toml
scripts/package-distribution.ps1
scripts/package-nuget.ps1
scripts/write-versions.ps1
src/distribution/Info.plist
src/inc/msquic.ver
src/test/lib/ApiTest.cpp

Now that release/2.1 has been created, update main to 2.2.
Existing CI
N/A

Update main Version to v2.2

---

scripts/make-packages.sh

missed in https://github.com/microsoft/msquic/pull/2945 as I did not have CI pipeline yet.

fix passing ARCH to make-packages

---

.github/workflows/test-down-level.yml

Now that we have a new release, run those tests to make sure we don't break them.
Automation
N/A

Onboard Downlevel Tests for v2.1

---

.azure/OneBranch.Docker.Official.yml
.azure/dockers/ob/Dockerfile

Add Build docker official pipeline.
CI

Build Docker pipeline

---

docs/api/ConfigurationOpen.md

Changed an RFC link in the docs to link to the page it redirects to.
N/A
This change directly modifies documentation.

Follow redirect

---

docs/Release.md

Added "Supported Platforms" to release documentation.

Added Supported Platforms to Release Docs

---

.azure/OneBranch.Publish.yml

Create a manual OBP to upload signed package to PMC

---

.github/workflows/cargo.yml
.gitignore
scripts/build.rs
src/lib.rs

Adds the missing (minimal) support for sending and receiving datagrams. 
Tests do not cover datagrams.
Documentation in general in Rust side is very minimal.

Enable minimal datagram support

---

src/test/lib/HandshakeTest.cpp
src/test/lib/TestHelpers.h

Closes #2997. Fix for Alpn Change Test, waiting for new connection event now.
N/A
No.

Fix: Alpn Change Test

---

.azure/templates/make-pgo-pr.yml

Fix PGO pipeline bugs

---

src/inc/quic_platform_posix.h
src/platform/datapath_kqueue.c
src/platform/platform_posix.c
src/platform/unittest/PlatformTest.cpp

Really fix kqueue generic events now.
Automated CI
N/A

Fix kqueue generic events

---

.azure/azure-pipelines.periodic.yml

Don't use loopback tests in PGO runs.
CI
N/A

Only run PGO weekly. Only use non-loopback results for PGO.

---

src/generated/linux/platform_posix.c.clog.h
src/generated/linux/platform_posix.c.clog.h.lttng.h
src/manifest/clog.sidecar
src/platform/platform_posix.c

Always creating worker threads without affinitization on error. (#3041)

---

.azure/obtemplates/push-vpack.yml
.azure/templates/test-distribution.yml
CMakeLists.txt
Cargo.toml
scripts/package-distribution.ps1
scripts/package-nuget.ps1
scripts/write-versions.ps1
src/distribution/Info.plist
src/inc/msquic.ver

Updates various files to reflect latest patch version.

Update Patch Version Number

---

.github/workflows/test-down-level.yml

Points the down level tests to the latest release test binaries to test.

Update Down Level Tests for v2.1.1

---

docs/Release.md

Documentation on how to create a release.

Add New Release Instructions

---

src/platform/datapath_epoll.c

Use correct length increment for msg_controllen (#3065)

---

src/core/unittest/VersionNegExtTest.cpp

Add missing test for the change in 5e41168127. Specifically, test generating a compatibility list for each supported version.
Adding tests
N/A

Add test for VN compatibility list generation.

---

.azure/OneBranch.Package.yml

Update the internal pipeline default Windows ingest branch to the latest/correct one.

Update Default Windows Ingest Branch

---

docs/Release.md

Update release documentation

---

.github/workflows/test-down-level.yml

Add 2.1.2 to downlevel test

---

src/inc/msquic_posix.h
src/test/bin/quic_gtest.cpp

Fixes a recent macOS build error. Not sure why it's just now showing up.
Automated CI
N/A

Fix iOS Build Errors

---

.github/ISSUE_TEMPLATE/bug_report.yaml

Updates the bug report's `Affected OS` to have simpler selection.

Simplify Bug Report

---

.azure/azure-pipelines.ci.yml
CMakeLists.txt
scripts/build.ps1
src/inc/msquic_posix.h
src/test/MsQuicTests.h
src/test/bin/quic_gtest.cpp
src/test/lib/HandshakeTest.cpp
src/test/lib/TestConnection.cpp

- Fix iOS build
- Disable preview tests

Backport Fixes to release/2.0

---

.azure/azure-pipelines.ci.yml
.github/workflows/test-down-level.yml
CMakeLists.txt
scripts/build.ps1
src/core/unittest/SettingsTest.cpp
src/inc/msquic_posix.h
src/inc/msquicp.h
src/test/MsQuicTests.h
src/test/bin/quic_gtest.cpp
src/test/bin/winkernel/control.cpp
src/test/lib/ApiTest.cpp
src/test/lib/HandshakeTest.cpp
src/test/lib/TestConnection.cpp
src/test/lib/TestHelpers.h

- Fix iOS build
- Disable preview tests

Backport Fixes to release/2.1

---

.github/workflows/test-down-level.yml
scripts/build.ps1

Updates to consume latest down-level test binaries.
GitHub automation.
N/A

Update Down-Level Tests

---

src/tools/interopserver/InteropServer.cpp

This change activates Grease Quic Bit feature in InteropServer.
N/A
N/A

Activate Grease Quic Bit in Interop Server

---

src/tools/sample/sample.c

1. Fixed ticket error in client code https://github.com/microsoft/msquic/issues/3130
2. Make the usage text clearer

Fixed ticket error in client code #3130

---

docs/Settings.md
src/core/connection.c
src/core/unittest/VersionNegExtTest.cpp
src/core/version_neg.c
src/core/version_neg.h
src/generated/linux/connection.c.clog.h
src/generated/linux/connection.c.clog.h.lttng.h
src/generated/linux/version_neg.c.clog.h
src/generated/linux/version_neg.c.clog.h.lttng.h
src/manifest/MsQuicEtw.man
src/manifest/clog.sidecar

Keep up with VNE spec by renaming OtherVersions to AvailableVersions
Existing CI.
Already updated.

Rename OtherVersions to AvailableVersions.

---

powershell/generate-graphs.ps1
powershell/merge-performance.ps1

Updates the performance publishing code to handle moving histogram files to a separate folder and having multiple runs.

Update Perf Publishing Scripts

---

src/platform/datapath_winkernel.c

Filling the ancillary data for ECN somehow isn't implemented for winkernel datapath.
Have not done any testing (it builds though) but hopefully will be tested soon by the future PR of ECN validation.

Wire up ECN for Winkernel datapath

---

src/platform/datapath_winkernel.c

Wire up RX ECN for winkernel.
CI

Wire up RX ECN for winkernel

---

.azure/azure-pipelines.perf.yml
docs/Diagnostics.md
scripts/log.ps1
scripts/performance.ps1
src/manifest/MsQuic.wprp
src/manifest/MsQuicEtw.man

Improves the logging for the NIC drop scenario we've been investigating.
Perf pipeline
N/A

Improved Logging for NIC Drop Scenario

---

.azure/azure-pipelines.ci.yml

Enable Windows ASAN testing again.
Automated CI
N/A

Enable Back Windows ASAN Testing

---

scripts/log_wrapper.sh

Fix logging issue for linux
Manually tried
N/A

add 'c' to 'msqui'

---

src/plugins/trace/dll/Properties/launchSettings.json
src/plugins/trace/dll/Tables/QuicConnectionTable.cs
src/plugins/trace/dll/Tables/QuicExecutionTable.cs
src/plugins/trace/dll/Tables/QuicNetworkTable.cs
src/plugins/trace/dll/Tables/QuicSchedulingTable.cs
src/plugins/trace/dll/Tables/QuicStreamStateTable.cs
src/plugins/trace/dll/Tables/QuicTxBlockedTable.cs
src/plugins/trace/dll/Tables/QuicWorkerActivityTable.cs
src/plugins/trace/exe/QuicTrace.csproj
src/plugins/trace/exe/SingleFileAssemblyLoader.cs

- Compile with the right .NET version
- Handle a change of default filter flag on WPA's side

Fix Some WPA Plugin Stuff

---

src/tools/spin/spinquic.cpp

ThreadID for client/server differs for each run.
0 for client, 1 for server.
This should be N % 2 == 0 for client, N % 2 == 1 for sever if multiple server/client work with determinisity
locally tested
N/A

ThreadID 0 for client, ThreadID 1 for server for more determinisity

---

src/core/connection.c

Cherry picks a timerwheel fix for #3206 back to v2.1.
N/A

CP: v2.1 Timewheel Fix

---

.gitmodules

Cherry-picks latest quictls to 2.1

CP: Update to QuicTls (OpenSSL) 1.1.1s (#3208)

---

.github/workflows/test-down-level.yml

Updates the down-level testing to use the latest v2.1 release (v2.1.5).
Automation
N/A

Update Down-Level Test to v2.1.5 Release

---

src/fuzzing/README.md

Add detail for everyone to be able to debug
N/A
This is doc

add repro/debug section

---

scripts/prepare-machine.ps1

Updates submodules in parallel. This saves about 50s on my devbox.
CI

Speed up git submodules update

---

src/core/connection.c

Fixes issues with kernel mode MsQuic not always using the correct silo. Might need to backport this.
Manual testing. Don't have the ability to automate silo testing yet.
N/A

Silo Improvements on Client Side

---

src/core/connection.c

Backports #3248 to v2.1 for servicing to Windows.

Backport 2.1: Silo Improvements on Client Side (#3248)

---

docs/Diagnostics.md
scripts/log_wrapper.sh

log_wrapper.sh to convert trace to text

---

src/perf/bin/appmain.cpp
src/perf/lib/PerfCommon.h
src/perf/lib/RpsClient.cpp

Increase the cap on RPS since XDP seems to be hitting it.
Perf tests
N/A

RPS Test Diagnostics Improvements

---

CMakeLists.txt
src/test/lib/MtuTest.cpp

A couple of simplifications/improvements of the MTU tests I made while working on #3274.
Automation
N/A

Some MTU Test Improvements

---

src/platform/datapath_winuser.c

Add support for multiple concurrent receives on the submission/completion code paths. Do not actually submit multiple receives.
CI/CD.
No.

Support multiple outstanding receives

---

src/plugins/trace/dll/DataModel/QuicConnection.cs
src/plugins/trace/dll/DataModel/QuicEvents.cs

Found while using the plugin to do some debuging.
N/A
N/A

Fix Recent Regression in WPA

---

src/core/binding.c
src/core/connection.c
src/generated/linux/datapath_epoll.c.clog.h
src/generated/linux/datapath_epoll.c.clog.h.lttng.h
src/generated/linux/datapath_kqueue.c.clog.h
src/generated/linux/datapath_kqueue.c.clog.h.lttng.h
src/inc/quic_datapath.h
src/platform/datapath_epoll.c
src/platform/datapath_kqueue.c

Updates the Posix platforms to also (like Windows) store the "queue" in the CXPLAT_ROUTE option to fast retrieval on the send path.
Perf tests
N/A

Update Posix Platforms to Use Route Queue

---

src/lib.rs

rust to support ticket completion api

---

.azure/dockers/ob/linux/Dockerfile

Add numa lib to the docker image.
CI

Fix onebranch linux build docker

---

.azure/OneBranch.Official.yml

Use the updated onebranch linux docker image for onebranch pipelines.
OB CI

Use new onebranch linux docker image

---

src/fuzzing/README.md

Debugging instructions
N/A
This is doc

Detail steps for fuzzing debug

---

docs/Settings.md
src/core/api.c

Schannel's HandshakeComplete is TRUE. That of OpenSSl is FALSE

remove Handshake state check

---

.devcontainer/devcontainer.json

perf command could not run due to lack of privilege access

Add privilege access to devcontainer

---

src/test/lib/ApiTest.cpp
src/test/lib/TestHelpers.h

Fixes #3330 
Local testing and CI
N/A

Fix QUIC_SETTINGS param validation tests.

---

src/platform/datapath_epoll.c

Try removing the registration for `IP_PKTINFO` since we register for the v6 version already.
Existing tests
N/A

Don't Use v4 Local Addr CMsg

---

scripts/xdp-devkit.json
src/platform/datapath_raw_xdp.c

Consume XDP v0.16.5 for TCP rules.
CI

Consume XDP v0.16.5

---

CMakePresets.json

Adds a CMake Presets file for faster dev loop building.
Built locally.
Not fully supported, so no documentation for now.

Add CMake Presets file.

---

.github/workflows/test-down-level.yml

Update Down Level Tests for v2.1.7
Automation
N/A

Update Down Level Tests for v2.1.7

---

.azure/OneBranch.Official.yml
.azure/dockers/ob/linux/Dockerfile
.github/workflows/cross-compile.yml

Some packages in the image have been flagged by component compliance.
OB CI

Update some packages in linux build docker image

---

scripts/generate-git-checkin.ps1

Updates for internal pipeline automation.
N/A
N/A

Remove Hard Coded Alias and WI from Ingest PR

---

src/generated/linux/platform_winuser.c.clog.h
src/generated/linux/platform_winuser.c.clog.h.lttng.h
src/inc/quic_platform_winuser.h
src/manifest/clog.sidecar
src/platform/datapath_winuser.c
src/platform/platform_winuser.c

It seems some setups don't return NUMA node info as expected. Work around this.
Existing CI and manual testing on repro
N/A

Work Around Missing NUMA Node Info

---

src/inc/quic_trace.h

Fix Disable Logs Build on Windows

---

scripts/make-packages.sh

adds proper dependencies for debian and rpm packages 
fixes #2975

[release/2.1] back-port fixes for package dependencies

---

.github/workflows/wan-perf.yml

Reduce overhead of these tests since we don't actively look at results

Reduce the Tests in Wan Perf

---

CMakeLists.txt

Confirmed most of unknown information has gone. then stack appearance is also changed accordingly
N/A
N/A

Fix unknown callgraph issue

---

scripts/make-pgo-pr.ps1

Fix automation script.
N/A
N/A

Update PGO Script to Include OpenSSL3 PGD

---

.azure/azure-pipelines.ci.yml
.gitmodules
scripts/package-nuget.ps1

OpenSSL just released. Let's update.
Automation
N/A

Update to the Latest OpenSSL

---

.azure/OneBranch.Docker.Official.yml
.azure/OneBranch.Official.yml
.azure/OneBranch.PullRequest.yml

Fix linux container image paths in OB pipeline.
OB CI. Tested manually in the internal repo.

Fix linux container image paths in OB pipeline

---

.github/workflows/stress.yml

Onboards spinquic to GitHub Actions.
New tests
N/A

Move Stress Tests to GitHub

---

.azure/azure-pipelines.ci.yml
.github/workflows/build.yml
.github/workflows/stress.yml
scripts/prepare-machine.ps1
scripts/spin.ps1
src/platform/platform_worker.c

More improvements
Automation
N/A

More GitHub Automation Improvements

---

.github/workflows/stress.yml
src/platform/platform_worker.c

Trying to figure out why stress is timing out.
Automation
N/A

Improvements to Trackdown Stress Failures

---

src/bin/CMakeLists.txt

Installs msquic static library to CMake install and does minor cleanup around the target filename.
No existing tests that I can see.
No documentation.

Add static msquic archive to CMake install.

---

.azure/dockers/ob/windows/install-tools.ps1
scripts/prepare-machine.ps1

Looks like NASM updated and the old version is no longer available. :( Update to the next version.
This will need to be backported.
Automation
N/A

Update NASM Version

---

.azure/dockers/ob/windows/install-tools.ps1
scripts/prepare-machine.ps1

Update NASM Version (#3457)

---

src/bin/CMakeLists.txt

Promotes static library builds to default build targets
No, yes a suite of build/install tests would catch issues like this.
no

Added static library build to default build targets.

---

.azure/OneBranch.Official.yml

Fixes for OneBranch build breaks down-level. Copies the values from main.
N/A
N/A

Fix OneBranch Images on release/2.1

---

src/generated/linux/datapath_winuser.c.clog.h
src/generated/linux/datapath_winuser.c.clog.h.lttng.h
src/platform/datapath_winuser.c

Trying to track down the source of #3484.
Existing CI
N/A

Windows Sockets Abstraction Improvements

---

src/platform/datapath_epoll.c

Partially fixes #3504
Nothing to be concerned about.
Nothing to be concerned about.

Fix 2 Valgrind warnings

---

README.md
scripts/package-nuget.ps1
src/distribution/Microsoft.Native.Quic.MsQuic.OpenSSL.nuspec
src/distribution/Microsoft.Native.Quic.MsQuic.Schannel.nuspec
src/distribution/Microsoft.Native.Quic.MsQuic.UWP.OpenSSL.nuspec
src/distribution/Microsoft.Native.Quic.MsQuic.XDP.Schannel.nuspec

Makes nuget happy by including the reamde.

Add Readme File to Nuget

---

.github/workflows/bvt.yml

Accidentally onboarded GitHub Action BVT with only "low volume" ETW events. Need more logs to diagnose failures.
N/A
N/A

Full Logging for BVTs

---

.azure/OneBranch.Publish.yml

The old ACR got deleted. Update the service connection for the new ACR.

Use the new service connection for ACR

---

src/generated/linux/datapath_winuser.c.clog.h
src/generated/linux/datapath_winuser.c.clog.h.lttng.h
src/platform/datapath_winuser.c

This improves the lifetime management in the Windows usermode socket code.
N/A

Fix and Clean up Windows Socket Delete Code Paths

---

.github/workflows/test-down-level.yml

Update Down Level Test to 2.1.8
Updates tests
N/A

Update Down Level Test to 2.1.8

---

.azure/dockers/ob/linux/Dockerfile
.azure/templates/test-distribution.yml
.github/workflows/codeql-analysis.yml
docs/BUILD.md
docs/Diagnostics.md
scripts/log.ps1
scripts/prepare-machine.ps1

https://lttng.org/docs/v2.13/#doc-whats-new
Automation
Updated

Update LTTng to Latest (v2.13)

---

README.md

This Pull Request aims to update and remove the typo from the README file for the microsoft/msquic repository
No, this change does not require any new tests as it only involves updating the README file of the microsoft/msquic repository
No, there will be no significant documentation impact for this change. The update only involves fixing a typo in the README file of the microsoft/msquic repository, ensuring that the documentation provides accurate and error-free information to users and contributors. The change does not introduce new features or change existing functionality, and the documentation impact would be limited to the correction of the typo.

Update README for microsoft/msquic repository

---

docs/BUILD.md

Always use Strawberry Perl as ActiveState Perl is known to not work well with NASM.

Fix instructions for installing perl

---

.azure/OneBranch.Official.yml
.azure/azure-pipelines.ci.yml
.azure/obtemplates/build-nuget.yml
.azure/templates/build-nuget.yml
src/distribution/Microsoft.Native.Quic.MsQuic.XDP.OpenSSL.nuspec
src/distribution/Microsoft.Native.Quic.MsQuic.XDP.OpenSSL.targets

To help partners integrate MsQuic over XDP on downlevel OSes.
CI

Build Microsoft.Native.Quic.MsQuic.XDP.OpenSSL nuget package

---

docs/Platforms.md
docs/Release.md

Summary of the changes in 2.2.
N/A
This is a doc change.

Release 2.2 Notes

---

.azure/obtemplates/push-vpack.yml
.azure/templates/test-distribution.yml
CMakeLists.txt
Cargo.toml
scripts/package-distribution.ps1
scripts/package-nuget.ps1
scripts/write-versions.ps1
src/distribution/Info.plist
src/inc/msquic.ver

Update the minor version to 2.3.0
Existing CI
N/A

Update main to 2.3

---

.azure/openssl.gdnsuppress
docs/CredScan.md

Update CredScan and create a document explaining how to do this in the future.

Update CredScan suppressions for OpenSSL

---

.github/workflows/test-down-level.yml

Now that we have a v2.2 we need to start running the down level tests for it.
New tests are added.
N/A

v2.2 Down Level Test Support

---

.github/ISSUE_TEMPLATE/bug_report.yaml
docs/Release.md

Updates the issue template to add v2.2 to the possible versions.
N/A
N/A

Update issue template for bugs for v2.2

---

.azure/OneBranch.Official.yml
.azure/obtemplates/build-distribution.yml
.azure/templates/build-distribution.yml

Adds internal and external support for generating openssl3 distributions.
Automation
N/A

Add OpenSSL v3 Distribution

---

.azure/OneBranch.Publish.yml

Support publishing all linux packages in one go for a particular tag.
OB CI

Publish all linux packages for a particular release tag all at once

---

.azure/OneBranch.PullRequest.yml
.azure/obtemplates/build-linux-packages.yml
scripts/package-distribution.ps1

Fixes #3587. Still need to figure out a good way to publish easily.
Via internal OneBranch PR
N/A

Generate Ubuntu 22.04 Packages (using OpenSSL v3)

---

src/inc/quic_datapath.h
src/platform/datapath_epoll.c
src/platform/datapath_kqueue.c
src/platform/datapath_raw.c
src/platform/datapath_winkernel.c
src/platform/datapath_winuser.c
src/platform/unittest/DataPathTest.cpp

This adds the interface we will use in the future for offloading QUIC encryption.
Minimal test added.
N/A

Initial Datapath QEO Interface

---

.azure/OneBranch.Publish.yml

Fixing OneBranch build errors using https://learn.microsoft.com/en-us/azure/devops/pipelines/process/pipeline-triggers?view=azure-devops#tag-filters documentation.
Automation
N/A

Fix OneBranch Publishing YAML

---

.azure/OneBranch.Publish.yml

Use the right param for publishing, which was intentionally misued.
OB CI

Turn on automated publishing

---

.azure/OneBranch.Publish.yml

Apply tag filtering at stage level in publishing pipeline
OB CI

Apply tag filtering at stage level in publishing pipeline

---

src/inc/msquic.hpp
src/perf/lib/HpsClient.h
src/perf/lib/PerfCommon.h
src/perf/lib/PerfServer.h
src/perf/lib/RpsClient.h
src/perf/lib/SecNetPerfMain.cpp
src/perf/lib/ThroughputClient.h

Use qeo flag in secnetperf

---

src/core/path.c
src/core/path.h

Cherry Pick #3624 to v2.2

---

src/core/api.c
src/core/binding.c
src/core/connection.c
src/core/operation.h
src/core/registration.c
src/core/stream_send.c

Cherry Pick #3637 to v2.2

---

src/generated/linux/platform_winuser.c.clog.h
src/generated/linux/platform_winuser.c.clog.h.lttng.h
src/platform/platform_winuser.c

Cherry Pick #3641 to v2.2

---

src/core/crypto.c
src/test/lib/HandshakeTest.cpp

New ALPN Negotiation Fix Backport 2.2

---

.azure/OneBranch.Publish.yml
.azure/dockers/ob/pkg-publish/Dockerfile
.azure/dockers/ob/pkg-publish/publish-packages.sh
scripts/upload-linux-packages.sh

This reverts commit 2831bf120d4fe9136e17d9a0adc3f9b0455d7419.
Revert it in case we accidentally trigger the publishing pipeline. There are critical bugs in PMC that have not been fixed yet.

Revert "pmc v4 (#3652)"

---

src/plugins/trace/dll/DataModel/QuicStreamTiming.cs

Updates the plugin code to trim trailing states that don't really matter.
Manually ran on some traces
N/A

Trim Stream States in WPA

---

docs/Streams.md

clarify BufferCount in QUIC_STREAM_EVENT_RECEIVE

doc: clarify BufferCount in QUIC_STREAM_EVENT_RECEIVE

---

src/core/connection.c
src/core/stream.c
src/core/stream.h
src/core/stream_set.c
src/plugins/dbg/quictypes.h
src/tools/spin/spinquic.cpp

Exctracting some fixes from #3665 to isolate any issues.
Added to spinquic
N/A

Additional Testing for Stream Close in Spinquic

---

.azure/obtemplates/push-vpack.yml
.azure/templates/test-distribution.yml
CMakeLists.txt
Cargo.toml
scripts/package-distribution.ps1
scripts/package-nuget.ps1
scripts/write-versions.ps1
src/distribution/Info.plist
src/inc/msquic.ver

Bump up the version for publishing.
CI

v2.2.2 version bump

---

.github/workflows/test-down-level.yml

Update downlevel tests for 2.2.2

---

src/platform/CMakeLists.txt
src/platform/datapath_raw_xdp_linux.h

link libbpf for Linux XDP

---

.azure/templates/build-config-winkernel.yml
scripts/prepare-machine.ps1
scripts/sign.ps1

Test sign drivers for perf tests using corenet key/cert.
AzP CI

Test sign drivers for perf tests

---

src/test/lib/ApiTest.cpp

See title. Relevant for arm64 testing.
Need to ingest into Windows for arm64 testing.
N/A

Split QuicTestConnectionParam to Reduce Stack Usage

---

.azure/OneBranch.Publish.yml
.azure/obtemplates/build-linux-packages.yml

Mariner packages are incorrectly signed with the general-purpose public key. Sign and publish them correctly.
OB CI

Correctly sign CBL mariner packages and publish them

---

docs/Settings.md

To address issue #3261 
Where some flags had a few mismatches.
No testing.
Yes, changed the values in docs/Settings to reflect the header file.

Update docs to reflect what is in msquic.h

---

.azure/OneBranch.PullRequest.yml

The OneBranch PR yaml was out of date and needed some updates to keep in sync with Official.
Internal CI
N/A

Fix Up OneBranch PR Yaml

---

.azure/OneBranch.Tests.Official.yml
.azure/OneBranch.Tests.PullRequest.yml
.azure/obtemplates/run-bvt.yml

No more office hosted test machines.
OB CI

Use 1ES pool for OneBranch test pipeline

---

.github/workflows/code-coverage.yml
.github/workflows/test.yml

No more prerelease specific BVT jobs.
CI

Consolidate BVT jobs for different runners

---

.github/workflows/code-coverage.yml
README.md

See how it looks in codecov.io.

Use codecov.io for code coverage

---

README.md

Fix links and labels for badges.

Minor badge fixes

---

.azure/obtemplates/build-linux-packages.yml
.azure/obtemplates/build-linux.yml
.azure/obtemplates/build-winuser-xdp.yml
.devcontainer/devcontainer.json
.devcontainer/developer/devcontainer.json
.github/workflows/build-reuse-unix.yml
scripts/prepare-machine.ps1

Use container build for Linux.
CI

Container based build workflow for Linux

---

src/core/settings.c
src/tools/spin/spinquic.cpp

Trying to improve the code coverage numbers. Added some extra validation to the settings code to prevent obviously bad values from being set.
Ran some locally and found/fixed a few things. Depending on the CI for the rest.
N/A

Add QUIC_SETTINGS Support to SpinQuic

---

README.md

Updates the shields on the main readme.
N/A
N/A

Update Readme Shields

---

.github/workflows/build-reuse-darwin-framework.yml

Fixing a "security" issue flagged on our repo.
Automation
N/A

Update build-reuse-darwin-framework.yml Permissions

---

src/core/binding.c
src/core/binding.h
src/core/connection.c
src/core/connection.h
src/core/library.c
src/core/library.h
src/core/operation.h
src/core/packet_space.c
src/core/packet_space.h
src/core/path.c
src/core/path.h
src/core/quicdef.h
src/core/worker.c
src/generated/linux/connection.c.clog.h
src/generated/linux/connection.c.clog.h.lttng.h

Updates most everything to use the QUIC_RX_PACKET instead of some using the cxplat struct.
Existing CI
N/A

More Refactoring of the QUIC Layer RX Packets

---

scripts/build.ps1

Addressing the build break for [https://github.com/dotnet/msquic/pull/149](https://github.com/dotnet/msquic/pull/149) by adding back the option to specify tool chain file.
CI

Support customizing tool chain file for cross compile

---

.github/workflows/build-reuse-win.yml
.github/workflows/build-reuse-winkernel.yml

Unnecessary stuff was being included in the build artifacts uploaded to GitHub. Clean them up.
CI/CD
N/A

Filter Build Artifacts

---

src/platform/CMakeLists.txt

Use appropriate variable
N/A
N/A

Fix raw datapath build for ARM

---

src/generated/linux/datapath_epoll.c.clog.h
src/generated/linux/datapath_epoll.c.clog.h.lttng.h
src/platform/datapath_epoll.c

Backports #3867 to release/2.2.
CI/CD
N/A

Backport v2.2: Disable Segmentation Support on EIO (#3867)

---

src/platform/datapath_raw.h
src/platform/datapath_raw_linux.h

Code scanning is warning that we missing some header guards.
Code scanning automation will validate.
N/A

Add Missing Header Guards

---

README.md
scripts/update-docfx-site.ps1

Updates the automation and README to include a link to [Official Dashboard](https://microsoft.github.io/msquic/msquicdocs/docs/API.html)
N/A
N/A

Update README and Automation Script to include documentation dashboard. 

---

.github/workflows/test-down-level.yml

Test v2.1.9 and v2.2.3 downlevel.
Automation
N/A

Point Down Level Tests to Latest Releases

---

src/platform/datapath_raw_xdp_win.c
src/test/lib/QuicDrill.cpp

Need to add a check to see if XDP Raw Data path is supported. Fixed https://github.com/microsoft/msquic/issues/3910
N/A
N/A

Drill test failure triage

---

docs/Diagnostics.md
scripts/log_wrapper.sh

On Ubuntu, Simply installing dotnet dependencies cause issue.
Add additional steps and note to avoid it.
N/A
done

Add note for default ubuntu dotnet issue

---

.azure/OneBranch.Publish.yml

Backport https://github.com/microsoft/msquic/pull/3789 to release/2.2
cc @wfurt @ManickaP

Add Debian 12 package & fix Fedora 37 package (#3789)

---

.github/workflows/code-coverage.yml

Runs the new recvfuzz tool in code coverage.
CI/CD
N/A

Run Recv Fuzzing in Code Coverage

---

.gitmodules

Use the latest OpenSSL (quictls) release branches.
CI/CD
N/A

Update OpenSSL Dependencies

---

.azure/OneBranch.Tests.Official.yml
.azure/OneBranch.Tests.PullRequest.yml
.github/workflows/code-coverage.yml
.github/workflows/test.yml

v2.2 has been using the misconfigured image as well. Needs to be fixed.
CI

Backport new 1ES image to v2.2

---

README.md
docs/Sample.md

Add documentation for getting started with the sample server-client app

---

src/inc/msquic.h
src/test/bin/winkernel/control.cpp

Publish helper functions to simplify MsQuic dynamic loading integration.
CI

NMR registration helpers

---

src/inc/msquic.h
src/test/bin/winkernel/control.cpp

Allows NMR registration helper to fail more elegantly.
CI

NMR helper improvement

---

scripts/secnetperf-helpers.psm1

Small bugfix to secnetperf automation script

---

scripts/secnetperf-helpers.psm1
scripts/secnetperf.ps1

With the merge of https://github.com/microsoft/msquic/commit/b0edc581f4ec2e230fe99fa5e57c0b198e3da6fe, it looks like the JSON produced is missing the entire array, but including only a single value like this: 
This PR will fix that. 
UPDATE: https://github.com/microsoft/netperf/actions/runs/7550005766
CI
N/A

Fix logic to persist data to JSON

---

scripts/secnetperf-helpers.psm1
scripts/secnetperf.ps1
src/perf/lib/SecNetPerfMain.cpp

This updates netperf so that it may test things like RIO and XDP.
Verified with a couple private runs.
N/A

Support Testing Multiple IO Models with netperf

---

scripts/prepare-machine.ps1
scripts/secnetperf-helpers.psm1
scripts/secnetperf.ps1

Lots of stuff to install and cleanup the kernel mode pieces necessary for testing kernel perf.
**Note** - It's not 100% ready to go because I'm hitting an unrelated hang on `NCryptOpenKey` for some reason. This PR is mainly to make sure there are no regressions.
Many manual runs of netperf.
N/A

Adds Kernel Support for netperf

---

.docker/ubuntu-20.04/Dockerfile
.docker/ubuntu-22.04/Dockerfile

Update ubuntu dockers for compliance
CI

Update ubuntu dockers for compliance

---

scripts/secnetperf-helpers.psm1
scripts/secnetperf.ps1
src/perf/lib/SecNetPerfMain.cpp

Long overdue, but we need to refactor the fragile logic of using the order of tests and add in latency insertion now that the database schema has been more stable. 
CI
N/A

Refactor fragile ID tracking and add latency insertion 

---

scripts/secnetperf.ps1

Found solution to SQL error: Quotes were misaligned. Confusing error messages in debugging SQL blocked the merge of PR: https://github.com/microsoft/msquic/commit/dadc3ea2b1722accf6fe8dd3fb46ca48c3c685d4 
Now that this is implemented, SQL should parse fine.
CI
N/A

Quotation mark error

---

scripts/secnetperf.ps1

Want to see if it improves result consistency.
netperf automation
N/A

Run netperf Tests Longer

---

src/platform/selfsign_capi.c

We've seen a case where we can get stuck into a loop getting the private RSA key. This adds additional logic to prevent that.
CI/CD
N/A

Break Endless Loop in GetPrivateRsaKey

---

docs/Release.md

v2.3 Release Notes

---

.azure/OneBranch.Package.yml
CMakeLists.txt
Cargo.toml
scripts/package-distribution.ps1
scripts/package-nuget.ps1
scripts/write-versions.ps1
src/distribution/Info.plist
src/inc/msquic.ver

Updates main to v2.4 now that we have release/2.3
N/A
N/A

Update Minor Version to v2.4 in main

---

.github/workflows/test-down-level.yml

More tests for new release.
Added
N/A

Add v2.3 to Down Level Tests

---

scripts/secnetperf-helpers.psm1
scripts/secnetperf.ps1
src/manifest/MsQuic.wprp
src/manifest/MsQuicEtw.man

- Fix remote directory creation for first Linux run
- Always collect low volume events (for drops) on Windows
- Always collect and upload client & server console output
netperf automation
N/A

Improvements for netperf

---

scripts/secnetperf-helpers.psm1
src/platform/datapath_raw_xdp_win.c

Looks like binding to the VF was causing issues. Remove that logic for now.
netperf automation
N/A

Fix XDP for netperf

---

src/inc/quic_trace.h

Some logs were cut off with the old buffer side. Increase the size so the logs can be viewed correctly.
CI/CD
N/A

Bigger printf-Style Log Buffer

---

scripts/secnetperf.ps1

Persist more data now that the infrastructure is more mature. 
CI. As a double, we can test our new lab infra VMs with this PR. 
N/A.

Persist more data for intermdiary JSON files + Add hps collection

---

docs/Deployment.md

Fix Deployment Docs Link

---

scripts/secnetperf.ps1

Artifact upload was broken because the artifact name was wrong.
CI/CD
N/A

Use Environment in secnetperf Output

---

.azure/OneBranch.Official.yml

The current one has become stale. Update it.
OB CI

New windows docker image for Onebranch

---

scripts/xdp.json

Consume latest XDP patch release.
CI.
N/A.

Update xdp.json to 1.0.1

---

scripts/secnetperf-helpers.psm1
scripts/secnetperf.ps1

Adding collection of various diagnostics on the netperf machines via `Get-NetView`.
CI/CD
N/A

Collect Get-NetView Diagnostics for netperf

---

docs/ThreatModel.md

Documentation of the threat model for MsQuic.
N/A
This is new documentation.

Add a Threat Model doc

---

src/test/lib/ApiTest.cpp

Another Fix for Perf Counters Test

---

.github/workflows/test-down-level.yml

Updates down level tests to consume latest version for a test fix.
CI/CD
N/A

Fix Down Level Tests

---

.github/workflows/test-down-level.yml

Add support for testing all supported versions of TLS on the various releases/platforms.
Also removed security hardener because we always just ignore it anyways.
CI/CD
N/A

Improve/Expand Down Level Test Coverage

---

src/manifest/MsQuic.wprp

WPA needs it to decode events in some views.
CI

Add perf merge events back

---

scripts/secnetperf-helpers.psm1
scripts/secnetperf.ps1
src/perf/bin/appmain.cpp

This PR attempts to unify everything data-storage related.
It will accommodate the next stage in netperf development where we have dynamically changing test environments.
In addition, this PR will persist the full latency txt curves, and netperf will handle parsing/condensing/saving it. 
CI
N/A

Unify data storage

---

docs/ThreatModel.md

Adds some text on recommending apps keep MsQuic up to date.
N/A
Updated

Threat Model Text Improvements

---

scripts/secnetperf.ps1

The logic behind determining if a regression occurred or not is subject to change, but we still need the implementation code to read / update the regression file and fail if a regression occurs. 
This PR addresses that gap. 
CI
N/A

Add regression detection mechansims to the secnetperf script

---

scripts/secnetperf.ps1

Now that dynamic SQL execution using our JSON has been tested and working, we can remove the dead code. 
In addition, we should update some of the logic in the dashboard / regression python scripts to decouple the artifacts of technical debt. 
CI
N/A

Cleanup dead code

---

scripts/secnetperf.ps1

Problem:
- when a regression occurs, we still want to generate results. 
Solution: 
- See this commit on netperf: https://github.com/microsoft/netperf/commit/000f09d5f0a1706d0f39c21763f37dee178294d5, and this commit: https://github.com/microsoft/netperf/commit/3eedf6b0d3596ebafdaf7c82bcb7c5bba9e45801 
- TLDR; offload the regression detection after we run the secnetperf script. If we see a regression, cache the result as (test ID) - regression.
- Look for a (test ID)-regression in the later stages of the pipeline. If found, stop it before we commit anything, but after we have generated the results summary file. 
CI
N/A

Generate results with regression information. 

---

docs/api/QUIC_NEW_CONNECTION_INFO.md

Update the documentation on NEW_CONNECTION_INFO::ServerName to quote information from the RFC.

Update documentation on NEW_CONNECTION_INFO::ServerName

---

scripts/recvfuzz.ps1
src/platform/tls_openssl.c
src/tools/recvfuzz/recvfuzz.cpp

This PR builds a Handshake fuzzer tool where random fuzzed handshake packets are sent to the server after establishing handshake.
Not Applicable.
No

Fuzz Handshake packet

---

.azure/OneBranch.Official.yml

Update OneBranch build docker image
OB CI

[2.3] Update OneBranch build docker image

---

.azure/OneBranch.Official.yml

Update OneBranch build docker image
OB CI

Update OneBranch build docker image

---

.azure/OneBranch.Official.yml

Update OneBranch build docker image
OB CI

[2.2] Update OneBranch build docker image

---

src/inc/msquic_posix.h

Fix Posix QuicAddrToString

---

.docker/ubuntu-22.04/Dockerfile

Another dep found for building xdp program.
manually tried from clean environment and could build msquic successfully

Add dep for building xdp prog

---

scripts/update-version.ps1
src/bin/winkernel/msquic.kernel.vcxproj
src/bin/winkernel/msquicpriv.kernel.vcxproj
src/core/core.kernel.vcxproj
src/core/precomp.h
src/manifest/manifest.kernel.vcxproj
src/nuget.config
src/perf/bin/drvmain.cpp
src/perf/bin/secnetperfdriver.kernel.vcxproj
src/perf/bin/secnetperfdriverpriv.kernel.vcxproj
src/perf/lib/perflib.kernel.vcxproj
src/platform/platform.kernel.vcxproj
src/test/bin/winkernel/msquictest.kernel.vcxproj
src/test/bin/winkernel/msquictestpriv.kernel.vcxproj
src/test/lib/precomp.h
src/test/lib/testlib.kernel.vcxproj
version.json

Fixes a number of issues encountered when using the official native compiler in OneBranch.
Internal automation
N/A

Support Native Compiler in OneBranch Builds

---

scripts/log.ps1

Follow up from: 
https://github.com/microsoft/msquic/pull/4222
CI
N/A

Log.ps1 should remove AppData ETL buildup

---

scripts/build.ps1

x86 package test failed to link libnl-3-*
see automation...

Fix pkg-config for x86

---

src/core/stream_recv.c
src/tools/spin/spinquic.cpp

This PR does two things:
1. Reverts a recent behavior change when an app returns an error in the stream receive event. We should be ignoring the error (besides a telemetry assert) and then continuing as success.
2. Adds a few things to spinquic to execute in callbacks to try to increase code coverage for certain code paths (especially receive events).
Ran spinquic locally. CI/CD automation.
N/A

Fix Stream Recv Behavior

---

.docker/ubuntu-20.04/Dockerfile
.docker/ubuntu-22.04/Dockerfile

Revert "update dependency for libxdp/libbpf"

---

src/core/recv_buffer.c
src/core/stream_send.c
src/perf/lib/SecNetPerfMain.cpp
src/platform/unittest/CryptTest.cpp

Fixes a few warnings found by CodeQL. All of them are test or not *real* issues, but we want to make the tool happy.
Must run through full OneBranch CI
N/A

Fix a Few CodeQL Warnings

---

src/generated/linux/TestHelpers.h.clog.h
src/generated/linux/TestHelpers.h.clog.h.lttng.h
src/manifest/clog.sidecar
src/test/MsQuicTests.h
src/test/bin/quic_gtest.cpp
src/test/bin/winkernel/control.cpp
src/test/lib/DataTest.cpp
src/test/lib/TestHelpers.h

Adds a test that uses a stream to send data over and over. Each iteration it drops the incremented Nth packet and validates no corruption happens.
New test
N/A

Drop Nth Packet Test

---

scripts/secnetperf.ps1

We've been seeing crashes lately due to noise in Azure.
This PR adds retry logic to smooth out the noise.
CI
N/A

Adds retry logic to creating Secnetperf remote powershell sessions

---

scripts/build.ps1
scripts/prepare-machine.ps1

Some install deps using prepare-machines.ps1, some are not.
see automation

pkg_config setting for arm

---

.github/workflows/plugins.yml
src/plugins/trace/dll/QuicTraceLib.csproj
src/plugins/trace/dll/pluginManifest.json

Packages the WPA plugin to a .PTIX file which can be installed by WPA.
Worked locally. Trying in CI/CD.
None, yet.

Package WPA Plugin

---

src/nuget.config

Don't need. Also causes alerts.
N/A
N/A

Remove Unnecessary Nuget Config File

---

scripts/xdp.json

To make some CVE automation happy.
CI/CD
N/A

Update release/2.3's XDP dependency to v1.0.2

---

.azure/OneBranch.Official.yml
.azure/OneBranch.PullRequest.yml
.azure/obtemplates/build-linux.yml

Azure pipeline have been using really old image. need update.
N/A
N/A

Fix azure pipeline to newer image

---

scripts/secnetperf-helpers.psm1

LD_LIBRARY_PATH is reset for remote execution. Set explicitly.
netperf UI based execution can find libmsquic.so
N/A

Secnet perf to set LD_LIBRARY_PATH for sudo

---

.azure/OneBranch.Official.yml
.azure/OneBranch.PullRequest.yml
.azure/obtemplates/build-linux.yml

Fix azure pipeline build for linux xdp
running.....
N/A

Fix azure pipeline build for linux xdp

---

.azure/OneBranch.Official.yml
.azure/OneBranch.PullRequest.yml
.github/workflows/build-reuse-unix.yml
.github/workflows/build.yml
.github/workflows/dotnet-test.yml
.github/workflows/package-linux.yml
.github/workflows/package-reuse-linux.yml
.github/workflows/stress.yml
.github/workflows/test.yml
docs/BUILD.md
scripts/build.ps1

Linux XDP Tests have not used xdp datapath.
Unify xdp enablement flag as `-UseXdp` then edit .yml files
Locally works.
see automation.
N/A

Use -UseXdp for github pipeline

---

src/core/api.c

A minor change used to test some internal pipeline infra.
N/A
N/A

Minor Abstract Update

---

.azure/OneBranch.Official.yml
.azure/OneBranch.PullRequest.yml
.azure/obtemplates/build-distribution.yml
.azure/obtemplates/build-linux-packages.yml
.azure/obtemplates/build-linux.yml
.azure/obtemplates/download-artifacts.yml

Azure pipeline has issue by extending for ubuntu 24.04
Syntax issue and publish mechanism.
Verified internal branch and saw all green
N/A

Azure pipeline fix Syntax and publisher

---

.azure/OneBranch.Package.yml
CMakeLists.txt
Cargo.toml
scripts/package-distribution.ps1
scripts/package-nuget.ps1
scripts/write-versions.ps1
src/distribution/Info.plist
src/inc/msquic.ver

Update Release Patch Version to 2.3.6

---

.azure/OneBranch.Official.yml

Updating because the current one is not cached anymore.
OB CI

Update OneBranch build docker tag

---

.azure/OneBranch.Official.yml
.azure/OneBranch.PullRequest.yml
.azure/obtemplates/build-linux.yml
.github/workflows/build-reuse-unix.yml
.github/workflows/build.yml
.github/workflows/docker-publish-xcomp.yml
.github/workflows/dotnet-test.yml
.github/workflows/package-linux.yml
.github/workflows/package-reuse-linux.yml
.github/workflows/stress.yml
.github/workflows/test.yml

Installing libxdp etc. from repository of 24.04 cause side effects like glibc version mismatch.
see automation
N/A

Drop xdp support on Ubuntu22.04

---

scripts/make-packages.sh
scripts/package-distribution.ps1

add xdp dependencies for publish command

---

.github/workflows/stress.yml

Fixes a name conflict on upload between stress and recvfuzz tests.
CI/CD
N/A

Fix Artifact Upload for Recv Fuzzing Tests

---

.azure/obtemplates/build-linux-packages.yml
scripts/make-packages.sh
scripts/package-distribution.ps1

* Pass OS information explicitly to package-distribution
* libssl3 variants for ubuntu24.04
* detail flag for time64

Fix package distribution. Specify OS explicitly (#4434)

---

src/test/bin/quic_gtest.cpp
src/test/lib/DataTest.cpp

specific build case cannot see the flag
See CI
internal CI
https://mscodehub.visualstudio.com/msquic/_build/results?buildId=515701&view=results
N/A

Wrap StreamMultiReceive by preview feature

---

src/test/bin/quic_gtest.cpp
src/test/lib/DataTest.cpp

Cherry-pick
Internal CI
https://mscodehub.visualstudio.com/msquic/_build/results?buildId=515701&view=logs&j=739cbe69-1240-59c5-c95a-68a0e108661f&t=14d2417a-2469-4256-b236-f6905d864f5e
N/A

wrap by preview feature (#4441)

---

.azure/OneBranch.PullRequest.yml
src/tools/sample/sample.c

- container used for PR and Official was different
- ignore getenv security warning (error) on sample.c
automation
N/A

Fix azure pipeline build

---

.azure/OneBranch.Official.yml
.azure/OneBranch.Package.yml
.azure/OneBranch.Publish.yml
.azure/OneBranch.PullRequest.yml
.azure/obtemplates/build-distribution.yml
.azure/obtemplates/build-linux-packages.yml
.azure/obtemplates/build-linux.yml
.azure/obtemplates/download-artifacts.yml
.github/workflows/package-linux.yml
.github/workflows/package-reuse-linux.yml
CMakeLists.txt
Cargo.toml
scripts/make-packages.sh
scripts/package-distribution.ps1
scripts/package-nuget.ps1
scripts/write-versions.ps1
src/distribution/Info.plist
src/inc/msquic.ver
version.json

cherry-picking
Internal Official build pipeline succeeds. Publish pipeline with fake publish should be working
https://mscodehub.visualstudio.com/msquic/_build/results?buildId=518243&view=results
N/A

Cherry-pick for release/2.4

---

src/plugins/trace/dll/DataModel/QuicEvents.cs
src/plugins/trace/dll/pluginManifest.json

They got out of sync with the code.
Will install new plugin
N/A

Fix the Enums for the WPA Plugin

---

.azure/OneBranch.Official.yml
.azure/OneBranch.PullRequest.yml
.azure/obtemplates/build-linux-packages.yml
.github/workflows/package-linux.yml
.github/workflows/package-reuse-linux.yml
scripts/package-distribution.ps1

Fixes the packaging of Time64Distros
CI
No

Fix Time64Distro Packaging on GH Actions

---

.azure/OneBranch.Official.yml
.azure/OneBranch.PullRequest.yml
.azure/obtemplates/build-linux-packages.yml
.github/workflows/package-linux.yml
.github/workflows/package-reuse-linux.yml
scripts/package-distribution.ps1

Fix Time64Distro Packaging on GH Actions (#4463)

---

src/platform/datapath_winuser.c

Fixes a recent regression causing test failures.
CI/CD
N/A

Revert CancelDatapathIo Call Order

---

.azure/OneBranch.Publish.yml

make 1 big variable then iterate all the elements.
Using internal pipelie
N/A

Refactoring Azure pipeline for publishing package

---

src/bin/CMakeLists.txt

Change public headers to support msh3

Change public headers to support msh3

---

.github/workflows/package-linux.yml

We were using preview versions of .NET containers, now there is a RC and we're not pinning into specific version now.
CI
No

Fix .NET containers

---

.github/workflows/package-linux.yml
scripts/docker-script.sh
src/cs/QuicSimpleTest/Program.cs
src/cs/QuicSimpleTest/QuicHello.net8.0.csproj
src/cs/QuicSimpleTest/QuicHello.net9.0.csproj

Backport of packaging testing changes.
CI
No

[release/2.4] Backport infra packaging changes

---

.github/workflows/package-alpine-linux.yml
docs/Release.md
scripts/alpine-configure-packaging-key.sh
scripts/alpine-generate-hash.sh
scripts/docker-script.sh
scripts/generate-alpine-packaging-file.ps1
scripts/package-build.sh
scripts/templates/APKBUILD.template

Backport of #4554 
CI
Release doc changes

[release/2.4] Add alpine pipeline backport

---

.github/workflows/test-down-level.yml

Updates the down-level testing to test all the latest version of supported releases.
CI/CD
N/A

Update Down Level Tests to Latest Release Versions

---

.azure/obtemplates/build-nuget.yml

Missing a `-` in the yaml in #4576.
Need to merge.
N/A

Fix typo from #4576

---

.azure/OneBranch.Official.yml
.azure/obtemplates/build-nuget.yml

Publish nuget packages automatically
CI/CD
N/A

CP Automatic Nuget Publishing

---

scripts/secnetperf-helpers.psm1
scripts/secnetperf.ps1

Adds a new 'Max RPS' test for netperf runs.
netperf testing
N/A

Max RPS NetPerf Test

---

.github/workflows/netperf.yml

Changing `scripts/quic_callback` should trigger netperf
CI
N/A

Add quic_callback as a netperf dep

---

src/core/binding.c
src/core/lookup.c
src/inc/quic_platform_posix.h
src/inc/quic_platform_winkernel.h
src/inc/quic_platform_winuser.h

Backport #4632 to release/2.2.

Don't Share Previous IRQL for Dispatch RW Locks (#4632)

---

.azure/OneBranch.Package.yml
CMakeLists.txt
Cargo.toml
scripts/package-distribution.ps1
scripts/package-nuget.ps1
scripts/write-versions.ps1
src/distribution/Info.plist
src/inc/msquic.ver

Preparing to service the release.

Increment Patch Version - v2.2.8

---

.azure/OneBranch.Package.yml
CMakeLists.txt
Cargo.toml
scripts/package-distribution.ps1
scripts/package-nuget.ps1
scripts/write-versions.ps1
src/distribution/Info.plist
src/inc/msquic.ver

Preparing to service the release.

Increment Patch Version - v2.3.7

---

.azure/OneBranch.Package.yml
CMakeLists.txt
Cargo.toml
scripts/package-distribution.ps1
scripts/package-nuget.ps1
scripts/write-versions.ps1
src/distribution/Info.plist
src/inc/msquic.ver
version.json

Preparing to service the release.

Increment Patch Version - v2.4.6

---

src/cs/lib/msquic_generated.cs

Needed to generate dotnet for the new TTL statistics field that was added.
CI
N/A

Generate DotNet for new Statistics field (TTL)

---

src/perf/lib/SecNetPerfMain.cpp
src/test/MsQuicTests.h
src/test/bin/quic_gtest.cpp
src/test/bin/winkernel/control.cpp

Kernel mode test to call SetParam for setting execution context.
see CI
N/A

Enable Raw datapath from kernel mode test

---

.github/workflows/build-reuse-darwin-framework.yml
.github/workflows/build-reuse-unix.yml
.github/workflows/build.yml
.github/workflows/cargo.yml
.github/workflows/dotnet-test.yml
.github/workflows/stress.yml
scripts/build.ps1
scripts/build.rs

[release/2.4] Update MacOS version as macos-12 was deprecated. (#4645)

---

src/platform/unittest/external/CMakeLists.txt

Add wbemuuid dependency for external test

Add wbemuuid dependency for external test

---

.github/workflows/build-reuse-darwin-framework.yml
.github/workflows/code-coverage.yml
.github/workflows/dotnet-test.yml
.github/workflows/package-reuse-linux.yml
.github/workflows/stress.yml
.github/workflows/test.yml

Add repo var to all other ci jobs

---

src/lib.rs

This pull request includes several additions and modifications to the `src/lib.rs` file, focusing on enhancing the event handling structures and adding new event types. The most important changes include the addition of new event types, the introduction of bitfield structures for event flags, and the modification of existing event structures to use these new bitfields.
NA
TBD

Add missing event structures

---

src/test/lib/DataTest.cpp

Cherry-pick fixing of connection priority tests.
CI
N/A

Cherry-pick fixing of connection priority tests

---

.github/workflows/cargo.yml

We don't want one job failure to cancel all the others. We want to see all failures.
CI/CD
N/A

Disable Matrix Fail Fast for Cargo Action

---

.github/workflows/stress.yml

We do not need a tag explicitly binding a pool to an image if that image is the only image defined in the pool.
CI
N/A

Update override image tag for stress CI

---

.azure/OneBranch.Tests.Official.yml
.azure/OneBranch.Tests.PullRequest.yml
.github/workflows/code-coverage.yml
.github/workflows/test.yml

Follow up on PR: https://github.com/microsoft/msquic/pull/4769
Repeats the fix but for all refs.
CI
N/A

Replace all stale refs

---

.github/workflows/package-alpine-linux.yml
.github/workflows/package-linux.yml
src/cs/QuicSimpleTest/QuicHello.net8.0.csproj

[release/2.4] Delete .NET 8.0 from pipeline

---

.azure/OneBranch.Tests.Official.yml
.azure/OneBranch.Tests.PullRequest.yml
.github/workflows/code-coverage.yml
.github/workflows/stress.yml
.github/workflows/test.yml

Backport PR to remove refs to deprecated images.
CI
N/A

backport PR to remove dead refs

---

scripts/secnetperf-helpers.psm1

Add option to be able to collect cpu traces on the lab machines also
CI
N/A

Add lab cpu traces

---

docs/Release.md

Removed release/2.2 which is passed its Dec 2024 support date.
N/A
Updated

Remove Older, Unsupported Release

---

scripts/update-version.ps1
src/bin/winkernel/msquic.kernel.vcxproj
src/bin/winkernel/msquicpriv.kernel.vcxproj
src/core/core.kernel.vcxproj
src/core/precomp.h
src/manifest/manifest.kernel.vcxproj
src/nuget.config
src/perf/bin/drvmain.cpp
src/perf/bin/secnetperfdriver.kernel.vcxproj
src/perf/bin/secnetperfdriverpriv.kernel.vcxproj
src/perf/lib/perflib.kernel.vcxproj
src/platform/platform.kernel.vcxproj
src/test/bin/winkernel/msquictest.kernel.vcxproj
src/test/bin/winkernel/msquictestpriv.kernel.vcxproj
src/test/lib/precomp.h
src/test/lib/testlib.kernel.vcxproj
version.json

Support Native Compiler in OneBranch Builds backport release 2.3

---

codecov.yml

Ignore documentation files in code coverage report
CI should validate the change
N/A

Ignore documentation in code coverage

---

src/ffi/linux_bindings.rs
src/ffi/win_bindings.rs
src/ffi/wrapper.hpp

Add preview apis to generated rust code. 
NA
NA

Rust: Support preview apis in ffi generated code

---

docs/ReceiveBuffer.md

Add Quic dev focused documentation for the receive buffer component.
N/A
N/A

Receive buffer documentation

---

.github/workflows/build.yml

Related to #4856. Disabled the broken jobs for now.
CI/CD
N/A

Disable Android on 24.04

---

src/cs/lib/msquic_generated.cs
src/rs/ffi/linux_bindings.rs
src/rs/ffi/win_bindings.rs

Fixing Rust and C# issues seen after changes in https://github.com/microsoft/msquic/pull/4868

task_3717_DotNetChanges: Changes in CS files

---

.github/workflows/test.yml

Onboad Linux Release config tests for configurations that closely match official shipping package versions.
CI/CD
N/A

Add Linux Release Tests

---

.github/workflows/code-coverage.yml
scripts/run-executable.ps1

Runs the BVTs with XDP enabled too to get the additional code coverage numbers.
Automation
N/A

Add XDP Code Coverage Support

---

docs/Streams.md

Update the send buffering documentation in `docs/Streams.md` to correct how to disable internal buffering on Send.
Closes #4917

Update send buffering documentation

---

src/core/send.c

If a path is not ready yet for a challenge, `QuicSendPathChallenges` might add `QUIC_CONN_SEND_FLAG_PATH_CHALLENGE` back to the `SendFlags` immediately to queue a new round of challenges on the next send operation.
This wasn't taken into account lower in the function: the flag was interpreted as a control frame needing to be sent, and `QuicSendWriteFrames` was called needlessly.
This could trigger a debug assertion in tests (Basic/WithRebindPaddingArgs.RebindAddrPadded), causing flakiness.
Closes #4948.
C/I
N/A

Avoid calling QuicSendWriteFrames whith only the path challenge flag

---

docs/Release.md

Document Supported Architectures

---

docs/Release.md

Clear step-by-step docs for uploading a new Rust crate.
N/A
Updated

Update Release Docs for Cargo Publish

---

.github/workflows/test.yml
src/platform/platform_worker.c

The kernel tests were timing out in PRs. Apparently all other tests were already updated.
CI/CD
N/A

Increase Kernel Test Timeout to 120 Minutes

---

.github/workflows/build-reuse-win.yml
.github/workflows/build.yml
src/test/bin/quic_gtest.cpp
src/test/lib/DataTest.cpp

Internal builds are built without preview features enabled externally (i.e. in tests). Those were broken recently. This fixes them.
CI/CD
N/A

Fix non-Preview Builds

---

docs/BUILD.md

I went through the steps of cloning and building on Ubuntu, and found a few doc improvements/updates are in order.

Update build documentation

---

src/core/library.c
src/core/library.h
src/core/worker.c
src/generated/linux/platform_worker.c.clog.h
src/generated/linux/platform_worker.c.clog.h.lttng.h
src/inc/quic_platform.h
src/perf/lib/SecNetPerfMain.cpp
src/perf/lib/Tcp.cpp
src/platform/datapath_epoll.c
src/platform/datapath_kqueue.c
src/platform/datapath_raw.c
src/platform/datapath_raw_xdp_linux.c
src/platform/datapath_raw_xdp_win.c
src/platform/datapath_winuser.c
src/platform/platform_internal.h
src/platform/platform_worker.c
src/platform/unittest/DataPathTest.cpp
src/platform/unittest/main.cpp
src/test/bin/quic_gtest.cpp
src/test/lib/QuicDrill.cpp
src/tools/attack/attack.cpp
src/tools/lb/loadbalancer.cpp
src/tools/load/load.cpp
src/tools/pcp/pcp.cpp
src/tools/recvfuzz/recvfuzz.cpp

As a next step in the path for the app to control execution, we need to tease out the worker pool initialization so QUIC will be able to pass app stuff to it and customize it.
CI/CD
N/A

Refactor Platform Worker Pool Initialization

---

docs/Execution.md
docs/PreviewFeatures.md
docs/Streams.md
docs/api/QUIC_CONNECTION_EVENT.md
docs/api/QUIC_LISTENER_EVENT.md
docs/api/StreamProvideReceiveBuffers.md
src/inc/msquic.h

- Address review feedback from pull request #4960 
- Add missing events/event payload descriptions
- Add a doc for preview features
Fixes [#1795](https://github.com/microsoft/msquic/issues/1795)

Follow up to event documentation updates

---

src/platform/datapath_epoll.c

`CxPlatSocketContextInitialize` initialization did not handle failures from `CxPlatSocketContextSqeInitialize` properly. Updates the logic to handle it properly.
CI/CD
N/A

Fix Socket Context Initialize Code Paths

---

.azure/OneBranch.Package.yml
CMakeLists.txt
Cargo.toml
scripts/package-distribution.ps1
scripts/package-nuget.ps1
scripts/write-versions.ps1
src/distribution/Info.plist
src/inc/msquic.ver
src/test/lib/ApiTest.cpp
version.json

Cherry-pick test fix for down-level tests.

Fix the QUIC_HANDSHAKE_INFO Test to Allow for Future Versions to Grow Size (#5032)

---

.azure/obtemplates/build-linux.yml

Fixes a build break.
Must merge into mscodehub
N/A

Fix Recent ADO YAML Break

---

.docker/ubuntu-22.04/Dockerfile

Latest commit for Ubuntu 22.04
CI/CD
N/A

Updates the Ubuntu 22.04 Docker File Dependency

---

.azure/OneBranch.Official.yml
.azure/obtemplates/build-nuget.yml

The latest pipeline run had a few other things that needed to be cleaned up.
Needs to merge internally
N/A

A Few More ADO Clean Ups

---

.azure/obtemplates/build-nuget.yml

Trying to fix the last ADO bug.
Must merge first.
N/A

Remove quictls UWP Nuget Package Download

---

.azure/obtemplates/build-nuget.yml

Fixes a few more NuGet packaging issues in the ADO pipeline.
Must merge internally
N/A

More ADO NuGet Pipeline Fixes

---

.azure/OneBranch.Package.yml
.github/workflows/build.yml
.github/workflows/test-down-level.yml
CMakeLists.txt
Cargo.toml
scripts/build.ps1
scripts/package-distribution.ps1
scripts/package-nuget.ps1
scripts/write-versions.ps1
src/bin/winkernel/driver.c
src/core/configuration.c
src/core/listener.c
src/distribution/Info.plist
src/inc/msquic.ver
src/inc/quic_platform_winkernel.h
src/tools/forwarder/forwarder.cpp
src/tools/interopserver/InteropServer.cpp
src/tools/ip/server/quicipserver.cpp
src/tools/lb/loadbalancer.cpp
src/tools/sample/sample.c
version.json

Backport ETW silo fix (#5049) to v2.4
CI

Backport ETW silo fix to v2.4

---

.github/workflows/test-down-level.yml

Tests the latest MsQuic releases and adds recent OS platform releases to the tests.
CI/CD
N/A

Update Down Level Tests to Latest

---

.azure/OneBranch.Package.yml
CMakeLists.txt
Cargo.toml
scripts/package-distribution.ps1
scripts/package-nuget.ps1
scripts/write-versions.ps1
src/bin/winkernel/msquic.kernel.vcxproj
src/bin/winkernel/msquicpriv.kernel.vcxproj
src/distribution/Info.plist
src/inc/msquic.ver
src/perf/bin/secnetperfdriver.kernel.vcxproj
src/perf/bin/secnetperfdriverpriv.kernel.vcxproj
version.json

CP: Randomize Base Address in Kernel Projects (#5063)

---

.github/workflows/test.yml
src/tools/interop/interop.cpp

Enabled interop testing with XDP.
CI/CD
N/A

Add XDP Interop Test

---

src/core/CMakeLists.txt
src/core/crypto.c
src/inc/msquichelper.h
src/test/lib/DrillDescriptor.cpp
src/tools/attack/attack.cpp
src/tools/recvfuzz/CMakeLists.txt
src/tools/recvfuzz/recvfuzz.cpp

Lots of improvements/fixes in the receive fuzzer code.
Ran locally. CI/CD
N/A

Refactor Receive Fuzzer

---

src/perf/lib/PerfClient.cpp

On code review found that it wasn't configuring the send buffering mode correctly.
CI/CD
N/A

Fix SecNetPerf SendBuffering Config

---

.azure/OneBranch.Package.yml
CMakeLists.txt
Cargo.toml
docs/Release.md
scripts/package-distribution.ps1
scripts/package-nuget.ps1
scripts/write-versions.ps1
src/distribution/Info.plist
src/inc/msquic.ver
version.json

Updates the docs and minor version now that we forked the release/2.5 branch.
CI/CD
Updated

Forked release/2.5 Branch

---

src/inc/quic_platform_winkernel.h

Define NTDDI_VERSION in Code to workaround OneBranch issues

CP: Define NTDDI_VERSION in Code (#5152)

---

src/core/api.c
src/core/api.h
src/core/binding.c
src/core/connection.c
src/core/connection.h
src/core/quicdef.h
src/core/send.c

Cherry-pick #5107 into release/2.5.
CI/CD
N/A

CP: Resend Close Frames (#5107)

---

.github/ISSUE_TEMPLATE/bug_report.yaml

The version list in the issue template was out dated.
N/A
N/A

Update Issue Template for Latest Versions

---

.azure/OneBranch.Package.yml
CMakeLists.txt
Cargo.toml
scripts/package-distribution.ps1
scripts/package-nuget.ps1
scripts/write-versions.ps1
src/distribution/Info.plist
src/inc/msquic.ver
version.json

[2.4] Bump version to 2.4.14

---

.azure/OneBranch.Package.yml
CMakeLists.txt
Cargo.toml
scripts/package-distribution.ps1
scripts/package-nuget.ps1
scripts/write-versions.ps1
src/distribution/Info.plist
src/inc/msquic.ver
version.json

[2.5] Bump version to v2.5.2

---

src/generated/linux/storage_winuser.c.clog.h
src/generated/linux/storage_winuser.c.clog.h.lttng.h
src/platform/storage_winuser.c

Backport gamecorefixes in release/2.5

---

.azure/OneBranch.Package.yml
CMakeLists.txt
Cargo.toml
scripts/package-distribution.ps1
scripts/package-nuget.ps1
scripts/write-versions.ps1
src/distribution/Info.plist
src/inc/msquic.ver
version.json

Increase version number to v2.5.3
CI
N/A

Increase version number to v2.5.3

---

.azure/OneBranch.Package.yml
CMakeLists.txt
Cargo.toml
scripts/package-distribution.ps1
scripts/package-nuget.ps1
scripts/write-versions.ps1
src/distribution/Info.plist
src/inc/msquic.ver
version.json

Increase version number to v2.5.4
CI
N/A

Bump version to 2.5.4

---

.azure/OneBranch.Package.yml
CMakeLists.txt
Cargo.toml
scripts/package-distribution.ps1
scripts/package-nuget.ps1
scripts/write-versions.ps1
src/distribution/Info.plist
src/inc/msquic.ver
version.json

Bump MsQuic version number to 2.5.5 after the publication of v2.5.4

Bump version to 2.5.5

---

.github/dependabot.yml

Updated Docker package ecosystem configurations to ignore specific dependency versions.
CI

Modify dependabot.yml for Docker ecosystem updates

---

.azure/OneBranch.Package.yml
CMakeLists.txt
Cargo.toml
scripts/package-distribution.ps1
scripts/package-nuget.ps1
scripts/write-versions.ps1
src/distribution/Info.plist
src/inc/msquic.ver
version.json

Update version to 2.4.16
CI
N/

[2.4] Update release 2.4 version to 2.4.16

---

src/core/connection.c

Some spurious test failures show a pattern when the two peers entered a loop of sending CONNECTION_CLOSE frames to each other. This regression was introduced by #5107.
According to RFC 9000:
- When a peer sends a CONNECTION_CLOSE frame, it enters the "closing" state and should answer any incoming packet on the connection with a new CONNECTION_CLOSE frame (subject to rate limiting), to ensure the peer get the CONNECTION_CLOSE.
- When a peer receives a CONNECTION_CLOSE frame, it enters the "draining" state and should not send any more packets.
(The RFC is not explicit about what happens when a peer in the "closing" state receives a CONNECTION_CLOSE, but since it means both peers are closing the connection, it can stop sending additional CONNECTION_CLOSE).
However, #5107 was re-sending …

Do not send CONNECTION_CLOSE frames in draining state

---

scripts/build.rs
src/rs/lib.rs

Fix static link on windows.

---

submodules/CMakeLists.txt

CP: Update OpenSSL submodule configuration for macOS SDK detection
