src/core/send.c
Fixes #358. The assert was incorrectly checking for `>` instead of `>=`.
=> Fix Debug Assert in Send

src/core/binding.c
Fixing a kernel mode build warning in binding.c from static analysis.
```
##[warning]src\core\binding.c(782,0): Warning C6385: Reading invalid data from 'NewDestCid':  the readable size is '13' bytes, but '14' bytes may be read.
```
Just adds a debug assert (which has the analysis assume) for the warning.
=> Fix Binding Build Warning from Static Analysis

scripts/build.ps1, scripts/interop.ps1, scripts/spin.ps1, scripts/test.ps1
Fixes #348. Makes Linux default to OpenSSL for the PowerShell scripts.
=> Per-Platform TLS Defaults in PowerShell Scripts

src/core/lookup.c
This PR fixes a crash/assert found via a spinquic run on AZP. A received packet was received before a listener completed it's registration with a newly created binding. This resulted in the lookup being called to find a matching connection before it was fully initialized. This change modifies the assert to just check and return instead.
=> Fix Race Condition Crash

src/core/ack_tracker.c, src/core/range.c, src/core/range.h
A recent run of spinquic hit one of the asserts in QuicRangeValidate. Now that we run for an extended amount of time, it's possible to eventually generate enough packets to hit these asserts. Therefore the asserts are no longer necessary.
=> Remove QuicRangeValidate Debug Function

src/core/crypto.c, src/core/crypto.h, src/core/loss_detection.c, src/core/send.c, src/core/send.h, src/core/stream.h, src/core/stream_send.c
There are cases where calling retransmit on an outstanding packet doesn't actually result in any new data being queued up. In those scenarios, we want to make sure to still queue up a PING frame for our loss detection probes. This PR updates those code paths to appropriate return back the state indicating if data is actually going to be sent out in response to the packet being "retransmitted".
=> Queue Ping Probe on No Retransmissions Available

src/tools/ping/QuicPing.cpp, src/tools/ping/QuicPing.h
Allows the command line to modify the execution profile used for quicping.
=> Add Execution Profile Command Line Arg to QuicPing

docs/BUILD.md, docs/TEST.md
Hopefully enough to resolve #345 and resolve #347. This PR updates the build documentation to be more clean on our usage of PowerShell. For those who want to use CMake directly, it adds *some* documentation.
FYI @am11, @mman, @larseggert, @saibamen, @zhengshuxin, @wiladams (folks who commented or up voted one of the above bugs). Please let me know if you'd like something more.
=> Update Build Docs for CMake Specific Instructions

.azure/scripts/run-gtest.ps1, scripts/test.ps1
This PR adds support to the test script to disable procdump usage. I made this initially to test the assumption that procdump was the reason that Windows tests run so slow (compared to Linux); and it definitely did confirm it. I'm not sure why, but it seems from start to finish, no matter how long the exe that is run takes, procdump launch of a process takes almost a second.
=> Support NoProcDump Mode for Windows Test Script

src/test/bin/quic_gtest.cpp
Also silences a warning by updating the macro used in the test code.
=> Update to Latest Googletest Master Branch

.gitattributes
Been having merge issues because of different tools & OS being used to make changes. This should force everything to use Windows line endings.
=> Use Git Attributes File to Normal Line Endings

docs/InteropServerSetup.md, src/tools/interopserver/InteropServer.cpp
This PR adds some documentation on how to fully set up a new instance of the interop server. The Linux instructions is still partially incomplete and will be finished in a future PR.
=> Interop Server Instructions

src/tools/interopserver/InteropServer.cpp, src/tools/interopserver/InteropServer.h
Related to #388. Adds explicit error codes when calling abort so that peer's logs provide more information as to where the failure occurred.
=> Create Explicit Error Codes for Interop Server Request Failures

src/tools/interopserver/InteropServer.cpp
Fixes a bug in the interop server code that was incorrectly calling `fread`. It had the `size` and `count` parameters swapped, which resulted in the `BytesRead` always being `1`.
Fixes #388 
Fixes #179
=> Fix Bug in fread Call in Interop Server

.azure/templates/run-spinquic.yml, src/core/stream.c, src/core/stream_send.c, src/manifest/MsQuic.wprp, src/tools/spin/spinquic.cpp
Now that we support injecting hooks into the data path, let's make use of it in spinquic to add some random loss.
Also increases runtime to 10 min.
=> Add Random Loss to SpinQuic

src/core/ack_tracker.c, src/core/ack_tracker.h, src/core/connection.c, src/core/crypto.c, src/core/loss_detection.c, src/core/packet_builder.c, src/core/send.c, src/core/sent_packet_metadata.c, src/core/sent_packet_metadata.h, src/core/session.c, src/platform/tls_openssl.c, src/platform/tls_stub.c, src/tools/dbg/packet.cpp, src/tools/dbg/quictypes.h, src/tools/spin/spinquic.cpp
Fixes bugs/issues found by spinquic with now that we have random loss and address sanitizer enabled. 
- Add some debug validation to loss detection.
- Fixes a loss detection bug where a packet in the sent packet's list was getting freed, but the tail of the list was not being properly updated.
- Fixes a few leaks found by address sanitizer.
- Certain loss patterns led to the ack tracker framing ACKs over and over.
- Spinquic doesn't really need to clean up datapath hooks.
- Update Linux address sanitizer to dump objects for better debugging.
- Update Crypto to clean up any recovery state when discarding keys.
- Updated stub TLS to use randomly generated secrets for connection encryption, to prevent cross-connection packet contamination (which doesn't exist with a real TLS solution).
- …
=> Get SpinQuic Running Clean

.azure/templates/run-bvt-int.yml, .azure/templates/run-spinquic.yml
The logs are overrunning and causing problems. Disabling them in a few places (spinquic & internal test runs) for now.
=> Disable Logs in Azure Pipelines Runs

src/core/connection.c
During some spinquic runs, it seems we were getting into a state where a RETRY packet is received after a packet with an ACK frame that had already acknowledged the previously sent CRYPTO data. This caused the Crypto code to get into a state where it thinks everything was sent already (and drained from the buffer) but we still need to send.
The fix here is to reject the RETRY packet if we've already received any packet from the server.
=> Don't Accept Retry after ACK

src/core/datagram.c, src/tools/spin/spinquic.cpp
This adds new Session parameters, connection parameters, and invokes the DatagramSend API. As well, I moved all code from rand() to GetRandom() as an effort to standardize. This should address #387
=> Add SpinQuic support for DatagramSend, and other settings parameters

src/test/lib/TestStream.cpp
In StartPing, when the QUIC_SEND_FLAG_FIN flag is set and there are no bytes left, if the SteamSend completes successfully, we are racing against stream callback, which deletes the instance we are currently executing. When the loop continues, BytesToSend is read again, which is the use after free. Explicitly exiting the loop upon no data left removes the race
Closes #395
=> Fix race condition in Ping tests

.azure/scripts/run-executable.ps1, .azure/scripts/run-gtest.ps1
Apparently CDB.exe isn't installed on the public Azure Pipelines images by default, though I just opened an Issue to hopefully get it added (https://github.com/actions/virtual-environments/issues/942). Until then, let's not crash or complain.
=> Improve Output when CDB.exe is Missing

src/core/stream_send.c
If send isn't enabled, the current send request was completed, but any existing requests left in the list were leaked. Continuing will cause any requests left over to be closed as well.
Closes #408
=> Fix leak in QuicStreamSendFlush

src/core/connection.c, src/core/send.c
Spinquic was occassionally hitting an assert in send.c that indicated nothing was being framed. This ended up because we had queued an app close while we were still writing handshake packets. This caused things to get stuck/confused. The proper fix is to not queue app close until we are on 1-RTT keys. Instead, just use the transport closed which can be used at any level.
=> Don't Use App Closed until 1-RTT Keys

src/core/connection.c
In the kernel mode loopback scenario, the receive callback is delivered inline from the send thread. If the receiver then updates their worker thread (and therefor the thread they send next from) based on that thread, it creates an endless loop of updating partitions.
The fix here is to only update the partition if the path is new (i.e. not yet validated yet). I validated this with Hermes.
=> Only Change Partitions for New Paths

src/core/connection.c, src/core/path.h
A slight modification to my previous PR. Instead of using the IsPeerValid flag, we add a new flag just for partition update. This allows for the initial client path update scenario (since it's path starts as valid).
=> Allow a Single Partition Update per Path

src/core/connection.h, src/core/datagram.c, src/core/inline.c
Assert that if SendFlags for Datagram is set, that the send queue is not null. Otherwise the opposite
Should help with debugging #425
=> Add flags and queue check to QuicDatagramValidate

CMakeLists.txt
In source builds cause weird tree corruptions, and most bigger projects disallow them just to not have to worry about them
=> Disallow in-source builds

src/bin/winkernel/msquic.kernel.vcxproj, src/core/core.kernel.vcxproj, src/platform/platform.kernel.vcxproj, src/test/bin/winkernel/msquictest.kernel.vcxproj, src/test/lib/testlib.kernel.vcxproj
Apparently string pooling was causing some strings to be put in the `PAGE` section of the driver, which caused a runtime error on Xbox. From binary inspection, this change seemed to move the string to the `.data` section:
```
0:000> uf msquic!QuicPlatformInitialize;!dh msquic
msquic!QuicPlatformInitialize [E:\msquic\src\platform\platform_winkernel.c @ 115]:
...
120 00000001`4004a0b1 488d151071ffff  lea     rdx,[msquic!`string'+0x128 (00000001`400411c8)]  <==== HERE
120 00000001`4004a0b8 4533c0          xor     r8d,r8d
120 00000001`4004a0bb 488d0de698ffff  lea     rcx,[msquic!QuicPlatform+0x8 (00000001`400439a8)]
120 00000001`4004a0c2 ff15b0cfffff    call    qword ptr [msquic!_imp_BCryptOpenAlgorithmProvider (00000001`40047078)]
...
SECTION HEADER #3
.data name
29F0 virtual size
41000 …
```
=> Disable String Pooling for Kernel Mode

src/core/datagram.c
If flag isn't reset, we get in an invalid state where we are told to write a datagram, but have none to write.
Also adds validation to ensure when leaving QuicDatagramWriteFrame the datagram is valid.
Closes #425
=> Reset Datagram SendFlag when writing last datagram and out of buffer

src/core/send.c
Without removing these flags, the framing logic thinks it has data that can be sent, even though congestion control told us that we could not send certain types of frames, causing empty frames to be generated.
=> Remove flags that can't be sent during congestion control without allowance

src/bin/winkernel/msquic.kernel.vcxproj, src/core/core.kernel.vcxproj, src/platform/platform.kernel.vcxproj, src/test/bin/winkernel/msquictest.kernel.vcxproj, src/test/lib/testlib.kernel.vcxproj
Looks like a more recent WDK has been released and Azure Pipelines will be updating to it soon. Update the VS project files to not explicit specify a target version, so that it implicitly uses the latest always.
=> Don't Explicitly Target a WDK Version

src/core/packet_builder.c, src/core/send.c
A follow up to #443 this fixes a bug where the wrong `SendFlags` variable was being used when deciding what type of packet to build next. Also makes a slight refactor of the packet builder code. Moves the assert to the first point of failure, and then cleans up the previous code.
=> Fix Send Flags used for Packet Building

src/test/lib/HandshakeTest.cpp, src/test/lib/TestConnection.cpp, src/test/lib/TestHelpers.h
When using random loss in the tests (especially with high loss rates like 10%) we should wait a lot longer than normal before considering the test case failed. This updates the rest of the places that seemed to be causing occasional timeout failures.
Fixes #440
=> Tests Wait Longer with Random Loss

src/core/unittest/SpinFrame.cpp, src/platform/unittest/TlsTest.cpp, src/test/lib/ApiTest.cpp
Azure Pipelines address sanitizer runs recently started complaining about more memory leaks. Looks like they've always been there and were just now being reported.
=> Fix Newly Found Leaks

.azure/templates/run-bvt-int.yml, .azure/templates/run-bvt.yml
I've noticed AZP timing out right after the tests complete. Let's give it just a bit more time to run.
=> Increase Azure Pipelines Timeout for BVTs

src/core/library.c
Make it so the datapath can't accept any new data and cause a race with shutdown cleanup.
Replacement for #448 as this might be a simpler fix. Don't want to loose all work in 448 in case it was on the right track.
=> Move datapath shutdown to occur before connection cleanup

src/platform/storage_winkernel.c
Newest WDK has ExInitializeWorkItem deprecated
Closes #464
=> Supress deprecation warning for ExInitializeWorkItem in kernel mode

.azure/azure-pipelines.ci.yml, src/bin/linux/exports.txt, src/bin/linux/init.c, src/platform/platform_linux.c, src/platform/unittest/CMakeLists.txt, src/tools/attack/CMakeLists.txt
Fixes #460. Only defines the LTTng tracepoint once, in the library init and explicitly exports it to share with the tools/tests.
=> Workaround for LTTng Duplicate Tracepoint

.azure/azure-pipelines.ci.yml, .azure/templates/build-config-user.yml, CMakeLists.txt, scripts/build.ps1, src/bin/CMakeLists.txt, src/inc/quic_platform_winuser.h, src/platform/datapath_winuser.c, src/tools/attack/CMakeLists.txt, src/tools/ping/QuicPing.cpp
Flags needed to be added to the build. Right now we have to force override a compiler defined macro in the platform header file. Looking to see if there is a way to do this only through the command line.
Running tests is possible, but requires installing the msix file, so not extremely feasable. I'll look into this more as well. I did add a build however so we can be sure this at leasts continues to build.
Closes #436
=> Add support for building in UWP mode

.azure/azure-pipelines.ci.yml
We don't use the test or tools. Let's not add build them right now, to reduce the AZP load.
=> Build DLL only for UWP

CMakeLists.txt, src/bin/CMakeLists.txt, src/core/CMakeLists.txt, src/core/unittest/CMakeLists.txt, src/platform/CMakeLists.txt, src/platform/unittest/CMakeLists.txt, src/test/bin/CMakeLists.txt, src/test/lib/CMakeLists.txt, src/tools/attack/CMakeLists.txt, src/tools/etw/CMakeLists.txt, src/tools/etwlib/CMakeLists.txt, src/tools/interop/CMakeLists.txt, src/tools/interopserver/CMakeLists.txt, src/tools/ping/CMakeLists.txt, src/tools/post/CMakeLists.txt, src/tools/reach/CMakeLists.txt, src/tools/sample/CMakeLists.txt, src/tools/siduck/CMakeLists.txt, src/tools/spin/CMakeLists.txt, src/tools/void/CMakeLists.txt
When the solution is opened in VS or another IDE that supports folders, the projects are grouped accordingly. This makes it much easier to find the specific project you're looking for
=> Add folder support to CMake

src/core/connection.c, src/core/registration.c, src/core/registration.h, src/core/session.c
If the connection received data after the registration worker pools were free, we hit a crash. This is caused by a race between cleaning up a connection and the binding receiving data. If we wait for the connections to be fully clean before cleaning up the worker threads, the race is avoided.
Should fix #472 but needs to be tested
=> Wait for all connections to be freed during registration close

scripts/interop.ps1, src/tools/interop/interop.cpp, src/tools/interop/interop.h
Adds a few improvements to the interop client tool:
- Allows specifying the test case letters, such as `-test:VHDC` in addition to the numerical equivalents.
- Doesn't use `h3-*` ALPNs for datapath tests as they are incorrect and cause weird test results.
- Adds a `-serial` option to run all tests serially. This improves results when either the network conditions don't allow for the parallel test cases or the server itself is not very good with parallel requests.
=> Adds Various Improvements to Interop Tool

src/inc/quic_trace_lttng.h, src/platform/datapath_linux.c, src/platform/datapath_winuser.c
No notifications were occuring when a datapath thread was created or shutdown, which is very helpful to debug thread race conditions
=> Add trace logging to datapath thread

.azure/scripts/run-executable.ps1, scripts/interop.ps1
Updates the PowerShell scripts with minor improvements:
- Spinquic script passes version parameter.
- Run exe script puts name for test failures, instead of just "Run"
=> Minor Script Improvements

src/core/connection.c, src/core/connection.h, src/tools/dbg/quictypes.h
Fixes #485. Now it correctly sends and validates the retry source CID.
=> Correctly Send & Validate Retry Source CID

.azure/templates/run-spinquic.yml, scripts/spin.ps1, src/core/library.c, src/core/session.c, src/tools/spin/spinquic.cpp
Without this, we race cleanup.
Should fix #482
=> Clean up worker pools before closing any leftover quic sessions

.github/CONTRIBUTING.md, README.md
We're now opening up some of the repo to external contribution! We're allowing all but the core and Windows kernel mode code. This adds new documentation on the guidelines for external contributions.
=> New External Contribution Rules

src/platform/selfsign_openssl.c
After commit https://github.com/microsoft/msquic/commit/2bf91b3ff5b9b9668e7ae1f2f2588cbc8e228c9c when trying to compile on linux using the Release config with gcc 9.3.0 you get the following error:
```
In function ‘strncat’,
inlined from ‘QuicPlatFreeSelfSignedCert’ at /home/tomxmm0/Documents/Dev/msquic/src/platform/selfsign_openssl.c:389:5:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:136:10: error: ‘__builtin___strncat_chk’ specified bound depends on the length of the source argument [-Werror=stringop-overflow=]
136 |   return __builtin___strncat_chk (__dest, __src, __len, __bos (__dest));
|          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/tomxmm0/Documents/Dev/msquic/src/platform/selfsign_openssl.c: In function ‘QuicPlatFreeSelfSignedCert’: …
```
=> Change strncat to strcat in QuicPlatFreeSelfSignedCert to fix compiling on linux

.dockerignore, Dockerfile, run_endpoint.sh
This builds a docker image for the quic-network-simulator (https://github.com/marten-seemann/quic-network-simulator/).
What's missing is a `run_endpoint.sh` script that configures the client and server binary for the various QNS tests. Since I'm not super-familiar with the options these things take, I'll let @nibanks or someone else add that script...
First step for #462.
=> Build QNS interop image

src/inc/msquic_linux.h, src/platform/datapath_linux.c, src/platform/platform_linux.c, src/platform/unittest/DataPathTest.cpp, src/test/lib/ApiTest.cpp, src/test/lib/DataTest.cpp, src/test/lib/EventTest.cpp, src/test/lib/HandshakeTest.cpp, src/test/lib/QuicDrill.cpp, src/tools/ping/QuicPing.cpp
**There is no functionality change in this PR**
This way we don't rely on the internal sockaddr structure ordering. On
darwin for example, si_family is not the first member of sockaddr. There's no
guarantee this structure will stay the same, and the proper way to do
this is to just use a sockaddr as the first member, which is guaranteed
to be the first member of both sockaddr_in and sockaddr_in6.
Note: quicping doesn't build currently.
```
/home/max/msquic/src/tools/ping/QuicPing.cpp: In function ‘void ParseClientCommand(int, char**)’:
/home/max/msquic/src/tools/ping/QuicPing.cpp:307:48: error: ‘QUIC_ADDR’ {aka ‘union QUIC_ADDR’} has no member named ‘si_family’
case 4: PingConfig.Client.RemoteIpAddr.si_family = AF_INET; break;
^~~~~~~~~
/home/max/msquic/src/tools/ping/QuicPing.cpp:308:48: …
```
=> [Linux] Move from si_family in the union to sockaddr;

.azure/scripts/publish-performance-results.ps1, .azure/templates/publish-performance.yml
Like the other secure token, these do not get decrypted during PRs, so its safe.
=> Use library to provide deployment key for GitHub

.azure/templates/publish-performance.yml, .azure/templates/run-performance.yml
It adds over 6 minutes to the build, and we don't publish anything we're not planning on directly pushing anyway
=> Skip component governance detection for perf results

CMakeLists.txt
Makes it so a clean build does not need to occur if ETW methods change.
=> Fix cmake dependencies for ETW generation

src/core/binding.c
Recent version refactoring broke the logic that builds up version negotiation packets. This PR fixes that logic.
=> Fix Version Negotiation Packet

src/platform/CMakeLists.txt, src/platform/datapath_linux.c, src/platform/platform_linux.c
TEMP_FAILURE_RETRY is a glibc extension, but the spec is very well defined, and easy to recreate manually. 
pthread attribute setting for affinity doesn't exist, so only use the attribute if glibc is defined, otherwise set the thread affinity after creating the thread.
The logging disable change in CMake is needed because I couldn't figure out how to install LTTng on Alpine. 
Fixes #477
=> Fix builds on non glibc based linux platforms

Dockerfile
When using docker to build I was hitting an interactive prompt. According to https://techoverflow.net/2019/05/18/how-to-fix-configuring-tzdata-interactive-input-when-building-docker-images/ I just disable that.
=> Update DockerFile to Install Noninteractive

src/core/api.c, src/core/stream_send.c, src/tools/interopserver/InteropServer.cpp
Fixes #522.
To make things simpler for the app, this updates the stream send API to allow for zero-length sends, so long as they also have the FIN flag set. Tested with the quicinterop server.
=> Allow Zero-Length Stream Sends with FIN Flag

.azure/azure-pipelines.ci.yml, .azure/templates/publish-performance.yml, .azure/templates/run-bvt-int.yml, .azure/templates/run-bvt.yml, .azure/templates/run-performance-int.yml, .azure/templates/run-performance.yml, .azure/templates/run-quicinterop.yml, .azure/templates/run-spinquic.yml
Adds more configurations to testing, though we might end up removing all stub testing. It's interesting to know the results, but not practically helpful really. Also decided to default all our templates to x64 architecture.
=> Expand Perf Testing

CMakeLists.txt
FindLTTngUST doesn't exist before 3.6.
I don't want to completely remove support for Ubuntu 16.04, so this will make it so that a build will work, just that logging will not.
Closes #528
=> Force disable logging for CMake versions older then 3.6

src/platform/tls_openssl.c
One step closer for #530. This PR improves perf for the header key, though it's still using a loop; but at least the cipher context is preallocated, and reused for each call.
=> Perf Improvement for OpenSSL Header Key

src/tools/spin/spinquic.cpp
In release mode, datapath hooks can't be enabled. Because we want to support debug spinquic with release libmsquic, we want to allow the failure rather then conditional compile.
Closes #532
=> Allow datapath hook failure happen in spinquic

.azure/templates/run-performance-int.yml, .azure/templates/run-performance.yml, scripts/performance.ps1
This adds a number of improvements to the perf script:
- New parameters for controlling behavior, generally to be used for local execution.
- Get perf output from the stream instead of the connection (since it's more accurate since it doesn't include the handshake).
- Pretty up the output.
=> Improvements to the Perf Script

.azure/azure-pipelines.perf.yml, .azure/azure-pipelines.pgo.yml, .azure/templates/build-config-user.yml, scripts/performance.ps1
This adds support for a new customizable performance pipeline: https://dev.azure.com/ms/msquic/_build?definitionId=356&_a=summary
You can run it in one of three modes:
- **Normal** - Just builds and runs performance tests for Release.
- **PGO** - Enables PGO for build and collects PGO counts during tests.
- **Record** - Records performance traces (ETW stackwalks) for the tests.
=> Customizable Performance Pipeline

src/core/packet_builder.c, src/core/send.c, src/core/sent_packet_metadata.c, src/core/sent_packet_metadata.h
Fixes #156.
The current send metadata struct could leak stream references if it failed to send (generally only will happen in OOM scenarios). This makes sure all that is cleaned up at the end, no matter what.
=> Fixes Leaks on Send Path

CMakeLists.txt, src/platform/CMakeLists.txt
This adds QUIC_PLATFORM Darwin option, and sets -DQUIC_PLATFORM_DARWIN. Also fixes a typo which had `--std=c++17`, instead of `-std=c++17`.  Adds -std=c++11 which was necessary for me to build the gtest suite. Currently this has everything building for debug as well, which I will address in a later commit as a flag. 
The next PR will have introduce the platform code, and then the datapath code.
=> Add cmake changes necessary for Darwin builds

CMakeLists.txt
These were accidentally added in #552 unconditionally, where they will cause large perf regressions in release mode.
=> Fix accidentally added no-inline and no-omit-frame-pointer flags on unix

src/core/connection.c, src/core/send.c, src/test/MsQuicTests.h, src/test/bin/quic_gtest.cpp, src/test/bin/winkernel/control.cpp, src/test/lib/HandshakeTest.cpp, src/test/lib/TestAbstractionLayer.h, src/test/lib/TestHelpers.h
Adds a new test case for timing out path validation. Also fixes an issue in the product code where we weren't correctly probing on the new and active path when there is a migration.
=> Migration Tests and Fixes

scripts/performance.ps1, src/platform/datapath_winuser.c
- Uses a consistent UDP tuple for the tests, so RSS always puts things on the same NUMA node.
- Uses UDP send batching (up to 7) to improve throughput.
=> Improve Loopback Perf Results

scripts/performance.ps1
The WPR profile XML wasn't collecting everything necessary to view the full stacks in WPA. Now it does.
=> Fix WPR Profile XML

scripts/performance.ps1, src/tools/ping/Client.cpp, src/tools/ping/PingConnection.cpp, src/tools/ping/PingConnection.h, src/tools/ping/QuicPing.cpp, src/tools/ping/QuicPing.h, src/tools/ping/Server.cpp
By doing this, performance tests can be cleaner to run, as they can explicitly state how many connections are expected. Also adds parity with the client
=> Allow QuicPing server to specify number of connections allowed before shutting down

scripts/performance.ps1
When looking at a trace for some of the latest perf runs I noticed some CPU from send buffering. Let's disable that in our automated tests to see how much benefit we get.
Results from latest perf run with these changes:
Stub (i.e. no crypto):
```
Median: 14931989 kbps (+64.34%)
Master: 9085911 kbps
```
Schannel:
```
Median: 5818387 kbps (+23.08%)
Master: 4727407 kbps
```
FYI, @maolson-msft & @pravb here is the cost of send buffering. It's a lot more than I expected.
=> Disable Send Buffering for Perf

.azure/templates/create-package.yml, .azure/templates/download-artifacts.yml, .azure/templates/publish-performance.yml
Build.TempDirectory is not a variable, and just gets used as the folder name. Agent.TempDirectory is unique per test
=> Fix azure build temp directory

scripts/prepare-machine.ps1
please verify this with a fresh WSL2 (I'm using Ubuntu18.04 LTS)
=> buildessential and not buildessentials

scripts/performance-helper.psm1, scripts/performance.ps1
Timeout added to local run (configurable)
Local matcher now prints error on failure
Release mode as default
Automatically configure tls to match system if not set
Validate sets for tls and arch to enable tab completion
=> Fix up issues in the PS Performance script

src/inc/quic_trace.h, src/test/lib/TestHelpers.h
Fixes for getting kernel mode tests running for debug builds. They now all run/pass locally. Next step is to get it automated.
=> Fix Kernel Mode Tests on Debug

src/inc/msquic.h, src/inc/msquic_linux.h
I ran into a case where I just copied msquic.h and msquic_winuser.h into a basic c++ project, and the headers failed to compile because it wasn't looking in the local directory.
=> Switch msquic.h to use local header includes rather then system header includes

src/inc/quic_trace.h, src/platform/datapath_winkernel.c, src/test/lib/TestHelpers.h
When looking at the performance traces, we found that the receive callbacks were taking a significant amount of time in a spinlock and it came down to MsQuic not using static callbacks.
=> Static WSK Receive Callbacks

scripts/performance.ps1
Without this, during PGO runs the PGO data has the same name, and gets put into the same location on azure, overwriting the prior test
=> Make perf results be placed into a path including configuration.

src/core/connection.c, src/core/listener.c, src/core/stream.c
When looking through performance traces, QPC (QueryPerformanceCounter on Windows) seemed to take an unacceptable amount of time for every event indicated up to the app. These checks have never resulted in any actionable bug, and even if we did see the event, it'd be very difficult to say the scheduler wasn't to blame here. So, it seems best just to remove these.
=> Remove QPC from Indicate Event Functions

src/core/crypto.c, src/core/recv_buffer.c, src/core/recv_buffer.h, src/core/settings.c, src/core/stream.c, src/core/worker.c, src/core/worker.h
One more (fairly large) performance bottleneck was the allocation of the stream's receive buffer. This change improves the initial allocation of said buffer, when the default initial size is used (which is the majority case), by using a per-worker/proc pool allocator for the buffer.
=> Pool Allocator for Default Stream Recv Buffer

src/core/range.c, src/core/range.h
Allocating range objects in stream initialization was another significant performance hit. This adds support to include the initial allocation of subranges for each range object along with the range object itself.
=> Preallocate Initial Subranges

.azure/templates/download-artifacts.yml, .azure/templates/run-bvt.yml, .azure/templates/upload-artifacts.yml, docs/InteropServerSetup.md, scripts/build.ps1, scripts/install-build-artifacts.ps1, scripts/interop.ps1, scripts/performance.ps1, scripts/prepare-package.ps1, scripts/spin.ps1, scripts/test.ps1, src/bin/winkernel/msquic.kernel.vcxproj, src/test/bin/winkernel/msquictest.kernel.vcxproj, src/tools/dbg/dbg.vcxproj
Some refactoring/shuffling of build artifacts so that downloading them can be a bit more efficient. Most of the change just consists of moving the actual build (binary) artifacts into a bin folder and renaming 'drop' to 'bin'.
=> Refactors Build Artifacts

src/core/timer_wheel.c
Fixes the loop in the timer wheel clean up code that logs connection pointer leaks. Big thanks to @tadiparthi who found and proposed this fix.
Fixes #619.
=> Fix Timer Wheel Leak Detection

src/tools/ip/client/quicipclient.cpp, src/tools/ip/quicip.h
Refactors the IP tool/helper API a bit. Allows for stubbing out logging. Allows for using private registration and function table.
=> Refactor IP Tool/Helper

src/core/recv_buffer.c
Bug in uninitialize found while trying to debug #627. 
Actual bug found in 2nd commit.
Closes #627
=> Fix preallocated buffer accidental deallocations in RecvBuffer functions.

.azure/templates/merge-publish-coverage.yml
pathToSources causes source files to be correctly looked up.
=> Make code coverage have correct file locations on CI

.azure/templates/run-spinquic.yml, scripts/run-executable.ps1, scripts/run-gtest.ps1
This updates code coverage to only look at the core code for now, which is what I'm most interested in (for the time being). Also, it enables some logging for spinquic to get some code coverage in the logging/tracing code paths. From my local execution, this brings coverage up to 80%. Not a bad start!
=> Code Coverage Core Only

src/inc/quic_trace.h, src/test/lib/ApiTest.cpp
Fixes two things when I investigated a test failure on the latest master run:
- Logs were cut too short, resulting in unhelpful log messages
- The test code didn't wait long enough between ConnectionStart calls.
=> Fix Some Kernel Mode Test Issues

src/test/lib/DataTest.cpp
Fixes a bug I saw in a test failure. The code didn't wait enough and ended up failing. Ideally, we'd have some better way to do this than just sleep and hope...
=> Fix server disconnect failure

README.md
Explicitly point to the master branch, instead of just the most recent build.
=> Use Master Branch for Readme Shields

src/core/datagram.c, src/core/stream_send.c, src/inc/msquic.h, src/test/lib/DataTest.cpp, src/test/lib/TestConnection.cpp, src/test/lib/TestConnection.h, src/test/lib/TestStream.cpp, src/test/lib/TestStream.h, src/tools/spin/spinquic.cpp
This adds a new flag for `StreamSend` that allows the app to send data and start the stream in a single API call. The reduces the complexity/overhead of streams in the scenarios where a stream is used to send a single complete message. All the app need do is call `StreamOpen` to allocate a stream (cheap, as it uses a lookaside list / pool allocator) and then call `StreamSend` with both the start and fin flags, along with the payload.
Also updates the tests and spinquic to exercise the code paths.
=> Send and Start Stream in One API Call

.azure/azure-pipelines.perf.yml, .azure/templates/run-performance.yml, scripts/performance-helper.psm1, scripts/performance.ps1, src/core/quicdef.h
Perf testing was seeing that we were hitting stream flow control rate limiting, causing instabilities in perf results. Increasing the ratio helps solve this issue by hitting that flow control limit much less often.
Also updates the perf CI runner to allow grabbing logs for remote tests.
=> Increase Receive Buffer Drain Ratio

src/core/connection.c, src/core/connection.h, src/core/loss_detection.c, src/core/path.c, src/core/quicdef.h
Updates the initial RTT value and usage to match the latest loss recovery spec. The PTO is still ~1 second after the first packet, so practically things are unchanged.
For the specific spec change, see https://github.com/quicwg/base-drafts/pull/3525/files
=> Updates Initial RTT Usage to Latest Spec

src/core/binding.c, src/core/library.c, src/tools/spin/spinquic.cpp
- Updates spinquic to get parameters randomly now.
- Rework a binding code path where the `else` was pointless because it was after a `return`.
Related to #634.
=> More Code Coverage

CMakeLists.txt, src/bin/winkernel/driver.c, src/core/library.c, src/core/sent_packet_metadata.c, src/core/worker.c, src/inc/quic_platform.h, src/inc/quic_platform_linux.h, src/inc/quic_platform_winkernel.h, src/inc/quic_platform_winuser.h, src/perf/bin/drvmain.cpp, src/perf/lib/PerfHelpers.h, src/platform/datapath_linux.c, src/platform/datapath_winkernel.c, src/platform/datapath_winuser.c, src/platform/platform_linux.c, src/test/bin/winkernel/driver.cpp
Adds tags for different allocations. Currently only used in kernel mode and only for lookaside list allocations (since that is where we have a leak).
=> Add Pool Tags

src/core/connection.c, src/core/connection.h, src/core/stream.c, src/core/stream.h, src/core/stream_set.c, src/core/stream_set.h
More info to debug #664.
Updates the connection & stream set to (in debug mode) track all allocated streams and assert if any are left over when the connection is cleaned up.
=> Catch Stream Leaks Earlier

.azure/templates/run-spinquic.yml, scripts/run-executable.ps1, src/core/ack_tracker.c, src/core/ack_tracker.h, src/core/api.c, src/core/binding.c, src/core/connection.c, src/core/connection.h, src/core/crypto.c, src/core/crypto_tls.c, src/core/frame.c, src/core/library.c, src/core/library.h, src/core/packet_space.c, src/core/range.c, src/core/range.h, src/core/recv_buffer.c, src/core/recv_buffer.h, src/core/registration.c, src/core/stream.c, src/core/unittest/FrameTest.cpp, src/core/unittest/SpinFrame.cpp
`QuicRangeInitialize` can no longer fail. This allows for a certain amount of cleanup for all the callers, resulting in some of them not being able to fail either. This results in even smaller cleanup code if those things fail to initialize (allocation failures). It should actually increase (by a small amount) code coverage because there are fewer lines that are never hit because of initialization/allocation failure.
=> Connection Initialization Cleanup

src/core/ack_tracker.c, src/core/ack_tracker.h, src/core/connection.c, src/core/frame.c, src/inc/quic_datapath.h, src/manifest/clog.sidecar, src/platform/datapath_linux.c, src/platform/datapath_winkernel.c, src/platform/datapath_winuser.c
This updates the core code to track received ECN counts and return them in the ACK frame (if received). It does not add any platform data path support, nor tests for the feature. FYI @larseggert.
First step for https://github.com/microsoft/msquic/issues/559
=> Track Received ECN Counts

src/core/ack_tracker.c, src/core/binding.c, src/core/packet_builder.c, src/inc/quic_datapath.h, src/platform/datapath_linux.c, src/platform/datapath_winkernel.c, src/platform/datapath_winuser.c, src/platform/unittest/DataPathTest.cpp, src/test/lib/QuicDrill.cpp, src/tools/attack/attack.cpp
Adds an abstraction layer to allow for a specific ECN marking to be sent on a send context. Also fixes a bug @larseggert pointed out where I had flipped the values of two ECN types.
Another step towards #559.
=> ECN Send Path Abstraction

CMakeLists.txt
Under Linux, openssl and clog were not built in the out-of-tree build directory, but in the source directory. This PR fixes that.
For other platforms, other pieces might still be built in-tree rather than out of tree. Someone else should check that. Basically, if `git clean -fdx --dry-run` and `git submodule foreach git clean -fdx --dry-run` show that a whole bunch of files would be removed, there are probably out-of-tree build issues.
Also see the `TODO`: I think the `make clean` step can be removed, too.
Finally, as a side effect, this seems to fix building with `ninja` as a generator.
=> Out of tree building fixes

CMakeLists.txt
* Define some more variables to avoid repetition.
* Factor out the common parts.
* Avoid building a bunch of unnecessary components.
* Don't create makedepend files (they are created in source; problematic.)
This also has the nice side effect of cutting build time roughly in half.
=> Refactor the openssl build.

src/inc/msquic.hpp, src/perf/bin/drvmain.cpp, src/perf/lib/PerfHelpers.h, src/perf/lib/ThroughputClient.cpp, src/perf/lib/quicmain.cpp, src/test/bin/winkernel/driver.cpp, src/test/lib/ApiTest.cpp, src/test/lib/DataTest.cpp, src/test/lib/DatagramTest.cpp, src/test/lib/EventTest.cpp, src/test/lib/HandshakeTest.cpp, src/test/lib/TestHelpers.h, src/test/lib/TestStream.cpp, src/test/lib/TestStream.h
By default, even in kernel mode, new will immediately call the constructor, before you even have a chance to check for null. nothrow new checks for null before calling the constructor, so the checks are actually valid.
Only needed to happen in the perf and test libs that are ran in kernel mode.
We will need to be sure this happens for all kernel mode allocations in the future.
=> Switch all C++ new in kernel mode to nothrow new

.azure/azure-pipelines.ci.yml, scripts/log.ps1, scripts/ping.ps1, scripts/run-executable.ps1, src/platform/tls_schannel.c, src/platform/unittest/TlsTest.cpp
The TLS alert buffer was being provided to Schannel incorrectly, causing the alert to always be zero.
A new TLS test was introduced to the platform unittests to cover this as well.
Adds a script to make it easier to run quicping.exe for repro and debugging purposes.
Fixes #255
=> Fix Schannel TLS alerts not being read correctly.

.azure/azure-pipelines.ci.yml, src/core/unittest/CMakeLists.txt, src/platform/datapath_linux.c, src/platform/unittest/CMakeLists.txt, src/platform/unittest/DataPathTest.cpp, src/test/bin/CMakeLists.txt
**Not ready for merging yet!** I started the PR so that folks could take a look and for the CI pipeline to kick in, to tell me if I broke the Windows build.
This set of patches makes msquic send ECT(0)-marked packets. It also extracts the ECN information from received packets, counts them per packet space, and uses those counters to send ACK frames with ECN information.
There is currently no logic for any ECN validation, and therefore no support for disabling ECN when that validation would fail.
There is also a (minor?) issue (see the `FIXME`) that causes ECN marks on 0-RTT packets to not be counted.
=> Add ECN support to the Linux datapath 

CMakeLists.txt
When these checkers are enabled, there are *tons* of issues flagged. Many definitely should be suppressed, but I wasn't sure, which.
=> Add option to run clang-tidy and cppcheck

scripts/RemoteTests.json
With the sidechannel exit, remote tests should work again.
=> Add RPS into perf test suite

scripts/run_endpoint.sh
* Create logs in the right place (/logs not /log)
* Unbuffer clog2text_lttng.
I only tested the "handshake" test case. With these changes, quic.log is now
always created. But there is still a race condition of some sort, because in
most of the runs, all it contains is something like "Decoded 0 in
00:00:00.0018700". In some runs, however, almost 50K of log are written.
=> Some improvements to docker interop logging

src/platform/tls_schannel.c
The resumption tests on Schannel take 2 seconds longer than the other TLS platforms because there's no clear indication when the resumption ticket has been received, so it retries until timeout.
This fixes that retry loop by setting a boolean when the test can be reasonably certain the resumption ticket has arrived.
Fixes #571
=> Fix schannel resumption tests to run faster.

src/tools/interopserver/InteropServer.cpp, src/tools/interopserver/InteropServer.h
Integrates the server side of the siduck protocol into quicinterop: https://tools.ietf.org/html/draft-pardue-quic-siduck-00
=> Add siduck handler to interop server

src/core/connection.c
We haven't seen it again, but when it does happen, having the assert here will make it much easier to detect the source. When it happens on the other side of the queue, its hard to tell what the source actually is. Related to #698.
=> Add assertions to enqueue connection operation to help solve 698

src/core/stream_send.c
Fixes #719.
The edge condition of queuing another send **after** shutting down the stream would result in the `PostedBytes` never getting incremented for that send request, but it was decremented when canceled. The fix is to pass an additional flag to indicate whether the request had been posted already or not, and only undo the PostedBytes change if it had.
Thanks @larseggert for finding this.
=> Fix Underflow for PostedBytes

src/inc/quic_platform_winkernel.h
If called before, it will fail on multiple numa node systems, as the ideal processor can only be assigned to the correct node.
=> Set processor affinity before processor ideal proc in kernel mode

.azure/azure-pipelines-int.ci.yml
They've been failing ever since #676 was merged because the filter was missing.
=> Filter out failing ECT tests on internal pipeline

src/platform/datapath_linux.c
=> Fix Datagram buffer resulting in a null deref in an OOM scenario

.github/codeql/codeql-config.yml, .github/workflows/codeql-analysis.yml, src/core/unittest/SpinFrame.cpp, src/core/unittest/VarIntTest.cpp, src/platform/unittest/TlsTest.cpp
This PR enables some additional CodeQL checks, and has fixes for some of the nits that were found this way.
Some others remain: https://github.com/larseggert/msquic/security/code-scanning?query=tool%3ACodeQL+is%3Aopen+ref%3Arefs%2Fheads%2Fmore-codeql
=> More codeql

.azure/azure-pipelines.ci.yml, .azure/templates/run-qns.yml
- Only pull the implementations used for the test (cc @marten-seemann)
- Remove `neqo` as it always times out, and add `quic-go` to master CI
=> Integrate Latest QNS Pull Option

.azure/azure-pipelines-int.ci.yml, .azure/azure-pipelines.ci.yml, src/platform/datapath_winuser.c
Next step for #559. Implements the ECN send/recv code in Windows user mode. Removes the filters for the associated tests.
=> Windows Usermode Datapath ECN Implementation

src/manifest/clog.sidecar, src/platform/tls_openssl.c, src/platform/tls_schannel.c, src/platform/tls_stub.c
I fixes the TLS created events to give more context, and in the schannel case, properly pass the right argument (not null).
@chgray, I updated the strings and rand clog in dev mode for all the affected TLS configurations, but it seems clog only updated stub for some reason.
=> Fix Bad TLS Events

src/inc/quic_platform_winuser.h, src/platform/platform_winuser.c
We were only matching the group, but not the specific processor in the group. Use a mask to find the specific processor to match.
=> Fix Incorrect numa node initialization with 2 numa nodes but 1 group

src/platform/datapath_winkernel.c
Fixes a bug in the kernel data path where the incorrect IRP size was being used.
=> Use Correct Size for Irp

src/test/lib/DataTest.cpp
It seems to be a race between the stream handle being set in the connection callback, and the test context being finished.
Fixes #537  (I think this was the actual issue there)
=> Fix Abortive Stream Tests leaking a stream on the remote side.

src/core/timer_wheel.c, src/core/worker.c, src/inc/quic_platform_winkernel.h, src/perf/bin/drvmain.cpp
In the rare case that creating and configuring a thread on kernel mode failed, it wasn't properly cleaning everything up.
=> Fix Thread Create Failure Crash

src/test/lib/DataTest.cpp
We've been running into a stream leak with AbortiveShutdown tests, caused by certain tests doing things in slightly different order. The remote stream is never used, so we can just close it in Stream shutdown complete
=> Close remote stream in stream shutdown for abortive tests

scripts/performance-helper.psm1, scripts/performance.ps1
Matrix values were incorrect, and defaults were always being used. Throughput this didn't matter, RPS it did matter a lot. Also increases the test timeout, some of the RPS tests take longer to finish
=> Fix issues with perf test matrix

src/core/connection.c, src/core/connection.h, src/manifest/clog.sidecar
Fixes #788 by throwing away connections that don't have valid initial packets.
=> Throw Away Connections from Bad Initial Packets

src/core/packet.c, src/manifest/MsQuicEtw.man, src/manifest/clog.sidecar, src/tools/etw/quicetw.h, src/tools/etw/trace.c
The packet number is almost never valid for dropped packets (because it's before decryption) and when it is valid, it doesn't really help. It's just wasted space.
=> Remove Packet Number from Packet Drop Events

src/perf/lib/RpsClient.cpp
=> Limit number of cores in RPS Client test, fix RPS thread out of range bug

scripts/log.ps1, scripts/run_endpoint.sh
They need to be explicitly enabled with a context, so this enables them in the 2 places we grab logs from.
=> Add vpid and vtid to lttng logs

src/core/connection.c, src/core/frame.h, src/core/quicdef.h, src/tools/etw/quicetw.h
Updates to the spec in https://github.com/quicwg/base-drafts/commit/71a1ff22aef4a3f948b032447dd5bb36e7314e18 require a connection to be closed on too many failed packet decryptions globally across a connection.
The lowest limit was chosen, at 2^23.5 (rounded down)
Closes #557
Still need to add tests
=> Close connection on AEAD integrity failure

src/core/library.c
Fixes #808, a bug where `(uint8_t)(256)` results in us setting `PartitionCount` to zero.
=> Fix Wrap Around Bug with Partition Count

src/core/connection.c
We have a leak, but its hard to detect where. By asserting that its already been cleaned up, we should be able to debug a bit easier
=> Clean up packet space in QuicConnFree

src/core/sent_packet_metadata.h, src/core/stream_send.c
This causes everything to be aligned correctly, removing potential bugs and performance penalties for unaligned reads and writes.
This commit currently loses 1 byte per packet, but gains 4 per frame. However, with a future optimization for StreamOffset, we can actually lose 4 bytes per frame, which will be a net win.
Solves #806 and many more silent packed bugs.
=> Pack QUIC_SENT_PACKET_METADATA manually to remove the need for pragma pack

src/platform/datapath_winuser.c
No longer use current processor index to allocate receive datagram buffers, but the current proc context's index.
Also fixed up a number of things that assumed 1 byte processor index.
=> Update Windows Usermode Datapath to Use Processor Context Index

.azure/azure-pipelines.ci.yml
Fixes #825. Reduces the number of test cases run on OpenSSL to reduce total execution time.
=> Reduce Test Cases for OpenSSL on Windows

src/core/binding.c, src/core/binding.h, src/core/connection.h, src/core/lookup.c, src/core/lookup.h
Without the lock, CID cleanup would race with a new packet from the binding.
Closes #476
=> Remove SourceCid entry from cid list under lock.

.azure/templates/run-qns.yml
Fixes the run-qns.yml pipeline Wireshark build errors.
=> Add Missing Wireshark Build Dependency

src/core/registration.c, src/inc/quic_platform.h, src/inc/quic_platform_linux.h, src/inc/quic_platform_winkernel.h, src/inc/quic_platform_winuser.h, src/perf/lib/HpsClient.cpp, src/platform/platform_linux.c, src/tools/attack/attack.cpp
Recent perf tests seem to indicate setting ideal processor actually hurts performance. This change refactors how we use that thread config flag, and removes it for default configurations.
=> Refactor Ideal Processor Usage

src/platform/datapath_winkernel.c
It can result in less contention and slightly higher performance.
=> Always copy DPC buffers in kernel mode

scripts/RemoteTests.json, scripts/performance.ps1
Not sure why these were not working when originally designed, but they seem to work perfectly now. This will reduce required setup on the perf machines.
=> Always use self signed certificates for remote performance tests.

scripts/run_endpoint.sh, src/tools/interop/interop.cpp
These diagnostic prints are only used in QNS.
=> Add diagnostic prints to quicinterop

Dockerfile, scripts/run_endpoint.sh
**FIXME:** There doesn't seem to be a way to specify to use `/certs/ca.pem` for certificate verification by the `quicinterop` client?
=> Use certs provided by interop framework

src/inc/msquic.h
Currently, the struct is perfectly aligned and has no padding anywhere.
=> Reorder QUIC_SETTINGS to remove all padding

scripts/performance-helper.psm1
I think we're hitting some timeouts, but we have no way of currently knowing.
=> Print how long each test run took

src/core/binding.c, src/core/binding.h, src/core/connection.c, src/core/packet_builder.c, src/inc/quic_crypt.h
Apparently, even though the IV is 12 bytes, BCrypt will read/write the buffer up to the block size (!) so we need to make sure we allocate enough space on the stack.
=> Work Around BCrypt IV Issues

src/core/binding.c, src/core/connection.c, src/core/packet.c, src/manifest/clog.sidecar
- Fixes an issue where the server would only send a Version Negotiation packet if it matching V1's CID requirements. V2 might have different requirements...
- Some other general clean up of code, logging and comments.
=> Version Negotiation Cleanup

src/core/binding.c, src/core/quicdef.h, src/inc/quic_versions.h
- Fixes some of the logic around calls/usage of the `QuicIsVersionSupported` function. It no longer includes the version negotiation. Updates the one caller where it needed that to be included. All the rest were bugs.
- Updates the logic to validate the minimum UDP length before sending a VN packet.
=> More Version Negotiation Improvements

src/core/connection.c, src/core/frame.h, src/core/inline.c, src/platform/inline.c
Before, anything not a few small errors was counted. Now, only things that are explicitly protocol errors are counted as protocol errors.
Closes #889
=> Properly count protocol errors in perf counters.

src/platform/tls_openssl.c
Fixes #900. Updates the OpenSSL code to reallocate the output TLS buffer if we don't have enough room. Note, the same bug exists in each TLS implementation, but the fixes will require specific code changes for each. Additionally, if it weren't for this specific interop failure, I'm not sure if we would fix this problem; at least not in the same way.
=> Reallocate TLS Buffer (OpenSSL)

scripts/run_endpoint.sh
Recent change in the interop runner broke our hardcoded server name
=> Don't Hardcode Interop Server Name

src/perf/lib/HpsClient.cpp
Makes it easier to test performance issues caused by contention
=> Add argument to quicperf to allow selecting number of threads for HPS tests

.azure/templates/build-config-user.yml, CMakeLists.txt
Binary size on windows is down to 2.7MB.
=> Remove a lot of options from openssl to decrease binary size

src/core/connection.c, src/inc/msquic.h, src/test/lib/EventTest.cpp, src/test/lib/TestConnection.cpp, src/tools/interop/interop.cpp, src/tools/ping/PingConnection.cpp, src/tools/sample/sample.cpp, src/tools/spin/spinquic.cpp
The interop client support of 0-RTT and Resumption was broken when the refactor to remove the Session layer was completed.
This change adds that support back.
=> Fix interop client to support resumption tickets and zeroRTT.

src/platform/tls_openssl.c
Previously all Hash abstraction layer actions with OpenSSL were taking all CPU in HPS tests. The new code seems to fix that.
=> Fix OpenSSL Hash/HMAC Performance

.azure/templates/create-package.yml, .azure/templates/download-artifacts.yml, .azure/templates/upload-artifacts.yml
Because of IIS, bin is a disallowed folder, so rename to artifacts so files can be properly downloaded.
https://github.com/microsoft/azure-pipelines-tasks/issues/13322
=> Rename bin artifact name to artifacts

scripts/RemoteTests.json, src/core/connection.c, src/inc/quic_platform_linux.h, src/inc/quic_platform_winkernel.h, src/inc/quic_platform_winuser.h, src/perf/lib/HpsClient.cpp, src/perf/lib/RpsClient.cpp, src/perf/lib/ThroughputClient.cpp
We were not setting this before, causing low performance for download performance tests. 
Should fix #917
=> Properly set thread affinity for throughput tests

src/core/crypto.c, src/core/crypto_tls.c, src/core/datagram.c, src/core/listener.c, src/manifest/clog.sidecar, src/platform/tls_mitls.c, src/platform/tls_openssl.c, src/platform/tls_schannel.c, src/platform/tls_stub.c, src/test/lib/EventTest.cpp
Updates the QUIC crypto TLS processing code to extract QUIC TP along with ALPN and SNI when pre-processing the client hello. This has a few affects:
1. Improves performance (amount dependent on TLS) because we are already reading the memory and have cache locality. We might as well do it with the rest.
2. Allows for the transport parameters to be fully available **before** the listener accept callback, which allows the listener to make its accept/reject decision based on the initial transport parameter values.
3. Allows for the server's outgoing transport parameters to be decided **based on** the clients TP now. This is useful for extension negotiation.
=> Server Prefetch QUIC TP

src/inc/quic_platform_winkernel.h
Need to use the macro instead of the ps function
=> Fix Zw*InformationThread calls to use correct handle

src/core/connection.c, src/perf/lib/PerfServer.cpp, src/tools/ping/PingConnection.cpp
Recent change to prefetch QUIC TP introduced a bug in the negotiation of the disable 1-RTT encryption extension. Server ended up disabling encryption even if the client didn't also negotiate this. This PR updates the code paths to handle the server side setting it's option after the client's TPs have already been received.
=> Fix Negotiation of Disable 1-RTT Encryption

src/tools/interopserver/InteropServer.cpp
Seems I forgot to update this tool twice in a row... Thanks @larseggert for pointing this out.
=> Add Missing ALPNs to Interop Server

scripts/performance-helper.psm1, src/perf/lib/HpsClient.cpp, src/perf/lib/RpsClient.cpp, src/perf/lib/ThroughputClient.cpp
0 size for upload or download doesn't make sense, as that case is handled by RPS, and you get no data (other then a single useless latency number) out of in in tput.
Then make 0 for all 3 tests an error, so 0's don't accidentally get uploaded to the server.
Also makes the test runner error if a 0 is received
=> Disallow 0 sizes in tput tests, make 0 in all perf tests an error

src/perf/bin/drvmain.cpp
There was a tight race window where a cancellation could happen after the request is already completed.
=> Reorder performance read cancellation request in kernel mode

CMakeLists.txt
Older gcc versions throw warnings (which will be treated as errors due to
-Werror) of the form "dereferencing type-punned pointer will break
strict-aliasing rules" in a bunch of places in the code. Since newer gcc
versions no longer do so, it seems safe to suppress these warnings.
=> Add -Wno-strict-aliasing for gcc earlier than 7.0

src/core/quicdef.h, src/core/send_buffer.c
In high BDP scenarios (e.g. 60+ ms RTT and 2+ Gbps links), tests showed that the calculation for ISB (ideal send buffer, or how much send data to keep queued) was resulting in the connection becoming application limited. This was caused by the way we tried to limit the number of these indications up to the app. We ended up not indicating the latest values because they hadn't reached "the threshold" yet.
This changes how we calculate and use the indication threshold. A 1.5x growth rate is used for calculating the thresholds and the ISB is rounded up to the next threshold so there is never underestimation.
=> Refactor ISB Indications

src/platform/datapath_winuser.c
Updates to the correct public name. See [here](https://docs.microsoft.com/en-us/windows/win32/winsock/winsock-ioctls#sio_cpu_affinity-opcode-setting-i-t3).
=> Update Per-Processor Socket IOCTL to Correct Name

src/platform/tls_mitls.c
The struct being used was the same size with the same alignment, so wasn't noticable, but still as potential for a bug in the future
=> Fix incorrect alloc size for mitls HP Key

.editorconfig
Removes static and private field namings, along with recommending var.
=> Update editorconfig to remove non helpful style guides

src/core/cid.h, src/core/connection.c, src/platform/platform_winuser.c, src/platform/tls_mitls.c, src/platform/unittest/TlsTest.cpp
Only in debug mode, but will both make debugging easier, and will help make sure all the pool tags are correct.
Found a few bugs in which pool tags were used, so those are fixed.
=> Add support for embedding pull tags in windows user mode alloc

.editorconfig, src/tools/wpa/DataModel/QuicConnection.cs, src/tools/wpa/DataModel/QuicObjectSet.cs, src/tools/wpa/DataModel/QuicState.cs, src/tools/wpa/DataModel/QuicWorker.cs, src/tools/wpa/QuicEventCooker.cs, src/tools/wpa/QuicEventDataSource.csproj
It's much better to suppress the compiler styles we don't want in the csproj rather then the editorconfig, as that way the project stays independent of the repo. Otherwise if for some reason we move the plugin source or build without the repo, it wouldn't build.
Also fixes a few missing readonly variables, and 1 missing public Debug.Assert.
Also converts some things public things that could be IReadOnlyLists to IReadOnlyLists.
=> A few more WPA code quality cleanups

src/tools/wpa/DataModel/QuicEventPayload.cs, src/tools/wpa/QuicEventDataSource.csproj
I had forgetten that the unmanaged generic restriction allows sizeof(T). So switching to that rather then including an extra dependency, as less deps is better for plugins
=> Remove Unsafe library in favor of unsafe block.

src/tools/wpa/DataModel/ETW/QuicEtwEvent.cs
EventData() would allocate a new array and copy. This instead just uses the DataStart and length directly to create a span to the backing memory directly.
The copy code can be seen here, so we're not going Out of Bounds or anything.
https://github.com/microsoft/perfview/blob/master/src/TraceEvent/TraceEvent.cs#L1258
=> Switch to using EventData backing memory directly

src/core/library.c, src/core/library.h, src/core/lookup.c, src/manifest/MsQuicEtw.man, src/manifest/clog.sidecar, src/plugins/wpa/DataModel/QuicEvent.cs, src/tools/etw/quicetw.h
Fixes #935. Adds a new event to indicate if the library is currently sending stateless retry packets in response to new connection attempts or not.
=> Add LibrarySendRetryStateUpdated Event

.azure/templates/build-config-user.yml
The old cache might be a bit corrupted, so bumpting the version number to force it to rebuild on the next master build
=> Force an update to the OpenSSL cache.

scripts/run-executable.ps1
This would cause the wait task to fail when looking for the process
=> Fix StartExecutable returning multiple values under AppVerifier

.azure/azure-pipelines.perf.yml, .azure/templates/run-performance.yml, scripts/RemoteTests.json, scripts/performance-helper.psm1, scripts/performance.ps1
Closes #949. Once we can stabilize the rests of the tests, we should make those failures as well.
=> Fail build if throughput up test has a 5% or more performance drop

src/plugins/wpa/DataModel/QuicEventPayload.cs, src/plugins/wpacmd/QuicEtw.csproj
I'm fine not adding the code analysis plugin to this, which is the more aggressive one, but since we have this enabled in the plugin we should enable it in the cmd program. It should be a lot less invasive here, as we're the caller, so we can check everything. Also not enabling warnings as errors here, although we can if you want.
Also switches to null! to bypass the nullable warning in Payload rather then pragma. They do the same thing in execution, but the null! is clearer in intent.
=> Turn on null checks in wpacmd

src/inc/CMakeLists.txt
In VS 16.8, C11 mode is broken including Windows.h. We want to skip this mode setting on Windows, and only enable it on linux
=> Fix C11 mode being set on windows.

src/perf/lib/quicmain.cpp
When `test` is used, at least in Ubuntu 18.04 LTS, the line 111-116 failed to parse the `argv` and get the input value.
=> Fix the key string for TestName

docs/BUILD.md, scripts/install-powershell-docker.sh, scripts/prepare-machine.ps1
This enables using .NET 5 as well as .NET Core 3.1. Docs have been updated to note this
=> Use clog 0.1.9

.azure/templates/run-qns.yml
Default is Ubuntu 16.04, which has Python 3.5, which isn't supported anymore by a dependency of the QNS runner. Just update to the latest to solve the issue
=> Make QNS templates use latest ubuntu image

.azure/azure-pipelines.wanperf.yml, .azure/templates/build-config-user.yml, .azure/templates/build-config-winkernel.yml, .azure/templates/run-wanperf.yml, scripts/emulated-performance.ps1, scripts/prepare-machine.ps1
- Adds a new wanperf pipeline to manually run wanperf on AZP machines.
- Improves the build pipelines to get only the necessary submodules.
- Fixes a few 'condition' issues with build pipeline yamls.
=> WanPerf Pipeline

docs/BUILD.md, scripts/install-powershell-docker.sh, scripts/prepare-machine.ps1
This enables using .NET 5 as well as .NET Core 3.1. Docs have been updated to note this
=> Use clog 0.1.9 (#1050)

CMakeLists.txt, src/inc/CMakeLists.txt, src/inc/quic_platform_winkernel.h, src/inc/quic_platform_winuser.h, src/inc/quic_trace.h
A few changes to macro string and vararg expansion, but the build still works in both conforming and non conforming mode. Necessary for future proofing when MSVC defaults to the conforming preprocessor in a few years
=> Fix windows build to build with conformant preprocessor

.azure/azure-pipelines.ci.yml
Just runs the tests for now. Next steps include uploading/persisting the results on mainline (like other perf tests) and then adding regression prevention.
=> Add WanPerf to CI

src/core/congestion_control.c
In low bandwidth/small-bottleneck-queue scenarios, perf is pretty bad because we never reduce CWND below initial window size. This fixes the "congestion event" code path to use the same min as "persistent congestion event" (which is what the spec says too).
=> Use the Same CWND Min for Congestion Events

src/core/congestion_control.c
=> Use the Same CWND Min for Congestion Events (#1066)

.azure/templates/build-config-user.yml
The CI setup is now fixed, but the build caches are incorrect. Bump the number to force a rebuild
=> Bump openssl cache number

.azure/templates/build-config-user.yml
The CI setup is now fixed, but the build caches are incorrect. Bump the number to force a rebuild.
Cherry picked from main
=> Bump openssl cache number (#1069)

.azure/azure-pipelines.ci.yml, CMakeLists.txt, src/platform/tls_openssl.c
* Support OpenSSL on Win32 and Arm windows platforms
* A bit of imported target adjustments
* Add openssl x86 and arm64 builds
* Fix target properties
Cherry-Picked from main to build for other platforms in release.
=> Support OpenSSL on Win32 and Arm windows platforms (#1061)

src/core/ack_tracker.c, src/core/ack_tracker.h, src/core/connection.c
Fix #1077. Include packet processing time in ACK delay (and therefor not in RTT measurement) by grabbing `Now()` before we process the frames instead of after.
=> Don't Include Packet Processing Time in RTT

src/test/lib/TestConnection.cpp, src/test/lib/TestStream.cpp
If the stream in FromConnectionHandle returns null, that was never checked, and a bugcheck would occur.
Also fixes a memory leak in FromConnectionHandle when an OOM occurs.
=> Fix nullptr deref in test stream creation on connection failure.

scripts/emulated-performance.ps1, scripts/log.ps1, scripts/run-executable.ps1, scripts/run-gtest.ps1, scripts/update-sidecar.ps1
Removes the extra directory level for logging. It's unnecessary, IMO.
=> Replace Output Directory with Path

scripts/emulated-performance.ps1
Adds `netput.exe` support to our WAN perf script.
Currently, netput is an unencrypted TCP app that doesn't quite produce an apples to apples comparison. My short term goal will be to add TLS encryption support to netput. My long term goal will be to produce a cross-platform TLS/TCP platform datapath abstraction layer to use for more accurate (secured) TCP performance comparisons.
=> TCP WAN Perf Support via netput

scripts/install-powershell-docker.sh, scripts/prepare-machine.ps1, scripts/update-sidecar.ps1, src/inc/quic_driver_helpers.h, src/manifest/clog.sidecar
Removes both the macro definition and the user code line for each trace. Makes it so file is half the number of lines, and updates to the caller variables will not require a sidecar update
=> Update CLOG to clean up sidecar

src/test/lib/DataTest.cpp, src/test/lib/TestConnection.cpp, src/test/lib/TestConnection.h
Fixes #1100. Add a new event to wait for the client to be deleted to avoid race condition.
=> Wait on Separate Client Deleted Event

.azure/azure-pipelines.ci.yml, .azure/templates/post-process-performance.yml, scripts/performance-helper.psm1, scripts/performance.ps1
Currently, all performance data gets uploaded to a database, and then displayed using PowerBi. The PowerBi dashboard is problematic, as is  adding anything new to the database. This setup will make storing arbitrary data easier, especially across branches.
This PR adds a new post perf step, that will grab all the perf results from each run, and merge them together. It does not currently publish to the new perf branch, but it will check that the configuration for doing that is correct.
=> Move perf tracking to branch on repo

scripts/prepare-machine.ps1
Adds a fallback in case the primary source goes down (again).
=> NASM Mirror as Fallback

.github/workflows/codeql-analysis.yml
> 1 issue was detected with this workflow: git checkout HEAD^2 is no longer
> necessary. Please remove this step as Code Scanning recommends analyzing the
> merge commit for best results.
=> Update CodeQL per the GitHub notice, which said:

.azure/azure-pipelines.ci.yml
Will mean that getting to testing happens quicker, which should be a good 10-15 minute speedup in the pipeline
=> Split release and debug into separate builds on AZP

.azure/azure-pipelines.ci.yml
They were using debug, when they should be depending on release. Sometimes this would work, but other times not.
=> Fix interop runner using the incorrect builds

.azure/templates/run-wanperf.yml, .azure/templates/upload-test-artifacts.yml
Logs folder should only be for failure cases, which allows scripting the failures
=> Move wanperf artifacts to separate log folder

scripts/download-failures.ps1
Requires an AuthKey to work in AZP, but simple to use otherwise.
Closes #293
=> Add a script to download all failures and related binaries for a specific build

.azure/azure-pipelines.ci.yml
interop depends on it, when it wasn't getting built previously in this block
=> Add mitls release to release build configuration

src/core/configuration.c, src/core/crypto.c, src/core/crypto.h, src/inc/quic_tls.h, src/platform/tls_mitls.c, src/platform/tls_openssl.c, src/platform/tls_schannel.c, src/platform/tls_stub.c, src/platform/unittest/TlsTest.cpp, src/tools/attack/packet_writer.cpp
Moves the callback functions from per-connection to per-secconfig.
=> Refactor TLS Callback Abstraction Layer

src/tools/sample/sample.cpp
Fixes #1138. Makes the sample use draft-29 by default for now.
=> Make Sample Work by Default

scripts/RemoteTests.json, scripts/performance-helper.psm1, scripts/performance.ps1
This removes a lot of what was generic about the remotes, and instead moves remote to a common root context.
This makes new tests much easier to add, especially once we get the full matrix RPS
=> Cleanup perf scripts

src/inc/quic_platform_winkernel.h, src/platform/storage_winkernel.c, src/platform/tls_schannel.c
Fixes an issue when user mode threads are used to call into kernel MsQuic code.
=> Replace NtClose with ZwClose

src/tools/sample/sample.cpp
For a lot of people working at the protocol level, theyre not used to working with certificates. This adds a bit of docs on how to create test certificates for the sample to make things easier to learn.
=> Add some documentation to sample about certificates

scripts/performance-helper.psm1, scripts/performance.ps1
Copy-Items is very slow over WMI, so use a file share to copy the files with robocopy.
=> Support using SMB to copy performance artifacts

scripts/update-sidecar.ps1, src/manifest/MsQuicEtw.man, src/manifest/clog.sidecar, src/platform/datapath_linux.c, src/platform/datapath_winkernel.c, src/platform/datapath_winuser.c, src/tools/etw/trace.c
Now that the datapath include TCP, it makes little sense to use `[ udp]` as the log prefix.
=> Rename Datapath Log Prefix

msquic.kernel.sln, scripts/performance-helper.psm1, scripts/run-gtest.ps1, src/perf/bin/appmain.cpp, src/perf/bin/drvmain.cpp, src/perf/bin/quicperfdriver.kernel.vcxproj, src/perf/bin/quicperfdriverpriv.kernel.vcxproj, src/test/bin/quic_gtest.cpp
Changing the name makes symbols not interfere between executable and driver, and we need a version that links into shipping msquic for internel tests
=> Rename quicperf driver to quicperfdrv, add private instance

src/inc/quic_platform.h, src/inc/quic_platform_dispatch.h, src/inc/quic_platform_linux.h, src/inc/quic_platform_winuser.h, src/platform/inline.c, src/platform/platform_linux.c
Previously, just malloc was being used. Switches the allocation to both be inlined, and to use a pool allocator.
On Windows, calling CxPlatPoolFree after CxPlatPoolUninitalize will result in a memory leak (assuming the pool still has memory), however in Linux it will crash. However, both of these are bugs, so I don't believe the difference will matter.
=> Make pool allocators on linux actually use pool

src/platform/datapath_winuser.c
With the change to cxplat, the casing was messed up.
=> Fix casing of datapath threads

src/inc/msquic_linux.h, src/platform/datapath_linux.c
Will make high level wrappers much easier to implement. Closes #404 
Note that this is an ABI breaking change, so cannot be done as part of a 1.x release.
=> Switch linux to using windows values for address family

.azure/azure-pipelines.wanperf.yml, .azure/templates/run-wanperf.yml, scripts/emulated-performance.ps1, src/perf/lib/PerfServer.cpp, src/perf/lib/PerfServer.h, src/perf/lib/Tcp.cpp, src/perf/lib/Tcp.h, src/perf/lib/ThroughputClient.cpp, src/perf/lib/ThroughputClient.h, src/platform/datapath_winuser.c
Adds the ability to abort a stream to the TCP logic. This is required for "timed` performance testing, which is what wanperf uses. Also fixes a few other TCP bugs found while debugging WAN perf.
=> TCP Perf: Support Abort Stream

scripts/emulated-performance.ps1, src/perf/bin/appmain.cpp, src/perf/bin/drvmain.cpp, src/perf/lib/PerfHelpers.h, src/perf/lib/ThroughputClient.cpp, src/perf/lib/ThroughputClient.h, src/perf/lib/quicmain.cpp
It seems sometime TCP was getting hung during periodic perf test run. This makes sure to exit each test case after a maximum amount of time (duration + 5 second).
=> Add MaxRuntime Support to QuicPerf

src/core/connection.c, src/core/crypto.c, src/inc/msquic.h, src/inc/quic_tls.h, src/manifest/clog.sidecar, src/platform/tls_mitls.c, src/platform/tls_openssl.c, src/platform/tls_schannel.c, src/platform/tls_stub.c, src/platform/unittest/TlsTest.cpp
Exposes the Schannel TLS feature to do "deferred certificate validation" and exposes those results to the app.
=> Deferred Certificate Validation Support

scripts/prepare-machine.ps1
MSBuild spits out a bunch of warnings when submodules are missing. By removing submodules, this issue is avoided.
=> Remove unused submodules from kernel build

src/platform/unittest/TlsTest.cpp
There are 6 fields, but only 4 initializers, which means TicketKey and AsyncHandler were never initialized.
=> Fix missing field initializer in TlsTest

.azure/azure-pipelines.ci.yml, src/core/connection.c, src/core/crypto.c, src/inc/msquic.h, src/inc/quic_tls.h, src/manifest/clog.sidecar, src/platform/tls_mitls.c, src/platform/tls_openssl.c, src/platform/tls_schannel.c, src/platform/tls_stub.c, src/platform/unittest/TlsTest.cpp, src/test/lib/HandshakeTest.cpp
Now MsQuic only has one event that can be used by the app for multiple purposes. The new flags were slightly refactored as well.
Fixes #1063.
=> Refactor Certificate Received Code Paths

src/inc/msquic.hpp, src/test/lib/HandshakeTest.cpp
Increases the chance of the random loss test scenarios of passing by decreasing the initial RTT estimate. This results in initial retransmits happening earlier, and therefore increasing the total number of transmits that happen in the timeout period.
=> Improve Random Loss Test Cases

.azure/azure-pipelines.perf.yml, scripts/RemoteTests.json
Adds a new perf test that uses few connections and parallel requests (that should not max out CPU) in an attempt to calculate reasonable latency numbers.
=> RPS Latency Test Case

src/test/lib/DataTest.cpp
ConnState wasn't getting deleted on failure of the TEST_FALSE because they returned prematurely.
=> Fix Test Code Leak on Failure

src/test/lib/TestStream.h
According to the C spec, even if length is 0, arguments to memset or memcpy must NOT be null. My WSL build has a hardened runtime, which causes these uses to spit out a runtime error.
=> Fix calling memset or memcpy with 0 length and null pointer

src/platform/tls_stub.c
Since for now, they cid's are always less then the stateless key size, juse use the cid as the stateless key. Not secure at all, but will make stub not fail tests anymore.
=> Fix stub tls stateless key generation

src/core/lookup.c
They are normally disabled, and they were using the wrong variables, which makes it harder to enable when needed for debugging
=> Fix lookup debug helpers to use correct variables

src/core/connection.c, src/core/connection.h, src/core/library.c, src/core/library.h, src/core/registration.c, src/core/registration.h, src/inc/quic_platform_winkernel.h, src/inc/quic_platform_winuser.h, src/plugins/dbg/quictypes.h
Updates the recently refactored CXPLAT_TEL_ASSERT to make sure it doesn't crash in release mode, just log.
=> CXPLAT_TEL_ASSERT Log Only

src/core/stream.c, src/inc/msquic.h, src/test/lib/ApiTest.cpp
Closes #1247. Adds a new flag for stream start that shuts down a stream that fails to start.
=> New Stream Start Flag for Shutdown on Failure

src/core/inline.c, src/core/library.c, src/core/library.h, src/core/timer_wheel.c, src/core/timer_wheel.h, src/core/worker.c, src/inc/quic_platform_linux.h, src/platform/inline.c
Periodically (currently hard coded to once ever 30 seconds) the library will snap shot the performance counters. Then it can compare the new snap shot to the previous values and have some heuristics to alert the system that something bad might be happening.
=> Periodically Snap-shot Performance Counters

src/core/crypto.c, src/core/unittest/TicketTest.cpp, src/manifest/clog.sidecar
Adds test cases which stress bounds-checking on resumption ticket parsing.
This PR largely addresses #1219
=> Add more bad-case testing of Resumption Tickets

docs/BUILD.md
Add Perl into `Additional Requirements` list for folks who want to build it on Windows with no schannel support / or with openssl explicitly.
=> Windows build with openssl option requires perl

src/inc/msquic_posix.h, src/platform/unittest/CMakeLists.txt, src/platform/unittest/Platform.cpp, src/platform/unittest/PlatformTest.cpp
QuicAddrToString has two issues:
1. Addr->Ip.sa_family is either QUIC_ADDRESS_FAMILY_INET or QUIC_ADDRESS_FAMILY_INET6. Passing it directly to `inet_ntop()` does not work on platforms where QUIC_ADDRESS_FAMILY_INET6 differs from AF_INET6.
2. The underlying socket structures are:
```c
struct sockaddr_in {
sa_family_t    sin_family; /* address family: AF_INET */
in_port_t      sin_port;   /* port in network byte order */
struct in_addr sin_addr;   /* internet address */
};
struct sockaddr_in6 {
sa_family_t     sin6_family;   /* AF_INET6 */
in_port_t       sin6_port;     /* port number */
uint32_t        sin6_flowinfo; /* IPv6 flow information */
struct in6_addr sin6_addr;     /* IPv6 address */
uint32_t        sin6_scope_id; /* Scope ID (new in 2.4) */
};
```
since the v6 has flowinfo, …
=> fix posix QuicAddrToString

src/platform/datapath_kqueue.c
I'm getting following error when trying to build squick on 10.15.
```
[ 31%] Building C object src/platform/CMakeFiles/platform.dir/datapath_kqueue.c.o
cd /Users/furt/github/wfurt-msquic/build/macos/x64_openssl/src/platform && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -DCX_PLATFORM_DARWIN -DQUIC_DISABLE_0RTT_TESTS -DQUIC_DISABLE_CLIENT_CERT_TESTS -DQUIC_DISABLE_RESUMPTION -DQUIC_EVENTS_STUB -DQUIC_LOGS_STUB -DVER_BUILD_ID=0 -DVER_SUFFIX=-private -D_GNU_SOURCE -I/Users/furt/github/wfurt-msquic/src/inc -isystem /Users/furt/github/wfurt-msquic/build/macos/x64_openssl/openssl/include  -Og -ggdb3 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk   -fms-extensions -fPIC …
```
=> fix compilation on macOS with XCode 11.5

src/core/crypto.c
Its possible a bad app will send the parameter when a connection either hasn't been started, or hasn't received anything back from the server. Instead of using a DBG assert, use a TEL assert so this will get entered into the logs
=> Switch assert for validation pending in validation complete to a TEL assert

src/platform/platform_posix.c
When you call pthread_cond_wait, the mutex and condition variable become linked together. This means that signaling the condition while holding the variable results in increased performance.
In addition, the scheduler can be smarter, as it knows that signaling the variable can never wake up a waiting thread, only the unlock can.
Finally, if a thread were to get preempted between the unlock and the signal, and a spurious wakeup were to occur, this could result in the condition variable being freed before the signal can be fired.
By firing the condition while holding the lock, all of these issues can be avoided.
=> Signal condition variable in CxPlatEventSet while holding lock

scripts/prepare-machine.ps1
`IsWindows` is not defined within the default PS.
=> prepare-machine: Detect default PS and warn dev to install the latest

src/platform/datapath_epoll.c, src/platform/datapath_kqueue.c
The synchronous cases can sometimes occur, theyre likely rare but still probably good to handle.
kqueue doesn't give a special event type for socket error, but does give a recvmsg with an error in that case.
I want to do some double checking that this works, but initial testing looks like it does.
=> Add unreachable support to datapath_kqueue, add synchronous case to datapath_epoll

src/platform/datapath_kqueue.c
As macOS doesn't support sockets spread across multiple threads, we shouldn't hard affinitize the datapath thread, and instead let the scheduler handle this correctly.
=> Don't affinitize datapath threads on macOS

scripts/log.ps1
By default, destroy will ensure all trace data has been finalized before returning. When cancelling, we don't need this behavior, so pass the no wait flag, which massively reduces the amount of time needed for logging.
Closes #679
=> Use no wait flag when cancelling lttng

src/core/loss_detection.c, src/core/loss_detection.h, src/core/packet_builder.c, src/core/path.c
See https://github.com/quicwg/base-drafts/issues/4830 for more details about the issue. This ensures that if we get unblocked from amplification protection logic, we trigger loss detection immediately (if necessary) instead of queuing it up, so that we can send lost packets first (and not application payload).
=> Loss Detection Immediately

CMakeLists.txt
Older versions of CMake don't allow setting folders on interface targets. They don't show up in VS anyway, so theyre not necessary.
Replaces #1264
=> Remove OpenSSL interface folder in build

src/platform/datapath_kqueue.c
Was originally done in #1279 as a similar change was needed on epoll, but it broke. I found the break, which was also a bug in 1279 which I fixed there as well.
=> Switch kqueue to not have all clients locked to core 0, and use proper proc contexts

src/platform/datapath_winkernel.c
It was only ever written to, never read, so let's just get rid of it. It will cause cross-processor access anyways, so this might improve perf.
=> Remove Unnecessary Outstanding Send Counter

scripts/merge-darwin.ps1
Apple recommends shipping universal binaries on macOS, and actually require it if shipping to store. The easiest way to do this is post build. This adds a script that will merge all artifact binaries that can then be used and shipped.
Not currently hooked into azure, as this requires we build both platforms with the same tls provider, and arm64 openssl builds have issues there. I did test this locally, and got universal binaries that worked.
Eventually, this is likely where we would also hook in the macOS signing, as this is the stage to do it.
=> Add script to merge macos binaries

src/core/congestion_control.c
Reduces the max pacing burst size to 1/4 CWND, instead of 1/2. Initial testing seems to indicate this helps the small bottleneck buffer WAN perf tests.
=> Reduce Max Pacing Window

src/core/ack_tracker.c, src/core/connection.c, src/core/connection.h, src/core/crypto_tls.c, src/core/frame.c, src/core/frame.h, src/core/transport_params.h, src/core/unittest/SpinFrame.cpp, src/inc/quic_platform_winkernel.h, src/inc/quic_platform_winuser.h, src/inc/quic_sal_stub.h, src/manifest/clog.sidecar
First part of #929. Implements https://tools.ietf.org/html/draft-iyengar-quic-delayed-ack. Supports receiving the new ACK_FREQUENCY frame but never sends it currently.
=> Initial ACK Frequency Support

src/core/connection.c, src/core/frame.c, src/core/frame.h, src/core/sent_packet_metadata.h, src/core/unittest/SpinFrame.cpp, src/core/unittest/main.h, src/manifest/clog.sidecar, src/plugins/dbg/quictypes.h
Fixes #1313. The encoding is actually a variable length integer, not a simple byte. Up until the ACK_FREQUENCY frame, the assumption held, but now that we've added support for that, it no longer holds and breaks interop.
=> Fix Frame Type Encoding Issues

.azure/templates/build-config-user.yml, CMakeLists.txt, scripts/performance-helper.psm1
1.1 is going to be easier to get certification for.
There still needs to be work done on macos, because of M1 issues, I'll look into that.
=> Switch to OpenSSL 1.1 quic branch

src/core/quicdef.h, src/perf/lib/PerfServer.h, src/platform/datapath_winkernel.c, src/platform/datapath_winuser.c
Previously, we had our batch counts high. Reducing batching count caused a 200% increase in user mode Throughput download perf, and a 150% increase in kernel mode RPS pert. Both of those scenarios were lower then they should have been, and this change solves both of those issues.
=> Reduce batching counts for sends

.azure/azure-pipelines.ci.yml, src/platform/tls_schannel.c
By default, Schannel wasn't actually using encrypted session tickets for resumption. That causes the session ticket key stuff not to work. This fixes that by configuring Schannel to always use them when doing resumption.
=> Configure Schannel to Always Use Session Tickets for Resumption

src/tools/interop/interop.cpp
Before the global index was used, which defaulted to -1
Closes #1330
=> Fix interop reading out of range when running all tests

src/tools/interop/interop.cpp
Cherry-Picked from main. Required due to an AZP update.
=> Fix interop reading out of range when running all tests (#1331)

CMakeLists.txt, src/platform/platform_posix.c
Make the CMake build if no flags are set build for native platform. Doesn't currently affect pwsh builds.
Make rosetta builds not all throw a FRE assertion.
Closes #1338 mostly. Missing pwsh current system support, but that will need a lot more work.
=> Fix issues with M1 mac build and running.

src/inc/quic_platform_posix.h, src/test/bin/quic_gtest.cpp
most likely just compiler differences. 
note that build from`pwsh` creates x64 binaries
```
PS /Users/furt/github/wfurt-msquic> uname -a
Darwin Tomass-MacBook-Pro.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101 x86_64
PS /Users/furt/github/wfurt-msquic> uname -m
x86_64
furt@Tomass-MacBook-Pro wfurt-msquic % file /Users/furt/github/wfurt-msquic/artifacts/bin/macos/x64_Debug_openssl/msquiccoretest
/Users/furt/github/wfurt-msquic/artifacts/bin/macos/x64_Debug_openssl/msquiccoretest: Mach-O 64-bit executable x86_64
```
this is described here: https://gitlab.kitware.com/cmake/cmake/-/issues/20989 
tests mostly pass
```
[----------] Global test environment tear-down
[==========] 1008 tests from 25 test suites ran. (206205 ms …
```
=> essential fixes to build on Silicon Mac

src/tools/ip/server/quicipserver.cpp
The quicipserver tool now prints out the usage arguments when supplied with no args.
Previously the ``PrintUsage()`` function was unused.
```bash
$ ./quicipserver 
Failed to load configuration from args!
```
```
$ ./quicipserver 
quicip runs a public IP lookup server.
Usage:
quicipserver.exe -selfsign or -cert_hash:<...> [and -cert_store:<...> | -machine] or (-cert_file:<...> and -key_file:<...>)
```
=> quicipserver now prints out usage information when supplied with incorrect args.

src/core/binding.c, src/core/binding.h, src/core/packet_builder.c, src/core/packet_builder.h, src/core/send.c, src/inc/msquicp.h, src/platform/datapath_epoll.c, src/platform/datapath_kqueue.c, src/platform/datapath_winkernel.c, src/platform/datapath_winuser.c, src/platform/pcp.c, src/platform/unittest/DataPathTest.cpp, src/test/lib/QuicDrill.cpp, src/test/lib/TestHelpers.h, src/tools/attack/attack.cpp, src/tools/spin/spinquic.cpp
The objects were renamed a while ago, but not the variables.
=> Rename SendContext and Datagram from datpath to SendData and Buffer

src/platform/datapath_epoll.c
For throughput tests, 43 is a magic number. Its 64,500 bytes, which is the largest UDP datagram able to be sent with a 1500 MTU. With a smaller batch size, we're not going to receive a full server send in 1 go, causing us to get behind. With a larger batch size, we can potentially grab a packet out of the next datagram send, causing send and receives to get out of sync with datagram boundaries. At 43, we pretty much run in lockstep, which results in the best performance
RPS should not be affected, we're not increasing the value enough to cause over allocations. Also, each packet is its own allocation, so underused packets are just used again without freeing and reallocating
=> Switch to 43 packet receive batch size

.azure/templates/build-config-user.yml, .gitmodules
OpenSSL just published new security update for 1.1.1. This consumes the quictls fork version.
=> Update to Latest quictls Branch

src/core/stream.c
Fixes an issue where the stream SHUTDOWN_COMPLETE event is incorrectly delivered while the app is still draining received data (in the graceful shutdown scenario).
Fixes #1384.
Opened #1383 to track improving the test coverage in this area.
=> Delay Stream SHUTDOWN_COMPLETE Event While Data Pending

scripts/build.ps1
Theres no direct flag in powershell to detect which architecture is being used. Use uname to get the processor, and if it shows up as x86_64 check to see if we're running in translated mode.
Works on an M1 mac. CI as that is running native on Intel, that will test the native intel case. Native arm powershell does not exist yet, but when it does that case is handled as well.
This also let me test the merge script. It worked, successfully merged all binaries, which ran tests on both platforms. Afterwards, I copies just the shared object file into the individual platform folders, and ran those tests as well, which succeeded. So an x86 only app can access the x86 portion of a universal msquic library binary, and same with arm.
=> Properly detect arm current platform for macos pwsh builds

src/platform/datapath_epoll.c
Seeing an issue where sometimes the client receives the servers port, which causes issues in the unit test. Not setting SO_REUSEPORT for client side might avoid this issue. Right now we don't have a great way to guarantee this, but it might help.
Might fix #1389
=> Only set SO_REUSEPORT on server sockets

CMakeLists.txt, Dockerfile, src/platform/datapath_epoll.c
The interop runner has issues with GSO, where it says its supported but it is not. Add a flag to completely disable GSO on the interop runner
=> Add build flag to disable GSO on posix for interop runner

CMakeLists.txt
Current setup does not allow cmake to be used as a transitive project. This is technically a regression, so fixing.
Closes #1402
=> Use CMAKE_CURRENT_SOURCE_DIR for openssl

.azure/azure-pipelines.ci.yml, scripts/build.ps1
* Fix Cmake generator arguments
CMake 3.20 seems to have gotten a lot more strict on the generator arguments. Properly use quotes, and also use -G not -g for generator
Cherry Picked from https://github.com/microsoft/msquic/pull/1405
=> Fix Cmake generator arguments (1.0) (#1405)

.azure/azure-pipelines.ci.yml, scripts/build.ps1
* Fix Cmake generator arguments
CMake 3.20 seems to have gotten a lot more strict on the generator arguments. Properly use quotes, and also use -G not -g for generator
Cherry Picked from #1405
=> Fix Cmake generator arguments (1.1) (#1405)

src/inc/quic_driver_helpers.h
We'd never noticed this in the past, but I noticed while running the clog regenerate script it was spitting out this error. It wasn't breaking builds, but still worth fixing
=> Fix not matching ETW trace string in quic driver helpers.

.azure/templates/build-config-user.yml, CMakeLists.txt
In CI, we use build caching to speed up the build. This made the OpenSSL pass in CI, however in a clean build the wrong version of OpenSSL would get built.
Fix up the build so this continues to work. Also fixes a missed PGO variable. Doesn't affect CI builds, but would affect local builds.
=> Fix generator changes not working for clean openssl builds

src/core/stream_send.c
Fixes the issue where sometime a zero length mem copy was happening. Also tries to move things around to make as efficient as possible.
=> Fixes Zero Length Mem Copy

.azure/templates/build-config-user.yml, CMakeLists.txt, submodules/CMakeLists.txt
*edit: It appears this problem may have existed before my last change*
My last change I believe had an unfortunate regression (? not entirely sure because I haven't worked with the project for too long).
I noticed that when compiling incrementally, "make" was running excessively on the OpenSSL target. While this isn't entirely disruptive because previously built objects were still cached by make, it meant that all OpenSSL headers and libraries would get recopied. This updates the modifiedAt timestamps which then causes downstream dependencies to relink, including `msquic` and any other downstream dependents.
This change does some minor cmake refactor. The issue was including both debug/release outputs in a single target. Because for a given config, only one variant of the lib was …
=> Prevent spuriously re-invoking make on OpenSSL targets during incremental builds

src/platform/platform_posix.c
On M1 macs, there is no way to get the current CPU. So our only option is to treat the system as a single core.
On Intel macs, with certain configurations CPUID can return processor numbers that are greater then the number the syscall tells us. This results in assertions, or out of range calls in release mode. We don't currently have a workaround, so treat Intel macOS as a single core.
Since both platforms have current core issues, TL;DR just always treat macOS as a single core platform.
=> Always treat macOS as a single core platform

src/core/quicdef.h, src/plugins/wpa/Properties/launchSettings.json
We had a maximum of 4k packets queued on a connection before the receive side would drop. In larger CPU limited tests, a buffer this big could actually be hit, resulting in dropped packets, and because the buffer was so big, we'd hit the max buffer size pretty consistently. By decreasing the max queue to ~4 full segments (180), we both reduce the amount of time we spend decrypting, which means if the buffer is hit, its less likely to bloat out of control.
=> Reduce the size of the receive packet queue

src/core/connection.c, src/core/crypto.c, src/core/crypto.h, src/core/operation.h, src/inc/quic_tls.h, src/perf/lib/Tcp.cpp, src/perf/lib/Tcp.h, src/platform/tls_openssl.c, src/platform/tls_schannel.c, src/platform/unittest/TlsTest.cpp, src/tools/attack/packet_writer.cpp
At one point in time we considered supporting the async version of the Schannel/SSPI API, so our TLS abstraction layer was built to support it. For various reasons, we've decided not to go down that path. So this PR removes support for it.
=> Remove Async TLS Support

.azure/templates/build-config-user.yml, submodules/CMakeLists.txt
The 2 fiber APIs used by openssl when this mode is enabled are blocked in UWP mode. Disable async fiber mode for UWP builds
=> Disable async fiber support for openssl UWP

src/platform/tls_openssl.c
More work may need to be done if the CAs would come wrong order of have unrelated entries. TLS should send the chain without root CA. 
TLS 1.3 seems more liberal about ordering: https://tools.ietf.org/html/rfc8446#section-4.4.2
```
Note: Prior to TLS 1.3, "certificate_list" ordering required each
certificate to certify the one immediately preceding it; however,
some implementations allowed some flexibility.  Servers sometimes
send both a current and deprecated intermediate for transitional
purposes, and others are simply configured incorrectly, but these
cases can nonetheless be validated properly.  For maximum
compatibility, all implementations SHOULD be prepared to handle
potentially extraneous certificates and arbitrary orderings from any
TLS version, with the exception of the …
```
=> pass CA certificates to SSLCtx when provided by pkcs12

scripts/RemoteTests.json, src/perf/lib/ThroughputClient.cpp, src/perf/lib/ThroughputClient.h
We usually want to be testing with no send buffering, however thats not the default. That makes manual testing more difficult, as thats something we have to explicitly set. Make the default no send buffering, and require it to be enabled explcitly
=> Default to send buffering off in secnetpert

src/core/binding.c, src/core/binding.h, src/core/packet_builder.c, src/inc/quic_datapath.h, src/perf/lib/Tcp.cpp, src/perf/lib/Tcp.h, src/platform/datapath_epoll.c, src/platform/datapath_kqueue.c, src/platform/datapath_winkernel.c, src/platform/datapath_winuser.c, src/platform/pcp.c, src/platform/unittest/DataPathTest.cpp, src/test/lib/QuicDrill.cpp, src/tools/attack/attack.cpp
By doing this, the worker thread will get more time to handle encryption and decryption, as the datapath thread will handle the send. This slooks to be about 8-10% throughput improvement with no regressions elsewhere.
Closes https://github.com/microsoft/msquic/issues/1223
=> Always send data through the datapath thread

src/core/binding.c, src/core/binding.h, src/core/packet_builder.c, src/platform/datapath_epoll.c, src/platform/datapath_kqueue.c, src/platform/datapath_winkernel.c, src/platform/datapath_winuser.c
In theory, these match, but computing the partition index from the connection is more expensive then the ideal processor of the worker thread. And ideally, we want the ideal processor of the worker thread anyway.
Attempt to see if we can gain some of the lost kernel performance back
=> Use worker ideal processor rather then connection partition ID for send.

src/inc/quic_platform_winuser.h, src/platform/platform_winuser.c
These are disallowed by WACK in UWP, however they are pretty easy to implement with simple functions we already were using. Provide custom impl's for UWP mode
=> Provide UWP implementations of GetProcessorCount functions

src/inc/quic_platform_winuser.h
UWP apps have no WACK allowed API to grab that data. So just assume 15.625 ms, and use that.
=> Hardcode timer resolution call for UWP apps

src/core/quicdef.h
Kernel mode seems to need a higher queue length to get performance matches with user mode. Lower queue lengths result in a lot of dropped packets.
=> Tune QUIC_MAX_RECEIVE_QUEUE_COUNT to be ideal for both kernel and user mode

src/inc/quic_platform_winuser.h
GetSystemTimeAdjustment is a documented API that returns the same piece of information we were getting from NtQueryTimerResolution, and is also allowed in UWP. It returns the same value, so its a safe switch for both UWP and normal user mode
=> Switch from NtQueryTimerResolution to GetSystemTimeAdjustment

src/perf/lib/HpsClient.h, src/perf/lib/PerfServer.h, src/perf/lib/RpsClient.h, src/perf/lib/ThroughputClient.h
Noticed we were missing the name when debugging some logs.
=> Add Name to SecNetPerf Registrations

src/core/library.c, src/inc/quic_trace.h, src/perf/bin/appmain.cpp, src/perf/bin/drvmain.cpp, src/platform/platform_posix.c, src/platform/platform_winkernel.c, src/platform/platform_winuser.c, src/platform/unittest/main.cpp, src/test/bin/quic_gtest.cpp, src/test/bin/winkernel/driver.cpp, src/tools/etw/main.c, src/tools/interop/interop.cpp, src/tools/interopserver/InteropServer.cpp, src/tools/ip/server/quicipserver.cpp, src/tools/ping/QuicPing.cpp, src/tools/post/post.cpp, src/tools/reach/reach.cpp, src/tools/spin/spinquic.cpp
Refactors the trace rundown interface to remove the requirement for all cxplatform consumers, by making it a dynamic function pointer instead.
=> Refactor Trace Rundown to Remove from Tools/Tests

.azure/templates/upload-test-artifacts.yml
We explicitly don't copy artifacts when codeCoverage is set, so the task always prints out a warning, which causes the build badge on the main page to show 1 test failed even though it didn't.
=> Skip publishing test results for codecoverage tasks

src/platform/datapath_winuser.c
Updates the UDP send logic to only queue to the worker thread if it's not actively doing something else. This is an attempt to stabilize perf. Note, it's possible this introduces reordering, which I have to think about.
UPDATE: Adds a build flag to control the UDP send queuing logic in general. Right now, disabling it because we have some other perf instability issues we need to debug before we can re-enable this.
=> Disable UDP Send Queuing (Temporarily)

src/perf/bin/appmain.cpp
When manually testing secnetperf, a pain point has been that secnetperfdrvpriv service is created and started if not already, however msquicpriv is not. This meant that msquicpriv was required to be manually created and started. Its an easy code change to automatically start the driver.
=> Create and Start msquicpriv from secnetperf

.azure/azure-pipelines-int.ci.yml, .azure/azure-pipelines.ci.yml
The bug has been fixed, and I think the builds on the test systems are new enough, so reenable the test.
=> Enable valid alpn length tests on schannel

scripts/run-gtest.ps1, scripts/test.ps1
We shouldn't require administrator to run tests. A warning has been added that crash dumps will not be generated without administrator privileges.
Closes #1355
=> Support running tests without administrator

src/core/unittest/PartitionTest.cpp
We run a LOT of test scenarios, and on unix platforms this test takes multiple minutes. On windows it takes > 10 seconds, which is still a bit crazy. This reduces the number of iterations. With how many times we run this test, the amount of randomness we are testing is still high.
Link to #1282 which was noticed by this test.
=> Reduce number of loops in RandomParitionId tests.

src/inc/quic_driver_helpers.h, src/perf/bin/drvmain.cpp
these are some minor errors in encoding that I caught in clog 0.3.0, hoping to get them accepted into quic to streamline my build processes
=> fix encoding collision issues

src/plugins/trace/dll/DataModel/QuicConnection.cs, src/plugins/trace/dll/DataModel/QuicEvents.cs, src/plugins/trace/dll/DataModel/QuicTimeStats.cs, src/plugins/trace/dll/DataModel/QuicWorker.cs, src/plugins/trace/exe/Program.cs
Adds logic for reporting unhealthy, idle and active workers in the `--report` command for `quictrace`.
=> Add Unhealthy Worker Check to Report Command

src/plugins/trace/exe/Program.cs, src/plugins/trace/exe/QuicTrace.csproj
.NET 5 has been out for a while, and most tools should be updated. Also gives us some nice performance boosts.
=> Upgrade QuicTrace to .NET 5

scripts/performance.ps1
Before there would be no comparison, but often we want to compare to main.
=> Compare manually ran builds to main

docs/api/ConnectionStart.md, src/core/api.c, src/core/api.h, src/inc/msquic.h, src/inc/quic_sal_stub.h, src/perf/lib/Tcp.cpp, src/perf/lib/Tcp.h
_In_reads_opt_z_(n) states either optional or reads n bytes. _In_reads_or_z_opt(n) states either optional, reads n, or reads to null terminator if less then n. This is the correct annotation for server name.
=> Update SAL annotation for ConnectionStart

scripts/run-gtest.ps1, src/inc/msquichelper.h, src/platform/unittest/main.cpp, src/tools/interop/interop.cpp, src/tools/interopserver/InteropServer.cpp, src/tools/ip/client/quicipclient.cpp, src/tools/sample/sample.cpp
Previously, -requests: would match a check for `request` as strnicmp just checks for length. This changes ensures that the character after the check is a :, and also that the string length for the argument is acceptable.
=> Update GetValue function to check for full string, and validate length

src/test/lib/ApiTest.cpp
I was looking at a recent test failure on `main` and it was because the test didn't expect to receive a `QUIC_STREAM_EVENT_RECEIVE` event. Looking deeper, the event was delivered for a graceful shutdown of a FIN, which shows up as a zero length receive event:
```
[1]0004.69AC::2021/04/27-08:54:15.968742100 [Microsoft-Quic][strm][0xFFFFD4019ED43C80] Indicating QUIC_STREAM_EVENT_RECEIVE [0 bytes, 0 buffers, 0x2 flags]
[1]0004.69AC::2021/04/27-08:54:15.968745700 [Microsoft-Quic][test] File: D:\a\1\msquic\src\test\lib\ApiTest.cpp, Function: DummyStreamCallback, Line: 1059
```
This should be allowed by the tests. This PR makes the test code a bit smarter about this.
=> Ignore Zero-Length Receive Events in Tests

src/core/inline.c, src/core/packet_builder.h, src/core/sent_packet_metadata.c, src/core/stream.h, src/core/stream_send.c
We've seen from past performance measurements that sometimes the stream ref counting was a non-trivial CPU chunk when building/sending QUIC packets. This PR refactors the logic here to have a separate counter for metadata and only inc/dec stream ref count when that changes to/from zero.
=> Refactor Sent Packet Metadata Stream Ref Counting

scripts/RemoteTests.json, src/perf/lib/HpsClient.cpp, src/perf/lib/HpsClient.h
Schannel has performance issues on the client side if connection the same client to the same server SNI multiple times. Work around that issue by having each core connect to a different address.
=> Special case targets in HPS tests

.azure/azure-pipelines.wanperf.yml, .azure/templates/run-wanperf.yml, scripts/emulated-performance.ps1
This should give us a better comparison between the two protocols by dropping packets in roughly the same place in the stream.
=> Use same RNG seed for TCP vs. QUIC random loss WAN tests.

.azure/templates/run-bvt.yml
The new tests put kernel mode right at the edge of passing. Increase the timeout so they don't fail
=> Increase BVT timeout

scripts/RemoteTests.json
Linux has a lot of performance fluctuation, and we don't currently have the time or knowledge to work on this. Its a future goal, but for now just increase the thresholds
=> Increase linux regression thresholds

scripts/run-gtest.ps1
Previously, any exception would be suppressed by by the write-error if not every test passed. This will always print out the exception so we can figure out whats happening.
=> Log exception if a failure occurs in BVT run

src/core/loss_detection.c, src/core/packet_builder.c
Fixes #1546. Updates the probe retransmit code path to not consider older probe packets as part of the "new" data to resend. It will just continue until it finds 2 packets with real data to retransmit. Only if there aren't any will it eventually just send a new probe.
Also improves the logic that decides the minimum datagram length to decide based on the packet being built and not the keys available, as we might not be currently using the highest available key for "this" packet.
=> Fix Handshake Stall Bug

scripts/run-gtest.ps1
We seem to have an issue that might be related to bad exit codes. So add some logging so we can figure out why.
=> Add exit code debugging to kernel mode test runs

src/platform/datapath_epoll.c
Not defined on some distributions, so just skip it in those cases.
Closes #1549
=> Only compile in RSS support on linux if CBPF macro is found

.azure/templates/run-bvt.yml
We've been seeing some timeouts for kernel BVT recently. We want to invest some time to reduce those times, but for now I'd rather not keep failing the pipelines. Increase the timeout some in the interim.
=> Increase BVT Timeout to 60 Minutes

src/core/connection.c, src/core/crypto.c, src/core/packet_space.h, src/test/MsQuicTests.h, src/test/bin/quic_gtest.cpp, src/test/bin/quic_gtest.h, src/test/bin/winkernel/control.cpp, src/test/lib/HandshakeTest.cpp
A bug was found while working on a separate PR that would cause the packets to be decoded incorrect upon key update. The root cause ended up being our method for choosing old or new keys when the opposite key phase was detected was incorrect. This PR updates the logic for selecting the keys to handle an updated key being used before the local side has confirmed its keys.
Closes #1552
=> Properly update the start point of the current key phase to decide old or new encryption keys

.azure/azure-pipelines.ci.yml
An earlier PR switched these to Full.Verbose. User mode was also switched, but reverted back in a later PR. This basically doubles the time for tests, and isn't usually necessary.
=> Switch kernel mode BVT's back to Full.Light logging

scripts/performance-helper.psm1
Without this, feature branches will crash in the perf pipeline
=> Read commit url in try for perf previous data results

src/inc/msquic.hpp, src/test/MsQuicTests.h, src/test/bin/quic_gtest.cpp, src/test/bin/winkernel/control.cpp, src/test/lib/DataTest.cpp
Fixes #1383. Adds a test that simulates a slow asynchronous receiver and ensures the events are still delivered in the proper order.
=> Add Slow Receiver Test

src/core/crypto.c, src/core/crypto.h, src/core/unittest/TicketTest.cpp
Fixes #1505. Checks the version against the list configured by the app (if set) instead of just the implementation's supported list.
=> Check Version against App Configured

scripts/RemoteTests.json
We've had several 8.* perf drops/fluctuations for sendbuffer perf test cases. This increases the thresholds a bit to try to account for those.
=> Increase Throughput Perf Threshold to 10%

src/core/stream.c, src/inc/msquic.h, src/manifest/clog.sidecar
Adds a new flag to the stream's shutdown complete event to indicate that this is because the connection is shutting down. Closes #1586.
=> Add Stream Shutdown Complete Flag

src/test/lib/TestConnection.cpp
In the headers we now have hex readouts of all the errors, and we see hex normally in the logs, and most things in test are hex anyway, so fix the few that don't.
=> Switch test error status messages from dec to hex

.azure/azure-pipelines.ci.yml
Because of #1297 its highly likely this test will fail. Disable it until we have that issue fixed.
=> Disable nth allocation failure test on linux

.azure/templates/run-quicinterop.yml, scripts/interop.ps1
Previously a crash would still show as successful. We definitely do not want this.
=> Fail interop tests in CI if interop crashes

src/test/lib/HandshakeTest.cpp
If this test fails to connect, the test will currently segfault rather then print out the correct failures. Make this not occur
=> Fix validation shutdown test to not deref null

.azure/azure-pipelines-int.ci.yml, .azure/azure-pipelines.ci.yml, scripts/test.ps1, src/inc/msquicp.h, src/test/bin/quic_gtest.cpp, src/test/lib/DatagramTest.cpp
The internal windows build uses release mode msquic and msquictest binaries, however this is not tested anywhere in CI. Its possible for tests to be added that break this, and this won't then be detectable until a windows build. Run a build in CI so this can be detected early.
=> Run release mode tests in CI

.azure/azure-pipelines-int.ci.yml, .azure/azure-pipelines.ci.yml, src/test/bin/quic_gtest.cpp
The CI were missing an argument to actually run kernel mode in release.
=> Actually Run Kernel Tests for Release

.azure/azure-pipelines-int.ci.yml, .azure/azure-pipelines.ci.yml, src/core/packet_builder.c, src/core/send.c, src/tools/spin/spinquic.cpp
Reenables all the allocation failure testing in BVT and SpinQuic (on Windows user mode).
=> Reenable Alloc Failures in CI

src/core/library.c, src/manifest/clog.sidecar
While looking at the code, I noticed the `QuicLibraryGetBinding` function was unnecessarily doing a lookup for an existing binding if the local port was zero. This is unnecessary because we never actually have a binding with a zero port. This is generally used to indicate to the networking stack that we wish to have an ephemeral port assigned. So simply skip this step and go straight to creation.
Edit: Added additional logic to improve the handling of the scenario when Linux reuses the ephemeral port.
=> Improve Handling of Ephemeral Port Reuse Scenario

docs/TSG.md, docs/tat/api.tat
Adds a filter that helps show all the failed API results from a log file (Posix or Windows). cc @wfurt
=> Add TAT Filter for API Failures

src/inc/quic_platform.h, src/inc/quic_platform_winkernel.h, src/inc/quic_platform_winuser.h, src/test/bin/winkernel/control.cpp
AZP just started pushing an update that includes the VS 2019 v16.10 update, causing many of our builds to fail. This PR fixes most of those issues so at least Windows user mode builds pass. Kernel mode still has a link error that I can't quite figure out.
=> Fix Windows User Mode Build Breaks from VS v16.10 Update

src/inc/msquic.hpp, src/inc/quic_platform.h, src/perf/bin/drvmain.cpp, src/perf/lib/PerfServer.cpp, src/perf/lib/Tcp.cpp, src/perf/lib/ThroughputClient.cpp, src/test/bin/quic_gtest.cpp, src/test/bin/winkernel/control.cpp, src/test/bin/winkernel/driver.cpp, src/test/lib/DataTest.cpp
Its still possible other functions are broken, but the unit tests should tell us. 
Annotations were changed on new and delete as well. For delete, just removed the in annotation, and just deleted the throwing new implementation entirely. Anywhere we use that is a bug in kernel mode, so we just shouldn't implement it at all.
=> Add workaround for Kernel Mode builds using wrong CRT

src/core/connection.c
It seems we forgot to copy out the Handshake payload sizes in the statistics struct.
=> Copy Handshake Sizes in Statistics

src/test/lib/HandshakeTest.cpp
We don't care how the transport shuts down or if it shuts down in this case. All we care is that no key update decryptions fail.
Helps #1596
=> Ignore how the transports shutdown in key update random loss test

src/core/core.kernel.vcxproj, src/platform/platform.kernel.vcxproj
Sets the build flag to enable `QUIC_PARAM_CONN_TLS_SECRETS` usage for msquic.sys.
=> Enable TLS Secrets Support for Windows Kernel

.azure/azure-pipelines.ci.yml, .azure/azure-pipelines.plugins.yml, .azure/templates/post-process-performance.yml, .azure/templates/post-process-periodic-performance.yml, .github/workflows/codeql-analysis.yml
They work during development, but once PR's start it becomes a problem. Its easy enough to manually trigger a build, so not worth having
=> Remove feature branches from automatically building in CI

src/core/mtu_discovery.c, src/core/quicdef.h, src/test/lib/MtuTest.cpp
For tunnelling scenarios, we want to lower the starting MTU. DPLPMTUD support made minimum MTU user configurable, so applications can enforce a higher minimum if requested
Our DPLPMTUD algorithm required 1280 at a starting point for ideal increments. This adds a special case where 1280 will always be selected as the first probe value.
closes #1216
=> Reduce minimum MTU to 1248

docs/api/ConnectionStart.md
On posix, using AF_INET6 would result in the wrong value.
=> Update ConnectionStart docs to use QUIC specific address family macro

src/inc/msquic_posix.h
Only the names of the error codes are actually specified to exist as part of the posix specifications. The actual values are completely arbitrary, and can and do differ between platforms. This adds macOS values to the comments for each error code.
=> Add macOS error codes to msquic_posix.h

src/platform/datapath_epoll.c, src/platform/datapath_kqueue.c, src/platform/datapath_winuser.c
Fixes #1615 by simply removing the assert/check. The result is still handled Ok, but is just less efficient. We don't care about efficiency in the random alloc failure cases.
=> Remove Assert in CxPlatSendDataFinalizeSendBuffer

src/core/library.c
Fixes #1685 (minor debug assert regression from #1621) by making sure to decrement the ref count before uninitializing, so the following assert won't fire:
```c
_IRQL_requires_max_(PASSIVE_LEVEL)
void
QuicBindingUninitialize(
_In_ QUIC_BINDING* Binding
)
{
QuicTraceEvent(
BindingCleanup,
"[bind][%p] Cleaning up",
Binding);
CXPLAT_TEL_ASSERT(Binding->RefCount == 0);  <====== HERE
```
=> Decrement Ref Count before Uninitializing Binding

src/core/stream_recv.c, src/tools/spin/spinquic.cpp
Its possible the stream enabled flag would be triggered after stream shutdown, causing a telemetry assert
Also adds some new asserts to ensure enabled is never set to true after the send shutdown is set.
Additionally updates spinquic to possibly return continue while draining the whole receive queue.
Closes #1667
=> Don't allow stream to be enabled when stop sending has been set

scripts/make-packages.sh
Is is neither perfect not complete but this scrips adds ability to create RPM package for RedHat/Centos and deb for Ubuntu/Debian distributions. 
I used 'fpm' tool recommended by .NET infrastructure people because it allows to support multiple formats including packages for macOS (not supported yet) 
I used simple shell script for now so it is easier (for me) to iterate. We can eventually fold it to some PowerShell but it also allows to package with minimal dependencies. When executed, it will produce something like 
```
furt@ubu20:~/github/wfurt-msquic$ ls -al artifacts/packages/linux/x64_Release_openssl/libmsquic*
-rw-rw-r-- 1 furt furt 1784275 Jun  4 14:57 artifacts/packages/linux/x64_Release_openssl/libmsquic-1.5.0-1.x86_64.rpm
-rw-rw-r-- 1 furt furt 1789496 Jun  4 14:57 …
```
=> add basic packaging script

src/core/congestion_control.c, src/core/connection.c, src/core/connection.h, src/core/library.c, src/core/loss_detection.c, src/core/mtu_discovery.c, src/core/packet.h, src/core/send_buffer.c, src/core/stream.c, src/core/stream_recv.c, src/core/stream_set.c, src/inc/msquichelper.h, src/inc/quic_platform.h, src/inc/quic_platform_posix.h, src/perf/bin/appmain.cpp, src/perf/lib/PerfServer.cpp, src/platform/unittest/TlsTest.cpp, src/test/lib/TestStream.cpp
The min and max macros in Windows.h are a huge pain point, however most windows libraries, including the stl, are able to handle this. However, we define these macros on posix, which most posix libraries, including the C++ standard libraries (which have min and max functions) completely breaks. Instead of defining these on posix, define a common CXPLAT_MIN and CXPLAT_MAX macro that works on all platforms, and doesn't interfere with use in posix applications and libraries.
Closes #1697
=> Switch uses of min and max to CXPLAT_MIN and CXPLAT_MAX

src/core/configuration.c, src/core/connection.c, src/core/settings.c, src/core/settings.h
While writing up #1723, I noticed the logic (and SAL) was wrong/missing for validating input size for new fields in QUIC_SETTING ([since v1.0](https://github.com/microsoft/msquic/blob/v1.0.0-129524/src/inc/msquic.h#L368)). This updates the annotations and logic (borrowing some code from #1723).
This is only a problem if the app code is compiled for an older version of MsQuic, but uses a newer MsQuic binary.
=> Fix QUIC_SETTINGS Size Validation Logic

docs/Settings.md, docs/api/QUIC_SETTINGS.md, src/core/binding.c, src/core/quicdef.h, src/core/settings.c, src/inc/msquic.h, src/manifest/clog.sidecar
Adds a settings knob that can be used to tune the timeout and max count for stateless operations on Bindings.
=> Setting for Binding Stateless Operations

src/core/stream.c
Was used for testing, however not necessary anymore
=> Remove registry accessable force bugcheck

src/inc/msquic.h
On linux, if optimization is completely turned off (can't happen with our normal build, but can with modifications that make testing easier), the linker might choose the inline definition of MsQuicOpen, which will then cause an infinite loop upon open. The solution to this is to force inline the inline function, which causes the out of line definition to never be generated.
=> Always force inline the shim MsQuicOpen function

src/tools/sample/CMakeLists.txt, src/tools/sample/sample.c
We have lots of API tests for C++, but not that actually test the API from C. Bugs have been caught in the past about this.
Because of bugs in the Windows SDK, we do have to disable 1 warning on windows.
=> Switch sample to be built in C instead of C++

src/core/library.c, src/tools/spin/spinquic.cpp
If the library fails to initialized after the list allocation, the list will leak.
=> Free DefaultCompatibilityList on initialization failure

src/platform/platform_posix.c
They were erroring upon success, and not erroring on failure.
=> Correct direction of pthread affinity logs

src/core/connection.c
If a connection hasn't completed a handshake and is shutting down, but receives a retry packet after processing some data from the server, the connection hits an assert in QuicCryptoReset. The connection has already processed some of the server's flight, so it's too late for the server to send a retry packet. The connection is already shutting down, so there's no reason to retry.
This change skips the retry logic in this case.
Fixes #1767
=> Ignore Retry packets when connection is shutting down.

src/inc/quic_platform_winuser.h, src/platform/datapath_winuser.c
Newer SDKs define some of the APIs we use to set thread information that we used to define locally. However, these APIs are not gated behind any version macros in the SDK headers, so we can't just conditionally check for the existance of them in the preprocessor. The solution is to rename the local versions of the struct and enum definition to not colide. Additionally, NtSetInformationThread needed its signature slightly changed to be compatible with the SDK.
This fix will also need to be backported to previous releases.
=> Fix compilation on newer windows SDKs

src/inc/quic_platform_winuser.h, src/platform/datapath_winuser.c
* Fix compilation on newer windows SDKs
Newer SDKs define some of the APIs we use to set thread information that we used to define locally. However, these APIs are not gated behind any version macros in the SDK headers, so we can't just conditionally check for the existance of them in the preprocessor. The solution is to rename the local versions of the struct and enum definition to not colide. Additionally, NtSetInformationThread needed its signature slightly changed to be compatible with the SDK
Cherry picked from #1772
=> Fix compilation on newer windows SDKs (1.0) (#1772)

src/inc/quic_platform_winuser.h, src/platform/datapath_winuser.c
* Fix compilation on newer windows SDKs
Newer SDKs define some of the APIs we use to set thread information that we used to define locally. However, these APIs are not gated behind any version macros in the SDK headers, so we can't just conditionally check for the existance of them in the preprocessor. The solution is to rename the local versions of the struct and enum definition to not colide. Additionally, NtSetInformationThread needed its signature slightly changed to be compatible with the SDK
Cherry picked from #1772
=> Fix compilation on newer windows SDKs (1.1) (#1772)

src/core/connection.c
Fixes #1779. Ignore min idle timeout requirement during the handshake, as PTO isn't necessarily even valid (no real RTT measurement yet) so don't require it as a min.
=> Don't Apply Min Idle Timeout During Handshake

src/core/path.c
At this point, the path should not be null because we are setting it to null. The existing check is wrong, because it expects the path to be null.
=> Fix incorrect assert in QuicPathRemove

CMakeLists.txt
option() is only for boolean values, so without anything set all folders get prefixed with OFF. This is not correct, so use the correct way for setting option strings
=> Fix IDE folder prefix option

CMakeLists.txt, scripts/build.ps1, src/bin/CMakeLists.txt, src/bin/winuser/msquic.def.in, src/bin/winuser/msquic.rc.in
In .NET, a different library name is preferred. This PR enables that name change to be selected at build time. .NET would prefer MsQuic.Native, but the def file errors if there is a dot in the name, so MsQuicNative is chosen.
Closes #1789 
@wfurt
=> Enable renaming the output shared binary

scripts/update-sidecar.ps1, src/core/crypto.c, src/core/send.c, src/core/send.h, src/core/stream.c, src/core/stream.h, src/inc/msquic.h, src/inc/msquic.hpp, src/manifest/clog.sidecar, src/test/MsQuicTests.h, src/test/bin/quic_gtest.cpp, src/test/bin/winkernel/control.cpp, src/test/lib/DataTest.cpp, src/tools/spin/spinquic.cpp
Adds a new (optional) parameter to set a 16-bit priority on a stream that controls the relative order between the streams to send the data out.
Still need to figure out some testing.
=> Stream Priority Support

src/core/connection.c, src/test/lib/EventTest.cpp
The previous check wasn't quite right as it would return 1-RTT key even if we couldn't write with it yet.
=> Use WriteKey for App Close Check

src/platform/tls_schannel.c
When the crypto code was refactored out of TLS, this got leftover unnecessarily.
=> Remove Unused Define

src/core/api.c, src/core/connection.c, src/core/connection.h, src/core/stream.c, src/plugins/dbg/quictypes.h
This makes a number of changes in an attempt to improve reentrancy around MsQuic event callbacks to the app:
1. The connection now tracks if it is in a reentrant API call (e.g. the app is calling a blocking function on the MsQuic thread).
2. A couple API calls were made async, even if on the callback thread (StreamShutdown and StreamStart(async)).
3. We now debug assert if we ever try to indicate an event to the app if we are in a non-*Close reentrant API call.
=> Improve Event Callback Reentrancy

src/core/stream.h, src/core/stream_recv.c, src/core/stream_send.c, src/test/MsQuicTests.h, src/test/bin/quic_gtest.cpp, src/test/bin/winkernel/control.cpp, src/test/lib/DataTest.cpp
Fixes #1807. Splits the internally tracked error code for sending out the stream shutdown related frames. While HTTP/3 generally uses the same error codes when aborting both directions, per spec, they are independent error codes, and an application should be  able to simultaneously abort both directions with different error codes.
=> Split Stream Abort Error Codes

src/core/send.c
Previously, if 0-RTT data was queued during the handshake, it has the potential to not queue the flush send. This makes it so if we have 0-RTT flags and sends are queued, we'll allow them to be flushed.
Also, there are cases where we could end up with stream data but no flags, which if this occured during the handshake would hit an assert. This assert is only there to tell if we're going to do no work, but this would only be a slight perf penalty when it does happen, so its not a valid assert
Fixes https://github.com/microsoft/msquic/issues/1749.
=> Fix queuing 0-RTT data during handshake

.azure/templates/build-config-user.yml, src/platform/tls_openssl.c
We were previously using a callback that would be called after openssl did all of its verification internally. This resulted in multiple callbacks. Instead, we can just completely replace OpenSSL's verification. We then can decide to call openssl's verification directly or windows cert store verification depending on OS and sec config flags. This will always result in just a single callback to the app layer, but otherwise results in no actual behavior changes.
Closes #1810
=> Use root level certificate verification callback in OpenSSL

CMakeLists.txt
I'm not sure this will solve the openssl cached builds being 1/4th the speed of non cached builds, but its the only difference I can find currently.
=> Fix linker order of openssl libraries in cached builds

src/core/stream_recv.c, src/test/bin/quic_gtest.h, src/test/lib/EventTest.cpp
Fixes #1821. Updates the stream abort receive code path to ignore duplicate calls (don't overwrite/change original error code). Also adds test case to validate.
=> Ignore Duplicate Stream Read Shutdowns

src/core/send.c
Under certain circumstances (lots of streams with small payloads) the deadlock detection can hit incorrectly. Theoretically, the loop could legally run `QUIC_MAX_FRAMES_PER_PACKET` * `QUIC_MAX_DATAGRAMS_PER_SEND` which is just under 500 right now. We'll double that for good measure.
cc @wfurt
=> Increase Send Deadlock Detection Threshold

src/core/binding.c, src/core/library.c
When looking through the binding initialization code path I noticed there was a possible race condition with a packet getting received and processed for a binding that ultimately was getting destroyed. The fix is to just not increment the ref count until it's actually added to the library's list, so that if we happen to receive a packet that creates a new connection before that happens, it would just be dropped/ignored.
=> Binding Ref Count Fixes in Error Paths

src/core/cid.h, src/core/connection.c, src/core/loss_detection.c
To make it easier to debug destination CID issues, extend the tracing done when cids are added and removed from path.
=> Add more path tracing to destination CIDs

.azure/templates/build-config-user.yml, CMakeLists.txt, scripts/prepare-machine.ps1, submodules/CMakeLists.txt
Jom is a QT NMAKE replacement which supports parallel builds. Its done as an optional dependency to make builds still work without it installed. This should massively drop compile times for OpenSSL builds.
=> Add support for building openssl with jom

src/platform/datapath_winuser.c
Updates the Windows user mode datapath to use `CancelIoEx` instead of `CancelIo` to cancel pending IO on **all** threads, instead of just the current one. .NET Core was encountering reliability issues related to this in their automated testing.
=> Use CancelIoEx Instead

CMakeLists.txt
OpenSSL changes requires 3.20 at minimum. However on windows this isn't a difficult requirement to have.
=> Increase cmake minimum version on windows

src/core/listener.c, src/test/MsQuicTests.h, src/test/bin/quic_gtest.cpp, src/test/bin/winkernel/control.cpp, src/test/lib/ApiTest.cpp
Fixes #1647. Correctly handles the case where the app accepts the connection (returns success) but closes the connection. Adds an additional assert to make sure the app doesn't both reject (return failure) and close the connection.
=> Support ConnectionClose in NEW_CONNECTION Event

scripts/make-packages.sh
this change has three parts:
1) add support for macOS
```
gem install fpm
Shining:wfurt-msquic furt$ ./scripts/make-packages.sh
Created package {:path=>"artifacts/packages/macos/x64_Release_openssl/libmsquic-1.6.0.pkg"}
sudo installer -pkg libmsquic-1.6.0.pkg  -target /
```
2) make packaging of `libmsquic.lttng.so` optional. 
I hit issue on some platforms and since this is not critical packaging would work with or without tracing e.g. follow `-DisableLog`
3)  #1830 regressed short options. 
The `-?` will match as one character wildcard and it will also incorrectly match `-o`. I fix that by escaping as well as moved the help to the bottom so more important parts are first.
=> improve packaging

src/generated/CMakeLists.txt
The lttng headers were being included as a library and not an include directory. In our CI this was only warning, but it's an error in .NETs.
=> Fix invalid path warning in linux build

docs/BUILD.md
Selecting "Desktop development with C++" for "Build Tools for Visual Studio 2019" (or installed as part of node.js native tools) only includes "MSVC v142 - VS 2019 C++ x64/x86 build tools". To target ARM64, select also "MSVC v142 - VS 2019 C++ ARM64 build tools" in "Individual components".
This also enable using GUI tools in Visual Studio 2019/2022 to configure and build with VS 2019 CMake tools without using the command line at all.
=> Add notes for targeting Windows ARM64 OpenSSL

CMakeLists.txt, scripts/build.ps1, src/bin/CMakeLists.txt
Remove excess prints from static builds
Remove gmock and gtest_main from builds
Allow using alternate build systems on windows builds with warning about dev command promt
Tested with VS 2022. Default is still 2019. Might add an option later to automatically detect 2022
=> General build cleanups and speedups

src/platform/datapath_winkernel.c
The bug is actually in SAL rather than in the MIB structs. So work around the issue by grabbing a local copy of the iteration variable, which works around the warning.
=> Remove disable of SAL for MIB structs

CMakeLists.txt, src/inc/CMakeLists.txt, src/test/bin/CMakeLists.txt, submodules/CMakeLists.txt
Will be required for compliance reasons in the near future.
=> Enable spectre and guard:cf for windows user mode builds

CMakeLists.txt, scripts/build.ps1, src/bin/CMakeLists.txt
For builds coming out of our CI, we want a minimum set up required flags and definitions, both for compliance and performance reasons. On linux, these checks are properly handled if missing at runtime, but we want them there in the binaries we build
=> Add minimum compiler requirements for CI builds

scripts/package-distribution.ps1
Regression in https://github.com/microsoft/msquic/commit/801132a6cf3f9c12afe87ba5605203fffbab50c3
=> Fix third party notices missing from OpenSSL packaging

.azure/OneBranch.Official.yml, .azure/OneBranch.PullRequest.yml, .azure/obtemplates/build-distribution.yml
This way onebranch builds will still build distributions
=> Reset distribution stages to what worked before separate pipeline testing

scripts/package-distribution.ps1
An extra file path is included in the official builds because of signing, which breaks the existing scripts
=> Fix official onebranch builds failing distribution stage

src/platform/datapath_epoll.c
This way not all performance will be lost without segmentation support
=> Increase epoll batch size if segmentation is not available at build time

CMakeLists.txt, src/platform/datapath_epoll.c
Some users have asked to build with glibc versions that do not have sendmmsg. This change checks for the existance of sendmmsg, and if its missing implements a shim version that has identical functionality.
Closes #1884
=> Add shim for sendmmsg when sendmmsg does not exist

scripts/package-nuget.ps1, scripts/update-version.ps1, src/nuget/Microsoft.Native.Quic.MsQuic.OpenSSL.nuspec, src/nuget/Microsoft.Native.Quic.MsQuic.Schannel.nuspec
Right now we don't have a way to trigger a release, so all builds will show up as a prerelease. That is a next step we need to work through.
=> Add proper CI versioning to nuget

src/core/worker.c, src/core/worker.h, src/generated/linux/worker.c.clog.h, src/generated/linux/worker.c.clog.h.lttng.h
Related to https://github.com/microsoft/msquic/issues/1923.
Refactors the inner worker processing loop so that it may be directly exposed to the app in the future, so that the app can drive its execution.
=> Refactor Worker Loop

src/core/binding.c, src/core/binding.h
A small race condition exists if a server binding is created and runs out of memory at a specific point in the process. If the socket and at least 1 receive buffer gets allocated, a packet can be received on that receive queue. This receive can post a stateless operation, even if one of the later receive buffers fails to allocate, and cause the socket and binding to be cleaned up early. During binding cleanup, there will be a stateless operation in the binding queue, causing an assertion to be hit. 
The solution to this is to not allow a stateless operation to queue until the binding has been fully initialized. The packet will be dropped instead, which is fine.
=> Don't allow stateless operations on a binding until fully initialized

src/core/congestion_control.c, src/core/congestion_control.h, src/core/loss_detection.c
We may lost the precision of the `TimeNow` timestamp if we do the `US_TO_MS` convertion in `loss_detection` layer, and this may not be compatible with other congestion control algorithm.
=> Change congestion control api to use "TimeNow" in microsecond

submodules/CMakeLists.txt
Makefile is capitalized on Linux, so having it lowercase was causing incremental checks to not work.
=> Fix casing of makefile on linux for openssl

submodules/CMakeLists.txt
By default, if a prefix is specified during the openssl build, that directory is used for the certificate store. However, in our build that directory is in the build dir, so is completely wrong. This makes it so that by default its impossible for OpenSSL that don't use the built in TLS provider to validate certificates without doing custom certificate validation (This is why .NET doesnt see this issue). This changes the cert directory during the build to point to the built in certificate store. 
We ideally should look at adding a test to ensure certificate validation against a valid remote server works.
=> Configure openssl certificate dir correctly during build

.azure/azure-pipelines.ci.yml, CMakeLists.txt, scripts/build.ps1, scripts/get-buildconfig.ps1, src/inc/quic_platform_winuser.h, src/platform/platform_winuser.c
GameCore supports only a subset of the Windows SDK API surface similarly to UWP, so add a new build flavor and adjust a couple of platform implementations accordingly.
=> Add GameCore build platform to MSQUIC

.azure/templates/create-package.yml, scripts/prepare-package.ps1
This reverts commit 0a0ae562c20a1a409c01f64c56eb26093771ffb3.
The new ingest method breaks a specific build type in windows. Revert it, and we will figure things out when I get back from vacation.
=> Revert "Publish separate vpacks for each configuration and architecture (#1940)"

src/platform/darwin_openssl.c, src/platform/datapath_epoll.c
In new compilers the lowercase usages are fine but not what we use in the rest of the code base and we want to be standardized.
=> Switch lowercase usages of true in c to TRUE

src/test/lib/ApiTest.cpp
Should fix #1616. It should fix #1582 too.
=> Fix Test Failures in SendResumption Tests

src/test/lib/HandshakeTest.cpp, src/test/lib/TestConnection.cpp
Should fix #1726 and improve logging for future issues around "expected" results.
=> Fixes/improvements for ConnectExpiredServerCertificate

src/core/congestion_control.c, src/core/congestion_control.h, src/core/connection.c, src/core/cubic_impl.c, src/core/cubic_impl.h, src/core/path.c
When a new path becomes active it resets congestion control (because you don't know anything about the new path's network characteristics yet). That was resetting BytesInFlight too. That shouldn't have been reset because you still can have packets in flight that might get ACK'ed.
Fixes https://github.com/microsoft/msquic/issues/1975.
=> Don't Reset BytesInFlight on Path Change

scripts/performance-helper.psm1, scripts/performance.ps1
Make sure cancellations happen in the correct order, and always wait for the local job to complete
=> Attempt to fix perf machines getting to a bad state when cancelled.

src/test/lib/EventTest.cpp
Fixes #1761. Waits for the handshake to complete before running the rest of the test code.
=> Update Stream Event Tests to Wait for Handshake Complete

src/test/lib/HandshakeTest.cpp
Should fix #1727 by increasing the wait time to account for the race with ACK delay. Not perfect, but no way to wait on the ACK explicitly.
=> Increase Test Delay to Account for Delayed ACKs

src/test/lib/TestConnection.cpp
Just saw a failure in a CI run on macOS. It really is slow. Allow more time for things to try to work.
=> More Time for macOS

.azure/templates/create-package.yml, scripts/prepare-package.ps1
This is a redo of #1940 
There was nothing inherently wrong with the original PR, it just needed to be reverted until we were at a point to take this into windows again. That break did reveal we need a special chpe vpack. That vpack has no binaries, but just headers.
=> Publish separate vpacks for each configuration and architecture

src/generated/linux/datapath_winkernel.c.clog.h, src/platform/datapath_winkernel.c
TDI/TDX only examines the cmsghdr of TDI IRPs from the
Options/OptionsLength fields if UserBuffer==(PVOID)8937731. This was
never documented and will probably never change, which in turn means
that TDI drivers that filter and reinject packets will strip the cmsghdr
unknowingly. TDI is a dead technology anyway, and bypassing it shouldn't
interfere with reasonable systems.
This mirrors https://git.zx2c4.com/wireguard-nt/commit/?id=c331ee4f18e98b7063dc74e3d8b0ab556cff3a96
=> Bypass TDI to make IP_PKTINFO work properly

CMakeLists.txt, scripts/build.ps1, scripts/get-buildconfig.ps1, src/platform/tls_schannel.c
Many xbox devs have older windows SDKs which have issues with UNICODE_STRING. Found a workaround to detect newer SDKs. For some of the functions, there is a minimum GDK version, so enforce that. Scarlett doesn't add any capabilities for our code, so move to 1 gamecore build.
=> Fix gamecore on older windows sdk, require a minimum gdk, remove scarlett

scripts/run-gtest.ps1
While the previous changes made the jobs show "green", they still show as failures when looking at the status badge. These changes should make them completely silent to AZP.
=> More gtest Warning Refactoring

.azure/templates/create-package.yml
Multiarchitecture flag is missing provenance, which is required to ingest into windows
=> Push individual vpacks rather than multiarchitecture flag

src/core/crypto.h, src/core/frame.h, src/core/library.h, src/core/precomp.h, src/core/range.h, src/core/transport_params.h, src/core/version_neg.h
Newer versions of lltng have templates, which don't properly work if extern C has been used around lttng headers. The fix to this is to not have a global extern C, but instead have it in individual headers.
Closes #2026
=> Don't wrap all headers in extern C

.github/workflows/docker-publish.yml
Adds a new GitHub Action to build the QNS Docker image and publish it (not on PRs). This will replace the other Docker image we have, since it's broken.
=> Publish Docker Image to GitHub Registry

src/core/stream_recv.c
Uncovered by .NET testing, we had an incorrect assert (should be `<=` instead of `<`) when doing some stream/connection flow control validation.
cc @ManickaP
=> Fix Flow Control Assert

src/platform/datapath_raw.c, src/platform/datapath_raw.h, src/platform/datapath_raw_socket.c
Reset NextLocalPort back to the (currently hardcoded) start port when it wraps.
Otherwise we'll use port 0, which is invalid, or a low reserved port number.
CxPlatSocketPoolGetNextLocalPort is also renamed to CxPlatSockPoolGetNextLocalPort
for consistency with sibling functions.
Synchronization is changed from interlocked to use of the RW lock. On this note,
probably we should make a future change to select the port in CxPlatTryAddSocket
while we already hold the lock; that function is called right after this one currently.
=> Fix wraparound bug in CxPlatSocketPoolGetNextLocalPort

src/platform/datapath_raw.c, src/platform/datapath_raw.h, src/platform/datapath_raw_socket.c
Adds a RemoteAddress parameter to CxPlatGetSocket so that only traffic matching
the socket's remote address will be delivered to a connected socket.
=> Filter for remote address for connected sockets in CxPlatGetSocket

src/platform/datapath_raw_xdp.c
Initial support for multiple XDP queues, i.e. multiple RSS queues.
1. QUIC core and raw abstractions do not not provide a TX spreading scheme other than implicitly via worker CPU.
2. For simplicity, use only one user mode worker thread to pump all the kernel mode XDP queues.
=> Support multiple XDP queues

scripts/install-test-certificates.ps1, src/platform/tls_openssl.c
When parsing a PKCS12 that includes a certificate chain, OpenSSL wasn't freeing the certificate chain memory, and introduced a leak.
This change fixes that by freeing the certificate chain when done adding the certificates to `SSL_CTX`.
Signed-off-by: Anthony Rossi <anrossi@microsoft.com>
=> Fix leak in OpenSSL PKCS12 parsing.

.azure/azure-pipelines.ci.yml, .github/workflows/mirror-repo.yml, scripts/sync-mirror.ps1
Moves the mirroring job to a GitHub Action. Also adds tag support, and now includes mirroring for prerelease branches. No longer requires that all builds complete first. This isn't really necessary any more since these consistently pass always anyways.
=> GitHub Action for Repo Mirroring

.github/workflows/wan-perf.yml, scripts/emulated-performance.ps1, scripts/prepare-machine.ps1
Starts the process of refactoring and moving WAN perf testing. Uses a matrix to run parallel jobs.
Future work:
- Remove AZP WAN perf and ensure this Action replaces all functionality.
- Periodically do even more cases (i.e. TCP)
=> GitHub Action for WAN Perf

src/core/binding.c, src/core/binding.h, src/core/connection.c, src/core/connection.h, src/core/crypto.c, src/core/datagram.c, src/core/loss_detection.c, src/core/packet_builder.c, src/core/path.c, src/core/path.h, src/core/send.c, src/generated/linux/connection.c.clog.h, src/generated/linux/connection.c.clog.h.lttng.h, src/generated/linux/datapath_winkernel.c.clog.h, src/generated/linux/datapath_winkernel.c.clog.h.lttng.h, src/inc/quic_datapath.h, src/perf/lib/Tcp.cpp, src/platform/datapath_epoll.c, src/platform/datapath_kqueue.c, src/platform/datapath_winkernel.c, src/platform/datapath_winuser.c, src/platform/pcp.c, src/platform/unittest/DataPathTest.cpp, src/test/lib/QuicDrill.cpp, src/tools/attack/attack.cpp, src/tools/lb/loadbalancer.cpp
The signature of CxPlatSocketSend is updated so that a pointer to the QUIC_PATH's CXPLAT_ROUTE is passed instead of pointers to its LocalAddress and RemoteAddress. This enables additional state (specifically the next hop for the selected route) to be stored in QUIC_PATH and passed to the datapath layer without massive plumbing.
=> Create CXPLAT_ROUTE to replace QUIC_PATH::LocalAddress and QUIC_PATH::RemoteAddress

src/core/binding.c, src/core/connection.c, src/core/packet.c, src/core/path.c, src/generated/linux/packet.c.clog.h, src/generated/linux/packet.c.clog.h.lttng.h, src/inc/quic_datapath.h, src/platform/datapath_epoll.c, src/platform/datapath_kqueue.c, src/platform/datapath_winkernel.c, src/platform/datapath_winuser.c, src/platform/pcp.c, src/platform/unittest/DataPathTest.cpp, src/test/lib/TestHelpers.h, src/tools/lb/loadbalancer.cpp
In addition to QUIC_PATHs having a "route", now CXPLAT_RECV_DATAs (which represent received packets) also have one. This enables the route of the received packet which triggered a stateless operation to be directly passed to QuicBindingSend in QuicBindingProcessStatelessOperation.
The idea here is that LoLa can potentially skip route lookup and ARP when sending stateless replies on the dpdk or xdp datapath.
=> Change CXPLAT_TUPLE field of CXPLAT_RECV_DATA to CXPLAT_ROUTE

src/platform/datapath_raw_socket.c, src/platform/datapath_raw_xdp.c
Only very slight difference between xsum on and off during my testing.
.\xdp\secnetperf.exe -test:rps -target:quic-server -bind:192.168.77.31 -conns:1 -requests:1 -request:512 -response:65536
These 2 metrics are consistently different between the xsum on and off. So, with xsum, min is smaller but 99th is larger. The variance in long tails are huge so I am not looking at them.
Xsum On: 
Min: 197, 99th: 238
Xsum Off:
Min: 203, 99th: 217
```
> # no xsum
> .\xdp\secnetperf.exe -test:rps -target:quic-server -bind:192.168.77.31 -conns:1 -requests:1 -request:512 -response:65536
Result: 4716 RPS, Min: 204, Max: 6082, 50th: 207.000000, 90th: 209.000000, 99th: 217.000000, 99.9th: 260.000000, 99.99th: 852.000000, 99.999th: 6082.000000, 99.9999th: 6082.000000, StdErr: 0.134733
> .\xdp\secnetperf.exe …
```
=> Xsum in forward direction and a knob to skip xsum for testing

.azure/azure-pipelines.ci.yml, scripts/build.ps1, scripts/get-buildconfig.ps1, src/inc/CMakeLists.txt
Arm64ec is an emulation compatible arm64 calling convention. It allows x64 and arm64 code to mix in the same exectable. This is great for a program that uses plugins, as it can use exisiting x64 plugins but run most of its code as arm code.
Only supports schannel, as openssl would require changes to their assembly files, which they do not have any interest in doing.
=> Add support for building arm64ec binaries

docs/api/QUIC_CONNECTION_EVENT.md, src/core/connection.c, src/generated/linux/tls_schannel.c.clog.h, src/generated/linux/tls_schannel.c.clog.h.lttng.h, src/inc/msquic.h, src/inc/quic_tls.h, src/platform/tls_schannel.c
When indicate certificate is set and the certificate is rejected, we would leak the cert context. Also if the cert context failed to be grabbed we'd deref a null pointer. Both issues are fixed
=> Fix memory leak when indicated certificate is rejected by app

scripts/performance-helper.psm1, src/perf/lib/SecNetPerfMain.cpp
Some devices broadcast on 9999, which previously would kill secnetperf
=> Require specific data to be received to shutdown secnetperf

src/core/binding.c, src/core/packet_builder.c, src/inc/quic_datapath.h, src/perf/lib/Tcp.cpp, src/perf/lib/Tcp.h, src/platform/datapath_epoll.c, src/platform/datapath_kqueue.c, src/platform/datapath_winkernel.c, src/platform/datapath_winuser.c, src/platform/pcp.c, src/platform/unittest/DataPathTest.cpp, src/test/lib/QuicDrill.cpp, src/tools/attack/attack.cpp, src/tools/lb/loadbalancer.cpp
Extracts out the change to pass the route to the send alloc function from #2165 to make that PR simpler to review.
=> Pass CXPLAT_ROUTE to CxPlatSendDataAlloc

scripts/performance-helper.psm1, src/perf/lib/SecNetPerfMain.cpp
Padding made the struct different. So avoid padding, and just use raw arrays
=> Fix linux perf shutdown not correctly working

CMakeLists.txt, scripts/build.rs, src/bin/CMakeLists.txt, src/generated/CMakeLists.txt
Removes /msquic from library install path, as it does make using raw gcc harder, and is non standard. Cmake install process is tested to still work
Replaces #2169 
@ami-GS the cmake target needed another change, and I realized I could remove all the boilerplate in the root cmake file, as it was completely unnecessary. I tested that both a raw gcc build and a build using cmake's find_package still work.
=> Clean up cmake install paths

docs/Development.md
I get asked these questions a lot, so figure documenting how to get intellisense in VS Code warning free is worth it
=> Add documentation for configuring editors for MsQuic dev

src/core/crypto.c, src/core/crypto.h, src/core/crypto_tls.c, src/perf/lib/Tcp.cpp
Thanks to @wqweto for finding. `crytpo` -> `crypto`
=> Fix Crypto Spelling Mistakes

scripts/build.ps1
Since we're open source, we don't mind having debug symbols in the object. And in release mode, debug symbols still help if crashes occur in the wild. So in pwsh builds, set release to relwithdebinfo, which will enable debug symbols for release mode.
=> Set release build in pwsh to relwithdbginfo on unix

src/core/binding.c, src/core/connection.c, src/core/packet.c, src/core/packet.h
Closes #2150 
In loopback scenarios, it is possible for multiple initial packets with retry tokens to be received at the same time on different threads. If this happens, its possible for the packet that isn't creating the connection to be queued first on the connection. This packet won't have its retry token validated, causing the non retry token path to be taken through the connection code. When the packet with the validated token is then handled, its expecting different state and asserts.
The solution is to always validate the retry token if it exists in the long header packet.
=> Fix connection mishandling out of order initial packets with retrys

src/generated/linux/datapath_raw_dpdk.c.clog.h, src/generated/linux/datapath_raw_socket.c.clog.h, src/generated/linux/datapath_raw_socket.c.clog.h.lttng.h, src/generated/linux/datapath_raw_xdp.c.clog.h, src/generated/linux/datapath_raw_xdp.c.clog.h.lttng.h, src/inc/quic_datapath.h, src/manifest/clog.sidecar, src/platform/datapath_raw.c, src/platform/datapath_raw.h, src/platform/datapath_raw_dpdk.c, src/platform/datapath_raw_socket.c, src/platform/datapath_raw_xdp.c
1. Abstracted all interface related stuff into CXPLAT_INTERFACE, XDP_INTERFACE and DPDK_INTERFACE. Interfaces are chained by a linked list.
2. No support for dynamic NIC add/removal yet.
3. Tested with both XDP and DPDK.
For DPDK, rte_eth_dev_info_get doesn't give us a valid ifindex. So, the ifindex of the interface being bound is looked up by mac address via GetIfTable2.
=> XDP automatically binds to all supported interfaces at startup

scripts/publish-quictrace.ps1, src/plugins/trace/dll/QuicTraceLib.csproj, src/plugins/trace/exe/Program.cs, src/plugins/trace/exe/QuicTrace.csproj, src/plugins/trace/exe/SingleFileAssemblyLoader.cs
Closes #1491 
A workaround was made to allow single file exes to work in our case.
=> Enable single file exe for QuicTrace

src/core/stream.c, src/cs/lib/msquic_generated.cs, src/inc/msquic.h, src/tools/sample/sample.c
Closes #2220 
If a stream is closed from an app thread, the shutdown complete event is called, which causes a double free if StreamClose is called again in that event. For the app to handle this, they'd have to add external state tracking. Instead add a small amount of internal state tracking. We had this same issue with connections, and solved this the same way.
=> Add Stream AppCloseInProgress flag to shutdown

src/platform/tls_openssl.c
Codecheck saw this in a PR run, where its possible for these to be null. Assert, because its really not, and if that ever happens things are very blown up.
=> Ensure TLS secrets code path doesn't read null pointer

src/core/binding.c, src/core/connection.c
0-RTT packets received out of order from initial packets should be considered valid packets and read. This is a behavior change from currently, where only initial packets can create a connection, and 0-RTT packets received out of order would be dropped. 
In a retry scenario, its possible for an initial to create the connection, but a 0-RTT packet to actually be the first one queued. If this occurs, its possible for the original dest cid to be overwritten. In dbg this would have asserted, but we now handle this case correctly.
=> Allow 0-RTT packets not in a retry scenario to start a connection

src/core/connection.c
If connection start fails on out of memory after initializing the binding, data can be received on a closed client connection. Additionally, the share binding flag can still be set on the connection, as it hasn't been started. This can cause a dbg assert to be triggered, as the binding is exclusive so its expecting 0 length cids, but once the flag is set the connection is expecting non 0 length cids. The solution to this is to not allow setting the share binding parameter on a closed connection either, as the closed flag is always set if a connection isn't started.
=> Don't allow changing share binding flag on closed connection

src/test/lib/ApiTest.cpp
Since the context is passed to the connection, it needs to be alive as long as all the server side connections. The solution to this is to allocate the variable before even the registration is opened
=> Fix use after scope exit on connection validate 0-RTT tests

.azure/templates/upload-test-artifacts.yml
Currently, logs are only published if a failure occurs. On mac, we suppress failures, so logs and dumps never get uploaded. This isn't what we want, as we want to be able to hopefully fix these issues.
=> Publish macos logs from bvt runs

src/platform/datapath_kqueue.c
Because of how we were doing connected sockets on macOS, the invalid address test would always fail, as we would always get the incorrect error code. The logic was only forcing a bind to an IPv4 socket if the remote was ipv4. But if a local ipv4 addr and remote ipv6 addr was passed, this would result in the failure not occurring until packets started to flow, and would be an unreachable error. Ideally macOS should fail to bind when an ipv4 mapped ipv6 address is passed to an ipv4 socket, but thats not the case.
=> Fix InvalidAddress test on macOS

src/core/library.c, src/core/library.h, src/generated/linux/library.c.clog.h
The PerProc library structures are not zeroed on initialization. This didn't used to be a problem until #2045 was merged. It uses a new ReceivePacketId field, and has an assertion that the value or'd with the proc is non zero. On all but core 0 this would always be fine, but on core 0 if this field starts high and then rolls over, the assertion hits. We likely should make it so that assertion can't be hit even in a rollover situation, but we also should always just 0 this memory out, as it will be a source of future buts, and it only happens during library initialization.
macOS tests have been hitting this since merge, since theyre always core 0, but since we don't report failures there it was never noticed.
=> Zero out perproc structures on library initialization

scripts/wpa.ps1, src/core/cubic.c, src/core/cubic.h
Fixes an issue with large pacing send allowances, where `QUIC_MAX_DATAGRAMS_PER_SEND` actually ends up limiting the send, instead of the allowance, resulting in a complete loss of all that allowance.
The fix is to save the previous allowance, subtract what was actually sent, and then in the next send use (add) that old allowance too.
=> Improve Pacing Send Logic

src/core/binding.c, src/core/packet_builder.c
The existing code has a lot of checks for Id not equal to 0. However, on core 0 with rollover this is a valid case. We can make this an always invalid case by artificially increasing the proc by 1 before shifting it.
=> Artificially increase ProcShifted by 1 for PacketId

.github/workflows/wan-perf.yml, docs/tat/default.tat, scripts/emulated-performance.ps1, src/core/congestion_control.h, src/core/cubic.c, src/core/inline.c, src/core/loss_detection.c, src/perf/bin/appmain.cpp, src/perf/lib/ThroughputClient.cpp
Collect WAN Perf ETL files and fixes the following issues found with those logs:
1. When recovering from a spurious retransmit, loss detection must account for flushing a new send if previously blocked on congestion control.
2. There are cases where huge bottleneck queues can't drain in the allowed test run time, so all the sent data doesn't complete. In this case, just use the amount of data that did complete to calculate the transfer rate.
3. In some test timeout situations there was an ordering issue with the console output, which broke the PS script that parsed the output to read the final rate. Updated the code to ensure this no longer gets swapped.
=> Collect WAN Perf Logs and Fix Issues Found with them

powershell/merge-performance.ps1
I have a follow up PR coming that moves all the WAN perf code into the GitHub Action, including the post processing merge and commit to `performance` branch, so remove all references from that here.
Note - This will break down-level releases, but only effects `release/1.1` (since this didn't exist before that) and those wanperf results aren't particularly useful anyways.
=> Remove WAN Perf from Merge Post Processing

src/core/connection.c
Related to #2188 and #2249. Minimal fix is to just always set the destination CID.
=> Release/1.0 - Always Set CID if NULL

src/plugins/trace/dll/DataModel/QuicConnection.cs, src/plugins/trace/dll/DataModel/QuicData.cs, src/plugins/trace/dll/DataModel/QuicObjectSet.cs, src/plugins/trace/dll/DataModel/QuicState.cs, src/plugins/trace/dll/QuicEventParser.cs, src/plugins/trace/dll/Tables/QuicDataBatchingTable.cs, src/plugins/trace/dll/Tables/QuicNetworkTable.cs
Adds a new graph type that plots the delay (in microseconds, capped to 1 ms) between sends, over time. This can help to see how spaced out transmits are for pacing related issues.
Also just added a few bug fixes I found while using this.
=> WPA Plugin Tx Delay Graph

src/plugins/trace/exe/Program.cs
To help debug high percentile latencies.
=> Log Stream ID in RPS Output

src/core/loss_detection.c
Fixes #2293. cc @Wizmann
Now the full 64-bit timestamp is passed (via `QUIC_ACK_EVENT`) to `QuicCongestionControlOnDataAcknowledged`. All other usages (comparing to packet sent times) stay 32-bit.
=> Use 64-bit TimeNow

src/inc/quic_platform_posix.h, src/inc/quic_platform_winuser.h
As described in #2298 , the `uint32_t SpecialFlag` field in `CXPLAT_POOL_ENTRY` could lead to some unexpected assertion error in debug mode.
In this PR, we make the `SpecialFlag` as `uint64_t` to reduce the possibility of the false alert.
=> Make `CXPLAT_POOL_ENTRY::SpecialFlag` to `uint64_t` to avoid unexpected assertion error

src/core/cubic.c, src/generated/linux/cubic.c.clog.h, src/generated/linux/cubic.c.clog.h.lttng.h
Fixes #2231. Don't apply both normal and persistent congestion logic on the same "data lost" event.
=> Don't Double CWND Reduction in Persistent Congestion

CMakeLists.txt, scripts/build.ps1, src/generated/linux/platform_winuser.c.clog.h, src/generated/linux/platform_winuser.c.clog.h.lttng.h, src/manifest/clog.sidecar, src/platform/CMakeLists.txt, src/platform/platform_winuser.c
Adds a compile-time flag to enable configuring the highest possible timer resolution for the system. Only implemented for Windows usermode right now.
=> Support High Resolution Timer (WinUser)

src/core/cubic.c, src/core/cubic.h
Changes time values (except `kCubic`) to microseconds instead of milliseconds, since they're already 64-bit (which can represent something like half a million years worth of microseconds). Also tries to update some of the calculations a bit to better handle limits/overflows at different stages, but still not exactly happy with it. I want to talk with @maolson-msft some on this.
=> Some Cubic Clean Up

scripts/emulated-performance.ps1
Updates it so all table columns are shown. Sorts TCP data last (main only).
=> Improve WAN Perf Formatted Output

src/perf/lib/PerfCommon.h, src/perf/lib/PerfServer.h, src/perf/lib/ThroughputClient.h
Set a really large FC window to make sure it's not limiting throughput in really large BDP WAN perf scenarios.
=> Set Large FC Window for Perf

.azure/azure-pipelines.ci.yml
Because we now have macOS dumps enabled, we can investigate failures here better. We should get to the bottom of why this was failing in the past.
=> Readd macos spinquic running

src/core/stream_send.c, src/test/bin/quic_gtest.h, src/test/lib/EventTest.cpp
This changes the behavior of `StreamSend` when supplied with the `QUIC_SEND_FLAG_START` flag.
With this change, the stream will only be started once and not subsequently if it has already been started.
This avoids an unwanted scenario that follows when multiple stream `QUIC_STREAM_EVENT_START_COMPLETE` events are raised that risk undefined application or implementation specific behavior.
This does not change the behavior of multiple calls to `StreamStart`.
=> QuicStreamSendFlush: Don't double start the stream

src/platform/tls_openssl.c
There is no need to overwrite whatever defaults OpenSSL already has. First part of #2374. cc @baentsch
=> Remove Setting OpenSSL Groups List

scripts/emulated-performance.ps1
Remove unnecessary output from emulated-performance.ps1. The DuoNic perf counters even caused a failure once.
=> Clean up WAN Perf Debug Output

docs/Release.md, src/inc/msquic.h
The downlevel user of this went a different route, so remove it.
=> Remove legacy compile mode

scripts/generate-git-checkin.ps1
This reverts commit f54c2355b133f254dfa6068da2624fd0f205e73b.
Its groups that don't work. Use users instead.
=> Revert "Remove optional reviewers from git checkin (#2427)"

src/test/bin/quic_gtest.cpp, src/test/bin/quic_gtest.h
Otherwise we get a warning, that will potentially fail windows builds
=> Remove VN gtest suite

src/test/bin/quic_gtest.cpp, src/test/bin/quic_gtest.h
Otherwise we get a warning, that will potentially fail windows builds
This will all be undone when VN is redone.
=> Remove VN gtest suite (#2435)

src/lib.rs
Updates the Rust interop layer so it no longer spits out warnings about the unused imports.
Ran `cargo build` and it passed locally.
=> Fix Rust Build Warnings

src/core/send.c, src/test/MsQuicTests.h, src/test/bin/quic_gtest.cpp, src/test/bin/winkernel/control.cpp, src/test/lib/DataTest.cpp
If the app enabled round robin stream scheduling, and stream priority is set to anything less than 0xFFFF, a possible infinite loop occurs.
The loop is checking the wrong variable, which means it turns infinite. There is an exit case, but it depends on a comparison to either another stream priority, or a random variable from the QUIC_SEND struct. If the stream priority is set to 0, the check will always fail, and the loop will go infinite. If only a single stream is used, and its priority is less then the random variable, this will also result in an infinite loop.
The fix is to use the correct loop condition. As this code was from last summer, can only be triggered by app behavior, and requires a non default setting to be explicitly set by the app, this can be fixed without an MSRC.
=> Fix possible infinite loop in priority stream scheduling

CMakeLists.txt, scripts/log.ps1, scripts/prepare-machine.ps1, scripts/run-executable.ps1, scripts/run-gtest.ps1, scripts/spin.ps1, scripts/test.ps1, src/inc/CMakeLists.txt, src/test/lib/DataTest.cpp
Debugging a dump on linux or mac at all requires downloading the dump, and corresponding symbols. Add code to print the stacks of the failures, which often can be used in many cases to avoid needing to do this.
Additionally, from the logs folder, deducing if the log is from a sanitize run or not is difficult. Solve this by adding the extra artifacts dir to the log folder
Do not merge this in its current state, as 2 tests are purposely failing (1 with a bugcheck, 1 with a segfault) to verify everything is working correctly.
=> Improve crash dump debugging in CI

src/core/connection.c, src/core/settings.c
Currently, the Stats getter only checked if the minimum required size existed in the outgoing struct. This updates the logic to allow expanding stats in the future easily, along with how to get the size check right for future fields.
Also adds an example to settings how to do the same thing in the future, as we want to make sure its easy to do and check for in the future.
=> Add size support to QUIC_STATISTICS_V2

.github/workflows/scorecards-analysis.yml
- Remove scheduled runs as they don't seem to be supported.
- Comment back in the publish results for main runs.
=> Fixes for Scorecard Action

src/core/send.c, src/core/send.h, src/core/stream.c
We've seen some crashes internally in the latest builds where somehow a stream seems to be dequeued twice. I haven't yet pinned down the extact repro steps of the scenario that triggers this, but it's simple enough to check and protect from this happening.
Verified existing tests pass. Ideally, I'd like to write a new test case to repro the original issue, but I haven't figured out the steps to do so yet.
=> Extra Protection Around Stream Send Queue

src/lib.rs
Would be nice to be able to shutdown connection & send status code in RUST
Manual test
=> Expose shutdown in RUST's connection object

.azure/azure-pipelines.ci.yml, .azure/templates/build-config-winkernel.yml
Recent AZP default changes moved to 2022, which breaks Windows builds.
=> Build on windows-2019 (release/1.1)

.azure/azure-pipelines.ci.yml, .azure/templates/build-config-winkernel.yml
Recent AZP default changes moved to 2022, which breaks Windows builds.
=> Build on windows-2019 (release/1.0)

src/perf/lib/HpsClient.cpp, src/perf/lib/PerfHelpers.h, src/perf/lib/PerfServer.cpp, src/perf/lib/PerfServer.h, src/perf/lib/RpsClient.cpp, src/perf/lib/RpsClient.h, src/perf/lib/SecNetPerfMain.cpp, src/perf/lib/ThroughputClient.cpp, src/perf/lib/ThroughputClient.h
Adds a new option `-cibir:<bytes>` to secnetperf for specifying the CIBIR extension's well-known identifier.
Tested by manually running over localhost.
=> Add CIBIR Support to SecNetPerf

scripts/prepare-machine.ps1, src/core/listener.c, src/inc/quic_datapath.h, src/platform/datapath_raw.c, src/platform/datapath_raw.h, src/platform/datapath_raw_socket.c, src/platform/datapath_raw_xdp.c
Passes any CIBIR identifier down to XDP on the listener side.
Manually verified on Azure VMs:
=> Pass CIBIR ID to XDP

scripts/onebranch-build-kernel.cmd
msbuild defaults to 32 bit, so the restore step was not correctly working.
=> Fix onebranch builds after removing 32 bit

.azure/azure-pipelines.qns.yml, .azure/obtemplates/push-vpack.yml, CMakeLists.txt, scripts/package-distribution.ps1, scripts/package-nuget.ps1, scripts/write-versions.ps1, src/distribution/Info.plist, src/inc/msquic.ver, src/lib.rs
- CP #2485 to release/2.0.
- Looks like I accidentally updated the clog submodule to latest as well, but it doesn't hurt.
=> release/2.0 CP - Fix Rust Issues #2485

scripts/make-packages.sh
It seems like this got broken by the versioning changes.
```
Shining:msquic furt$ ls -al artifacts/bin/macos/x64_Release_openssl/
total 1768
drwxr-xr-x  8 furt  staff     256 Mar  8 18:35 .
drwxr-xr-x  4 furt  staff     128 Mar  8 18:35 ..
-rwxr-xr-x  1 furt  staff  901816 Mar  8 18:35 libmsquic.2.1.0.dylib
drwxr-xr-x  3 furt  staff      96 Mar  8 18:35 libmsquic.2.1.0.dylib.dSYM
lrwxr-xr-x  1 furt  staff      21 Mar  8 18:35 libmsquic.2.dylib -> libmsquic.2.1.0.dylib
drwxr-xr-x  3 furt  staff      96 Mar  8 18:35 libmsquic.2.dylib.dSYM
lrwxr-xr-x  1 furt  staff      17 Mar  8 18:35 libmsquic.dylib -> libmsquic.2.dylib
drwxr-xr-x  3 furt  staff      96 Mar  8 18:35 libmsquic.dylib.dSYM
```
Unlike Linux, the version precedes the extension. Bottom of the script was properly updated,
```bash …
```
=> fix packaging on macOS

.azure/azure-pipelines.ci.yml, .azure/azure-pipelines.perf.yml
This change completely refactors the performance automation so that it is only run from the "perf" pipeline. We constantly have (windows) perf machines issues which cause perf jobs to stall, which causes the main AZP CI pipeline to stall. Putting all perf in its own pipeline means it will only stall other perf pipeline runs.
The refactor also cleans up the options for running custom jobs as well.
This might be a candidate for backport to release/2.0
=> Refactor Performance Pipeline

.azure/azure-pipelines.ci.yml, .azure/templates/run-bvt.yml, scripts/run-gtest.ps1, scripts/test.ps1
Creates a test job for XDP which downloads the XDP build, installs duonic,
and invokes test.ps1/run-gtest.ps1 with a new "DuoNic" parameter. The tests
have not been modified to use duonic yet, so for the time being the test
is short-circuited in the beginning of run-gtest.ps1.
=> Create XDP BVT test job

src/platform/datapath_kqueue.c
kqueue was receiving an absolute timeout, when it needed a relative timeout. 
Closes #2500
=> Fix kqueue timeout with shared ec mode

.azure/azure-pipelines.ci.yml, .azure/templates/run-bvt.yml
The XDP build's BVT currently runs on the MsQuic-Win-Latest pool, which reuses VMs.
This is problematic because the duonic installation is not cleaned up at the end of the
test. There's no reason not to run on Server 2022, for which we have one-time-use VMs.
=> Switch XDP BVT job to run on Server 2022

src/inc/quic_platform_posix.h, src/inc/quic_platform_winuser.h, src/platform/platform_posix.c, src/platform/platform_winuser.c
CxPlatFree does not allow a nullptr on input, but SAL was marked as such. Fix up the SAL, and hopefully nothing breaks. (#2512 should be triggered)
=> Mark CxPlatFree as not allowing an optional input

src/core/unittest/SettingsTest.cpp
Closes #2529 
macOS is treated as only having a single core.
=> Make GlobalRawDataPathProcsSetAndGet pass with 1 cpu

.azure/OneBranch.Official.yml, .azure/obtemplates/build-nuget.yml
Necessary to publish non-prerelease NuGet packages.
=> Support Building Release NuGet Packages

src/core/send.h, src/core/stream_recv.c
When many small streams are used, it's possible that we never actually send MAX_STREAM_DATA updates. The current logic ties MAX_STREAM_DATA and (connection-wide) MAX_DATA updates together, which causes the peer to be eventually connection FC blocked in this case.
This PR adds an accumulator variable for connectionwide delivered bytes. When the accumulator hits a fraction (I propose 1/4 but haven't carefully thought about it) of the conn FC window, we send a MAX_DATA frame to open the window.
=> Accumulator logic for MAX_DATA updates

.github/workflows/cargo.yml, .github/workflows/check-clog.yml, .github/workflows/check-dotnet.yml, .github/workflows/mirror-repo.yml, .github/workflows/test-down-level.yml, .github/workflows/wan-perf.yml, docs/Release.md
- Remove security hardener from all Windows jobs since it's not supported.
- Try add back security hardener to cargo (since the issue might be fixed)
- Update 2.0.0 references to latest patch 2.0.1
=> Misc Updates

src/platform/datapath_epoll.c, src/platform/datapath_kqueue.c
Newer versions of clang are detecting TailBuffer as unused in release mode, as its only ever set to, and not read from. Make it so the entire variable is gone in release mode. Will need to be backported.
=> Only compute TailBuffer in FreeBuffer on debug builds

Cargo.toml, src/lib.rs
This is a minor change to the lib.rs file to support the connection stats v2 function and struct. In addition, the PR also implements some StreamEvents types that were missing. 
No tests implemented, porting of the C structs were manually converted to Rust.
=> [RUST] Implements stats v2 struct and missing stream events 

src/core/operation.c
While inspecting the code I noticed that we only were apply the logic for `QUIC_STREAM_START_FLAG_SHUTDOWN_ON_FAIL` in the failure path of `QuicStreamStart`, and not in the operation clean up path of `QuicOperationQueueClear` which happens when a connection is cleaned up.
As this is a nearly impossible timing window to hit with a test, I will rely on spinquic and existing tests to hopefully exercise.
None. This is just fixing a bug.
=> Stream Shutdown on Failure in Operation Cleanup

src/inc/msquic.h
They should not have been considered preview features anyway.
=> Remove library git hash and datapath processors from preview features

src/core/operation.c
While inspecting the code I noticed that we only were apply the logic for `QUIC_STREAM_START_FLAG_SHUTDOWN_ON_FAIL` in the failure path of `QuicStreamStart`, and not in the operation clean up path of `QuicOperationQueueClear` which happens when a connection is cleaned up.
As this is a nearly impossible timing window to hit with a test, I will rely on spinquic and existing tests to hopefully exercise.
None. This is just fixing a bug.
=> Stream Shutdown on Failure in Operation Cleanup (#2591)

.azure/azure-pipelines.perf.yml, .github/workflows/wan-perf.yml, scripts/RemoteTests.json
- Onboards a single connection, single stream RPS test so we can get the minimal latency numbers from it.
- Decided to officially only run perf on main branch, so we don't have to maintain perf on previous releases.
- Some WAN perf cleanup too.
Perf automation runs in CI.
N/A
=> One Connection/Stream Perf Test for Latency Data

scripts/RemoteTests.json
In order to get a larger data set, let's run the RPS used for latency measurements longer (30 seconds).
=> Run Latency RPS for Longer

src/core/binding.c, src/inc/msquic.hpp, src/test/MsQuicTests.h, src/test/bin/quic_gtest.cpp, src/test/bin/winkernel/control.cpp, src/test/lib/HandshakeTest.cpp
After discussing with the QUIC WG (on Slack) I am taking their recommendation to block certain client source ports to prevent possible DoS attacks from our servers.
Added test case to validate.
N/A
=> Block Certain Source Ports

src/generated/linux/datapath_raw.c.clog.h, src/generated/linux/datapath_raw.c.clog.h.lttng.h, src/platform/datapath_raw.c
Make DNS work for LoLa by duplicating DNS functions from winuser as a workaround. Will be cleaned up in the future when XDP merges with winuser.
Locally tested. Will be covered by perf test when it's enabled for XDP.
=> Lola uses winuser DNS functions as a stopgap

src/core/connection.c, src/core/crypto.c
Thanks to `elden_ring_fan` on Discord to pointing out that we were double counting dropped packets on the Connection. This PR fixes this by removing the deuplicate counter increases (only logged the `QuicPacketLogDrop` functions now) and adds a few drop calls in places that were missing it.
Existing tests will handle regression testing. No new tests are added right now.
N/A
=> Don't Double Count Connection Packet Drops
